### ISSUE TITLE
[Bug]: gRPC should set the Content-Type header

### ISSUE THREAD

**Issue by tayler-king** [gravitl/netmaker#1000]
### What happened?

Cloudflare [expects a `Content-Type` header](https://support.cloudflare.com/hc/en-us/articles/360050483011-Understanding-Cloudflare-gRPC-support) of `application/grpc`, or one detailing the protocol such as `application/grpc+proto`.

Unfortunately it isn't sent by the client meaning netmaker doesn't seem to support Cloudflare.

I'm not sure on the specifics of the gRPC protocol, but I believe you can do it through the following: https://github.com/grpc/grpc-go/blob/master/Documentation/grpc-metadata.md#sending-metadata-1

### Version

v0.12.2

### What OS are you using?

Linux

### Relevant log output

```shell
[netclient] 2022-03-30 18:29:08 joining x at x:443 
2022/03/30 18:29:08 rpc error: code = PermissionDenied desc = unexpected HTTP status code received from server: 403 (Forbidden); malformed header: missing HTTP content-type
```

### Contributing guidelines

- [X] Yes, I did.

**Comment by afeiszli** [comment]
gRPC has been removed as of 0.14.0, no longer relevant
