### ISSUE TITLE
[Bug]:  Deploying Netmaker to MacOS Monterrey fails with unsupported OS  error

### ISSUE THREAD

**Issue by sullrich** [gravitl/netmaker#1001]
### Contact Details

sullrich@gmail.com

### What happened?

Using the curl command given by the Netmake Create Key interface results in the error:

OS unsupported for automatic dependency install

### Version

v0.12.2

### What OS are you using?

Mac

### Relevant log output

```shell
checking dependencies...
OS unsupported for automatic dependency install
bash-3.2# uname -a
Darwin scottullrich 21.4.0 Darwin Kernel Version 21.4.0: Mon Feb 21 20:34:37 PST 2022; root:xnu-8020.101.4~2/RELEASE_X86_64 x86_64

bash-3.2# sw_vers
ProductName:	macOS
ProductVersion:	12.3
BuildVersion:	21E230
```

### Contributing guidelines

- [X] Yes, I did.

**Comment by mattkasun** [comment]
the script (netclient-install.sh) downloaded by the curl command does not support macOS at this time. The UI should not have Mac in the label for this command.  

you will have to download the netclient binary (https://github.com/gravitl/netmaker/releases/download/v0.12.2/netclient-darwin) and run the command manually
`./netclient join -t <token>`

**Comment by sullrich** [comment]
Good to know!  Thank you
