### ISSUE TITLE
[Bug]: New version v0.12.2 didn't create comms network automatically

### ISSUE THREAD

**Issue by Herobs** [gravitl/netmaker#1004]
### What happened?

As title says, with a clean try the new version v0.12.2, the comms network didn't appear after login.

### Version

v0.12.2

### Contributing guidelines

- [X] Yes, I did.

**Comment by 0xdcarns** [comment]
Sorry this occurred, there seems to be some randomness with generating the comms network successfully. If you try restarting your netmaker server, it should correct itself. `docker restart netmaker`

**Comment by afeiszli** [comment]
Comms network removed as of 0.13, this should no longer be relevant.
