### ISSUE TITLE
[Bug]: The red "error" is because it is in the same LAN as the netmaker server.

### ISSUE THREAD

**Issue by goldsoft8888** [gravitl/netmaker#1013]
### What happened?

The red "error" is because it is in the same LAN as the netmaker server. After I changed it to "is local", I waited for a few hours, and the status did not change. I guess MQ has failed at this time and can't push the changed configuration, but the customer didn't get it from https://grpc.my.domain.com Get the correct configuration again

The problematic client is win11,

Other external clients are normal, including other win11 clients

### Version

v0.12.2

### What OS are you using?

Linux

### Contributing guidelines

- [X] Yes, I did.

**Comment by goldsoft8888** [comment]
![图片](https://user-images.githubusercontent.com/11472472/162856138-8901bceb-099f-4a16-a071-5b4ffc4cf71c.png)

**Comment by goldsoft8888** [comment]
![图片](https://user-images.githubusercontent.com/11472472/162856479-3e04badf-c101-4eb0-8782-797ea5bfa033.png)

**Comment by goldsoft8888** [comment]
After I reinstalled netclient, I displayed "health" for a short time. I changed it quickly, and then observed it for a long time. There was no red "error",

**Comment by mattkasun** [comment]
> 

Can we interpret this to mean that the reinstalling netclient eliminated the issue?

**Comment by afeiszli** [comment]
Closing, no response from user.
