### ISSUE TITLE
[Bug]: Windows Powershell error re: Add-MpPreference

### ISSUE THREAD

**Issue by sullrich** [gravitl/netmaker#1018]
### Contact Details

sullrich@gmail.com

### What happened?

Installing on Windows Server 2012 R2 and Also latest up to date Windows 10 results in:

'WireGuard' is installed.
Add-MpPreference:
Line |
  56 |  …             Add-MpPreference -ExclusionPath "C:\ProgramData\Netclient …
     |                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Operation failed with the following error: 0x800106ba. Operation: MpPreference. Target: ConfigListExtension.
Add-MpPreference:
Line |
  56 |  …             Add-MpPreference -ExclusionPath "C:\ProgramData\Netclient …
     |                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Operation failed with the following error: 0x%1!x!

### Version

v0.12.2

### What OS are you using?

Windows

### Contributing guidelines

- [X] Yes, I did.

**Comment by si458** [comment]
i had the exact same issue,
the command `Add-MpPreference` doesnt exist in Server 2012R2,
so i modified the script to work with all windows if you want to point the url to it to try?
https://github.com/si458/netmaker/blob/server2012r2/scripts/netclient-install.ps1 - CODE
https://github.com/si458/netmaker/raw/server2012r2/scripts/netclient-install.ps1 - RAW

**Comment by afeiszli** [comment]
As of 0.14.0 we now have an MSI installer, which is the new way of installing as opposed to the powershell script. I am going to close this. Users running the older version can use @si458's scripts as a workaround.
