### ISSUE TITLE
My CADDY needs to be customized,how will I set the docker-compose.yml file?

### ISSUE THREAD

**Issue by goldsoft8888** [gravitl/netmaker#1026]
My CADDY needs to be customized, my command line is "./caddy run -config Caddyfile -envfile hurricane.env", added hurricane.env file, CADDY is also customized, how will I set the docker-compose.yml file?

**Comment by cristiioan** [comment]
Just remove the caddy part and it should work. This is what I use as well. I import the Caddyfile in my custom caddy config

**Comment by afeiszli** [comment]
Closing based on @cristiioan 's comment. You can also follow standard Caddy docs to customize / add to docker.
