### ISSUE TITLE
[Bug]: External client config gets an extra comma in AllowedIPs when having egress network added (v0.13.0)

### ISSUE THREAD

**Issue by pellz0r** [gravitl/netmaker#1046]
### Contact Details

sebastian@norbacker.se

### What happened?

I currently have a node in the network that also acts as an egress. When I then created an ingress and tried adding an external client it failed when trying to import the external client config on my phone. Looking at the client config file, it looks like an extra comma has been added to the AllowedIPs field, causing it not to work.

`[Interface]
Address = 10.10.100.4/32
PrivateKey = <key>
MTU = 1280

[Peer]
PublicKey = <key>
AllowedIPs = 10.10.100.0/24,,192.168.1.0/24
Endpoint = 123.123.123.123:51822
PersistentKeepalive = 20`

### Version

Not listed

### What OS are you using?

Linux

### Contributing guidelines

- [X] Yes, I did.

**Comment by 0xdcarns** [comment]
patched in 0.13.1, which will be released likely Monday (05/02). Thanks for pointing it out.

**Comment by afeiszli** [comment]
Fixed in 0.13.1
