### ISSUE TITLE
[Feature Request] set the endpoint and port Static separately

### ISSUE THREAD

**Issue by xcf13363175** [gravitl/netmaker#1061]
Is Static , UDP Hole Punching must be set to connect.
v0.9.2 works fine.（ListenPort: 5182X ）
v0.13.1 Two clients behind NAT cannot connect.（ListenPort: random）

Is it possible to set the endpoint and port Static separately.

**Comment by xcf13363175** [comment]
ListenPort must be fixed and UDP Hole Punching selected to connect.

**Comment by xcf13363175** [comment]
The latest v0.14.0 version is the same, I need to update the endpoint and fix the port to successfully punch the hole.

**Comment by afeiszli** [comment]
will have this in 0.14.1. How it will work is the following:
IsUDPHolePunching --> determines if port is dynamic. If turned off, it will be whatever you set.

IsStatic --> determines if endpoint is dynamic. If turned on, it will be whatever you set.

A little confusing bc we're using legacy vars, but will be better for compatibility with older systems. We'll re-lable in UI to something like "Is IP Dynamic" and "Is Port Dynamic"

**Comment by afeiszli** [comment]
added in 0.14.1:

In Node Details, you now have Endpoint + "Dynamic Endpoint" switch and Port + "Dynamic Port" switch.

If the "dynamic" switch is on, it is set automatically. If off, it's set manually. Endpoint and Port are independent.

<img width="1151" alt="image" src="https://user-images.githubusercontent.com/31018251/170267455-9887a851-e141-4b96-b347-29f734edc6f4.png">
