### ISSUE TITLE
About Licensing.

### ISSUE THREAD

**Issue by xoraingroup** [gravitl/netmaker#1064]
Can I use this product for connecting nodes in our infrastructure? 

We will not modify the source code, neither we will sell netmaker as a service to anyone but to use it for our own infrastructure mesh networking. 

Do we need license for that or do we have to open our source code for that?

**Comment by afeiszli** [comment]
You do not need a license for this purpose and do not need to open your source code. The license is largely to protect against direct re-packaging/selling of the code.
