### ISSUE TITLE
[Question]: Routing traffic between two networks + Assigning multiple IPs

### ISSUE THREAD

**Issue by 4nner** [gravitl/netmaker#1077]
Hello,
thank you for developing NetMaker.

This is not an issue but a question.

It is possible to route traffic from 'Network A' to 'Network B' so that 'Device 1 in Network A' can ping 'Device x in Network B' and vice-versa?

Also, is it possible to assign multiple IPs to the same node? The use case would be the following:
Netclient docker in Docker Network H.
Caddy docker in Docker Network H.
Nginx docker in Docker Network H.

If the netclient has a pool of IPs, Caddy could use port 80, 443 of eg. 10.0.0.4 while nginx using the same ports on 10.0.0.5
Something similar was possible to be implemented with ZeroTier. I believe this could be implemented on Netmaker using an Egress Gateway

**Comment by mattkasun** [comment]
1.  you would need an egress node in Network A that is a member of Network B.  Similarly you would need an egress node in Network B that is a member of Network A.
2. use the AllowedIPs (i think it should have been called extra ips) field in the node tab in the UI
