### ISSUE TITLE
[Bug]: Node instantly deleted after joining

### ISSUE THREAD

**Issue by r-bar** [gravitl/netmaker#1080]
### Contact Details

ryan@barth.tech

### What happened?

I attempted to add a linux node to a new network. When I run `netclient join -t <token>` I got the following output from the client:
```
[netclient] 2022-05-10 21:28:00 joining home at api.<mydomain>:443
[netclient] 2022-05-10 21:28:00 starting wireguard
[netclient] 2022-05-10 21:28:02 deleted node venus  on network  home
```

Other possibly relevant details:
The joining node already exists on a functioning network. Ideally after joining this node would be a member of both netmaker networks. Both client and server are running v0.13.1. This server and node were previously upgraded from 0.11.x (seemingly) successfully following the instructions [here](https://gist.github.com/afeiszli/f53f34eb4c5654d4e16da2919540d0eb).

The decoded token contained:
```
{"server":"","apiconnstring":"api.<mydomain>:443","network":"home","key":"<accesskey>","localrange":""}
```

PS: Thank you for the awesome project!

### Version

v0.13.1

### What OS are you using?

Linux

### Relevant log output

```shell
mq             | 1652243265: Client yf8r4O9k6OJrNQnuU2IRgOz disconnected.
netmaker       | [netmaker] 2022-05-11 04:27:45 error getting node  1efdcdb4-4029-4114-be32-3d57f1884476 no result found
netmaker       | [netmaker] 2022-05-11 04:28:00  created new node venus on network home
mq             | 1652243280: New connection from 172.19.0.2:40004 on port 1883.
mq             | 1652243280: New client connected from 172.19.0.2:40004 as 56o1k1xVnXBLD55CyXCJJCA (p2, c1, k60).
mq             | 1652243280: Client 56o1k1xVnXBLD55CyXCJJCA disconnected.
netmaker       | [netmaker] 2022-05-11 04:28:00 sent peer update for node venus on network: home
netmaker       | [netmaker] 2022-05-11 04:28:00 set new peers on network home
netmaker       | [netmaker] 2022-05-11 04:28:02  Deleted node 49f8bfee-78b3-41a4-914d-49f482a9a4d6 from network home
netmaker       | [netmaker] 2022-05-11 04:28:02 set new peers on network home
mq             | 1652243282: New connection from 172.19.0.2:40006 on port 1883.
mq             | 1652243282: New client connected from 172.19.0.2:40006 as 3RpBpLe23D5T356i4Z2Y5pm (p2, c1, k60).
mq             | 1652243282: Client 3RpBpLe23D5T356i4Z2Y5pm disconnected.
netmaker       | [netmaker] 2022-05-11 04:28:02 error getting node  49f8bfee-78b3-41a4-914d-49f482a9a4d6 no result found
netmaker       | [netmaker] 2022-05-11 04:28:39 set new peers on network home
```

### Contributing guidelines

- [X] Yes, I did.

**Comment by afeiszli** [comment]
It looks like you're missing the broker domain in your token (server":""), which means it's not configured on the server (SERVER_NAME). Also, if you run netclient join with the "-vvv" flag, it will display more logs about what is happening.

**Comment by r-bar** [comment]
Good catch @afeiszli and thank you for your reply. I had configured the `SERVER_NAME` env variable on the docker-compose.yml so was confused at first. I was able to resolve the issue by deleting and regenerating the access keys for this network and using the new token to join the network. It appears the keys snapshot the server state when they are generated.

I left a comment on the gist, but you may want to consider adding in the docs or in the gist that access keys generated before the upgrade will be invalid after the upgrade.

The valid key contents contained:
```
{"server":"broker.<mydomain>","apiconnstring":"api.<mydomain>:443","network":"home","key":"<accesskey>","localrange":""}
```

**Comment by afeiszli** [comment]
Thanks for the comment on the gist! A good catch for upgrades
