### ISSUE TITLE
[Bug]: On Ubuntu Failed to restart netclient.service: Unit netclient.service not found.

### ISSUE THREAD

**Issue by peanutyost** [gravitl/netmaker#1087]
### What happened?

# netclient pull
[netclient] 2022-05-14 02:38:09 No network selected. Running Pull for all networks.
[netclient] 2022-05-14 02:38:11 certificates/key saved
[netclient] 2022-05-14 02:38:13 error running command: systemctl restart netclient.service
[netclient] 2022-05-14 02:38:13 Failed to restart netclient.service: Unit netclient.service not found.

### Version

v0.13.1

### What OS are you using?

Linux

### Relevant log output

```shell
netclient daemon
[netclient] 2022-05-14 02:39:12 initializing network UpdateNet
[netclient] 2022-05-14 02:39:13 pulling latest config for  UpdateNet
[netclient] 2022-05-14 02:39:15 waiting for interface...
[netclient] 2022-05-14 02:39:15 interface ready - netclient.. ENGAGE
[netclient] 2022-05-14 02:39:17 started daemon for server  broker.FQDN
[netclient] 2022-05-14 02:39:17 netclient daemon started for server:  broker.FQDN
[netclient] 2022-05-14 02:39:47 unable to connect to broker, retrying ...
[netclient] 2022-05-14 02:39:47 could not connect to broker broker.FQDN connect timeout
[netclient] 2022-05-14 02:39:47 connection issue detected.. attempt connection with new certs
[netclient] 2022-05-14 02:39:47 register at https://api.FQDN:443/api/server/register
[netclient] 2022-05-14 02:39:47 certificates/key saved
[netclient] 2022-05-14 02:39:48 restarting netclient.service
[netclient] 2022-05-14 02:39:49 error running command: systemctl restart netclient.service
[netclient] 2022-05-14 02:39:49 Failed to restart netclient.service: Unit netclient.service not found.
```

### Contributing guidelines

- [X] Yes, I did.

**Comment by mattkasun** [comment]
could you run the pull with extra logging
`netclient pull -vvv`

**Comment by peanutyost** [comment]
netclient pull -vvv
[netclient] 2022-05-16 02:43:10 No network selected. Running Pull for all networks.
[netclient] 2022-05-16 02:43:13 waiting for interface...
[netclient] 2022-05-16 02:43:13 interface ready - netclient.. ENGAGE
[netclient] 2022-05-16 02:43:13 pulled network config for UpdateNet
[netclient] 2022-05-16 02:43:13 register at https://api.fqdm:443/api/server/register
[netclient] 2022-05-16 02:43:13 certificates/key saved
[netclient] 2022-05-16 02:43:14 restarting netclient.service
[netclient] 2022-05-16 02:43:15 error running command: systemctl restart netclient.service
[netclient] 2022-05-16 02:43:15 Failed to restart netclient.service: Unit netclient.service not found.
[netclient] 2022-05-16 02:43:15 reset network and peer configs

**Comment by afeiszli** [comment]
How did you install the netclient, and is a service running on the machine? 

Check with "systemctl status netclient"

**Comment by peanutyost** [comment]
I updated from 18.04 to 20.04 and it fix my problem. I did realize that machine was on 18.04.
