### ISSUE TITLE
[Bug]: apt.clustercat.com invalid TLS

### ISSUE THREAD

**Issue by dschaper** [gravitl/netmaker#1098]
### Contact Details

dan.schaper@pi-hole.net

### What happened?

Unable to use apt repo at clustercat.

Ign:11 https://apt.clustercat.com stable InRelease
Err:12 https://apt.clustercat.com stable Release
  Could not handshake: A TLS fatal alert has been received. [IP: 178.128.147.45 443]

### Version

v0.14.0

### What OS are you using?

Linux

### Contributing guidelines

- [X] Yes, I did.

**Comment by afeiszli** [comment]
Fixed, had some bad proxy settings, should work now if you retry.
