### ISSUE TITLE
[Bug]: netclient apt package leaves netclient binary in 644 mode.

### ISSUE THREAD

**Issue by dschaper** [gravitl/netmaker#1099]
### Contact Details

dan.schaper@pi-hole.net

### What happened?

A bug happened!

`apt install netclient` results in:

```bash
-rw-r--r--  1 root root   18934399 May 16 20:51 netclient
```
in the `/usr/sbin` directory

### Version

v0.14.0

### What OS are you using?

Linux

### Contributing guidelines

- [X] Yes, I did.

**Comment by afeiszli** [comment]
We are aware of the issue and will have a fix up tomorrow that will install with the appropriate permissions. In the meantime, please run "chmod +x /usr/sbin/netclient"

**Comment by mattkasun** [comment]
deb files at apt.netmaker.org updated to correct permission issue on netclient binary
