### ISSUE TITLE
[Bug]: netclient unable connect to mq server[Unable to connect (A TLS error occurred.)]

### ISSUE THREAD

**Issue by raojinlin** [gravitl/netmaker#1100]
### Contact Details

1239015423@qq.com

### What happened?

netclient was unable to connect to the MQ server because of a certificate problem。

I have three clients, two Linux and one Mac OS. None of them can connect to the MQ server.

When I use the OpenSSL command to verify the certificate, one Linux can pass the verification, but the other Linux and MacOS fail. The following is the version and verification output of OpenSSL.

version: 
Linux1: OpenSSL 1.1.1f  31 Mar 2020
Linux2: OpenSSL 1.0.2k-fips  26 Jan 2017
MacOS: LibreSSL 2.8.3 

Linux1:

```
root@ubuntu:/etc/netclient/netmaker-api.xxx.com# openssl verify -CAfileroot.pem client.pem
client.pem: OK

root@ubuntu:/etc/netclient/netmaker-api.xxx.com# mosquitto_pub -h netmaker-api.xxx.com -p 8883 -t hello/test -m 'dddxxx' --cert client.pem --cafile root.pem --key /etc/netclient/client.key -d
Client mosq-bI0YtDTTcIrbLGxeXV sending CONNECT
Client mosq-bI0YtDTTcIrbLGxeXV received CONNACK (0)
Client mosq-bI0YtDTTcIrbLGxeXV sending PUBLISH (d0, q0, r0, m1, 'hello/test', ... (6 bytes))
Client mosq-bI0YtDTTcIrbLGxeXV sending DISCONNECT

```

Linux2:

```
[root@localhost netmaker-api.xxx.com]# openssl verify -CAfile root.pem client.pem
client.pem: C = US, O = Gravitl, CN = CA Root
error 6 at 0 depth lookup:unable to decode issuer public key
140375689643920:error:0609E09C:digital envelope routines:PKEY_SET_TYPE:unsupported algorithm:p_lib.c:239:
140375689643920:error:0B07706F:x509 certificate routines:X509_PUBKEY_get:unsupported algorithm:x_pubkey.c:148:
140375689643920:error:0609E09C:digital envelope routines:PKEY_SET_TYPE:unsupported algorithm:p_lib.c:239:
140375689643920:error:0B07706F:x509 certificate routines:X509_PUBKEY_get:unsupported algorithm:x_pubkey.c:148:
140375689643920:error:0B06E06C:x509 certificate routines:X509_get_pubkey_parameters:unable to get certs public key:x509_vfy.c:2098:

[root@localhost netmaker-api.xxx.com]# mosquitto_pub -h netmaker-api.xxx.com -p 8883 -t hello/test -m 'dddxxx' --cert /etc/netclient/netmaker-api.xxx.com/client.pem --cafile /etc/netclient/netmaker-api.xxx.com/root.pem --key /etc/netclient/client.key  -d
Error: Unable to load client certificate "/etc/netclient/netmaker-api.xxx.com/client.pem".
OpenSSL Error[0]: error:0609E09C:digital envelope routines:PKEY_SET_TYPE:unsupported algorithm
OpenSSL Error[1]: error:0B07706F:x509 certificate routines:X509_PUBKEY_get:unsupported algorithm
OpenSSL Error[2]: error:140BF10C:SSL routines:SSL_SET_CERT:x509 lib
Unable to connect (A TLS error occurred.).
```

MacOS:

```
MacBook-Air:netmaker-api.xxx.com root# openssl verify -CAfile root.pem client.pem
client.pem: C = US, O = Gravitl, CN = CA Root
error 6 at 1 depth lookup:unable to decode issuer public key
8673539756:error:06FFF09C:digital envelope routines:CRYPTO_internal:unsupported algorithm:/AppleInternal/Library/BuildRoots/66382bca-8bca-11ec-aade-6613bcf0e2ee/Library/Caches/com.apple.xbs/Sources/libressl/libressl-2.8/crypto/evp/p_lib.c:245:
8673539756:error:0BFFF06F:x509 certificate routines:CRYPTO_internal:unsupported algorithm:/AppleInternal/Library/BuildRoots/66382bca-8bca-11ec-aade-6613bcf0e2ee/Library/Caches/com.apple.xbs/Sources/libressl/libressl-2.8/crypto/asn1/x_pubkey.c:197:


MacBook-Air:netmaker-api.xxx.com root# mosquitto_pub -h netmaker-api.xxx.
com -p 8883 --cafile ./root.pem --cert client.pem --key ../client.key -t hello/wt -m x -d
Client null sending CONNECT
Error: host name verification failed.
OpenSSL Error[0]: error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed
Error: A TLS error occurred.

```

Although the openssl command of Linux 1 and mosquitto_pub command runs successfully, but when netclient is started, it is still unable to connect to the MQ server.

Please let me know how I can solve this problem. Thank you!

### Version

v0.14.0

### What OS are you using?

Linux, Mac

### Relevant log output

```shell
[root@localhost ~]# netclient daemon -vvv
[netclient] 2022-05-17 23:42:05 initializing network default
[netclient] 2022-05-17 23:42:05 pulling latest config for  default
[netclient] 2022-05-17 23:42:08 waiting for interface...
[netclient] 2022-05-17 23:42:08 interface ready - netclient.. ENGAGE
[netclient] 2022-05-17 23:42:10 started daemon for server  netmaker-api.xxx.com
[netclient] 2022-05-17 23:42:10 netclient daemon started for server:  netmaker-api.xxx.com
[netclient] 2022-05-17 23:42:40 unable to connect to broker, retrying ...
[netclient] 2022-05-17 23:42:40 could not connect to broker netmaker-api.xxx.com connect timeout
[netclient] 2022-05-17 23:42:40 connection issue detected.. attempt connection with new certs
[netclient] 2022-05-17 23:42:40 register at https://netmaker-api.xxx.com/api/server/register
[netclient] 2022-05-17 23:42:40 certificates/key saved
[netclient] 2022-05-17 23:42:41 restarting netclient.service
[netclient] 2022-05-17 23:43:11 local port has changed from  0  to  51821

root@ubuntu:~# docker logs mq --tail 20 -f
1652845513: New connection from 127.0.0.0:21825 on port 8883.
1652845513: OpenSSL Error[0]: error:14094412:SSL routines:ssl3_read_bytes:sslv3 alert bad certificate
1652845513: Client <unknown> disconnected: Protocol error.
```

### Contributing guidelines

- [X] Yes, I did.

**Comment by afeiszli** [comment]
Hi @raojinlin, please paste output from the netclient.service logs on those machines, since they should be pulling new certificates automatically, but it sounds like they are not. Then, try running "netclient pull" on those clients, which should manually pull new certificates for those clients.

**Comment by afeiszli** [comment]
Ah! The broker domain appears to be incorrect. The value of SERVER_NAME in your docker-compose should be the broker domain. In yours, it appears to be pointing to the api:  netmaker-api.xxx.com. Please change this to the relevant domain such as netmaker-broker.xxx.com. You will then have to restart the server, create a new key (to get the correct details) and rejoin.

**Comment by raojinlin** [comment]
Is this certificate generation related to the domain name? In my environment both netmaker-api and borker are on the same server. Their public ip is the same.

I have tried changing the domain name to netmaker-broker.xxx.com, but I still have the same error after restarting docker-compose.

netclient.service logs:
```
May 18 23:51:22 10-25-241-158 systemd[1]: netclient.service: Succeeded.
May 18 23:51:22 10-25-241-158 systemd[1]: Stopped Netclient Daemon.
May 18 23:51:22 10-25-241-158 systemd[1]: Started Netclient Daemon.
May 18 23:51:22 10-25-241-158 netclient[965664]: [netclient] 2022-05-18 23:51:22 initializing network default
May 18 23:51:22 10-25-241-158 netclient[965664]: [netclient] 2022-05-18 23:51:22 started daemon for server  netmaker-broker.xxx.com
May 18 23:51:22 10-25-241-158 netclient[965664]: [netclient] 2022-05-18 23:51:22 netclient daemon started for server:  netmaker-broker.xxx.com
May 18 23:51:52 10-25-241-158 netclient[965664]: [netclient] 2022-05-18 23:51:52 unable to connect to broker, retrying ...
May 18 23:51:52 10-25-241-158 netclient[965664]: [netclient] 2022-05-18 23:51:52 could not connect to broker netmaker-broker.xxx.com connect timeout
May 18 23:51:52 10-25-241-158 netclient[965664]: [netclient] 2022-05-18 23:51:52 connection issue detected.. attempt connection with new certs
May 18 23:51:52 10-25-241-158 netclient[965664]: [netclient] 2022-05-18 23:51:52 register at https://netmaker-api.xxx.com/api/server/register
May 18 23:51:52 10-25-241-158 netclient[965664]: [netclient] 2022-05-18 23:51:52 certificates/key saved
May 18 23:51:53 10-25-241-158 netclient[965664]: [netclient] 2022-05-18 23:51:53 restarting netclient.service
May 18 23:51:54 10-25-241-158 netclient[965664]: [netclient] 2022-05-18 23:51:54 shutting down netclient daemon
May 18 23:51:54 10-25-241-158 netclient[965664]: [netclient] 2022-05-18 23:51:54 checkin routine closed
May 18 23:51:54 10-25-241-158 netclient[965664]: [netclient] 2022-05-18 23:51:54 shutdown complete
May 18 23:51:54 10-25-241-158 systemd[1]: Stopping Netclient Daemon...
May 18 23:51:54 10-25-241-158 systemd[1]: netclient.service: Succeeded.
May 18 23:51:54 10-25-241-158 systemd[1]: Stopped Netclient Daemon.
May 18 23:51:54 10-25-241-158 systemd[1]: Started Netclient Daemon.
```

**Comment by mattkasun** [comment]
does netmaker-broker.xxx.com resolve?   and is port 8883 publicly accessible?

**Comment by raojinlin** [comment]
Hi @mattkasun netmaker-broker.xxx.com can be resolved,  I have configured it in /etc/hosts.  8883 port is publicly accessible.

**Comment by simon-mao** [comment]
I have the same problem. It happened at first, but then it became normal for no apparent reason. But the same problem appeared when I installed on another server.

You can try cleaning /etc/netclient and rejoining it.

**Comment by mattkasun** [comment]
Have you tried everything in the MQ troubleshooting:
https://gist.github.com/mattkasun/face2a7c1f32031a2126ff7243caad12

**Comment by afeiszli** [comment]
@raojinlin @simon-mao have you checked outbound firewall to see if it is blocking 8883? We have a suspicion this is causing an issue for some users, would be good to check.

**Comment by raojinlin** [comment]
I just deployed a new environment. When debugging the ```netclient daemon```, I found an error when the client shook hands with the server TLS: network error: ```network Error : x509: cannot validate certificate for 192.168.122.87 because it doesn't contain any IP SANs```.


/github.com/eclipse/paho.mqtt.golang@v1.3.5/client.go
![image](https://user-images.githubusercontent.com/19492031/169704515-6e1fd678-e18b-4fce-98d7-df1e08cd7477.png)

This is my docker-compose.yaml configuration:

![image](https://user-images.githubusercontent.com/19492031/169703610-a018d4f0-31e7-4d63-8b30-948528e4ae74.png)

Then I checked the certificate of netmaker：

![image](https://user-images.githubusercontent.com/19492031/169703989-141c7fde-1c96-40dd-a7b3-d0a0d80486be.png)


I checked the code for generating the certificate ```servercfg Getserver() ```, according to the logic of this function, it should get ```SERVER_NAME``` this environment variable. However, the subject CN of the certificate is not the environment variable```SERVER_NAME```, but IP address.

![image](https://user-images.githubusercontent.com/19492031/169704237-2575a707-75ad-46f3-804d-fc247c2fb2bd.png)

**Comment by raojinlin** [comment]
> I just deployed a new environment. When debugging the `netclient daemon`, I found an error when the client shook hands with the server TLS: network error: `network Error : x509: cannot validate certificate for 192.168.122.87 because it doesn't contain any IP SANs`.
> 
> /github.com/eclipse/paho.mqtt.golang@v1.3.5/client.go ![image](https://user-images.githubusercontent.com/19492031/169704515-6e1fd678-e18b-4fce-98d7-df1e08cd7477.png)
> 
> This is my docker-compose.yaml configuration:
> 
> ![image](https://user-images.githubusercontent.com/19492031/169703610-a018d4f0-31e7-4d63-8b30-948528e4ae74.png)
> 
> Then I checked the certificate of netmaker：
> 
> ![image](https://user-images.githubusercontent.com/19492031/169703989-141c7fde-1c96-40dd-a7b3-d0a0d80486be.png)
> 
> I checked the code for generating the certificate `servercfg Getserver() `, according to the logic of this function, it should get `SERVER_NAME` this environment variable. However, the subject CN of the certificate is not the environment variable`SERVER_NAME`, but IP address.
> 
> ![image](https://user-images.githubusercontent.com/19492031/169704237-2575a707-75ad-46f3-804d-fc247c2fb2bd.png)

Sorry, I just checked this certificate. It was generated before. The previous s was 192.168.122.87.

**Comment by afeiszli** [comment]
> Sorry, I just checked this certificate. It was generated before. The previous s was 192.168.122.87.

@raojinlin so does it currently have the correct CA or no?

**Comment by afeiszli** [comment]
Okay, I want to confirm the steps it took to fix. Was it fixed by just restarting the server?

**Comment by afeiszli** [comment]
So these troubleshooting instructions are correct then: https://gist.github.com/mattkasun/face2a7c1f32031a2126ff7243caad12

Can we close this issue?

We will need to determine how this issue started and potentially put in something to auto-heal.

**Comment by raojinlin** [comment]
OK thanks

**Comment by afeiszli** [comment]
Closing. For those who find this issue, PLEASE follow the above Gist, in particular the part about deleting /root/certs
