### ISSUE TITLE
[Bug]: Netclient Push "No help topic for 'push'"

### ISSUE THREAD

**Issue by sidearse** [gravitl/netmaker#1102]
### What happened?

When attempting to use "netclient push" the response is "No help topic for 'push'", with no further info.

Attempted on amd64 and arm7 clients.

### Version

v0.14.0

### What OS are you using?

Linux

### Relevant log output

```shell
sudo netclient push -n mynet
No help topic for 'push'

sudo netclient push
No help topic for 'push'
```

### Contributing guidelines

- [X] Yes, I did.

**Comment by mattkasun** [comment]
Push has been deprecated

**Comment by afeiszli** [comment]
Closing. Netclient settings are now all sent from server side.
