### ISSUE TITLE
client can not join a network when the apiconnstring is http and IP address

### ISSUE THREAD

**Issue by imwower** [gravitl/netmaker#1110]
https://github.com/gravitl/netmaker/blob/c147cc2eb92b1b3e419b0640ce4025d8ae0b1d2d/netclient/functions/join.go#L122

url shoud be:
`url := cfg.Server.API + "/api/nodes/" + cfg.Network `

without the "https://" prefix

**Comment by afeiszli** [comment]
What is your use case for running over http? Running server with http is highly discouraged and insecure.

**Comment by afeiszli** [comment]
Closing. HTTP should not be used for server.
