### ISSUE TITLE
[Bug]: WARNING / ERROR UI Message

### ISSUE THREAD

**Issue by Epod** [gravitl/netmaker#1113]
### What happened?

I have a 2 node setup at the moment. One is a dedicated server with a straight public IP. The other is a server at home behind a firewall with a NAT. 

The dedicated server always returns a "HEALTHY" message in the UI. The system behind the NAT though returns "HEALTHY" at first, followed by "WARNING" then after some time a "ERROR". 

All consoles return no helpful errors indicating any errors. Traffic routes just fine also between the nodes. 

I do have a port forward setup also for the system behind the NAT, but this did not change anything. 

### Version

v0.14.0

### What OS are you using?

Linux

### Contributing guidelines

- [X] Yes, I did.

**Comment by Epod** [comment]
It also appears that any ingress functions will not work on the NATed node. 

Port forwarding is confirmed working - however handshakes on external clients fail.

**Comment by locmai** [comment]
I also have this issue with the Linux netclient. While my Macbook and the server are healthy all the time. Although all connections if fine.

**Comment by mattkasun** [comment]
Have you tried the MQ troubleshooting instructions:

https://gist.github.com/mattkasun/face2a7c1f32031a2126ff7243caad12
