### ISSUE TITLE
[Bug]: apt upgrade to netclient 0.14.1 fails in dpkg

### ISSUE THREAD

**Issue by dschaper** [gravitl/netmaker#1134]
### Contact Details

dan.schaper@pi-hole.net

### What happened?

Ran `apt -y upgrade` to upgrade from 0.14.0 to 0.14.1.

Process errors out trying to set up the package.

```plain
Setting up netclient (0.14.1-0) ...
/var/lib/dpkg/info/netclient.postinst: 4: cannot create /root/gravitl/netclient_0.0.14.1-0_arm64/DEBIAN/postinst: Directory nonexistent
dpkg: error processing package netclient (--configure):
 installed netclient package post-installation script subprocess returned error exit status 2
Errors were encountered while processing:
 netclient
needrestart is being skipped since dpkg has failed
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

### Version

v0.14.0

### What OS are you using?

Linux

### Contributing guidelines

- [X] Yes, I did.

**Comment by afeiszli** [comment]
Workflow failed to push out the new packages, please give us a couple of hours before upgrading.

**Comment by dschaper** [comment]
Seems good now.
