### ISSUE TITLE
[Bug]: Cannot be reached when two peers both roaming

### ISSUE THREAD

**Issue by hanskorg** [gravitl/netmaker#1146]
### What happened?

PeerA:  Dynamic Endpoint / Dynamic Port 
```
interface: nm-xxx 
  public key: ***
  private key: (hidden)
  listening port: 60525

peer: [publickey]
  endpoint: 8*****7:40569
  allowed ips: 10.150.0.3/32
  transfer: 0 B received, 2.02 KiB sent
  persistent keepalive: every 5 seconds
```
PeerB:  Static Endpoint / Dynamic Port 
```
interface: nm-xxx
  public key: ***
  private key: (hidden)
  listening port: 40572

peer: nm-xxx
  endpoint: [peerA public IP(end of nat)]:60525
  allowed ips: 10.150.0.4/32
  latest handshake: 6 minutes, 30 seconds ago
  transfer: 180 B received, 5.99 MiB sent
  persistent keepalive: every 20 seconds
....
```

PeerC:  Static Endpoint / Static Port 
```
interface: nm-xxx
  public key: [key]
  private key: (hidden)
  listening port: 51821

peer: [peerB's key]
  endpoint: 8****7:40572
  allowed ips: 10.150.0.3/32
  latest handshake: 1 minute, 1 second ago
  transfer: 594.66 KiB received, 442.46 KiB sent
  persistent keepalive: every 20 seconds

peer: [peerA's key]
  endpoint: 12*****6:13295
  allowed ips: 10.150.0.4/32
  latest handshake: 1 minute, 58 seconds ago
  transfer: 730.27 KiB received, 3.81 MiB sent
  persistent keepalive: every 20 seconds
```

---

Peer A And Peer B can not get  the correct port when both use Dynamic Port, but Peer C is successful.

### Version

v0.14.1

### What OS are you using?

Linux

### Contributing guidelines

- [X] Yes, I did.

**Comment by hanskorg** [comment]
They are in different network, peer A behind NAT, peer B using  EIP on Cloud

**Comment by hanskorg** [comment]
> are the roaming nodes on the same network or different networks. Are they behind NAT?

They are in different network, peer A behind NAT, peer B using EIP on Cloud

**Comment by hanskorg** [comment]
> what is EIP?
Sorry, it may not be a piece of helpful information, EIP means elastic IP which binds the virtual router  forward to Peer B

**Comment by abhishek9686** [comment]
@hanskorg please try your setup on latest versions
