### ISSUE TITLE
Bad GPG configuration for RPM repository

### ISSUE THREAD

**Issue by chamburr** [gravitl/netmaker#1156]
I noticed the [RPM repository configuration](https://rpm.netmaker.org/netclient-repo) provided does not properly implement GPG signature checking.

The current configuration is:
```
[netclient-repo]
name=netclient 
baseurl=https://rpm.netmaker.org/packages
enabled=1
pgpcheck=1
pgpkey=https://rpm.netmaker.org/gpg.key
```

However, the correct keys to configure GPG signature checking are `gpgcheck` and `gpgkey`. I am afraid that GPG signature is not actually being checked due to the erroneous keys, which are unfortunately not aliases.

**Comment by mattkasun** [comment]
repo and build scripts updated.

**Comment by mattkasun** [comment]
> Thank you. I think you made a typo, it's not `gpgkpey`.

Good catch. Thankyou.. Fixed
