### ISSUE TITLE
Feature Request: ACLs for External Clients

### ISSUE THREAD

**Issue by juris** [gravitl/netmaker#1174]
### Contact Details

juris@juro.com

### What happened?

Would be great to have ACLs for external clients.
Currently, if a group of users access a network via an ingress, they all share the same access levels. So if an ingress has access to some DB server, all the users will be able to access it.

### Version

v0.14.2

### What OS are you using?

Linux

### Contributing guidelines

- [x] Yes, I did.

**Comment by ashokrajar** [comment]
In addition to this, need option to limit the Users only to access the External Client config allocated to that particular user and not see other client configs.

**Comment by markusglaetzner** [comment]
A complete separate ACL for ports and protocols for every external route would be nice (like it is implemented in other products like netbird, tailscale and so on).

**Comment by abhishek9686** [comment]
> Hi @afeiszli! Do y'all have any updates on this? In Discord you mentioned this would ideally be coming Q1 2023: https://discord.com/channels/825071750290210916/825071821594034196/1060000352407146517
> 
> I'm in no rush but wanted to check in. 😅
Acls for Extclients are available, was added couple of release back
