### ISSUE TITLE
Force Peers to Reconnect

### ISSUE THREAD

**Issue by doodlemania2** [gravitl/netmaker#1179]
### Discussed in https://github.com/gravitl/netmaker/discussions/1171

<div type='discussions-op-text'>

<sup>Originally posted by **doodlemania2** June  2, 2022</sup>
I'm troubleshooting an issue with some nodes that are behind a wicked NAT (double NAT in fact). UDP hole punching is enabled.
Wondering if there's a way (on Linux) to force the peers to reconnect as they keep going down. I don't see any errors or anywhere to really troubleshoot if it's the network connection, the IP address changing frequently, or something in netclient misbehaving.

Any thoughts on how to kick it to reconnect and or dump logs?</div>

**Comment by mattkasun** [comment]
you can manually run a pull and get the latest config from the netmaker server

`sudo /sbin/netclient pull -n <network name> -vvv`

**Comment by doodlemania2** [comment]
Nice!
