### ISSUE TITLE
[Bug]: netmaker server side generated token is lack of server field

### ISSUE THREAD

**Issue by vv1vv2** [gravitl/netmaker#1180]
### What happened?

I installed nemaker in cloud server by quick install, ervery step was smooth, but generated token was lack of server field. when I executed netclient to join the network, it would instantly remove the network and when I joined the server field into the token manually, netclient can join the network.but the server side can't ping the netclient side.only netclient side can ping the netmaker server

### Version

v0.14.2

### What OS are you using?

Linux

### Relevant log output

```shell
//netclient side
[netclient] 2022-06-04 03:32:45 joining netty at api.vv1vv2.com:443 
[netclient] 2022-06-04 03:32:46 node created on remote server...updating configs 
[netclient] 2022-06-04 03:32:46 starting wireguard 
[netclient] 2022-06-04 03:32:49 waiting for interface... 
[netclient] 2022-06-04 03:32:51 interface ready - netclient.. ENGAGE 
[netclient] 2022-06-04 03:32:51 error installing:  no server provided 
[netclient] 2022-06-04 03:32:51 deleted node zhangsaideMacBook-Airlocal  on network  netty 
[netclient] 2022-06-04 03:32:51 removed  netty  network locally 
//cloud side mq
1654280297: mosquitto version 2.0.11 starting
1654280297: Config loaded from /mosquitto/config/mosquitto.conf.
1654280297: Opening ipv4 listen socket on port 8883.
1654280297: Opening ipv6 listen socket on port 8883.
1654280297: Error: Unable to load CA certificates. Check cafile "/mosquitto/certs/root.pem".
1654280297: Error: Unable to load server certificate "/mosquitto/certs/server.pem". Check certfile.
1654280297: OpenSSL Error[0]: error:02001002:system library:fopen:No such file or directory
1654280297: OpenSSL Error[1]: error:20074002:BIO routines:file_ctrl:system lib
1654280297: OpenSSL Error[2]: error:140DC002:SSL routines:use_certificate_chain_file:system lib
1654280301: mosquitto version 2.0.11 starting
```

### Contributing guidelines

- [X] Yes, I did.

**Comment by mattkasun** [comment]
If you restart the netmaker container, the certs will be regenerated

**Comment by vv1vv2** [comment]
> If you restart the netmaker container, the certs will be regenerated

thank you for your reply! I have tried to restart netmaker many times, and even deleted the certs folder, but it didn't resolve the problem

**Comment by afeiszli** [comment]
@vv1vv2 are you still experiencing this issue?

**Comment by afeiszli** [comment]
Closing, as no response
