### ISSUE TITLE
[Question] Thoughts on large scale deployment

### ISSUE THREAD

**Issue by iqbalaydrus** [gravitl/netmaker#1191]
I'm planning on using netmaker with my project. But it will have many nodes, somewhere around 30,000 nodes, all of them are raspberries and connects limited mobile networks (most of them are 2G). Netmaker and some of the nodes are deployed on kubernetes. A full mesh network doesn't sound good on raspberries (or maybe it does?), since it will have p2p connections on all other 29,999 nodes. I have a few ideas on how to tackle this with netmaker:

- All raspberries configured as external clients. But as stated in the docs, the raspberry won't be reachable via the network. So this is a no-go. And it will be a hassle if any config changes (changing the ingress ip, etc)
- All raspberries will go through one or more relay nodes. This seems like the most viable option since I can still have all the benefits of netmaker. And I can change configs through the UI without messing with the raspberry nodes, also they will be reachable in the network.

What are your thoughts on this? I did consider using a regular hub-and-spoke architecture, but I'm afraid to hit a single node resource limitation on the server.

Also is there any docs on the APIs? Since managing a lot of nodes via the UI is a lot of effort, I would prefer creating a script to provision them.

**Comment by mattkasun** [comment]
multiple relay node has only had limited testing with unpromising results.. For now I suggest limiting to one relay hop only.

Do all nodes need to reach all the others?  If not, would multiple networks might be better

API -- https://docs.netmaker.org/api.html

**Comment by iqbalaydrus** [comment]
> Do all nodes need to reach all the others? If not, would multiple networks might be better
No, it doesn't need to. But it does need to be able to reach some IPs on the netmaker's kubernetes cluser (probably can be dealt with an egress node on each network). So are you suggesting to use multiple networks and have one relay on each network?

> API -- https://docs.netmaker.org/api.html
Ah right, missed that one. Thanks!

**Comment by mattkasun** [comment]
what is the relay for?

**Comment by iqbalaydrus** [comment]
I was thinking to further minimize network usage by avoiding many p2p connections. But I guess I can break them to /24 networks. Those are small enough and probably won't have that issue.

Ok, I think I have the general picture now. All that's left to do is some testing. Thank you @mattkasun

**Comment by afeiszli** [comment]
Yes this is likely the best method. However, at the moment, the ACL API is not user friendly. You must submit an API request for the whole network every time, which is likely not going to work when your json would include 30,000 machines.
