### ISSUE TITLE
Can't create an admin password

### ISSUE THREAD

**Issue by paul19920801** [gravitl/netmaker#1197]
### Contact Details

paulbarnett@axxess.co.za

### What happened?

I am new to the world of Netmaker, I installed last night, and installed a few nodes.  

Namely a few VPSses. I know Oracle cloud was mentioned as being problematic, my install was working fine. - Till I accidentally activated an ingress node, and locked some of my VPS machines out - so as a result I decided to wipe everything, and start again. I install using the script.  wget -qO - https://raw.githubusercontent.com/gravitl/netmaker/master/scripts/nm-quick.sh | sudo bash

This time it would not let me create a password. This is the error message I get 

![image](https://user-images.githubusercontent.com/90729302/172928399-c195a7ae-88fd-4899-afeb-04169cc2e997.png)

This is very strange as it was working this morning. 
Please advise

### Version

v0.14.2

### What OS are you using?

Linux, Windows

### Relevant log output

```shell
Can't access it
```

### Contributing guidelines

- [X] Yes, I did.

**Comment by mattkasun** [comment]
Clearing brower cache will correct.
