### ISSUE TITLE
Trying to install Client Mode - youtube video says Netmaker in client mode doesn't use Docker??

### ISSUE THREAD

**Issue by bmullan** [gravitl/netmaker#120]
I want to try Netmaker out across multiple clouds to interconnect LXD (system not app containers) containers.

The Youtube video at the 2:25 mark describes Client Mode **doesn't** use Docker (which is what I want ! ).

My system is Ubuntu 20.04.

I tried to install netmaker using the script Alex mentions in the video:  
**https://www.youtube.com/watch?v=krCKBJhwwDk&t=51s**  

> **sudo curl -sfL https://raw.githubusercontent.com/gravitl/netmaker/v0.2/netmaker-install-clientmode.sh | sudo SERVER_DOMAIN=< myIP > sh -**

However, when I run this I get an error:  

> **$ sudo curl -sfL https://raw.githubusercontent.com/gravitl/netmaker/v0.2/netmaker-install-clientmode.sh | sudo SERVER_DOMAIN=192.168.1.241 sh -**  
> [sudo] password for bmullan:   
> **sh: 7: docker: not found**  

The script outputs some other docker related error messages and completes

However, Netmaker does **not** get installed and I can't access the Web UI 
http 

The above curl command does specify Netmaker v0.2  

So I looked at the Source on Github for:  
> **https://github.com/gravitl/netmaker/blob/master/netmaker-install-clientmode.sh**

_**and the very last line still uses Docker?**_

> **docker run -d --name netmaker-ui -p 80:80 -e BACKEND_URL="http://$SERVER_DOMAIN:8081" gravitl/netmaker-ui:v0.2**

If I install Docker then run the "netmaker-install-clienmode.sh" it works?    But the _**video said client-mode doesn't use Docker**_ ?

How do I install client mode w/out Docker use or is there a bug w/some artifact in the client-mode script referencing Docker still ?

Thanks
Brian

**Comment by afeiszli** [comment]
Hi Brian, I should have clarified. The server component of Netmaker does not use docker when you run that script, but MongoDB and the UI are still deployed using Docker. We don't currently have an installer for non-docker, but have written down all the steps here: https://github.com/gravitl/netmaker/blob/master/docs/USAGE.md#non-docker-installation

**Comment by bmullan** [comment]
@afeiszli 
thanks... I actually looked at that Usage doc but never scrolled down far enough to see that.

**Comment by bmullan** [comment]
@afeiszli 

Alex, in a previous post in this thread you said:

**

> We don't currently have an installer for non-docker, but have written down all the steps here: https://github.com/gravitl/netmaker/blob/master/docs/USAGE.md#non-docker-installation

**

that link no longer appears to work?  **_Did the non-docker install steps change?_**

thanks
brian

**Comment by afeiszli** [comment]
@bmullan the non-docker install steps are now in the docs. They will need some updates but it is a good place to start: https://docs.netmaker.org/server-installation.html#linux-install-without-docker. Post in this thread was from when we were storing docs as markdown in the repo.

**Comment by catm4n** [comment]
I was able to install Netmaker on a droplet vps rather quickly as per the instructions, however I have not been able to install the netclient on Arch with the script or manually. it fails with a dependency error. I have also not been successful in using the vpnclient config to create a wireguard connection for networkmanager.  has anyone been able to get it working on arch using these instuctions: https://itnext.io/how-to-create-four-types-of-vpns-quickly-with-wireguard-and-netmaker-1db7a6270a0f

**Comment by afeiszli** [comment]
@catm4n what logs do you get? I'm guessing there's missing dependencies.
