### ISSUE TITLE
Does Netmaker have an "Un-Install" script?

### ISSUE THREAD

**Issue by bmullan** [gravitl/netmaker#121]
See title...

**Comment by afeiszli** [comment]
For the server I'm assuming? If you ran in "client mode" it would be something like this:

sudo docker kill mongodb
sudo docker rm mongodb
sudo docker volume rm mongovol
sudo docker kill netmaker-ui
sudo docker rm netmaker-ui
sudo rm -rf /etc/netmaker
sudo rm -f /etc/systemd/system/netmaker.service
sudo systemctl daemon-reload

I have a script written up that I meant to push to the repo. Will do that later today.

**Comment by bmullan** [comment]
@afeiszli 

Above you show commands using "docker"...?

Alex, if you look at another "issue" I opened:  
https://github.com/gravitl/netmaker/issues/120

The Youtube Demo video: https://www.youtube.com/watch?v=krCKBJhwwDk&t=51s    
**_At the 2:25 mark you described the nw "client mode" as NOT using Docker?_**    

I would like to install Netmaker with out Docker.

Thanks
Brian
