### ISSUE TITLE
[Bug]:  Hub clients do not allow for dynamic endpoints (isStatic=="no")

### ISSUE THREAD

**Issue by ygelfand** [gravitl/netmaker#1213]
### What happened?

Hub nodes currently are always set to IsStatic (https://github.com/gravitl/netmaker/blob/d0c42e28b432f8a119426be045ede2d2a93c72d3/models/node.go#L366-L367).  Looking to have dynamic endpoints for hubs, e.g. in a k8s deployment, where the hub pod can shift nodes. 

Mentioned in https://discord.com/channels/825071750290210916/975815715556851782/983737306722734132

### Version

v0.14.2

### What OS are you using?

Linux

### Contributing guidelines

- [X] Yes, I did.

**Comment by abhishek9686** [comment]
@ygelfand there is no concept of hub pod anymore, netclients can have dynamic endpoints
