### ISSUE TITLE
Error installing Mongodb for non-Docker client-mode

### ISSUE THREAD

**Issue by bmullan** [gravitl/netmaker#122]
The documentation:

says

> MongoDB Setup
> 
>     Install MongoDB on your server. For Ubuntu: sudo apt install -y mongodb. For more advanced installation or other operating systems, see the MongoDB documentation.
> 
>     Create a user: 

mongo admin db.createUser({ user: "mongoadmin" , pwd: "mongopass", roles: ["userAdminAnyDatabase",   "dbAdminAnyDatabase", "readWriteAnyDatabase"]})  

MongoDb installls ok.  
but I get an error trying to create the admin user:

> ./mk-netmaker.sh: line 55: syntax error near unexpected token `('   
>    
> ./mk-netmaker.sh: line 55: `mongo admin db.createUser({ user: "mongoadmin" , pwd: "mongopass", roles:     ["userAdminAnyDatabase", "dbAdminAnyDatabase", "readWriteAnyDatabase"]})'    

I am not very knowledgeable on mongodb.

Any help?

**Comment by afeiszli** [comment]
apologies...markdown formatting error. Those two lines should be separate.  "mongo admin" opens an interactive shell, and then you paste in that command to create the user.

**Comment by afeiszli** [comment]
so like this:
sh $ mongo admin
    > db.createUser({ user: "mongoadmin" , pwd: "mongopass", roles: ["userAdminAnyDatabase", "dbAdminAnyDatabase", "readWriteAnyDatabase"]})

**Comment by afeiszli** [comment]
I've update the docs on master

**Comment by bmullan** [comment]
thanks...
