### ISSUE TITLE
[Bug]: point to site network is peering to every device 0.14.3

### ISSUE THREAD

**Issue by si458** [gravitl/netmaker#1224]
### What happened?

for some reason after update to 0.14.3, every device is now peering with each other rather than ONLY peering with the master node even though my network is set as point to site?

### Version

v0.14.3

### What OS are you using?

Linux

### Contributing guidelines

- [X] Yes, I did.

**Comment by afeiszli** [comment]
Just merged a hotfix that should fix this. Docker image is still building. Thanks for pointing this out. We discovered some other issues with point-to-site that need to be fixed, which we'll get in the next release. In particular, it's a bad idea to switch the hub from one node to another right now.

**Comment by si458** [comment]
> Just merged a hotfix that should fix this. Docker image is still building. Thanks for pointing this out. We discovered some other issues with point-to-site that need to be fixed, which we'll get in the next release. In particular, it's a bad idea to switch the hub from one node to another right now.

thats fine, glad i alerted you to this issue!
for my use case the computers are all remote and i look after them so they dont need to peer with each other,
just the main server so i can access them haha

**Comment by si458** [comment]
@afeiszli ok ive pulled the latest docker image of `0.14.3` this morning and it does sorta fix it but not fully...
its changed the wireguard config to only show one peer now instead of loads of peers
but the allowedips line i believe is wrong and completely missing the whole subnet?
`AllowedIps = 10.128.128.254/32, 10.128.128.4/32`

**Comment by afeiszli** [comment]
@si458 it should only show the allowedips for the "hub" node, not the full subnet. The point-to-site setup is meant for more simple one-to-many use cases. It's not a hub-and-spoke VPN, just a simple remote access VPN. I should add this to the docs probably...

https://itnext.io/why-you-might-not-want-a-mesh-vpn-21ac040c767b
