### ISSUE TITLE
Helm Chart / K8S HA Setup 

### ISSUE THREAD

**Issue by nashford77** [gravitl/netmaker#1236]
Hello - Is the Helm Chart not used anymore as I don't see support in it for current versions of PostGreSQL or Netmaker ? If it is not, how would one do an HA setup in K8S from 0 - I see no walkthrough. Also - can version control be implemented for the components in CLI on the helm chart? EG :: --UI-Version=X --NM-Version=Y etc. so that a new chart is not always needed? Thanks in advance.

**Comment by nashford77** [comment]
Can i change the charts index.yaml to use the new postgres and NM ? would it work? What is the ETA of a modern HEL chart inclusive of ingress for the UDP clients etc etc

**Comment by wibed** [comment]
any updates on this kinda lost installing this on kubernetes, if any documentation is outdated

**Comment by afeiszli** [comment]
The helm charts are not updated yet. In the meantime, we have updated manual deployment instructions here: https://github.com/gravitl/netmaker/tree/master/k8s/server

**Comment by afeiszli** [comment]
Helm chart has been updated to 0.14.5
