### ISSUE TITLE
[Bug]: RTNETLINK answers: File exists - on egress gateway when using a relay server

### ISSUE THREAD

**Issue by janhendrik-rust** [gravitl/netmaker#1243]
### What happened?

Most of our remote nodes are behind CGNAT or Double NAT so we decided to use our netmaker-1 node as a relay - relaying all nodes.

One of the nodes is our office Egress Gateway.

### Expected behaviour:
When the Egress Gateway restarts it should join the netmaker wireguard network. The netclient should ignore routes already present on the local host.

### Current behaviour:
When the egress gateway restarts the netclient fails to join the netmaker wireguard network, and I have to disable the egress, pull the config and then re-enable the egress. I would have to do this on every restart of the egress gateway.

### Additional Info
#netclient pull                                                                                                                                    
[netclient] 2022-06-23 08:38:41 No network selected. Running Pull for all networks. 
[netclient] 2022-06-23 08:38:44 error running command: wg-quick up /etc/netclient/config/nm-netmaker.conf 
[netclient] 2022-06-23 08:38:44 [#] ip link add nm-netmaker type wireguard
[#] wg setconf nm-netmaker /dev/fd/63
[#] ip -4 address add 192.168.100.4 dev nm-netmaker
[#] ip link set mtu 1280 up dev nm-netmaker
[#] ip -4 route add 192.168.100.9/32 dev nm-netmaker
[#] ip -4 route add 192.168.100.8/32 dev nm-netmaker
[#] ip -4 route add 192.168.100.7/32 dev nm-netmaker
[#] ip -4 route add 192.168.100.6/32 dev nm-netmaker
[#] ip -4 route add 192.168.100.5/32 dev nm-netmaker
[#] ip -4 route add 192.168.100.3/32 dev nm-netmaker
[#] ip -4 route add 192.168.100.254/32 dev nm-netmaker
[#] ip -4 route add 192.168.100.2/32 dev nm-netmaker
[#] ip -4 route add 192.168.100.11/32 dev nm-netmaker
[#] ip -4 route add 192.168.100.10/32 dev nm-netmaker
[#] ip -4 route add 192.168.100.1/32 dev nm-netmaker
[#] ip -4 route add 10.0.0.0/24 dev nm-netmaker
RTNETLINK answers: File exists
[#] ip link delete dev nm-netmaker 

The egress gateway is already on the 10.0.0.0/24 network and already has a route registered for that subnet -  when the route add fails the whole process fails
 

### Version

v0.14.3

### What OS are you using?

Linux

### Relevant log output

```shell
#netclient pull                                                                                                                                    
[netclient] 2022-06-23 08:38:41 No network selected. Running Pull for all networks. 
[netclient] 2022-06-23 08:38:44 error running command: wg-quick up /etc/netclient/config/nm-netmaker.conf 
[netclient] 2022-06-23 08:38:44 [#] ip link add nm-netmaker type wireguard
[#] wg setconf nm-netmaker /dev/fd/63
[#] ip -4 address add 192.168.100.4 dev nm-netmaker
[#] ip link set mtu 1280 up dev nm-netmaker
[#] ip -4 route add 192.168.100.9/32 dev nm-netmaker
[#] ip -4 route add 192.168.100.8/32 dev nm-netmaker
[#] ip -4 route add 192.168.100.7/32 dev nm-netmaker
[#] ip -4 route add 192.168.100.6/32 dev nm-netmaker
[#] ip -4 route add 192.168.100.5/32 dev nm-netmaker
[#] ip -4 route add 192.168.100.3/32 dev nm-netmaker
[#] ip -4 route add 192.168.100.254/32 dev nm-netmaker
[#] ip -4 route add 192.168.100.2/32 dev nm-netmaker
[#] ip -4 route add 192.168.100.11/32 dev nm-netmaker
[#] ip -4 route add 192.168.100.10/32 dev nm-netmaker
[#] ip -4 route add 192.168.100.1/32 dev nm-netmaker
[#] ip -4 route add 10.0.0.0/24 dev nm-netmaker
RTNETLINK answers: File exists
[#] ip link delete dev nm-netmaker
```

### Contributing guidelines

- [X] Yes, I did.

**Comment by janhendrik-rust** [comment]
I would like to say a Great Big Thank You for creating netmaker.

It has been a absolute breeze to get everything working and the cross platform and cross architecture clients are awesome. I love WireGuard, but I LOVE Netmaker even more - It has turned my point to point wg links into an auto-magic VPN - its fantastic.

If I've missed anything in this bug report, or miss configured anything that's on me.

**Comment by mattkasun** [comment]
bug confirmed

**Comment by janhendrik-rust** [comment]
@mattkasun - I've just updated my server and egress nodes to netmaker 0.14.5
I'm still getting the same results "RTNETLINK answers: File exists" - and then the wireguard interface fails to initialize. I believe this is the same issue as #1269.

I still have to disable the egress gateway on the egress-node, pull the netclient config and then re-add the egress gateway settings.  It seems like I have to remove the 10.0.0.0/24 AllowedIP from the nm-netmaker.conf wireguard config file to allow the wireguard interface to initialize as part of ```wg-quick up /etc/netclient/config/nm-netmaker.conf```

![Netmaker_Network_20220711](https://user-images.githubusercontent.com/574128/178226536-95ef472c-03f9-4735-99db-31ec7e3565a6.png)

**Comment by afeiszli** [comment]
Closing as per #1443
