### ISSUE TITLE
In Agent Setup steps need to clarify "create a key"

### ISSUE THREAD

**Issue by bmullan** [gravitl/netmaker#127]
I want to clarify a sentence in the In the Non-Docker install steps.

In **[Agent Setup](https://github.com/gravitl/netmaker/blob/master/docs/USAGE.md#agent--setup)**, Step 3 it says:

> Create a key or enable manual node signup at the network level

Is "Create a key"... simply using something like:  **ssh –keygen –t rsa 4096**

or something else?

**Comment by afeiszli** [comment]
That would be creating an "Access Key" via the Netmaker UI or API:

https://github.com/gravitl/netmaker/blob/master/docs/API.md#access-keys

**Comment by bmullan** [comment]
thanks...
