### ISSUE TITLE
[Bug]: Could you change image version in template?

### ISSUE THREAD

**Issue by crustulumtheoneandonly** [gravitl/netmaker#1271]
### What happened?

A bug happened!
Not really.

Its just a little confusing if you follow the instructions but get an very old version installed if you dont change the version in [netmaker-template.yaml](https://raw.githubusercontent.com/gravitl/netmaker/master/kube/netmaker-template.yaml)

### Version

v0.14.4

### Contributing guidelines

- [X] Yes, I did.

**Comment by afeiszli** [comment]
The netmaker template is outdated and will not work by just changing the version. We are working on updated templates which will be in the next release (0.14.5). In the meantime, I recommend you take a look here: https://github.com/geragcp/netmaker-k3s

**Comment by afeiszli** [comment]
updated in 0.14.5: https://github.com/gravitl/netmaker/tree/master/k8s/server
