### ISSUE TITLE
New Windows after clicking "view netclient install instructions"

### ISSUE THREAD

**Issue by pete1019** [gravitl/netmaker#1283]
### What happened?

Hi would be better to open a NEW Windows when clicking on "view netclient install instructions" at "Viewing your Access Key Details".

Without the new windows there will be a white page when clicking back in the browser.

### Version

v0.14.4

### What OS are you using?

Linux

### Contributing guidelines

- [X] Yes, I did.

**Comment by afeiszli** [comment]
Please open this issue on the netmaker-ui repo: https://github.com/gravitl/netmaker-ui/issues
