### ISSUE TITLE
Cannot connect to server - netmaker docker logs "error retrieving networks for keepalive"

### ISSUE THREAD

**Issue by bodleytunes** [gravitl/netmaker#1284]
### Contact Details

supertent@gmail.com

### What happened?

Hiya

I was wondering what this message means

Trying to create server on a chinese mini PC with proxmox installed.

Firstly tried in LXC and then tried again on the host but getting the same error messages

```
[netmaker] 2022-07-03 07:47:27 REST Server successfully started on port  8081  (REST)
[netmaker] 2022-07-03 07:47:27 connecting to mq broker at mq:1883
[netmaker] 2022-07-03 07:48:29 error retrieving networks for keepalive could not find any records
[netmaker] 2022-07-03 07:49:29 error retrieving networks for keepalive could not find any records
```

The UI gets to the part of setting up admin / password but says it can't connect to server.

I'm not sure on what else to look at regarding troubleshooting it.

Thanks!

Jon.

### Version

v0.14.4

### What OS are you using?

Linux

### Relevant log output

```shell
[netmaker] 2022-07-03 07:47:27 REST Server successfully started on port  8081  (REST)
[netmaker] 2022-07-03 07:47:27 connecting to mq broker at mq:1883
[netmaker] 2022-07-03 07:48:29 error retrieving networks for keepalive could not find any records
[netmaker] 2022-07-03 07:49:29 error retrieving networks for keepalive could not find any records
```

### Contributing guidelines

- [X] Yes, I did.

**Comment by mattkasun** [comment]
The error message is expected if no networks have been created. 

What is the problem creating admin?  Have you set up all required DNS entries?  How did you install?  Docker or baremetal?

**Comment by bodleytunes** [comment]
I used nm-quick.sh to set it up using docker.

Error when trying to create admin user initially is "cant connect to
server" or something along those lines

Let me check DNS as this server isn't public facing, I had to use NAT to
forward the wireguard port.

**Comment by bodleytunes** [comment]
This sort of error.  Checked dns and made sure everything was resolvable using hosts file
<img width="385" alt="image" src="https://user-images.githubusercontent.com/619239/177260131-3f58ae9a-5497-47b8-94c7-18c97d732c2c.png">

**Comment by mattkasun** [comment]
check for errors in traefik logs.

**Comment by afeiszli** [comment]
@bodleytunes any updates? otherwise we will close this issue.

**Comment by afeiszli** [comment]
Closing, as no updates have been received

**Comment by bodleytunes** [comment]
Hi, you can close, thank you
