### ISSUE TITLE
Enabling/disabling Node signup without keys duplicate IP's

### ISSUE THREAD

**Issue by pcfriek1987** [gravitl/netmaker#130]
When having existing nodes, if on the network you enable or disable the Allow node signup without keys all of your nodes will get either duplicate or new additional IP's from the wireguard range breaking everything.

See below for an example:

Without the issue:
Side A:
9: nm-default: <POINTOPOINT,NOARP,UP,LOWER_UP> mtu 1420 qdisc noqueue state UNKNOWN group default qlen 1000
    link/none 
    inet 10.10.10.2/24 scope global nm-default
       valid_lft forever preferred_lft forever
Side B:
6: nm-default: <POINTOPOINT,NOARP,UP,LOWER_UP> mtu 1420 qdisc noqueue state UNKNOWN group default qlen 1000
    link/none 
    inet 10.10.10.1/24 scope global nm-default
       valid_lft forever preferred_lft forever

With the issue:
Side A:
7: nm-default: <POINTOPOINT,NOARP,UP,LOWER_UP> mtu 1420 qdisc noqueue state UNKNOWN group default qlen 1000
    link/none 
    inet 10.10.10.1/24 scope global nm-default
       valid_lft forever preferred_lft forever
    inet 10.10.10.2/24 scope global secondary nm-default
       valid_lft forever preferred_lft forever

Side B:
5: nm-default: <POINTOPOINT,NOARP,UP,LOWER_UP> mtu 1420 qdisc noqueue state UNKNOWN group default qlen 1000
    link/none 
    inet 10.10.10.2/24 scope global nm-default
       valid_lft forever preferred_lft forever
    inet 10.10.10.3/24 scope global secondary nm-default
       valid_lft forever preferred_lft forever

While checking using the command:
curl -H "Authorization: Bearer YOUR_SECRET_KEY" http://localhost:8081/api/nodes | jq

It will still show only 2 nodes but with their IP's changed to the either one of the duplicate's or the new ones.

**Comment by afeiszli** [comment]
Fixed in 0.7
