### ISSUE TITLE
Network Access Keys - do you leave it at "0" if you don't want the key to expire?

### ISSUE THREAD

**Issue by bmullan** [gravitl/netmaker#134]
There may be  use-cases where you don't want the Network Access Key to expire?   Lab, internal-only network etc.

If its left a "0" does that set it to don't expire?

**Comment by mattkasun** [comment]
If it is left at zero, it will be automatically set to 1.
number of uses is stored as int so you can set it to a very large number.

**Comment by bmullan** [comment]
What if you just used "0" to indicate "no expiration" instead of changing it to "1" ?

**Comment by afeiszli** [comment]
There is no option to have an "unexpiring" key right now. But you can set an arbitrarily large number of uses (10000000000000000), which should accomplish the same goal.
