### ISSUE TITLE
[Bug]: documentation links broken on latest update

### ISSUE THREAD

**Issue by axlroden** [gravitl/netmaker#1371]
### What happened?

(https://k8s.netmaker.org/deployment.html
Seems like some documentation broke on this update (links to files that don't exist anymore.)

### Version

v0.14.5

### What OS are you using?

Linux

### Contributing guidelines

- [X] Yes, I did.

**Comment by afeiszli** [comment]
please open docs-related issues in the appropriate repo: https://github.com/gravitl/netmaker-k8s-docs/
