### ISSUE TITLE
Server/Client install script fails with dual mac address

### ISSUE THREAD

**Issue by MikePadge** [gravitl/netmaker#139]
When creating an access key to add the server as a client to itself
And running the script output on the Netmaker client/server - the client install script attempts fails on: 

Error installing:  rpc error: code = Unknown desc = Key: 'Node.MacAddress' Error:Field validation for 'MacAddress' failed on the 'macaddress_unique' tag

This could be either due to failed cleanup install failure on the previous run; Where the cleanup occurs locally, but the mac address and initial connection attempt is not cleaned from the database? 

or possibly the client just recognizing the servers mac address as its own, and does not liek

-- I re-ran it again, (I think I cleaned everything up before I did), and it failed with the doubled up macs again. So this does seem to be the server and client both claiming the same mac address? I could be wrong. 

Note: I also deleted the key from the UI as well, before I created a new one for testing. 
I ran into the following issue.

* Because I manually edited /etc/netmaker/config/environments/dev.yaml to include the WAN IP address of the netmaker 
server, the server/client was no longer set as localhost in the access key creation base64 encoded output

so I decoded it, removed the "localNetwork" designation from the end, and changed the wan IP address to localhost:127.0.0.1, I tried both separately, re-encoded it and used it as the key in sudo curl netclient install command. 
This failed on the dual mac issue both attempts as well.

**Comment by SiM22** [comment]
i am getting the same thing on an instance i have.

```
2021/11/01 21:57:49 [netclient] error installing: rpc error: code = Unknown desc = Key: 'Node.MacAddress' Error:Field validation for 'MacAddress' failed on the 'macaddress_unique' tag
2021/11/01 21:57:49 Failed to authenticate: rpc error: code = Unauthenticated desc = Something went wrong with Auto Login: rpc error: code = Unknown desc = crypto/bcrypt: hashedPassword is not the hash of the given password
2021/11/01 21:57:49 [netclient] removed homev1 network locally
2021/11/01 21:57:50 [netclient] removed systemd remnants if any existed
2021/11/01 21:57:50 [netclient] removed systemd remnants if any existed
```

I do only have one physical NIC, the rest are virtual so maybe there is a tweak that can be made to the installer to define a specific NIC?

**Comment by afeiszli** [comment]
I'm going to put this as closed since we have changed the server client model since this was written, and the netmaker client is now automagically managed inside the container.
