### ISSUE TITLE
[Bug]: systemctl daemon-reload missing on apt upgrade for netclient client

### ISSUE THREAD

**Issue by pquan** [gravitl/netmaker#1390]
### Contact Details

use the ticket ;)

### What happened?

When updating the netclient binary (from 14.4 to 14.5 in my case) a new systemd service file is generated. The required "systemctl daemon-reload" command is never executed, so systemctl fails to manage the service until a reboot or manually executing the command.
```
# systemctl restart netclient
Warning: The unit file, source configuration file or drop-ins of netclient.service changed on disk. Run 'systemctl daemon-reload' to reload units.
# systemctl daemon-reload
# systemctl restart netclient
--> OK!
```

### Version

v0.14.5

### What OS are you using?

Linux

### Contributing guidelines

- [X] Yes, I did.

**Comment by mattkasun** [comment]
apt package netclient 0.14.5-2 now available with fix
