### ISSUE TITLE
[Bug]: content of /etc/hosts gets deleted with netclient update (14.4->14.5)

### ISSUE THREAD

**Issue by pmffromspace** [gravitl/netmaker#1394]
### What happened?

Please do not delete the content of the /etc/hosts file when netclient gets upgraded. Please only edit the section of netclient at the end of the file. This is really disturbing if any other services depend on that file.

Thanks.

### Version

v0.14.5

### Contributing guidelines

- [X] Yes, I did.

**Comment by crustulumtheoneandonly** [comment]
Attention:

I noticed that at every reboot, the /etc/hosts file gets deleted.

(systemctl netclient enabled)

This issue turned out to be a much bigger problem than I expected.

is it possible to just edit the lines below The user generated entries?

**Comment by mattkasun** [comment]
I cannot seem to duplicate behaviour where /etc/hosts file gets deleted on reboot.   Maybe it has something to do with network names.  Could you provide the names of the networks that your node is connected to?

**Comment by crustulumtheoneandonly** [comment]
The network name is "global-c".

Also I do run a /etc/crontab entry every 30 minutes to run the command "netclient daemon" as root to update the node.

**Comment by mattkasun** [comment]
netclient daemon runs forever; so you are starting multiple copies of netclient, It could be that the multiple copies are clobberring each other when updating /etc/hosts

**Comment by crustulumtheoneandonly** [comment]
oh ok. My fault. Sorry for wrong set up.
Will remove the crontab and reboot.

**Comment by crustulumtheoneandonly** [comment]
I need to correct myselft. My crontab command was "timeout 30 netclient daemon"

**Comment by mattkasun** [comment]
#1401 should prevent going forward

**Comment by afeiszli** [comment]
Fixed in v0.14.6
