### ISSUE TITLE
[Bug]: "netclient leave" terminates "netclient daemon" even if other other networks are active on the client

### ISSUE THREAD

**Issue by vitex** [gravitl/netmaker#1396]
### What happened?

Executing version v0.14.5 of `netclient leave` seems to always terminate `netclient daemon`, even if the client is also a member of a second network. Thus dashboard updates from the second network are not received unless the user manually restarts `netclient daemon`. This behavior happens if the client is a member of multiple networks hosted by a single server or by multiple servers.

### Version

v0.14.5

### What OS are you using?

Linux

### Contributing guidelines

- [X] Yes, I did.

**Comment by afeiszli** [comment]
This should be fixed as of 0.15.1
