### ISSUE TITLE
[Bug]: documentation error - Install without Docker secrtion

### ISSUE THREAD

**Issue by bmullan** [gravitl/netmaker#1403]
### Contact Details

bmullan.mail@gmail.com

### What happened?

Documentation says:

`curl -sfL https://raw.githubusercontent.com/gravitl/netmaker/master/scripts/netmaker-server.sh `

should be:

`curl -sfL https://raw.githubusercontent.com/gravitl/netmaker/tree/master/scripts/netmaker-server.sh `

### Version

v0.14.5

### What OS are you using?

Linux

### Contributing guidelines

- [X] Yes, I did.

**Comment by bmullan** [comment]
After working on this for a bit I think there are several documentation errors in the section:

**`https://docs.netmaker.org/server-installation.html#linux-install-without-docker`**

Has anyone verified the commands listed?

thanks
brian

**Comment by mattkasun** [comment]
I am guessing that the last time there were verified was probably around version 0.9.x or 0.10.x.

Everyone seems to be using docker so keeping that section of the documents up to date does not merit high priority.

**Comment by terrytriplett** [comment]
> Everyone seems to be using docker so keeping that section of the documents up to date does not merit high priority

Maybe there's a little bit of a chicken vs egg situation going on here?  The project members and interested parties favor Docker so the Docker documentation is maintained and Docker installs work better.  Non-Docker documentation is way out of date and under-maintained, so anyone attempting an install directly onto the OS immediately experiences pain and frustration, so tries again with the Docker install which works ...

:-)

**Comment by afeiszli** [comment]
Non-docker instructions were updated a few weeks ago, so I'm closing this for now. Check them out here: https://docs.netmaker.org/server-installation.html#linux-install-without-docker

**Comment by bmullan** [comment]
Oh well thanks anyway.
The errors I saw just seemed related to NOT having the right "paths" to
files in the 2 command examples ?

That to me shouldn't seem to take a lot of maintainer time to correct...

Especially if you know your GitHub repository's layout !

Docker isn't a good option for everybody.

Brian
