### ISSUE TITLE
[Bug]: Windows service fails to start with 0.14.6

### ISSUE THREAD

**Issue by pellz0r** [gravitl/netmaker#1427]
### What happened?

After upgrading the Windows netclient to 0.14.6 the service fails to start (Error 1067: The process terminated unexpectedly). Nothing of value is seen in the Windows event viewer, but running 'netclient daemon' from CMD throws the following:

`C:\Program Files (x86)\Netclient>netclient daemon
[netclient.exe] 2022-07-27 22:47:51 netclient.exe is in proper location, C:\Program Files (x86)\Netclient\netclient.exe
2022/07/27 22:47:51 Gravitl Netclient on Windows started
[netclient.exe] 2022-07-27 22:47:51 [daemon.go-46] Daemon(): netclient daemon started -- version: v0.14.6
[netclient.exe] 2022-07-27 22:47:51 [clientconfig.go-22] UpdateClientConfig(): checking for netclient updates...
[netclient.exe] 2022-07-27 22:47:51 [clientconfig.go-48] UpdateClientConfig(): finished updates
2022/07/27 22:47:51 pid tracking not supported on windows`

Guessing that the pid tracking is the culprit as netclient seem to terminate after that line.

### Version

v0.14.6

### What OS are you using?

Windows

### Contributing guidelines

- [X] Yes, I did.

**Comment by knd775** [comment]
I can confirm this. It happened on multiple windows devices here. Linux devices are fine.

**Comment by afeiszli** [comment]
hotfix is merged in https://github.com/gravitl/netmaker/pull/1429

We will have updated Windows binaries/installer later tonight or tomorrow morning

**Comment by afeiszli** [comment]
fixed via hotfix #1429
