### ISSUE TITLE
[Bug]: open /sbin/netclient: text file busy

### ISSUE THREAD

**Issue by cirrusflyer** [gravitl/netmaker#1435]
### What happened?

After successfully installing on FreeBSD using this:

curl -sfL https://raw.githubusercontent.com/gravitl/netmaker/master/scripts/netclient-install.sh | sudo VERSION="0.14.6" sh -

Ran the join command with my key (removed for posting here)

sudo netclient join -t

Results below (and redacted info), but see the line "open /sbin/netclient: text file busy"

### Version

v0.14.6

### What OS are you using?

FreeBSD

### Relevant log output

```shell
[netclient] 2022-07-31 18:27:05 joining xxxx-net at api.xxxx.network:443 
[netclient] 2022-07-31 18:27:05 network: xxxx-net node xxxxxxxx is using port 51821 
[netclient] 2022-07-31 18:27:05 starting wireguard 
[netclient] 2022-07-31 18:27:08 network: xxxx-net sent a node update to server for node xxxxxxxx ,  xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx 
[netclient] 2022-07-31 18:27:08 updating netclient binary in  /sbin/ 
2022/07/31 18:27:08 open /sbin/netclient: text file busy
[netclient] 2022-07-31 18:27:08 error installing:  open /sbin/netclient: text file busy
```

### Contributing guidelines

- [X] Yes, I did.

**Comment by snoyiatk** [comment]
Thanks for the great project. I'm facing the same issue, and there's no additional output when specified -vvv.

**Comment by eidetic-av** [comment]
Thanks @snoyiatk I can confirm this workaround fixed the issue for me. 
```
mv /sbin/netclient /tmp/netclient
cd /tmp
./netclient install
./netclient joint -t .....
```

**Comment by abhishek9686** [comment]
netclient is no longer supported on FreeBSD
