### ISSUE TITLE
 unable to authenticate: Post   http: server gave HTTP response to HTTPS client 

### ISSUE THREAD

**Issue by chinasoftgit** [gravitl/netmaker#1437]
### What happened?

docker-compse.yml:

version: "3.4"

services:
  netmaker:
    container_name: netmaker
    image: gravitl/netmaker:v0.14.2
    volumes:
      - dnsconfig:/root/config/dnsconfig
      - sqldata:/root/data
      - /root/certs:/etc/netmaker/
    cap_add: 
      - NET_ADMIN
      - NET_RAW
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv6.conf.all.disable_ipv6=0
      - net.ipv6.conf.all.forwarding=1
    restart: always
    environment:
      SERVER_NAME: "HOST_IP"
      SERVER_HOST: "HOST_IP"
      SERVER_API_CONN_STRING: "HOST_IP:8081"
      COREDNS_ADDR: "HOST_IP"
      DNS_MODE: "on"
      SERVER_HTTP_HOST: "HOST_IP"
      API_PORT: "8081"
      CLIENT_MODE: "on"
      MASTER_KEY: "secretkey"
      CORS_ALLOWED_ORIGIN: "*"
      DISPLAY_KEYS: "on"
      DATABASE: "sqlite"
      NODE_ID: "netmaker-server-1"
      MQ_HOST: "mq"
      HOST_NETWORK: "off"
      VERBOSITY: "1"
      MANAGE_IPTABLES: "on"
      PORT_FORWARD_SERVICES: "dns"
    ports:
      - "51821-51830:51821-51830/udp"
      - "8081:8081"
  netmaker-ui:
    container_name: netmaker-ui
    depends_on:
      - netmaker
    image: gravitl/netmaker-ui:v0.14.2
    links:
      - "netmaker:api"
    ports:
      - "8082:80"
    environment:
      BACKEND_URL: "http://HOST_IP:8081"
    restart: always
  coredns:
    depends_on:
      - netmaker 
    image: coredns/coredns
    command: -conf /root/dnsconfig/Corefile
    container_name: coredns
    restart: always
    ports:
      - "127.0.0.1:53:53/udp"
      - "127.0.0.1:53:53/tcp"
    volumes:
      - dnsconfig:/root/dnsconfig
  mq:
    image: eclipse-mosquitto:2.0.11-openssl
    container_name: mq
    restart: unless-stopped
    ports:
      - "127.0.0.1:1883:1883"
      - "8883:8883"
    volumes:
      - /root/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - /root/certs/:/mosquitto/certs/
      - mosquitto_data:/mosquitto/data
      - mosquitto_logs:/mosquitto/log
volumes:
  sqldata: {}
  dnsconfig: {}
  mosquitto_data: {}
  mosquitto_logs: {}

 ./netclient join -t eyJhcGljb25uc3RyaW5nIjoiNDcuMTA0LjI0OC4xODI6ODA4MSIsIm5ldHdvcmsiOiJzZGFpY3QiLCJrZXkiOiJmNGM1YWY5OTVmMzIyMTJhIiwibG9jYWxyYW5nZSI6IiJ9
[netclient] 2022-08-02 15:33:03 joining sdaict at xxxxxxx:8081 
[netclient] 2022-08-02 15:33:03 unable to authenticate: Post "https://xxxxxx:8081/api/nodes/adm/sdaict/authenticate": http: server gave HTTP response to HTTPS client 
[netclient] 2022-08-02 15:33:05 removed systemd remnants if any existed 
[netclient] 2022-08-02 15:33:05 removed systemd remnants if any existed 

I used host IP, how can close https ?

### Version

v0.14.0

### Contributing guidelines

- [X] Yes, I did.

**Comment by afeiszli** [comment]
**You Have:** 
SERVER_NAME: "HOST_IP"

**These should be:**
SERVER_API_CONN_STRING: "api.BASE_DOMAIN:443"
SERVER_HTTP_HOST: "api.BASE_DOMAIN"
SERVER_NAME: "broker.BASE_DOMAIN"

**example:**
SERVER_API_CONN_STRING: "api.netmaker.example.com:443"
SERVER_HTTP_HOST: "api.netmaker.example.com"
SERVER_NAME: "broker.netmaker.example.com"


You must change these values, restart the server, and create new access keys.

**Comment by chinasoftgit** [comment]
I don't have a domain 。I revise it as you say, but log error:
./netclient join -t eyJhcGljb25uc3RyaW5nIjoiYXBpLm5ldG1ha2VyLmV4YW1wbGUuY29tOjQ0MyIsIm5ldHdvcmsiOiJ0ZXN0Iiwia2V5IjoiNDY3YTQzNzk3YWQ2NGM2MiIsImxvY2FscmFuZ2UiOiIifQ==
[netclient] 2022-08-02 18:49:35 joining test at api.netmaker.example.com:443 
[netclient] 2022-08-02 18:49:35 unable to authenticate: Post "http://api.netmaker.example.com:443/api/nodes/adm/test/authenticate": dial tcp: lookup api.netmaker.example.com on 127.0.0.53:53: no such host

netmaker must have domain ?  can only use host IP？

**Comment by chinasoftgit** [comment]
I don't have a domain 。I revise it as you say, but log error:
./netclient join -t eyJhcGljb25uc3RyaW5nIjoiYXBpLm5ldG1ha2VyLmV4YW1wbGUuY29tOjQ0MyIsIm5ldHdvcmsiOiJ0ZXN0Iiwia2V5IjoiNDY3YTQzNzk3YWQ2NGM2MiIsImxvY2FscmFuZ2UiOiIifQ==
[netclient] 2022-08-02 18:49:35 joining test at api.netmaker.example.com:443
[netclient] 2022-08-02 18:49:35 unable to authenticate: Post "http://api.netmaker.example.com:443/api/nodes/adm/test/authenticate": dial tcp: lookup api.netmaker.example.com on 127.0.0.53:53: no such host

netmaker must have domain ? can only use host IP？

**Comment by afeiszli** [comment]
You must have a domain, this is a requirement.
