### ISSUE TITLE
Netmaker for Multi-Tenant with same egress gateway

### ISSUE THREAD

**Issue by pete1019** [gravitl/netmaker#1439]
### What happened?

Hi,

Goal: something like a Multi-Tenancy where **multiple** _Independent_ networks can have **same** egress gateway like 192.168.2.0/24.
Right now this is not not possible since only one route (egress gateway) of 192.168.2.0/24 would be possible. Not multiple.

For that: manual docker commands (different port for every tenant) might be needed or would there be something easy in CLI or even Web-Gui be possible?

Thank a lot.

### Version

v0.14.6

### Contributing guidelines

- [x] Yes, I did.

**Comment by pete1019** [comment]
Any update on this? Thanks!

**Comment by mattkasun** [comment]
This is possible if you do not use the server as the gateway.

On each network, create a node to use as egress gateway.  Each egress gateway can only be on one network for this case.

in order to reach the egress range, other clients can only be on the network with the desired egress gateway.  suggest using netclient disconnect/connect to ensure node is on correct network.

**Comment by pete1019** [comment]
Having a connect/disconnect button on Windows Client Gui would help in this case:
https://github.com/gravitl/netmaker/issues/1601

**Comment by mattkasun** [comment]
netclient disconnect/connect can be run from a command prompt on all supported platforms

**Comment by pete1019** [comment]
Issue: netclient disconnect/connect takes a long time on windows.
Wireguard Client instead is almost instant.

**Comment by pete1019** [comment]
@abhishek9686 why was this completed?
"Multi-Tenant with same egress gateway" still not possible.
Since only one route to same subnet is possible.

**Comment by pete1019** [comment]
> > @abhishek9686 why was this completed? "Multi-Tenant with same egress gateway" still not possible. Since only one route to same subnet is possible.
> 
> you can add multiple egress ranges on an egress gateway

Yes but you can not have the sampe egress gateway like 192.168.2.0/24 on Network A and Network B

**Comment by abhishek9686** [comment]
> > > @abhishek9686 why was this completed? "Multi-Tenant with same egress gateway" still not possible. Since only one route to same subnet is possible.
> > 
> > 
> > you can add multiple egress ranges on an egress gateway
> 
> Yes, but you can not have the same egress gateway like 192.168.2.0/24 on Network A and Network B

Do you have same clients part of network A and network B?

**Comment by pete1019** [comment]
@abhishek9686 thanks for asking.

No, we just use this setup to give remote help. So only connected to one at the time.
Since the route 192.168.2.0/24 is added to the routes of Netmaker, it can only be there once per Netmaker Network.
But sure, multiple Networks can have 192.168.2.0/24 in their local network. But Netmaker can not handle it.
