### ISSUE TITLE
netclient join  error dial tcp: lookup no such host 

### ISSUE THREAD

**Issue by huangfxx** [gravitl/netmaker#1440]
### Contact Details

13717723877@163.com

### What happened?

![image](https://user-images.githubusercontent.com/62193722/182589381-4f90bfe6-3bd6-45c1-8864-ce7397ea1182.png)
![image](https://user-images.githubusercontent.com/62193722/182589661-c1b42dad-5c36-4b00-8b75-7c8eb7a0d397.png)

### Version

v0.14.5

### What OS are you using?

Linux

### Relevant log output

```shell
[netclient] 2022-08-03 18:42:38 joining net at api.wg-test.teddymobile.net:443 
[netclient] 2022-08-03 18:42:38 error installing:  error creating node Post "https://api.wg-test.teddymobile.net:443/api/nodes/net": dial tcp: lookup api.wg-test.teddymobile.net on 103.224.222.222:53: no such host 
[netclient] 2022-08-03 18:42:38 removed systemd remnants if any existed
```

### Contributing guidelines

- [X] Yes, I did.

**Comment by Milokita** [comment]
I encoutered the same error on both netclient windows version 0.14.5 and 0.14.6, I tried to add api.example.com to the host files still reports the same error.

**Comment by abhishek9686** [comment]
> I encoutered the same error on both netclient windows version 0.14.5 and 0.14.6, I tried to add api.example.com to the host files still reports the same error.

@Milokita please give it a try on the latest version
