### ISSUE TITLE
[Bug]: Disabling nat on egress gateway not working 

### ISSUE THREAD

**Issue by Userb31** [gravitl/netmaker#1445]
### Contact Details

userb31@protonmail.com

### What happened?

PR (#1399) added the ability for users to disable source natting for egress gateways. The feature does not seem to be working i.e. the wg config of egress node still contains the nat rules: "iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE", "iptables -t nat -D POSTROUTING -o eth0 -j MASQUERADE". Deleting and recreating the egress does not fix this issues. Also, the logs do not give valuable input into what is failing.

### Version

v0.14.6

### What OS are you using?

Linux

### Contributing guidelines

- [X] Yes, I did.

**Comment by mattkasun** [comment]
fixed in v0.16.0

**Comment by Userb31** [comment]
Can confirm this is now working as it should
