### ISSUE TITLE
[Bug]: Download Link in Install Shell Script Returns 404

### ISSUE THREAD

**Issue by Torsitano** [gravitl/netmaker#1454]
### Contact Details

shawn.torsitano@gmail.com

### What happened?

I was attempting to install netmaker using the [Linux Install Without Docker](https://docs.netmaker.org/server-installation.html#linux-install-without-docker) instructions, but am running into an error.

The script includes the following command:
```shell
wget -O /etc/netmaker/netmaker https://github.com/gravitl/netmaker/releases/download/latest/netmaker
```

This command results in the following error:
```shell
--2022-08-09 09:16:43--  https://github.com/gravitl/netmaker/releases/download/latest/netmaker
Resolving github.com (github.com)... 140.82.113.3
Connecting to github.com (github.com)|140.82.113.3|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2022-08-09 09:16:44 ERROR 404: Not Found.
```

Attempting to navigate to that URL in the browser also results in a 404.

### Version

v0.14.6

### What OS are you using?

Linux

### Relevant log output

```shell
--2022-08-09 09:16:43--  https://github.com/gravitl/netmaker/releases/download/latest/netmaker
Resolving github.com (github.com)... 140.82.113.3
Connecting to github.com (github.com)|140.82.113.3|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2022-08-09 09:16:44 ERROR 404: Not Found.
```

### Contributing guidelines

- [X] Yes, I did.

**Comment by mattkasun** [comment]
https://github.com/gravitl/netmaker/releases/download/v0.14.6/netmaker

**Comment by mattkasun** [comment]
Docs for advanced server install have been updated.
