### ISSUE TITLE
[Bug]: error installing client on opnsense

### ISSUE THREAD

**Issue by lndlw** [gravitl/netmaker#1459]
### What happened?

After successfully installing the client using the code below on opnsense (OPNsense 22.7.1-amd64
FreeBSD 13.1-RELEASE). I tried joining my node which is running on a vps. It throws the below mentioned error.

curl -sfL https://raw.githubusercontent.com/gravitl/netmaker/master/scripts/netclient-install.sh | VERSION="0.14.6" sh -

### Version

v0.14.6

### What OS are you using?

FreeBSD

### Relevant log output

```shell
ifconfig nm-netmaker mtu 1280 [#] ifconfig nm-netmaker up [#] route -q -n add -inet 10.101.255.254/32 -interface nm-netmaker [#] route -q -n add -inet 10.101.0.2/32 -interface nm-netmaker [#] route -q -n add -inet 10.101.0.1/32 -interface nm-netmaker [#] ifconfig nm-netmaker destroy [netclient] 2022-08-16 10:02:48 error running command: wg-quick up /etc/netclient/config/nm-netmaker.conf [netclient] 2022-08-16 10:02:48 [#] ifconfig wg create name nm-netmaker [#] wg setconf nm-netmaker /dev/stdin [#] ifconfig nm-netmaker inet 10.101.0.3 alias ifconfig: WARNING: setting interface address without mask is deprecated, default mask may not be correct. [#] ifconfig nm-netmaker m
```

### Contributing guidelines

- [X] Yes, I did.

**Comment by afeiszli** [comment]
I do not see an error in your logs, just a Warning. What is the error?

**Comment by lndlw** [comment]
`ifconfig nm-netmaker destroy
[netclient] 2022-08-27 11:41:37 error running command: wg-quick up /etc/netclient/config/nm-netmaker.conf
[netclient] 2022-08-27 11:41:37 [#] ifconfig wg create name nm-netmaker
[#] wg setconf nm-netmaker /dev/stdin
[#] ifconfig nm-netmaker inet 10.101.0.4 alias
ifconfig: WARNING: setting interface address without mask is deprecated,
default mask may not be correct.
[#] ifconfig nm-netmaker mtu 1280
[#] ifconfig nm-netmaker up
[#] route -q -n add -inet 10.101.255.254/32 -interface nm-netmaker
[#] route -q -n add -inet 10.101.0.3/32 -interface nm-netmaker
[#] route -q -n add -inet 10.101.0.2/32 -interface nm-netmaker
[#] route -q -n add -inet 10.101.0.1/32 -interface nm-netmaker
[#] ifconfig nm-netmaker destroy
[netclient] 2022-08-27 11:41:38 deleted node opnsenseankittulsianin  on network  netmaker
[netclient] 2022-08-27 11:41:38 error running command: wg-quick down /etc/netclient/config/nm-netmaker.conf
[netclient] 2022-08-27 11:41:38 wg-quick: `nm-netmaker' is not a WireGuard interface
[netclient] 2022-08-27 11:41:39 error running command:  service netclient stop
[netclient] 2022-08-27 11:41:39`

**Comment by lndlw** [comment]
> I do not see an error in your logs, just a Warning. What is the error?

`netclient] 2022-08-27 11:41:38 deleted node opnsenseankittulsianin  on network  netmaker
[netclient] 2022-08-27 11:41:38 error running command: wg-quick down /etc/netclient/config/nm-netmaker.conf
[netclient] 2022-08-27 11:41:38 wg-quick: `nm-netmaker' is not a WireGuard interface
[netclient] 2022-08-27 11:41:39 error running command:  service netclient stop
[netclient] 2022-08-27 11:41:39`

**Comment by abhishek9686** [comment]
we no longer support netclient on FreeBSD, instead, you can generate wireguard VPN configuration for your netmaker network and connect your FreeBSD machine to the VPN. https://docs.netmaker.io/external-clients.html
