### ISSUE TITLE
[Bug]: Invalid OAuth State on Kubernetes

### ISSUE THREAD

**Issue by 0xADD1E** [gravitl/netmaker#1477]
### Contact Details

github-netmaker@0xADD1E.me

### What happened?

When running more than one replica of the API service, OAuth (and Azure AD) authentication fail with the message "invalid OAuth state" consistently. 

When scaling down to a single replica, the issue is no longer present (at the cost of reduced availability)

### Version

v0.14.6

### What OS are you using?

Linux

### Relevant log output

```shell
[netmaker] 2022-08-24 11:25:25 error when getting user info from callback: invalid OAuth state 
[netmaker] 2022-08-24 11:25:26 processed request error: error verifying user token
```

### Contributing guidelines

- [X] Yes, I did.

**Comment by 0xdcarns** [comment]
This is fixed in the upcoming release, which is slated for this week.

**Comment by 0xADD1E** [comment]
Ah- I'd looked through issues, but apparently missed PR #1444
