### ISSUE TITLE
[Bug]: two endpoints behind nat can not handshake

### ISSUE THREAD

**Issue by thanatos40** [gravitl/netmaker#1501]
### What happened?

I have three endpoints one is a cloud server and the other two are pcs with udp hole punching enabled in different nat. The three one all have registered in netmaker, this two endpoints behind nat can successfully handshake with cloud server，but can not handshake with each other. My question is, can this scenario worked if so, what have I miss?  Or I have to make the cloud server as a relay server so that this two can communicate with each other？

one of my pc：
![image](https://user-images.githubusercontent.com/68845284/187733129-629ebc9e-3815-4f94-825f-cd792a5b59ef.png)

netmaker-server：
![image](https://user-images.githubusercontent.com/68845284/187733365-7311137d-5d11-458b-b026-6e7dc4c72bd4.png)

my cloud server
![image](https://user-images.githubusercontent.com/68845284/187733929-0b6efe07-ed32-46cf-b11a-916fce991b58.png)

my other pc
![image](https://user-images.githubusercontent.com/68845284/187734290-6905ca7c-2731-4cd1-b5b3-0f82145ae1d4.png)

### Version

v0.14.6

### What OS are you using?

Linux, Windows

### Contributing guidelines

- [X] Yes, I did.

**Comment by mattkasun** [comment]
As long as the peers are behind a simple NAT, it should just work.  Double NAT or CGNAT may require a relay of one or both peers

**Comment by thanatos40** [comment]
I used some tools to determine the two endpoints's nat type and found out they weren't the same nat type, one was port restricted cone and the other was symmetric. Since they weren't the same nat type, I used netmaker-1 as a relay server, they could now communicate with each other. But I met another problem, one of my pcs are egress gateway, I couldn't ping the subnet, but egress gateway could, did I miss something?

![image](https://user-images.githubusercontent.com/68845284/188062384-80a984c8-edb8-4b93-bf05-75de1d3f1131.png)

![image](https://user-images.githubusercontent.com/68845284/188062501-3cbe0ee2-fff7-41d2-b91f-8875dfadef06.png)

**Comment by varoudis** [comment]
@thanatos40 can you advise on the tools and troubleshooting you did? I have a similar problem and two systems behind nat wont handshake. One has port forwarding (via Pfsense fw) and the other one is on LTE router.

**Comment by lexbritvin** [comment]
I face the similar issue with UDP Hole punching (v0.15.2).
I'm behind CGNAT on both sides.
But I noticed that Tailscale can actually establish the direct connection. 
Is there a way to troubleshoot it on Netmaker? 
I believe there is a way to fix this in Netmaker if Tailscale can make it.

**Comment by lexbritvin** [comment]
I was able to resolve the issue in the following way:
1. Go to Nodes
2. Edit every node that's behind NAT
3. Toggle Dynamic port to On (it was disabled in my case, some why).
4. Save

That's it! I have working connection behind CGNAT and home router. My home router is set to NAT Full cone.
