### ISSUE TITLE
ports occupied and how to port forward 

### ISSUE THREAD

**Issue by tompatulpan** [gravitl/netmaker#151]
Hi,
Im trying to setup netmaker on a local server for testing using the docker image.
port 80 and 53 are occupied to another local server.

Iv tried some different yaml configs but have not tottaly succeeded.

    ports:
      - "8880:80"
    environment:
      BACKEND_URL: "http://my-ip:8881"
    ports:
      - "8853:53/udp"

firewall port forward
my-ip:8881 -> local-ip:8880 ??
my-ip:8853 -> local-ip:8853 ??

Always a bit confusing doing this to me, so any help would be much appropriated!

**Comment by afeiszli** [comment]
Hi @tompatulpan that looks right but depends on some other factors as well. Can you please share the full docker-compose file?

I would also not recommend running DNS on a non-53 port. While it will run, I have not succeeded in getting machines to successfully use a nameserver that isn't running on 53. But if you know a good way to do it, I'd like to hear it!

**Comment by tompatulpan** [comment]
Ok, thanks for the tip and answer!
I did run the your default docker file without any changes.

**Comment by afeiszli** [comment]
What are the errors you encountered? Can you post any logs?

**Comment by afeiszli** [comment]
Closing without response.
