### ISSUE TITLE
Package for oe-alliance-core (for Enigma2 STB's)

### ISSUE THREAD

**Issue by estimadarocha** [gravitl/netmaker#1516]
### Contact Details

estimadarocha@gmail.com

### What happened?

I move recently to netmaker but i am fighting the missing integration on https://github.com/oe-alliance/oe-alliance-core so that it could be integrated and installed on Enigma2 stb's. I did ask on some forums about those devices and the feature will be very welcome.

Could someone look into it?

I can help on testing.

Thanks

### Version

Not listed

### Contributing guidelines

- [X] Yes, I did.

**Comment by afeiszli** [comment]
You're welcome to develop a community package but this is out of scope for the core team to develop. I will leave this open for a while in case anyone else is interested in picking it up or commenting.

**Comment by afeiszli** [comment]
Given there have been no other comments and the Netmaker team is not supporting this, I am closing this issue.
