### ISSUE TITLE
[Bug]: netclient service can delay boot on systemd distributions not otherwise using systemd-networkd

### ISSUE THREAD

**Issue by bsherman** [gravitl/netmaker#1524]
### Contact Details

bsherman on github and discord

### What happened?

After installing `netclient` on my Fedora 36 desktop and laptop I noticed that booting was taking a long time... 

Upon inspection, I found that `netclient.service` wants `systemd-networkd-wait-online.service` and this is hanging on my machines, making boot last an extra 2 minutes.

I believe this status helps to illustrate the problem:
```
$ systemctl status systemd-networkd
● systemd-networkd.service - Network Configuration
     Loaded: loaded (/usr/lib/systemd/system/systemd-networkd.service; disabled; vendor preset: disabled)
     Active: active (running) since Tue 2022-09-06 23:03:17 CDT; 5min ago
TriggeredBy: ● systemd-networkd.socket
       Docs: man:systemd-networkd.service(8)
   Main PID: 943 (systemd-network)
     Status: "Processing requests..."
      Tasks: 1 (limit: 76792)
     Memory: 3.3M
        CPU: 21ms
     CGroup: /system.slice/systemd-networkd.service
             └─ 943 /usr/lib/systemd/systemd-networkd

Sep 06 23:03:17 anduril systemd[1]: Starting systemd-networkd.service - Network Configuration...
Sep 06 23:03:17 anduril systemd-networkd[943]: lo: Link UP
Sep 06 23:03:17 anduril systemd-networkd[943]: lo: Gained carrier
Sep 06 23:03:17 anduril systemd-networkd[943]: Enumeration completed
Sep 06 23:03:17 anduril systemd[1]: Started systemd-networkd.service - Network Configuration.
Sep 06 23:03:18 anduril systemd-networkd[943]: enp3s0: Link UP
Sep 06 23:03:22 anduril systemd-networkd[943]: enp3s0: Gained carrier
Sep 06 23:03:24 anduril systemd-networkd[943]: enp3s0: Gained IPv6LL
Sep 06 23:05:17 anduril systemd-networkd[943]: nm-csgw: Link UP
Sep 06 23:05:17 anduril systemd-networkd[943]: nm-csgw: Gained carrier
```
And this output...
```
$ networkctl 
IDX LINK    TYPE      OPERATIONAL SETUP    
  1 lo      loopback  carrier     unmanaged
  2 enp3s0  ether     routable    unmanaged
  3 nm-csgw wireguard routable    unmanaged

3 links listed.
```

Netclient wants `systemd-networkd-wait-online` which means that it forces the `systemd-networkd` service to start and wait for a managed link to come online...  it times out after 2 minutes because there are no `networkd` managed links.  Even netclient/wireguard isn't using networkd, though that link comes online and shows in the status after the timeout due to the "Wants".

I found one somewhat authoritative comment on the matter... 
> It seems no interface is managed by networkd. systemd-networkd-wait-online.service is usable only when some interfaces are managed by systemd-networkd.
https://github.com/systemd/systemd/issues/23304#issuecomment-1120733061

With this in mind, it definitely seems to be a bug in this service file, at least on a host which is not running systemd-networkd.  Closer inspection of both `NetworkManager-wait-online` and `systemd-networkd-wait-online` seems that either will delay the `network-online.target` until the respective service believes the host is online, but only if that network management service is enabled.

I suggest that `systemd-networkd-wait-online.service` simply be removed from the Unit as that would be the most generic solution. 

I'm happy to provide the simple PR and test it on a few different distributions (fedora, rocky, debian, ubuntu, arch). 

### Version

v0.15.0

### What OS are you using?

Linux

### Contributing guidelines

- [X] Yes, I did.

**Comment by mattkasun** [comment]
#1543

**Comment by afeiszli** [comment]
Closing
