### ISSUE TITLE
[Bug]: Netclient not forgetting when removing

### ISSUE THREAD

**Issue by doodlemania2** [gravitl/netmaker#1538]
### Contact Details

me@derekmartin.org

### What happened?

A bug happened!

After the recent upgrade, one of my nodes was having troubles, so I started with a ping from one node to another node over the overlay network (10.11.12.0/24)

root@doodlemanage:/home/derek# ping 10.11.12.4
PING 10.11.12.4 (10.11.12.4) 56(84) bytes of data.
^C
--- 10.11.12.4 ping statistics ---
6 packets transmitted, 0 received, 100% packet loss, time 5102ms

root@doodlemanage:/home/derek# ip address
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
2: enp6s18: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP group default qlen 1000
    link/ether 66:c4:ef:1d:55:a1 brd ff:ff:ff:ff:ff:ff
    inet 192.168.1.12/24 brd 192.168.1.255 scope global enp6s18
       valid_lft forever preferred_lft forever
    inet6 --removed-- scope link
       valid_lft forever preferred_lft forever
3: docker0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default
    link/ether 02:42:ed:de:7a:22 brd ff:ff:ff:ff:ff:ff
    inet 172.17.0.1/16 brd 172.17.255.255 scope global docker0
       valid_lft forever preferred_lft forever
    inet6 fe80::42:edff:fede:7a22/64 scope link
       valid_lft forever preferred_lft forever
5: veth0089fd4@if4: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue master docker0 state UP group default
    link/ether 4a:63:a5:48:c1:a6 brd ff:ff:ff:ff:ff:ff link-netnsid 0
    inet6 --removed-- scope link
       valid_lft forever preferred_lft forever

Odd, the interface isn't there!
Maybe netclient needs daemon going

root@doodlemanage:/home/derek# netclient daemon &
[1] 26969
root@doodlemanage:/home/derek# [netclient] 2022-09-09 16:42:50 [daemon.go-49] Daemon(): netclient daemon started -- version: v0.15.1
[netclient] 2022-09-09 16:42:50 [clientconfig.go-22] UpdateClientConfig(): checking for netclient updates...
[netclient] 2022-09-09 16:42:50 [clientconfig.go-51] UpdateClientConfig(): finished updates
[netclient] 2022-09-09 16:42:50 [daemon.go-95] startGoRoutines(): initializing network DoodleNet
[netclient] 2022-09-09 16:42:50 [mqpublish.go-27] Checkin(): starting checkin goroutine
[netclient] 2022-09-09 16:42:50 [netclientutils_linux.go-18] RunCmd(): error running command: wg-quick up /etc/netclient/config/nm-DoodleNet.conf
[netclient] 2022-09-09 16:42:50 [netclientutils_linux.go-19] RunCmd(): [#] ip link add nm-DoodleNet type wireguard
[#] wg setconf nm-DoodleNet /dev/fd/63
Line unrecognized: `10.11.12.3/32,10.11.12.7/32,10.11.12.6/32'
Configuration parsing error
[#] ip link delete dev nm-DoodleNet
[netclient] 2022-09-09 16:42:50 [daemon.go-110] startGoRoutines(): started daemon for server  --removed--
[netclient] 2022-09-09 16:42:50 [daemon.go-113] startGoRoutines(): error setting route for netmaker: exit status 2
[netclient] 2022-09-09 16:42:50 [daemon.go-196] messageQueue(): network: DoodleNet netclient message queue started for server: --removed--
[netclient] 2022-09-09 16:42:51 [daemon.go-158] setSubscriptions(): subscribed to node updates for node doodlemanage update/DoodleNet/1e0df654-64b9-4d68-a23c-7bb123174469
[netclient] 2022-09-09 16:42:51 [daemon.go-163] setSubscriptions(): subscribed to peer updates for node doodlemanage peers/DoodleNet/1e0df654-64b9-4d68-a23c-7bb123174469
[netclient] 2022-09-09 16:42:51 [mqhandlers.go-214] UpdatePeers(): error updating wireguard peerskey-value delimiter not found: 10.11.12.3/32, 10.11.12.7/32, 10.11.12.6/32

[netclient] 2022-09-09 16:42:58 [mqhandlers.go-214] UpdatePeers(): error updating wireguard peerskey-value delimiter not found: 10.11.12.3/32, 10.11.12.7/32, 10.11.12.6/32

[netclient] 2022-09-09 16:43:50 [mqpublish.go-43] checkin(): checkin with server(s) for all networks
[netclient] 2022-09-09 16:43:50 [mqpublish.go-134] Hello(): checkin for DoodleNet complete

That's not so good, I don't like errors, let's see if it created the interface:

root@doodlemanage:/home/derek# ifconfig
docker0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 172.17.0.1  netmask 255.255.0.0  broadcast 172.17.255.255
        inet6 fe80::42:edff:fede:7a22  prefixlen 64  scopeid 0x20<link>
        ether 02:42:ed:de:7a:22  txqueuelen 0  (Ethernet)
        RX packets 659153  bytes 160630440 (160.6 MB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 859360  bytes 109046951 (109.0 MB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

enp6s18: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 192.168.1.12  netmask 255.255.255.0  broadcast 192.168.1.255
        inet6 --removed--  prefixlen 64  scopeid 0x20<link>
        ether 66:c4:ef:1d:55:a1  txqueuelen 1000  (Ethernet)
        RX packets 5443106  bytes 1592097466 (1.5 GB)
        RX errors 0  dropped 14  overruns 0  frame 0
        TX packets 1891046  bytes 490734145 (490.7 MB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
        inet 127.0.0.1  netmask 255.0.0.0
        inet6 ::1  prefixlen 128  scopeid 0x10<host>
        loop  txqueuelen 1000  (Local Loopback)
        RX packets 176869  bytes 13604871 (13.6 MB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 176869  bytes 13604871 (13.6 MB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

veth0089fd4: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet6 --removed--  prefixlen 64  scopeid 0x20<link>
        ether 4a:63:a5:48:c1:a6  txqueuelen 0  (Ethernet)
        RX packets 659153  bytes 169858582 (169.8 MB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 859375  bytes 109048217 (109.0 MB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

That's no good! Let's leave and rejoin the network:

root@doodlemanage:/home/derek# netclient leave
[netclient] 2022-09-09 16:44:05 used backup file for network:  all
2022/09/09 16:44:05 open /etc/netclient/config/netconfig-all: no such file or directory
root@doodlemanage:/home/derek# netclient list
{"networks":[{"name":"DoodleNet","node_id":"1e0df654-64b9-4d68-a23c-7bb123174469","current_node":{"name":"doodlemanage","interface":"nm-DoodleNet","private_ipv4":"10.11.12.2","public_endpoint":"172.58.178.236"},"peers":--removed--

That's bizzare, okay, let's try to rejoin?

root@doodlemanage:/home/derek# netclient join -t --removed--
[netclient] 2022-09-09 16:45:30 ALREADY_INSTALLED. Netclient appears to already be installed for DoodleNet. To re-install, please remove by executing 'sudo netclient leave -n DoodleNet'. Then re-run the install command.
root@doodlemanage:/home/derek# netclient leave -n DoodleNet
[netclient] 2022-09-09 16:45:38 error deleting wireguard interface error flushing routes file does not exist
[netclient] 2022-09-09 16:45:38 [mqhandlers.go-57] NodeUpdate(): network: DoodleNet received message to update node doodlemanage
[netclient] 2022-09-09 16:45:38 [mqhandlers.go-70] NodeUpdate(): network: DoodleNet  received delete request for %s doodlemanage
[netclient] 2022-09-09 16:45:38 error running command: wg-quick down /etc/netclient/config/nm-DoodleNet.conf
[netclient] 2022-09-09 16:45:38 wg-quick: `nm-DoodleNet' is not a WireGuard interface
[netclient] 2022-09-09 16:45:38 success
[netclient] 2022-09-09 16:45:38 [daemon.go-79] Daemon(): received reset
[netclient] 2022-09-09 16:45:38 [daemon.go-204] messageQueue(): shutting down message queue for server --removed--
[netclient] 2022-09-09 16:45:38 [mqpublish.go-32] Checkin(): checkin routine closed
[netclient] 2022-09-09 16:45:38 [daemon.go-82] Daemon(): restarting daemon
[netclient] 2022-09-09 16:45:38 [mqpublish.go-27] Checkin(): starting checkin goroutine
root@doodlemanage:/home/derek# [netclient] 2022-09-09 16:45:38 [daemon.go-188] unsubscribeNode(): network: DoodleNet successfully unsubscribed node  1e0df654-64b9-4d68-a23c-7bb123174469  :  doodlemanage
[netclient] 2022-09-09 16:45:38 [config.go-208] ReplaceWithBackup(): used backup file for network:  DoodleNet
[netclient] 2022-09-09 16:45:38 [mqhandlers.go-74] NodeUpdate(): failed to leave, please check that local files for network DoodleNet were removed

One more try maybe?

root@doodlemanage:/home/derek# netclient join -t --removed--
[netclient] 2022-09-09 16:45:45 joining DoodleNet at --removed--:443
[netclient] 2022-09-09 16:45:45 error installing:  error creating node 500 Internal Server Error {"Code":500,"Message":"address --removed--:--removed--:1:0:1:--removed--:--removed--:--removed--:48505: too many colons in address"}
[netclient] 2022-09-09 16:45:45 error running command: wg-quick down /etc/netclient/config/.conf
[netclient] 2022-09-09 16:45:45 wg-quick: `/etc/netclient/config/.conf' does not exist
[netclient] 2022-09-09 16:45:47 removed systemd remnants if any existed
root@doodlemanage:/home/derek# ifconfig
docker0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 172.17.0.1  netmask 255.255.0.0  broadcast 172.17.255.255
        inet6 --removed--  prefixlen 64  scopeid 0x20<link>
        ether 02:42:ed:de:7a:22  txqueuelen 0  (Ethernet)
        RX packets 659363  bytes 160679422 (160.6 MB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 859615  bytes 109076360 (109.0 MB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

enp6s18: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 192.168.1.12  netmask 255.255.255.0  broadcast 192.168.1.255
        inet6 --removed--  prefixlen 64  scopeid 0x20<link>
        ether 66:c4:ef:1d:55:a1  txqueuelen 1000  (Ethernet)
        RX packets 5445179  bytes 1592613822 (1.5 GB)
        RX errors 0  dropped 14  overruns 0  frame 0
        TX packets 1892165  bytes 490956637 (490.9 MB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
        inet 127.0.0.1  netmask 255.0.0.0
        inet6 ::1  prefixlen 128  scopeid 0x10<host>
        loop  txqueuelen 1000  (Local Loopback)
        RX packets 177071  bytes 13619527 (13.6 MB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 177071  bytes 13619527 (13.6 MB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

veth0089fd4: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet6 fe80::4863:a5ff:fe48:c1a6  prefixlen 64  scopeid 0x20<link>
        ether 4a:63:a5:48:c1:a6  txqueuelen 0  (Ethernet)
        RX packets 659363  bytes 169910504 (169.9 MB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 859630  bytes 109077626 (109.0 MB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

Darnit! Let's get whack a mole style:

root@doodlemanage:/home/derek# netclient leave -n DoodleNet
[netclient] 2022-09-09 16:46:04 used backup file for network:  DoodleNet
2022/09/09 16:46:04 open /etc/netclient/config/netconfig-DoodleNet: no such file or directory
root@doodlemanage:/home/derek# netclient list
{"networks":[]}

Cool, let's rejoing:

root@doodlemanage:/home/derek# netclient join -t --removed--
[netclient] 2022-09-09 16:46:12 joining DoodleNet at --removed--:443
[netclient] 2022-09-09 16:46:12 error installing:  error creating node 500 Internal Server Error {"Code":500,"Message":"address --removed--:--removed--:1:0:1:6d:0:1:--removed--: too many colons in address"}
[netclient] 2022-09-09 16:46:12 error running command: wg-quick down /etc/netclient/config/.conf
[netclient] 2022-09-09 16:46:12 wg-quick: `/etc/netclient/config/.conf' does not exist
[netclient] 2022-09-09 16:46:14 removed systemd remnants if any existed
root@doodlemanage:/home/derek# [netclient] 2022-09-09 16:46:38 [mqpublish.go-43] checkin(): checkin with server(s) for all networks
[netclient] 2022-09-09 16:46:38 [mqpublish.go-76] checkin(): network:  local Address has changed from    to  192.168.1.12
[netclient] 2022-09-09 16:46:38 [netclientutils.go-327] GetFileWithRetry(): failed to retrieve file  /etc/netclient/config/traffic- , retrying...
[netclient] 2022-09-09 16:46:38 [netclientutils.go-327] GetFileWithRetry(): failed to retrieve file  /etc/netclient/config/traffic- , retrying...
[netclient] 2022-09-09 16:46:39 [mqpublish.go-79] checkin(): Network:    could not publish local address change
[netclient] 2022-09-09 16:46:39 [localport.go-26] GetLocalListenPort(): failed to parse interface
[netclient] 2022-09-09 16:46:39 [localport.go-38] UpdateLocalListenPort(): network:  error encountered checking local listen port:   file does not exist
[netclient] 2022-09-09 16:46:39 [netclientutils.go-327] GetFileWithRetry(): failed to retrieve file  /etc/netclient/config/traffic- , retrying...
[netclient] 2022-09-09 16:46:39 [netclientutils.go-327] GetFileWithRetry(): failed to retrieve file  /etc/netclient/config/traffic- , retrying...
[netclient] 2022-09-09 16:46:39 [mqpublish.go-127] Hello(): Network:  error publishing ping, open /etc/netclient/config/traffic-: no such file or directory
[netclient] 2022-09-09 16:46:39 [mqpublish.go-128] Hello(): running pull on  to reconnect
[netclient] 2022-09-09 16:46:39 [mqpublish.go-131] Hello(): could not run pull on , error: no network provided - exiting
[netclient] 2022-09-09 16:46:39 [register.go-53] RegisterWithServer(): register at https:///api/server/register

Hmm, let's kill off daemon and really uninstall things:

root@doodlemanage:/home/derek# kill -9 26969

Well, now it's thinking my endpoint is self for whatever reason - definitely not per the join (copy/pasted from NetClient GUI)

root@doodlemanage:/home/derek# netclient list
{"networks":[{"name":"DoodleNet","node_id":"","current_node":{"public_endpoint":"--this was definitely the wrong address--},"peers":[]}]}

root@doodlemanage:/home/derek# netclient leave -n DoodleNet
[netclient] 2022-09-09 16:48:33 error deleting node from server unable to authenticate could not read secrets file open /etc/netclient/config/secret-DoodleNet: no such file or directory
[netclient] 2022-09-09 16:48:33 error deleting wireguard interface error flushing routes file does not exist
[netclient] 2022-09-09 16:48:33 error running command: wg-quick down /etc/netclient/config/.conf
[netclient] 2022-09-09 16:48:33 wg-quick: `/etc/netclient/config/.conf' does not exist
2022/09/09 16:48:33 SIGHUP failed -- os: process already finished

How on earth!?

root@doodlemanage:/home/derek# netclient list
{"networks":[{"name":"DoodleNet","node_id":"","current_node":{"public_endpoint":"--still definitely wrong address"},"peers":[]}]}

root@doodlemanage:/home/derek# apt remove netclient --purge
Reading package lists... Done
[netclient] 2022-09-09 16:49:38 error deleting node from server unable to authenticate could not read secrets file open /etc/netclient/config/secret-DoodleNet: no such file or directory
[netclient] 2022-09-09 16:49:38 error deleting wireguard interface error flushing routes file does not exist
[netclient] 2022-09-09 16:49:38 error running command: wg-quick down /etc/netclient/config/.conf
[netclient] 2022-09-09 16:49:38 wg-quick: `/etc/netclient/config/.conf' does not exist
[netclient] 2022-09-09 16:49:40 removed systemd remnants if any existed
[netclient] 2022-09-09 16:49:40 uninstalled netclient

root@doodlemanage:/home/derek# rm -rf /etc/netclient

Now it should be all the way really really gone and fresh
Even removed the node from NetClient GUI at this point.

root@doodlemanage:/home/derek# apt install netclient
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following NEW packages will be installed:
  netclient
0 upgraded, 1 newly installed, 0 to remove and 6 not upgraded.
Need to get 6993 kB of archives.
After this operation, 0 B of additional disk space will be used.
Get:1 https://apt.netmaker.org stable/main amd64 netclient amd64 0.15.1-0 [6993 kB]
Fetched 6993 kB in 2s (3018 kB/s)
Selecting previously unselected package netclient.
(Reading database ... 110116 files and directories currently installed.)
Preparing to unpack .../netclient_0.15.1-0_amd64.deb ...
Unpacking netclient (0.15.1-0) ...
Setting up netclient (0.15.1-0) ...

Let's join again, but should be no issue seeing any previous config:

root@doodlemanage:/home/derek# netclient join -t 
[netclient] 2022-09-09 16:51:54 ALREADY_INSTALLED. Netclient appears to already be installed for DoodleNet. To re-install, please remove by executing 'sudo netclient leave -n DoodleNet'. Then re-run the install command.
root@doodlemanage:/home/derek# cd /etc/netclient
root@doodlemanage:/etc/netclient# ls
config
root@doodlemanage:/etc/netclient# cd config
root@doodlemanage:/etc/netclient/config# ls
netconfig-DoodleNet

How on earth did it remember that? I removed and purged and deleted /etc/netclient and removed from Netclient GUI

root@doodlemanage:/etc# netclient list
{"networks":[]}
root@doodlemanage:/etc# netclient pull
[netclient] 2022-09-09 16:56:37 No network selected. Running Pull for all networks.
[netclient] 2022-09-09 16:56:37 registration error could not read secrets file open /etc/netclient/config/secret-DoodleNet: no such file or directory
2022/09/09 16:56:37 could not read secrets file open /etc/netclient/config/secret-DoodleNet: no such file or directory

Repeat process several more times - somehow it is still remembering DoodleNet

### Version

v0.15.1

### What OS are you using?

Linux

### Relevant log output

```shell
See above
```

### Contributing guidelines

- [X] Yes, I did.

**Comment by mattkasun** [comment]
if you run `netclient uninstall` it should remove all of netclient.

**Comment by doodlemania2** [comment]
Yep, but it remains!

root@doodlemanage:/etc# netclient list
{"networks":[{"name":"DoodleNet","node_id":"","current_node":{"public_endpoint":"--removed--"},"peers":[]}]}
root@doodlemanage:/etc# netclient uninstall
[netclient] 2022-09-09 17:27:11 uninstalling netclient...
[netclient] 2022-09-09 17:27:11 error deleting node from server unable to authenticate could not read secrets file open /etc/netclient/config/secret-DoodleNet: no such file or directory
[netclient] 2022-09-09 17:27:11 error deleting wireguard interface error flushing routes file does not exist
[netclient] 2022-09-09 17:27:11 error running command: wg-quick down /etc/netclient/config/.conf
[netclient] 2022-09-09 17:27:11 wg-quick: `/etc/netclient/config/.conf' does not exist
[netclient] 2022-09-09 17:27:13 removed systemd remnants if any existed
[netclient] 2022-09-09 17:27:13 uninstalled netclient
root@doodlemanage:/etc# netclient
bash: /usr/sbin/netclient: No such file or directory
root@doodlemanage:/etc# apt remove netclient
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following packages will be REMOVED:
  netclient
0 upgraded, 0 newly installed, 1 to remove and 6 not upgraded.
After this operation, 0 B of additional disk space will be used.
Do you want to continue? [Y/n] Y
(Reading database ... 110118 files and directories currently installed.)
Removing netclient (0.15.1-0) ...
root@doodlemanage:/etc# apt install netclient
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following NEW packages will be installed:
  netclient
0 upgraded, 1 newly installed, 0 to remove and 6 not upgraded.
Need to get 6993 kB of archives.
After this operation, 0 B of additional disk space will be used.
Get:1 https://apt.netmaker.org stable/main amd64 netclient amd64 0.15.1-0 [6993 kB]
Fetched 6993 kB in 3s (2686 kB/s)
Selecting previously unselected package netclient.
(Reading database ... 110116 files and directories currently installed.)
Preparing to unpack .../netclient_0.15.1-0_amd64.deb ...
Unpacking netclient (0.15.1-0) ...
Setting up netclient (0.15.1-0) ...
root@doodlemanage:/etc# netclient join -t --remove--
[netclient] 2022-09-09 17:28:18 ALREADY_INSTALLED. Netclient appears to already be installed for DoodleNet. To re-install, please remove by executing 'sudo netclient leave -n DoodleNet'. Then re-run the install command.
root@doodlemanage:/etc# cd /etc/netclient
root@doodlemanage:/etc/netclient# ls
config
root@doodlemanage:/etc/netclient#

**Comment by doodlemania2** [comment]
Had a thought - after another purge, rm of /etc/hosts I rebooted, then reinstalled netclient - check out this fun error though:

 netclient join -t --removed--
[netclient] 2022-09-09 17:39:26 joining DoodleNet at --removed:443
[netclient] 2022-09-09 17:39:26 error installing:  error creating node 500 Internal Server Error {"Code":500,"Message":"address --removed--:--removed:1:0:1:--removed--:0:1:48505: too many colons in address"}
[netclient] 2022-09-09 17:39:26 error running command: wg-quick down /etc/netclient/config/.conf
[netclient] 2022-09-09 17:39:26 wg-quick: `/etc/netclient/config/.conf' does not exist
[netclient] 2022-09-09 17:39:28 removed systemd remnants if any existed

**Comment by mattkasun** [comment]
that last one is because netclient determined that your local ip was an IPv6 address and it is not handled properly .... fix in works for that one

**Comment by doodlemania2** [comment]
Huzzah! Any way to force it down to ip4 in the interim?

**Comment by mattkasun** [comment]
manually editing the line localaddress: x.x.x.x  in /etc/netclient/config/netconfig-<network name>  should work

**Comment by doodlemania2** [comment]
thanks @mattkasun !!!

**Comment by doodlemania2** [comment]
Reopening this after updating to 0.16.0-2:

[netclient] 2022-09-26 19:24:32 joining DoodleNet at api.network.thedoodleproject.net:443
[netclient] 2022-09-26 19:24:32 error installing:  error creating node 500 Internal Server Error {"Code":500,"Message":"address 2602:ff16:4:0:1:20:0:1:58176: too many colons in address"}
[netclient] 2022-09-26 19:24:32 error running command: wg-quick down /etc/netclient/config/.conf
[netclient] 2022-09-26 19:24:32 wg-quick: `/etc/netclient/config/.conf' does not exist
[netclient] 2022-09-26 19:24:35 removed systemd remnants if any existed

**Comment by Mydreamandreality** [comment]
> Reopening this after updating to 0.16.0-2:
> 
> [netclient] 2022-09-26 19:24:32 joining DoodleNet at api.network.thedoodleproject.net:443 [netclient] 2022-09-26 19:24:32 error installing: error creating node 500 Internal Server Error {"Code":500,"Message":"address 2602:ff16:4:0:1:20:0:1:58176: too many colons in address"} [netclient] 2022-09-26 19:24:32 error running command: wg-quick down /etc/netclient/config/.conf [netclient] 2022-09-26 19:24:32 wg-quick: `/etc/netclient/config/.conf' does not exist [netclient] 2022-09-26 19:24:35 removed systemd remnants if any existed

I also encountered the same problem....

**Comment by helbgd** [comment]
I have the same issue

too many colons in address
