### ISSUE TITLE
defaultnetrange/defaultnetname aren't used

### ISSUE THREAD

**Issue by mrobinsn** [gravitl/netmaker#155]
I'm trying to change the default network setting on startup, but the `defaultnetname` & `defaultnetrange` settings in the `dev.yaml` don't seem to actually change anything.

Doesn't seem like those options are even wired into the code: https://github.com/gravitl/netmaker/blob/master/config/config.go#L37

Am I missing something or is this feature just not supported yet?

**Comment by afeiszli** [comment]
As of now those options are hardcoded. Can you please expand on your use case? 

You can delete the default network after startup and replace it with your own network, but understand that this might be needed for some automation.

**Comment by mrobinsn** [comment]
Essentially I wanted a network to be created automatically after installation with a specific range and name.

I was able to work around by using a combination of `MASTER_KEY` and the API 👍
