### ISSUE TITLE
[Bug]: Can't ping/ssh configured netclient node from local network.

### ISSUE THREAD

**Issue by ghgeiger** [gravitl/netmaker#1563]
### What happened?

Since 0.15.2, I have been unable to access a Debian Bullseye (RaspberryPi OS) netclient node on my local network from other computers. I can connect to it via a computer connected via "external client" with it's netmaker IP. After debugging several other things, I came to netclient, left the netmaker network & then I was able to access via LAN again. I tried uninstalling/reinstalling and setting up netclient again, but it again cut off access from LAN. Doing some cursory research, I've found that this can happen with a mis-configured wireguard configuration, but I don't know how to change, or even verify this with netclient.

### Version

v0.15.2

### What OS are you using?

Linux

### Contributing guidelines

- [X] Yes, I did.

**Comment by mattkasun** [comment]
what is the cidr for your lan and wireguard networks?

**Comment by ghgeiger** [comment]
Lan is 192.168.2.0/24, Netmaker is 10.10.10.0/24

**Comment by ghgeiger** [comment]
I do have a separate wg0.conf on this box at 10.10.0.0/24, but this has never been a problem in the past.

**Comment by mattkasun** [comment]
can you provide the wg config (/etc/netclient/config/nm-<network_name>.conf) and the output of ip route before and after joining a network

**Comment by mattkasun** [comment]
no response received, closing

**Comment by ghgeiger** [comment]
I apologize, I missed the notification for your previous query. I ended up removing netclient from that box & utilized egress on another box on the same network to access it remotely. I haven't updated from 16.0 to 16.1 yet, but once I do I will install netclient on that box again and see if the error has persisted.

**Comment by ghgeiger** [comment]
This is still a problem for me on 0.16.1 as well. Unfortunately I can't take much time to debug it because this is a headless machine that needs max uptime & it's *very* inconvenient when netclient takes out the ssh access. I will try again when 0.16.2 is released, but @mattkasun, please remove the closed & completed tag, this problem still exists.
