### ISSUE TITLE
[Bug]: Windows Netclient DNS Issues, when client connected the internet connection is lost

### ISSUE THREAD

**Issue by MatthewReed303** [gravitl/netmaker#1569]
### What happened?

As soon as windows 10 netclient connects the windows 10 host losses internet connectivity. I have to disable the netclient network interface in network and sharing center to regain internet access. This has only happened since server v15 and greater. I went back to v14.6 server and works fine. 

I have tried flushing the win 10 host DNS etc and still no luck. I have tried the win10 v15 client with v15 and v15.2 server without any luck. 

Maybe there are some new settings or adjustments I am missing? 

My linux Netclients work fine and my server is Ubuntu. It's just the windows clients which is the issue.

Edit:

I have tried to reset windows networks, have removed all network drivers and reinstalled, including wireguard etc my normal wireguard connections still work fine and don't bring down the network. 

As soon as the netclient connects I can't even ping my network router etc it drops my whole network.

### Version

v0.15.2

### What OS are you using?

Windows

### Contributing guidelines

- [X] Yes, I did.

**Comment by flower-knight** [comment]
I have the same situation in win11. Have you solved it?
