### ISSUE TITLE
[Bug]:  Netclient not installing via windows powershell

### ISSUE THREAD

**Issue by sulagna206** [gravitl/netmaker#1608]
### What happened?

I followed this instruction as per the official site to install netclient via windows powershell:
. { iwr -useb  https://raw.githubusercontent.com/gravitl/netmaker/master/scripts/netclient-install.ps1 } | iex; Netclient-Install -version v0.16.0

It gave me the error exiting - token required

### Version

v0.16.0

### What OS are you using?

Windows 10

### Contributing guidelines

- [X] Yes, I did.

**Comment by TBT-TBT** [comment]
Happened to me as well.

I like Netclient under Linux. The installation experience under Windows and MacOS however is terrible.

The Windows and MacOS installation instructions on https://docs.netmaker.org/netclient.html are wrong / outdated / the links to the msi and pkg files are not valid anymore. And the powershell installation method is just not suitable nor working.

**Comment by pete1019** [comment]
@TBT-TBT click on "show all 25 assets" here:
https://github.com/gravitl/netmaker/releases

There is the .msi file.

But i agree: Install / Update on Windows should be better.

**Comment by pete1019** [comment]
@TBT-TBT @sulagna206 
Could you please test if netclient disconnect and netclient connect is working on Windows for you? 
Ping Netmaker Server on Wireguard Network. For example: 10.10.10.254
"netclient disconnect -n NetworkName"
keep pinging and watch it
"netclient connect -n NetworkName"

Thanks

**Comment by TBT-TBT** [comment]
With
.\netclient.exe disconnect -n MY-NW
I get the following:
[netclient.exe] 2022-10-01 18:55:32 netclient.exe is in proper location, C:\Program Files (x86)\Netclient\netclient.exe 
2022/10/01 18:55:32 Gravitl Netclient on Windows started
[netclient.exe] 2022-10-01 18:55:32 network: MY-NW sent a node update to server for node MY-NW ,  XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX
[netclient.exe] 2022-10-01 18:55:32 running stop of Windows Netclient daemon
[netclient.exe] 2022-10-01 18:55:34 successfully ran stop of Windows Netclient daemon
[netclient.exe] 2022-10-01 18:55:34 running start of Windows Netclient daemon
[netclient.exe] 2022-10-01 18:55:35 successfully ran start of Windows Netclient daemon

The daemon immediately restarts netclient and connects again. The status of the network is reset, so this is more a "reconnect" than a disconnect, at least with my installation (which might differ from what is recommended).

Oh, btw: the Windows GUI Netclient program is prevented by MS SmartScreen from starting.

**Comment by pete1019** [comment]
> 

You summed it up nicely.
Will you open an issue please?

**Comment by abhishek9686** [comment]
it is recommended to our MSI installer for netclient on Windows. Netclient install commands are not supported on windows.
https://fileserver.netmaker.io/releases/download/v0.24.2/netclient_x86.msi
