### ISSUE TITLE
[Bug]: Windows Client - Disconnect broken

### ISSUE THREAD

**Issue by pete1019** [gravitl/netmaker#1625]
### What happened?

Infos from User TBT.
Same thing for me and other users wich tested it.

.\netclient.exe disconnect -n MY-NW
on an admin Powershell I get the following:

```
[netclient.exe] 2022-10-01 18:55:32 netclient.exe is in proper location, C:\Program Files (x86)\Netclient\netclient.exe 
2022/10/01 18:55:32 Gravitl Netclient on Windows started
[netclient.exe] 2022-10-01 18:55:32 network: MY-NW sent a node update to server for node MY-NW ,  XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX
[netclient.exe] 2022-10-01 18:55:32 running stop of Windows Netclient daemon
[netclient.exe] 2022-10-01 18:55:34 successfully ran stop of Windows Netclient daemon
[netclient.exe] 2022-10-01 18:55:34 running start of Windows Netclient daemon
[netclient.exe] 2022-10-01 18:55:35 successfully ran start of Windows Netclient daemon
The daemon immediately restarts netclient and connects again. The status of the network is reset, so this is more a "reconnect" than a disconnect, at least with my installation (which might differ from what is recommended).
```
The daemon immediately restarts netclient and connects again. The status of the network is reset, so this is more a "reconnect" than a disconnect, at least with my installation (which might differ from what is recommended).

Oh, btw: the Windows GUI Netclient program is prevented by MS SmartScreen from starting.

### Version

v0.16.0

### What OS are you using?

Windows

### Contributing guidelines

- [X] Yes, I did.

**Comment by cameronts** [comment]
@pete1019 have you tested since?  Wondering if you're still seeing the error with 0.16.1 or 0.16.2.

**Comment by pete1019** [comment]
@cameronts think this is fixed.
