### ISSUE TITLE
[Bug]: Link to macOS Netclient install package is broken

### ISSUE THREAD

**Issue by 42Network** [gravitl/netmaker#1627]
### What happened?

I tried to follow the Netclient install instructions for macOS you provide at this page: https://netmaker.readthedocs.io/en/master/netclient.html

It says to download the Netclient.pkg package from this URL: https://fileserver.netmaker.org/latest/darwin/Netclient.pkg

However, this URL gives a 404 Not Found error.

### Version

v0.16.0

### What OS are you using?

Mac

### Relevant log output

```shell
This fileserver.netmaker.org page can’t be foundNo webpage was found for the web address: https://fileserver.netmaker.org/latest/darwin/Netclient.pkg
HTTP ERROR 404
```

### Contributing guidelines

- [X] Yes, I did.

**Comment by pete1019** [comment]
All other links are broken, too.

**Comment by abhishek9686** [comment]
Links have been fixed
