### ISSUE TITLE
Quick install fails if ipv6 is disabled

### ISSUE THREAD

**Issue by Qubitium** [gravitl/netmaker#1635]
### What happened?

Quick install failed when ipv6 is disabled via kernel bootup (grub).

Ubuntu 22.04 + Kernel 6.0 release. 

Install attempt via:

```
wget -qO - https://raw.githubusercontent.com/gravitl/netmaker/master/scripts/nm-quick.sh | sudo bash
```

### Version

v0.16.0

### What OS are you using?

Linux

### Relevant log output

```shell
Digest: sha256:f3e0c93746565d721152d0c58fe000feb24e9c7b3ee5d042299ff942bc783698
Status: Downloaded newer image for eclipse-mosquitto:2.0.11-openssl
Creating traefik  ... done
Creating netmaker ... error

ERROR: for netmaker  Cannot start service netmaker: failed to create shim: OCI runtime create failed: runc create failed: unable to start container process: error during container init: open /proc/sys/net/ipv6/conf/all/disable_ipv6: no such file or directory: unknown

ERROR: for netmaker  Cannot start service netmaker: failed to create shim: OCI runtime create failed: runc create failed: unable to start container process: error during container init: open /proc/sys/net/ipv6/conf/all/disable_ipv6: no such file or directory: unknown

```
```


### Contributing guidelines

- [X] Yes, I did.

**Comment by mattkasun** [comment]
You will have to remove the following to lines from the netmaker/sysctls section of the docker-compose file
 - net.ipv6.conf.all.disable_ipv6=0
 - net.ipv6.conf.all.forwarding=1

**Comment by macduff23** [comment]
removing net.ipv6 - from docker-compose is not working is not resolving the issue in my case - Installing in lxd. Security.nesting=true is enable on the container. 

ERROR: for afd788dff0a8_afd788dff0a8_afd788dff0a8_netmaker  Cannot start service netmaker: failed to create shim: OCI runtime create failed: runc create failed: unable to start container process: error during container init: open /proc/sys/net/ipv6/conf/all/disable_ipv6: no such file or directory: unknown

ERROR: for netmaker  Cannot start service netmaker: failed to create shim: OCI runtime create failed: runc create failed: unable to start container process: error during container init: open /proc/sys/net/ipv6/conf/all/disable_ipv6: no such file or directory: unknown
ERROR: Encountered errors while bringing up the project.

**Comment by abhishek9686** [comment]
please try it with latest version
