### ISSUE TITLE
[Bug]: Netclient clients are not allowed to contact broker

### ISSUE THREAD

**Issue by benpro** [gravitl/netmaker#1652]
### Contact Details

netmaker@benpro.fr

### What happened?

I just installed a fresh server manually and a net client.
Seeing that the netclient is not allowed to connect to the broker.

Mosquitto is configured like the [documentation](https://netmaker.readthedocs.io/en/master/server-installation.html#mq). Not sure where is the issue, client certificate authentication seems OK.

### Version

v0.16.0

### What OS are you using?

Linux

### Relevant log output

```shell
1665670848: New connection from 2400:4051:[...] on port 8883.
1665670848: Client <unknown> disconnected, not authorised.
```

### Contributing guidelines

- [X] Yes, I did.

**Comment by afeiszli** [comment]
If this is a fresh install, I would re-install with 0.16.1 instead, which changes the MQ model.

**Comment by benpro** [comment]
Moved to 0.16.1 via Docker compose setup. I think the manual setup doc need to be updated to reflect 0.16.1 though...
Closing.
