### ISSUE TITLE
[Bug]: All networks recreated in lowercase on upgrade to 0.16.1

### ISSUE THREAD

**Issue by StarkZarn** [gravitl/netmaker#1663]
### Contact Details

@StarkZarn 

### What happened?

I upgraded my server to 0.16.1 following the instructions posted in the gist. Everything went well. I noticed that on one of my networks, the egress gateway was not connecting. Further inspection revealed the original network (OffSite) had been duplicated as "offsite" with all lowercase. It looked like nodes were connected to the original, but the netmaker server node acting as an ingress point was only responding on the lowercased version. I readded the nodes on the lowercase network and everything worked. I could not get the original cased network to work properly again.

This isn't a dealbreaker for me, as I've regained connectivity, but I believe this should be documented somewhere as a potentially breaking change, as people who upgrade with remote nodes that aren't easily accessible to them are going to run into issues.

### Version

v0.16.1

### What OS are you using?

Linux

### Relevant log output

```shell
N/A
```

### Contributing guidelines

- [X] Yes, I did.

**Comment by mattkasun** [comment]
network names were limited to lowercase names only in v0.14.3
