### ISSUE TITLE
[Bug]: Weird/Broken IPv6-Addressing 

### ISSUE THREAD

**Issue by Ruakij** [gravitl/netmaker#1679]
### What happened?

When enabling IPv6 for a netmaker-network, the auto-generated IPv6-addresses for nodes may be wrong/invalid.

Unlike with IPv4, Addressing doesnt start with the 0+1-Address of the CIDR, but 0.
Example: Prefix is `fd00::/64`
First Node gets Address: `fd00::`

That is the Subnet-Router anycast address as per RFC4291 (2.6.) and maybe shouldnt be used for an individual-node.

Furthermore, i have found out, netmaker handles the Addresses weirdly.
When manually setting a node to have the Address `fd00::0`, the next node will still take `fd00::`, even though its the same address, thus creating an address-conflict.

### Version

v0.16.1

### What OS are you using?

Linux

### Contributing guidelines

- [X] Yes, I did.

**Comment by kwinsch** [comment]
Also noted, that the `netmaker-1` node gets the last possible address  `:ffff:ffff:ffff:ffff`. This is also wrong and must be set to a lower value.
