### ISSUE TITLE
[Bug]: Network names with dashes break other software

### ISSUE THREAD

**Issue by osi8** [gravitl/netmaker#1682]
### Contact Details

via Github

### What happened?

Auto generated network interface names contain "-" (dash) which breaks some network tools. Mainly found this to be an issue with Proxmox servers. (They use an Ubuntu Kernel and a Debian System)

Is there a way to change the template of interface names?
Maybe "nm-${network}"  -> "nm${network}" would suffice.
Or "nm0${network}", since that keeps the division between the Netmaker part and the chosen name.

### Version

v0.16.1

### What OS are you using?

Linux

### Contributing guidelines

- [X] Yes, I did.

**Comment by mattkasun** [comment]
you can specify the interface name when joining a network with the interface flag (--interface <name> or -i <name>)

**Comment by osi8** [comment]
Arg, sorry. I missed that, allthough search in the docs now brought it up instantly. Very sorry. Will close this issue and get more coffee.
