### ISSUE TITLE
[Bug]: SSO github permission reverts

### ISSUE THREAD

**Issue by vzhong** [gravitl/netmaker#1684]
### What happened?

I'm testing out the newest NetMaker setup and managed to set up login via an application created from a Github group. I have the following users:

A: an admin account, created locally
B: a Github account, created via logging in through github

After B is created, I see that the user has no permissions. Logs from `netmaker` says 

```
[netmaker] 2022-10-23 21:10:30 user created from  vzhong
[netmaker] 2022-10-23 21:10:30 completed github OAuth sigin in for vzhong
[netmaker] 2022-10-23 21:10:31 processed request error: unauthorized
[netmaker] 2022-10-23 21:10:31 processed request error: unauthorized
[netmaker] 2022-10-23 21:10:31 processed request error: unauthorized
[netmaker] 2022-10-23 21:10:31 processed request error: unauthorized
[netmaker] 2022-10-23 21:10:31 processed request error: unauthorized
[netmaker] 2022-10-23 21:10:31 processed request error: unauthorized
[netmaker] 2022-10-23 21:10:31 processed request error: unauthorized
[netmaker] 2022-10-23 21:10:31 processed request error: unauthorized
[netmaker] 2022-10-23 21:10:31 processed request error: unauthorized
```

Next, I log out and log back in as the admin user A, and change B to admin (and assign B to a network), in the logs I see

```
[netmaker] 2022-10-23 21:11:06 updated user vzhong
[netmaker] 2022-10-23 21:11:06 vzhong status was updated
```

I go to Users and see that B is now listed as `admin` and assigned to the correct network. Now I log out again and log back in as B, but again I see nothing in the UI. In the logs I see

```
[netmaker] 2022-10-23 21:11:14 processed request error: unauthorized
[netmaker] 2022-10-23 21:11:14 processed request error: unauthorized
[netmaker] 2022-10-23 21:11:14 processed request error: unauthorized
[netmaker] 2022-10-23 21:11:14 processed request error: unauthorized
[netmaker] 2022-10-23 21:11:14 processed request error: unauthorized
[netmaker] 2022-10-23 21:11:14 processed request error: unauthorized
[netmaker] 2022-10-23 21:11:15 processed request error: unauthorized
[netmaker] 2022-10-23 21:11:15 processed request error: unauthorized
[netmaker] 2022-10-23 21:11:15 processed request error: unauthorized
```

When I re-login as A again, I see that the act of logging in through SSO as B has reverted B from admin to regular user. , The network assignments have been erased as well.

### Version

v0.16.1

### What OS are you using?

Linux

### Contributing guidelines

- [X] Yes, I did.

**Comment by AndreyNovik1993** [comment]
I have the same issue with OKTA OAuth system. 
[netmaker] 2022-10-28 13:33:57 completed OIDC OAuth signin in for email 
[netmaker] 2022-10-28 13:33:57 processed request error: unauthorized 
[netmaker] 2022-10-28 13:33:57 processed request error: unauthorized 
[netmaker] 2022-10-28 13:33:57 processed request error: unauthorized

**Comment by markusglaetzner** [comment]
I have the same issue with the same logs with github as auth provider.

**Comment by axute** [comment]
I have the same error with oicd provider (authelia)

**Comment by 0xdcarns** [comment]
This has been fixed in v0.16.3, thanks for the feedback

**Comment by markusglaetzner** [comment]
Hi Alex,
I updated netmaker-ui to 0.16.3 and Client-binaries, but I still can not save the new github-account as Admin! I am able to login with github as my identity-provider, then logoff and login again with my local admin account, change to users-tab and make the second account (github) to Admin. Once I updated the page, I see "Is Admin - false" like bevor.
--
Beste Grüße
Markus Glaetzner
Am Mi., Nov. 16, 2022 17:42 schrieb dcarns ***@***.***>:
	This has been fixed in v0.16.3, thanks for the feedback

**Comment by vzhong** [comment]
@markusglaetzner Did you change `netmaker` to 0.16.3 as well? e.g. `image: gravitl/netmaker:v0.16.3`?

**Comment by markusglaetzner** [comment]
Hi, I realisted this stupid mistakes just 1 minute bevor you posted this question :-)  With both updated it works like a charm :-) Thanks a lot!!!

**Comment by vzhong** [comment]
Excellent - I don't have an install to test this but since the fix worked for @markusglaetzner I am closing this issue.
