### ISSUE TITLE
Please document client vs server version compatibility and update path

### ISSUE THREAD

**Issue by dionorgua** [gravitl/netmaker#1685]
### What happened?

It looks like there is no documentation for API compatibility. There should be a way to update server or client independently. Surely older server/client may have limited functionality.

Ideally every server release should mention minimal supported client version. Also every client version should mention supported server versions. Plus there _should_ be at least one version overlap between supported client and server versions to be able to keep some clients at different versions. 

Also it would be cool to have some sort of documented update strategy. It's not always possible to update all clients at the same time (for example some of them may be just laptops that are turned off when not used). Also keep in mind that some machines may be available only via same netmaker VPN. 

### Version

v0.16.1

### Contributing guidelines

- [X] Yes, I did.

**Comment by mattkasun** [comment]
netclient will update itself to be same as server version
