### ISSUE TITLE
[Bug]: Windows MSI Installer is missing in 0.16.2

### ISSUE THREAD

**Issue by kbzowski** [gravitl/netmaker#1689]
### What happened?

MSI installer is missing in github release page for 0.16.2. I understand that this is prerelase, but windows exe is there. Can I build msi package somehow by myself (i didn't find suitable manual in docs)?

### Version

v0.16.1

### What OS are you using?

Windows

### Contributing guidelines

- [X] Yes, I did.

**Comment by afeiszli** [comment]
Uploaded
