### ISSUE TITLE
Unable to create a network

### ISSUE THREAD

**Issue by ennnnny** [gravitl/netmaker#1693]
### What happened?

When I first created the network, it showed.
“could not reliably create interface, please check wg installation and retry”

Operation steps：

- use this file：https://github.com/gravitl/netmaker/blob/master/compose/docker-compose.yml
- remove traefik related
- see "Nginx Reverse Proxy Setup with https" and "Nginx Proxy Manager Setup Nginx" in the documentation.
- use nginx proxy "api","dashboard","grpc","broker"
- visit the website and create an administrator account
- error when I created the network

### Version

v0.16.1

### What OS are you using?

Linux

### Relevant log output

```shell
netmaker     | [#] ip link add nm-netty type wireguard
netmaker     | RTNETLINK answers: Not supported
netmaker     | Unable to access interface: Protocol not supported
netmaker     | [#] ip link delete dev nm-netty
netmaker     | Cannot find device "nm-netty" 
netmaker     | [netmaker] 2022-10-26 18:03:04 error running command: wg-quick up /etc/netclient/config/nm-netty.conf 
netmaker     | [netmaker] 2022-10-26 18:03:04 Warning: `/etc/netclient/config/nm-netty.conf' is world accessible
netmaker     | [#] ip link add nm-netty type wireguard
netmaker     | RTNETLINK answers: Not supported
netmaker     | Unable to access interface: Protocol not supported
netmaker     | [#] ip link delete dev nm-netty
netmaker     | Cannot find device "nm-netty" 
netmaker     | [netmaker] 2022-10-26 18:03:05 error running command: wg-quick up /etc/netclient/config/nm-netty.conf 
netmaker     | [netmaker] 2022-10-26 18:03:05 Warning: `/etc/netclient/config/nm-netty.conf' is world accessible
netmaker     | [#] ip link add nm-netty type wireguard
netmaker     | RTNETLINK answers: Not supported
netmaker     | Unable to access interface: Protocol not supported
netmaker     | [#] ip link delete dev nm-netty
netmaker     | Cannot find device "nm-netty" 
netmaker     | [netmaker] 2022-10-26 18:03:06 error running command: wg-quick up /etc/netclient/config/nm-netty.conf 
netmaker     | [netmaker] 2022-10-26 18:03:06 Warning: `/etc/netclient/config/nm-netty.conf' is world accessible
netmaker     | [#] ip link add nm-netty type wireguard
netmaker     | RTNETLINK answers: Not supported
netmaker     | Unable to access interface: Protocol not supported
netmaker     | [#] ip link delete dev nm-netty
netmaker     | Cannot find device "nm-netty" 
netmaker     | file does not exist
netmaker     | [netmaker] 2022-10-26 18:03:07 kuye failed to create network:  could not reliably create interface, please check wg installation and retry 
netmaker     | [netmaker] 2022-10-26 18:03:07 processed request error: could not reliably create interface, please check wg installation and retry
```

### Contributing guidelines

- [X] Yes, I did.

**Comment by schniggie** [comment]
same here with traefik. host is debian 10.

**Comment by afeiszli** [comment]
This indicates WireGuard is not installed on the host. Please install and try again.

**Comment by ennnnny** [comment]
> This indicates WireGuard is not installed on the host. Please install and try again.

I checked and it was installed。
![Snipaste_2022-11-02_11-38-11](https://user-images.githubusercontent.com/9587073/199389882-9e8d76da-e6fd-4940-958b-2d9caec38c21.jpg)

docker is also running
![Snipaste_2022-11-02_11-39-58](https://user-images.githubusercontent.com/9587073/199389974-ef663748-98d5-402c-9b1d-5f4fb7be2898.jpg)

**Comment by schniggie** [comment]
yea exactly the same for me too.

```
root@mail:~ # apt -qq list wireguard
wireguard/buster-backports,now 1.0.20210223-1~bpo10+1 all  [installed]
```

any idea ;) ?

**Comment by rallep71** [comment]
same here, ubuntu server 20.04 openvz
wireguard/focal-updates,now 1.0.20200513-1~20.04.2 all [installed]
failed to create network: could not reliably create interface, please check wg installation and retry 
processed request error: could not reliably create interface, please check wg installation and retry

**Comment by rallep71** [comment]
Update: does not run on vps openvz, runs on vps can loaded wireguard kernel module!

**Comment by ennnnny** [comment]
> Update: does not run on vps openvz, runs on vps can loaded wireguard kernel module!

Thanks for the reminder, I try to use：
`apt-get install wireguard-dkms wireguard-tools`

It solved the problem
