### ISSUE TITLE
[Bug]: Cannot update client using MSI package (windows)

### ISSUE THREAD

**Issue by kbzowski** [gravitl/netmaker#1735]
### What happened?

Cannot update windows client from version 0.16.1 -> 0.16.3, nor 0.16.2 -> 0.16.3 due to an error: Another version of this program is already installed. The only option is to uninstall previous version and install 0.16.3. 

### Version

v0.16.1

### What OS are you using?

Windows

### Contributing guidelines

- [X] Yes, I did.

**Comment by abhishek9686** [comment]
this should be resolved with latest msi installer
