### ISSUE TITLE
[Bug]: Firewall rules are cleared

### ISSUE THREAD

**Issue by Someonesz** [gravitl/netmaker#1746]
### What happened?

# Impact
Firewall rules are cleared and the firewall denies all connections by default, so I can't connect to my server.

# Steps
0. Connect to any of the networks
1. Create egress(or ingress) gateway
2. Remove egress(or ingress) gateway
3. Firewall rules are cleared

### Autofill postUp and postDown rules
```
# postUp
nft add table ip filter ; nft add chain ip filter FORWARD ; nft add rule ip filter FORWARD iifname nm-k8s-world counter accept ; nft add rule ip filter FORWARD oifname nm-k8s-world counter accept ; nft add table nat ; nft add chain nat postrouting ; nft add rule ip nat postrouting oifname nm-k8s-world counter masquerade ; 

# postDown
nft flush table filter ; nft flush table nat ; 
```

## Before
![Before](https://user-images.githubusercontent.com/37020030/202728673-20671c7c-68ab-479d-be87-4e9c71475c55.png)
## After
![After](https://user-images.githubusercontent.com/37020030/202728797-f0bc8033-736b-40aa-a021-e8e58cb61cbd.png)

### Version

v0.16.3

### What OS are you using?

Linux

### Relevant log output

```shell
[netmaker] 2022-11-18 13:52:03 ping processed for node wl-test 5dda9533-9606-47b6-ac61-65fcbef2108b (2)
[netmaker] 2022-11-18 13:52:35 creating ingress gateway firewall in use is ' nftables ' (4)
[netmaker] 2022-11-18 13:52:35 creating ingress gateway nftables is present (4)
[netmaker] 2022-11-18 13:52:35 luna created ingress gateway on node 5dda9533-9606-47b6-ac61-65fcbef2108b on network k8s-world (4)
[netmaker] 2022-11-18 13:52:37 updated peers on server netmaker-1 (4)
[netmaker] 2022-11-18 13:52:37 sent peer updates after signal received from 5dda9533-9606-47b6-ac61-65fcbef2108b wl-test (4)
[netmaker] 2022-11-18 13:52:39 deleting ingress gateway (4)
[netmaker] 2022-11-18 13:52:39 deleting ingress gateway firewall in use is ' nftables ' and isEgressGateway is no (4)
[netmaker] 2022-11-18 13:52:39 luna deleted ingress gateway 5dda9533-9606-47b6-ac61-65fcbef2108b (4)
[netmaker] 2022-11-18 13:52:39 publishing node update to wl-test (9)
[netmaker] 2022-11-18 13:52:39 updated node 5dda9533-9606-47b6-ac61-65fcbef2108b wl-test (9)
```

### Contributing guidelines

- [X] Yes, I did.

**Comment by bubbleatgit** [comment]
题主英语真棒，我也遇到这个问题了，题主有临时解决方案吗？

**Comment by PeterWang-dev** [comment]
> 题主英语真棒，我也遇到这个问题了，题主有临时解决方案吗？

You two can try vnc from your vps management panel.
可以试试VPS后台的VNC直接登陆。

**Comment by Someonesz** [comment]
> 题主英语真棒，我也遇到这个问题了，题主有临时解决方案吗？

先卸载nftables，然后再安装netclient就可以了。
```
apt remove nftables 
```

**Comment by abhishek9686** [comment]
@Someonesz  netmaker only manages rules added by it, which has appended comment signature for each rule
