### ISSUE TITLE
[Bug]: Issue after same Address Range

### ISSUE THREAD

**Issue by pete1019** [gravitl/netmaker#1749]
### What happened?

Hi,

Server v0.16.3 (v0.16.2 same).
on accident i was able to give 2 different Networks the same Address Range (IPv4) (10.10.6.0/24).
Why is that possible?

I then i changed one of them to 10.10.7.0/24
I now can not ping anything anymore (i already downloaded new external client file).
Both networks are not accessible for me anymore.

![image](https://user-images.githubusercontent.com/56532989/202805301-ca7d77d4-0397-4c02-9e30-61c8051f9614.png)
Stange is: 10.10.6.2/32 ist still in there. Even after netclient pull or netclient uninstall and rejoin.

Thanks

### Version

v0.16.3

### What OS are you using?

Linux

### Contributing guidelines

- [X] Yes, I did.

**Comment by abhishek9686** [comment]
@pete1019 we have enforced checks to avoid this scenario on the latest versions
