### ISSUE TITLE
issue joining a network 

### ISSUE THREAD

**Issue by hussainalhaddad** [gravitl/netmaker#175]
Hi

The command to install the agent isn't working, as it's pointing to v0.3 and can't be found. it works when i manually change it to v0.5 but then i get the below error message

 
panic: runtime error: index out of range [1] with length 1

goroutine 1 [running]:
github.com/gravitl/netmaker/netclient/config.GetCLIConfigRegister(0xc00039e680, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /home/runner/work/netmaker/netmaker/netclient/config/config.go:450 +0x830
main.main.func1(0xc00039e680, 0x1c, 0x38)
        /home/runner/work/netmaker/netmaker/netclient/main.go:202 +0x65
github.com/urfave/cli/v2.(*Command).Run(0xc000223d40, 0xc000033c00, 0x0, 0x0)
        /home/runner/go/pkg/mod/github.com/urfave/cli/v2@v2.3.0/command.go:163 +0x4dd
github.com/urfave/cli/v2.(*App).RunContext(0xc0002dfd40, 0xebba30, 0xc000036090, 0xc000032080, 0x4, 0x4, 0x0, 0x0)
        /home/runner/go/pkg/mod/github.com/urfave/cli/v2@v2.3.0/app.go:313 +0x810
github.com/urfave/cli/v2.(*App).Run(...)
        /home/runner/go/pkg/mod/github.com/urfave/cli/v2@v2.3.0/app.go:224
main.main()
        /home/runner/work/netmaker/netmaker/netclient/main.go:370 +0x2445

**Comment by afeiszli** [comment]
Did you provide an access key to the join command?

**Comment by afeiszli** [comment]
Slash what is the command you ran to generate that error?

**Comment by hussainalhaddad** [comment]
> Did you provide an access key to the join command?

Yes, i did

**Comment by hussainalhaddad** [comment]
> Slash what is the command you ran to generate that error?

I just followed the docker installation procedure

**Comment by afeiszli** [comment]
Which docker-compose file did you use? Some of them were pointing to the wrong version, and the keyvalue generated would be incompatible with the new version of the netclient. If it was docker-compose.slim.yml, then please try using the updated docker-compose file. You should be able to keep your network but will need to delete/create the keys again.

**Comment by hussainalhaddad** [comment]
> Which docker-compose file did you use? Some of them were pointing to the wrong version, and the keyvalue generated would be incompatible with the new version of the netclient. If it was docker-compose.slim.yml, then please try using the updated docker-compose file. You should be able to keep your network but will need to delete/create the keys again.

i think i used the slim.yml file, again, just following the quick setup guide here https://docs.netmaker.org/quick-start.html

I'll try again using the newer docker compose file

thanks mate
