### ISSUE TITLE
Can not create an admin user after installation

### ISSUE THREAD

**Issue by use3r** [gravitl/netmaker#176]
Hello,

I used the quick-start approach to install netmaker

ssh root@your-host
wget -O docker-compose.yml https://raw.githubusercontent.com/gravitl/netmaker/master/compose/docker-compose.slim.yml
sed -i ‘s/HOST_IP/< Insert your-host IP Address Here >/g’ docker-compose.yml
docker-compose up -d

I adjusted the IP in docker-compose.yml and can access the webserver.
But I can not set a password. Is there a script that I can create or reset the user in docker shell?

root@photonOS [ ~ ]# cat /etc/photon-release
VMware Photon OS 4.0
PHOTON_BUILD_NUMBER=1526e30ba

root@photonOS [ ~ ]# docker version
Client: Docker Engine - Community
 Version:           19.03.10
 API version:       1.40
 Go version:        go1.15.8
 Git commit:        9424aea
 Built:             Thu Feb 25 02:04:27 2021
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.10
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.15.8
  Git commit:       9424aea
  Built:            Thu Feb 25 02:05:19 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.1
  GitCommit:        %{CONTAINERD_GITCOMMIT}
 runc:
  Version:          1.0.0-rc92
  GitCommit:        d736ef14f0288d6993a1845745d6756cfc9ddd5a
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683

root@photonOS [ ~ ]# docker-compose version
docker-compose version 1.29.2, build 5becea4c
docker-py version: 5.0.0
CPython version: 3.7.10
OpenSSL version: OpenSSL 1.1.0l  10 Sep 2019

**Comment by afeiszli** [comment]
Apologies, the file was still pointing to the v0.3 images, I've updated that to the v0.5 images. Can you please try again? If you get the same result, please post the output of "docker logs netmaker"

**Comment by afeiszli** [comment]
Did you happen to change the mongodb user/pass before deploying?

**Comment by use3r** [comment]
> Did you happen to change the mongodb user/pass before deploying?

Nope, I strictly followed the orders :)

**Comment by use3r** [comment]
> Apologies, the file was still pointing to the v0.3 images, I've updated that to the v0.5 images. Can you please try again? If you get the same result, please post the output of "docker logs netmaker"

First of all. Thank you for the very quick reply :) and awesome work ...

Unfortunately it is still the same problem. - Can not create a user. ---> MongoDB does not connect. 

Also I get the folowing error massage in my browser after I have connected:
Error connecting to backend. Given: http://192.168.1.95:8081 Server may be down, address may be incorrect, or port may not be open. Please investigate.
- On the host I accepted traffic to Port 8081 --> iptables --append INPUT --protocol tcp --dport 8081 --jump ACCEPT
- But then I don´t even get the site.

docker logs belows:

root@photonOS [ ~ ]# docker logs netmaker
2021/06/08 18:29:23 Connecting to MongoDB at 127.0.0.1:27017...
2021/06/08 18:29:53 Error encountered pinging MongoDB. Terminating.
2021/06/08 18:29:53 server selection error: server selection timeout, current topology: { Type: Unkno                                                                                                                 wn, Servers: [{ Addr: 127.0.0.1:27017, Type: Unknown, State: Connected, Average RTT: 0, Last error: `c`                                                                                                          onnection() : dial tcp 127.0.0.1:27017: connect: connection refused }, ] }
2021/06/08 18:29:54 Connecting to MongoDB at 127.0.0.1:27017...
2021/06/08 18:30:24 Error encountered pinging MongoDB. Terminating.

**Comment by afeiszli** [comment]
Hmmm everyone is having this problem today...there's a problem in the docker-compose and the netmaker network cannot access the mongo network. The quick fix should be to add this line to the netmaker section of the docker compose:

    network_mode: host 

(see line 34 of the reference: https://github.com/gravitl/netmaker/blob/master/compose/docker-compose.reference.yml)

Please let me know if that fixes the issue. I will be investigating the permanent fix.

**Comment by use3r** [comment]
> > Hmmm everyone is having this problem today...there's a problem in the docker-compose and the netmaker network cannot access the mongo network. The quick fix should be to add this line to the netmaker section of the docker compose:
> 
> ```
> network_mode: host 
> ```
> 
> (see line 34 of the reference: https://github.com/gravitl/netmaker/blob/master/compose/docker-compose.reference.yml)
> 
> Please let me know if that fixes the issue. I will be investigating the permanent fix.

If I add the line to the netmaker section the following error acures:

nano docker-compose.yml
root@photonOS [ ~ ]# docker-compose up -d
mongodb is up-to-date
Recreating netmaker ...

ERROR: for netmaker  "host" network_mode is incompatible with port_bindings

ERROR: for netmaker  "host" network_mode is incompatible with port_bindings
Traceback (most recent call last):
  File "docker-compose", line 3, in <module>
  File "compose/cli/main.py", line 81, in main
  File "compose/cli/main.py", line 203, in perform_command
  File "compose/metrics/decorator.py", line 18, in wrapper
  File "compose/cli/main.py", line 1186, in up
  File "compose/cli/main.py", line 1182, in up
  File "compose/project.py", line 702, in up
  File "compose/parallel.py", line 108, in parallel_execute
  File "compose/parallel.py", line 206, in producer
  File "compose/project.py", line 688, in do
  File "compose/service.py", line 581, in execute_convergence_plan
  File "compose/service.py", line 503, in _execute_convergence_recreate
  File "compose/parallel.py", line 108, in parallel_execute
  File "compose/parallel.py", line 206, in producer
  File "compose/service.py", line 496, in recreate
  File "compose/service.py", line 615, in recreate_container
  File "compose/service.py", line 334, in create_container
  File "compose/service.py", line 941, in _get_container_create_options
  File "compose/service.py", line 1073, in _get_container_host_config
  File "docker/api/container.py", line 598, in create_host_config
  File "docker/types/containers.py", line 339, in __init__
docker.errors.InvalidArgument: "host" network_mode is incompatible with port_bindings
[12632] Failed to execute script docker-compose
root@photonOS [ ~ ]# nano docker-compose.yml

[docker-compose.txt](https://github.com/gravitl/netmaker/files/6619056/docker-compose.txt)

**Comment by afeiszli** [comment]
ok forget that one, I updated the docker-compose file on the master and v0.5 branches. The new one should work.

Also, if you're following the quick start guide, there's a point at which you'll run a command to add a node. You'll need to replace the reference from "netclient-install.sh" to "netclient-install.slim.sh". EX:

curl -sfL https://raw.githubusercontent.com/gravitl/netmaker/v0.5/scripts/netclient-install.slim.sh | KEY=NTA1NTV8MTkyLMTI6NTAwNTF8MTkyLjQ2LjIxOS4xMTI6ODA4MXx0ZXN0fGR8 sh -

Apologies, these issues are due to not updating the quickstart guide from the previous version.

**Comment by afeiszli** [comment]
Fixed in 0.7

**Comment by bsamadi** [comment]
I have the same problem in v0.9.2.
