### ISSUE TITLE
[Bug]: Fyne Error when running Netclient on Windows server 

### ISSUE THREAD

**Issue by jekcom** [gravitl/netmaker#1763]
### What happened?

Installed and tried to run Netclient on Windows 2016 datacenter and got Fyne Error

![Clipboard Image](https://user-images.githubusercontent.com/4057992/203817180-cb2f3ab6-367a-47b1-bf8d-f3d2d3bee8ab.jpg)

I assume it is somehow related to the GUI
There is [suggestion ](https://github.com/fyne-io/fyne/issues/410#issuecomment-524105900)to emulate  OpenGL but that is unfortunately not under my control. The machine is VPS hosted by Contabo hosting and they don't emulate OGL

Any suggestions?

### Version

v0.16.3

### What OS are you using?

Windows

### Contributing guidelines

- [X] Yes, I did.

**Comment by ConnectcomAVikol** [comment]
same bug on windows 10 inside virtualbox

**Comment by afeiszli** [comment]
this is a known issue with virtualized windows and some versions of windows server. Here is the workaround, which isn't in official docs yet: https://github.com/gravitl/netmaker-docs/pull/73/files

In the near future we will have a new netclient GUI that does not use Fyne, so wont have the issue.
