### ISSUE TITLE
[REQUEST] Multiple ranges egress gateway

### ISSUE THREAD

**Issue by pcfriek1987** [gravitl/netmaker#179]
As sometimes a bit of a more traditional VPN is needed to being able to reach certain IP ranges eg. for example my DC management network is firewalled for everything except for a few ranges (home, Office etc). At this moment I still need to use a regular VPN to connect to this as I can't do it easily over Netmaker, I would have to create multiple netclients and assign each node a different range using the egress gateway.

Could it be updated perhaps so that you can update/add ranges to an egress gateway?

**Comment by afeiszli** [comment]
@pcfriek1987 this is implemented in the new release 0.7 with "egress gateway range" moving to "egress gateway ranges". Will provide reference once release is out (8/11/21).

**Comment by pcfriek1987** [comment]
This should be done now, or at least it works fine here :)
