### ISSUE TITLE
default network gets re-created after reboot

### ISSUE THREAD

**Issue by jr200** [gravitl/netmaker#180]
Hi,

If I delete the network named 'default' from the UI, it gets re-created after a reboot (or docker-compose down/up).
This is problematic because if I have another network listening on the standard port (51821), the 'default' network is created and also listens on 51821.

1. Is there a way to avoid re/creating the 'default' network.
2. When a network is configured/created, maybe there could be a check to see if any other network is listening on that port already.

**Comment by afeiszli** [comment]
@jr200 This is fixed in the 0.7 release, which removes the "default network" entirely.

**Comment by afeiszli** [comment]
Fixed in 0.7
