### ISSUE TITLE
[Bug]: netclient faulty IPv4 public IP detection when API domain has IPv6 DNS record

### ISSUE THREAD

**Issue by taladar** [gravitl/netmaker#1807]
### What happened?

Netclient apparently used the API public IP detection (as opposed to the separate ip detection services) in GetPublicIP and since our API domain had an AAAA record it detected the IPv6 instead of the public IPv4 address. This was then updated as the peer address and when e.g. joining a new node there was an error because it apparently treats IPv6 addresses wrong (does not add [] before adding colon and port).

Regardless of the format error shown in the log below it should probably force IPv4 for the detection request if it intends to detect the public IPv4 address.

When it does get an IPv6 address it should format that properly to avoid the low level error even if it intends to reject IPv6 addresses (which it probably should if there are any IPv4 only nodes on the network and/or a per network setting says so and/or netmaker does not support IPv6 endpoints at all yet)

### Version

v0.17.0

### What OS are you using?

Linux

### Relevant log output

```shell
Dec 09 13:39:06 vpn-hetzner1 netmaker_0.17.0[2936967]: [netmaker_0.17.0] 2022-12-09 13:39:06  error fetching wg peers config for node [ 6d75d328-1572-4211-97d1-3ac504be4777 ]: address 2001:9e8:4e3d:a800:8615:bc40:2fa5:fa8b:51821: too many colons in address
Dec 09 13:39:06 vpn-hetzner1 netmaker_0.17.0[2936967]: [netmaker_0.17.0] 2022-12-09 13:39:06 processed request error: address 2001:9e8:4e3d:a800:8615:bc40:2fa5:fa8b:51821: too many colons in address
```

### Contributing guidelines

- [X] Yes, I did.

**Comment by abhishek9686** [comment]
@taladar  netmaker has added IPV6 support from 0.24.0, so this should be resolved
