### ISSUE TITLE
ingress-gateway public key rotates after reboot

### ISSUE THREAD

**Issue by jr200** [gravitl/netmaker#181]
When adding an external client to an ingress-gateway, the (generated) client configuration file contains the public-key of the peer running the ingress-gateway.

After a reboot the public-key of the ingress-gateway peer is rotated, invalidating all of it's external-client configurations. Although the external-client configurations can be regenerated from netmaker with the updated node's public-key, the configuration is not long-lived as other events can also force a key rotation.

In the discord session we discussed fixing the public-key of the ingress gateway node, and allowing only explicit rotation through the UI/API.

**Comment by afeiszli** [comment]
@jr200 This has been fixed in the new release, which introduces "Static Nodes". Static nodes will not update their public keys, address, or endpoint unless manually updated. I will close with a link to this once the new release is out (8/11/21).

**Comment by afeiszli** [comment]
Fixed in 0.7
