### ISSUE TITLE
Netclient does not install on windows 11

### ISSUE THREAD

**Issue by Gamechiefx** [gravitl/netmaker#1811]
I upgraded one of my machines to windows 11 to test netclient compatibility it would appear that it will not install because it is not detecting the installation of wireguard.

1. Wireguard was installed before the upgrade - Result: same issue
2. Wirguard was uninstalled and then reinstalled - Result: same issue
3. I had an older version of wireguard (0.16.1) already installed and it worked flawlessly (but with the windows ping bug)

Asks:

Please give the option in deployment with the MSI installer to continue with the installation regardless of the presence of wireguard.

**Comment by Riyooo** [comment]
Same issue on Windows 11 as well.
I also tried disabling Windows Defender or using Administrator rights.

![image](https://user-images.githubusercontent.com/6316242/227689037-07e06e08-a44b-4ecd-9d19-3c0db104e9a0.png)

Wireguard is however installed and working.

![image](https://user-images.githubusercontent.com/6316242/227689591-6ad2443a-5acc-4fda-aa81-113e8bd61944.png)

**Comment by M09Ic** [comment]
Same issue on Windows 11 as well.

**Comment by abhishek9686** [comment]
This has been resolved on the latest versions, please re-try.
