### ISSUE TITLE
issue when changing wireguard-assigned ip

### ISSUE THREAD

**Issue by jr200** [gravitl/netmaker#182]
If I change the IP address of a node (from the UI), the network-interface gets assigned with additional secondary ips. Here is an example starting with `10.70.0.226`, then changing the ip to `10.70.0.229` then `10.70.0.230`.

```
4: nm-k3s: <POINTOPOINT,NOARP,UP,LOWER_UP> mtu 1420 qdisc noqueue state UNKNOWN group default qlen 1000
    link/none
    inet 10.70.0.226/24 scope global nm-k3s
       valid_lft forever preferred_lft forever
    inet 10.70.0.229/24 scope global secondary nm-k3s
       valid_lft forever preferred_lft forever
    inet 10.70.0.230/24 scope global secondary nm-k3s
       valid_lft forever preferred_lft forever
```

After a reboot, I see (as expected):

```
4: nm-k3s: <POINTOPOINT,NOARP,UP,LOWER_UP> mtu 1420 qdisc noqueue state UNKNOWN group default qlen 1000
    link/none
    inet 10.70.0.230/24 scope global nm-k3s
       valid_lft forever preferred_lft forever
```

The old IPs in the list appear non-functional, but it causes issues for me as a `dig <node>.k3s @10.70.0.1` (where the CoreDNS runs) returns the first item in the list.

**Comment by afeiszli** [comment]
fixed in 0.7. Checkin will now delete interface and recreate, which will avoid duplicate IP's.
