### ISSUE TITLE
Installation Script Syntax Error

### ISSUE THREAD

**Issue by josifbg** [gravitl/netmaker#1856]
Using the installation script: 
sudo wget -qO /root/nm-quick-interactive.sh https://raw.githubusercontent.com/gravitl/netmaker/master/scripts/nm-quick-interactive.sh && sudo chmod +x /root/nm-quick-interactive.sh && sudo /root/nm-quick-interactive.sh

I`ve got an error msg:

/root/nm-quick-interactive.sh: line 318: syntax error near unexpected token `fi'

**Comment by abhishek9686** [comment]
@josifbg try out the latest install script 
`sudo wget -qO /root/nm-quick.sh https://raw.githubusercontent.com/gravitl/netmaker/master/scripts/nm-quick.sh && sudo chmod +x /root/nm-quick.sh && sudo /root/nm-quick.sh`
