### ISSUE TITLE
allow multiple A records for custom DNS entries

### ISSUE THREAD

**Issue by jr200** [gravitl/netmaker#187]
I have setup a multi-master k3s cluster over wireguard. 
I'd like to create a custom dns entry to round-robin between my api-server nodes.

When I try and add a second IP for the dns entry, I get:

```
{
  "Code":400,
  "Message":
    "Key: 'DNSEntry.Name' 
     Error:Field validation for 'Name' failed on the 'name_unique' tag"
}
```

Would it be sufficient to relax this constraint?

**Comment by afeiszli** [comment]
Hi @jr200, after looking into this, I don't believe it is feasible with the current implementation. Reason is we are using the CoreDNS "hosts" plugin, which does not seem to allow this. The standard way to solve this would be with some form of external load balancer, which is probably what you need.

**Comment by afeiszli** [comment]
Closing, as it is not currently feasible to load balance DNS with CoreDNS.
