### ISSUE TITLE
Error while joining raspberry pi to network ./netclient: XXXX: not found

### ISSUE THREAD

**Issue by franciscosuca** [gravitl/netmaker#190]
I am trying to connect to the server using a raspberry pi 4, but after following the [quick-start](https://docs.netmaker.org/quick-start.html) guide I get the following errors :

./netclient: 1: ./netclient: ELF: not found
./netclient: 1: ./netclient: Wv: not found
./netclient: 1: ./netclient: v: not found
./netclient: 1: ./netclient: ��m�m�$$: not found
./netclient: 2: ./netclient: @$: not found
./netclient: 1: ./netclient: �: not found
./netclient: 1: ./netclient: {�: not found
./netclient: 3: ./netclient: @�@$@Q�t�e@*Ev: not found
./netclient: 4: ./netclient:��{��{��
                                   v�: not found
./netclient: 4: ./netclient: ����~�~��
                                      ����: not found
./netclient: 6: ./netclient: Syntax error: "(" unexpected

----------------------------------------------------------------------

**Replicate scenario:**

1. Installed wireguard `apt install wireguard`
2. Join the network using `curl -sfL https://raw.githubusercontent.com/gravitl/netmaker/v0.5/scripts/netclient-install.slim.sh | KEY=MY_TOKEN`

Am I missing any step to run this on a ARM device, or something like that?

**Comment by afeiszli** [comment]
updated arm64 binary here: https://github.com/gravitl/netmaker/releases/download/v0.5-beta/netclient-arm64
Use this one, and you will have to manually join a network with the correct info ("netclient-arm64 join --help" to see options)

**Comment by franciscosuca** [comment]
> updated arm64 binary here: https://github.com/gravitl/netmaker/releases/download/v0.5-beta/netclient-arm64
> Use this one, and you will have to manually join a network with the correct info ("netclient-arm64 join --help" to see options)

Thanks for the info, and sorry for the delay! but what I did a couple of hours later was to try the connection using wireguard only and the setup worked as expected. 

Nevertheless, I will give it a chance to this solution later!
