### ISSUE TITLE
Testing Caddy Setup Fails

### ISSUE THREAD

**Issue by clintonmarshall** [gravitl/netmaker#1943]
### Contact Details

Clinton.Marshall@gmail.com

### What happened?

Installing a fresh Digital Ocean Netmaker Market Place Droplet or Standalone fresh Ubuntu server using the GitHub install script as per quick setup results in caddy setup failings and whole install stops.

checking the Docker logs shows 

### Version

v0.17.1

### What OS are you using?

Linux

### Relevant log output

```shell
Testing Caddy setup (please be patient, this may take 1-2 minutes)
    Issue establishing connection...retrying in 15 seconds...
    Issue establishing connection...retrying in 20 seconds...
    Issue establishing connection...retrying in 25 seconds...
    Issue establishing connection...retrying in 30 seconds...
    Issue establishing connection...retrying in 35 seconds...
    Issue establishing connection...retrying in 40 seconds...
    Issue establishing connection...retrying in 45 seconds...
    Caddy is having an issue setting up certificates, please investigate (docker logs caddy)
    Exiting...


——
Docker caddy log. Note domain working, but removed from this log extract. I thought DNS issue but all is working. Could be certificate service issue?

{"resumed":false,"version":772,"cipher_suite":4865,"proto":"h2","server_name":"netmaker-exporter.xxx"}},"duration":0.00078337,"status":502,"err_id":"6g6q45aif","err_trace":"reverseproxy.statusError (reverseproxy.go:1272
```

### Contributing guidelines

- [X] Yes, I did.

**Comment by afeiszli** [comment]
Sounds like an issue requesting certificates, not sure if this is something we can solve.

**Comment by clintonmarshall** [comment]
Seems as there was an issue with cert pricier , now working

**Comment by musaulker** [comment]
> Seems as there was an issue with cert pricier , now working

how did you solve? having the same problem

**Comment by msaum** [comment]
I am having the same problem in 18.5.  Completely rebuilt the server from scratch and tried both the CE and EE versions.
