### ISSUE TITLE
Minimum number of characters for network name (change from 3 to 2 character)

### ISSUE THREAD

**Issue by FDrebin** [gravitl/netmaker#195]
In accordance with the documentation, when planning to use DNS of netmaker the network name must match the domain name. When utilizing a 3 character network name this functions perfectly (com, net, org, as examples) , but when attempting to use a 2 character network name it does not allow the creation of the network, a 2 character network name of ai, me, us, as examples are ones that do not allow the creation of the network.

Testing was performed using netmaker v0.5 , successful creation of a network name of "com" worked and allowed the dns creation of service1.domain.(network name of com) functions perfectly, as well as net and org; but was unable to test the use of ai, me, us as the network was unable to be created.

**Comment by afeiszli** [comment]
This has been updated on Develop branch and is in the v0.5.9 version docker image.
