### ISSUE TITLE
[Bug]: error installing:  error creating node 502 Bad Gateway 

### ISSUE THREAD

**Issue by cmbcbe** [gravitl/netmaker#1987]
### Contact Details

cedric@cmbc.be

### What happened?

Freshly installed server with first client:
[netclient] 2023-01-28 18:24:51 joining net-private at api.vpn.mydomain.be:443 
[netclient] 2023-01-28 18:25:15 error installing:  error creating node 502 Bad Gateway  
[netclient] 2023-01-28 18:25:15 error running command: wg-quick down /etc/netclient/config/.conf 
[netclient] 2023-01-28 18:25:15 wg-quick: `/etc/netclient/config/.conf' does not exist 
[netclient] 2023-01-28 18:25:16 removed systemd remnants if any existed 
Debian 11 same on MacOS M1
[netclient] 2023-01-28 18:27:47 joining cmbc-private at api.vpn.mydomain.be:443 
[netclient] 2023-01-28 18:27:53 error installing:  error creating node 502 Bad Gateway  
[netclient] 2023-01-28 18:27:53 error running command: wg-quick down /Applications/Netclient/config/.conf 
[netclient] 2023-01-28 18:27:53 wg-quick: The config file must be a valid interface name, followed by .conf 

### Version

v0.17.1

### What OS are you using?

Linux, Mac

### Relevant log output

```shell
docker logs netmaker
[netmaker] 2023-01-28 17:28:26 connecting to sqlite
[netmaker] 2023-01-28 17:28:26 database successfully connected
[netmaker] 2023-01-28 17:28:26 no OAuth provider found or not configured, continuing without OAuth
[netmaker] 2023-01-28 17:28:26 could not update user admin
[netmaker] 2023-01-28 17:28:26 Configuring MQ...
[netmaker] 2023-01-28 17:28:26 MQ config exists already, So Updating Existing Config...
[netmaker] 2023-01-28 17:28:26 REST Server successfully started on port  8081  (REST)
[netmaker] 2023-01-28 17:28:26 connecting to mq broker at ws://mq:1883 with TLS? false
```

### Contributing guidelines

- [X] Yes, I did.

**Comment by cmbcbe** [comment]
A field *.vpn.mydomain pointing to VPS, all url are accessible (api,dashboard,broker)

**Comment by oudong90** [comment]
Is wireguard installed? log error running command

**Comment by cmbcbe** [comment]
hello yes, i d'ont know why, i have reninstall from existing compose. Now it work, only things i have change is the dns configuration from cname *.vpn.domain.com pointing to A vpn.domain.com to A field *.vpn.domain.com pointing to vps  (cloudflare)

**Comment by oudong90** [comment]
cloudflare dns agent needs to be disabled

cmbcbe ***@***.***> 于2023年1月29日周日 17:50写道：

**Comment by cmbcbe** [comment]
it was already disable, perhaps netmaker don't like cname and need A field...

**Comment by oudong90** [comment]
ok, if you have a domain name certificate, you can try localization.my
configuration file is as follows, you can refer to it!
vi Caddyfile
 {
         # LetsEncrypt account



         auto_https disable_certs
 }

 # Dashboard
  8 https://dashboard.vpn.xxx.xxx {
  9         tls /certs/xx/fullchain.pem /certs/xx/privkey.pem
 10         # Apply basic security headers
 11         header {
 12                 # Enable cross origin access to *.vpn.dofun.work
 13                 Access-Control-Allow-Origin *.vpn.dofun.work
 14                 # Enable HTTP Strict Transport Security (HSTS)
 15                 Strict-Transport-Security "max-age=31536000;"
 16                 # Enable cross-site filter (XSS) and tell browser to
block detected attacks
 17                 X-XSS-Protection "1; mode=block"
 18                 # Disallow the site to be rendered within a frame on a
foreign domain (clickjacking protection)
 19                 X-Frame-Options "SAMEORIGIN"
 20                 # Prevent search engines from indexing
 21                 X-Robots-Tag "none"
 22                 # Remove the server name
 23                 -Server
 24         }
 25
 26         reverse_proxy http://netmaker-ui
 27 }
 28
 29 # API
 30 https://api.vpn.xxx.xxx {
 31         tls /certs/xx/fullchain.pem /certs/xx/privkey.pem
 32         reverse_proxy http://netmaker:8081
 33 }
 34
 35 # MQ
 36 wss://broker.vpn.xxx.xxx {
 37         tls /certs/xx/fullchain.pem /certs/xx/privkey.pem
 38         reverse_proxy ws://mq:8883
 39 }

vi docker-compose.yml
modify caddy volumes,add certificate mount
 55   caddy:
 56     image: caddy:2.6.2
 57     container_name: caddy
 58     restart: unless-stopped
 59     volumes:
 60       - /root/Caddyfile:/etc/caddy/Caddyfile
 61       - /root/certs/:/certs #Local certificate path
 62       - caddy_data:/data
 63       - caddy_conf:/config


cmbcbe ***@***.***> 于2023年1月29日周日 18:46写道：

**Comment by cmbcbe** [comment]
just retried a fresh install of netmaker server, same issue. the joincommand create the node on the dashboard but get always this error. DNS is configured as before when it was working...
