### ISSUE TITLE
[Bug]: docker logs mq -f /mosquitto/config/wait.sh: line 5: curl: not found

### ISSUE THREAD

**Issue by bcookatpcsd** [gravitl/netmaker#2018]
### What happened?

docker logs mq -f /mosquitto/config/wait.sh: line 5: curl: not found

docker exec -it mq sh

apk add curl

Waiting for netmaker server to startup
Waiting for netmaker server to startup
Waiting for netmaker server to startup
Waiting for netmaker server to startup
Waiting for netmaker server to startup
Waiting for netmaker server to startup

cannot find what problem this was causing or what it may have fixed.. 

coredns cannot find netmaker host.. 

/var/lib/docker/volumes/root_dnsconfig/_data/netmaker.hosts

is empty.. 

when I populate it with correct entries.. it reboots and wipes it out again.. 

chattr -i netmaker.hosts ; echo 172.23.0.23 netmaker >> netmaker.hosts ; echo 172.23.0.5 mq >> netmaker.hosts; chattr +i netmaker.hosts ; cat netmaker.hosts

172.23.0.23 netmaker
172.23.0.5 mq

still problems.. 

[netmaker] 2023-02-11 12:25:56 connecting to sqlite
[netmaker] 2023-02-11 12:25:56 database successfully connected
[netmaker] 2023-02-11 12:25:56 no OAuth provider found or not configured, continuing without OAuth
[netmaker] 2023-02-11 12:25:56 could not update user '8< -snip- >8'
[netmaker] 2023-02-11 12:25:56 error occurred initializing DNS:  open ./config/dnsconfig/netmaker.hosts: operation not permitted
[netmaker] 2023-02-11 12:25:56 Configuring MQ...
[netmaker] 2023-02-11 12:25:56 MQ config exists already, So Updating Existing Config...
[netmaker] 2023-02-11 12:26:16 REST Server successfully started on port  8081  (REST)
[netmaker] 2023-02-11 12:26:36 connecting to mq broker at ws://mq:1883 with TLS? false
[netmaker] Fatal: Admin: could not connect to broker, token timeout, exiting ...

### Version

v0.17.1

### Contributing guidelines

- [X] Yes, I did.

**Comment by mattkasun** [comment]
use v0.18.+
