### ISSUE TITLE
[Bug]: admin user reset

### ISSUE THREAD

**Issue by tril0byte** [gravitl/netmaker#2020]
### Contact Details

tril@metapipe.net

### What happened?

created Dedipath KVM based instance with Ubuntu 20.04
Upgraded to Ubuntu 22.04
Installed Netmaker CE by downloading https://raw.githubusercontent.com/gravitl/netmaker/master/scripts/nm-quick-interactive.sh and choosing CE.
Logged in, started using it, created networks and nodes, everything has been working (for > 30 days).
Today it would not let me login to the admin user and instead prompted me to create a new admin user.  I could not create the old admin user, but made an admin user with a new name and it worked.  Now I can login to both admin users, but all the networks and nodes show up on the new admin user and not the old one.

This  seems a serious security problem since someone else could have created a user by visiting my server with HTTPS and accessed all my Netmaker configuration.

### Version

v0.17.0

### What OS are you using?

Linux

### Relevant log output

```shell
Unsure which logs are relevant here, will check back and see if any are requested.
```

### Contributing guidelines

- [X] Yes, I did.

**Comment by mattkasun** [comment]
email request for additional data sent

**Comment by tril0byte** [comment]
My Last email reply includes Steps to reproduce this bug should be easy fix

**Comment by mattkasun** [comment]
confirmed issue in v017.0; has been fixed in v0.17.1; recommend upgrade

**Comment by tril0byte** [comment]
The bug is: when signed in as an Admin, on the edit user screen accessible from your profile icon above Logout or from your name in the list of users, it is possoble to get the "Is Admin" checkbox to show as unchecked ( by reloading the page ) and then submit (by filling in both new password fields and pressing the Are You Sure You Want to Change Password button).  This results in changing your password while also removing your admin privileges. Due to you still remaining logged in, along with caching, this may not be immediately clear. If you were the last Admin and removed your Admin ability, then the next user attempting to login will be prompted to create a new admin with full access to all networks.

**Comment by tril0byte** [comment]
Upgraded looks good
