### ISSUE TITLE
[Bug]: Caddy is having an issue setting up certificates

### ISSUE THREAD

**Issue by kindberg-hub** [gravitl/netmaker#2027]
### Contact Details

mrkindberg@gmail.com

### What happened?

Hello

I have tried to install netmaker several times through digitalocean 1-click. But it stops at Caddy setup every time : 

"Issue establishing connection...retrying in 35 seconds...
    Caddy is having an issue setting up certificates, please investigate (docker logs caddy)"

I am a complete newbie when it comes to linux. So bear with my incompetence

### Version

v0.17.1

### What OS are you using?

Windows

### Contributing guidelines

- [X] Yes, I did.

**Comment by afeiszli** [comment]
Hi, I just tested the 1-Click and are unable to recreate.

1. What region are you running in?
2. Are you using a custom domain?

If using a custom domain, the most likely culprit is that the domain is set incorrectly in either DNS or in the docker-compose.yml file, and so Caddy is unable to obtain certificates.

**Comment by afeiszli** [comment]
If you can try again, we just pushed a hotfix that may resolve your issue.

**Comment by kindberg-hub** [comment]
Hi

Im running a custom .eu domain.

I tried again today where I switched from their Frankfurt servers to the Amsterdam servers, and then it worked.

So I don't know if it was your hotfix or their sever that solved the problem, but thanks for the response

**Comment by afeiszli** [comment]
Thanks for your response, closing issue.

**Comment by baerwang** [comment]
I also came across , fix question is?

**Comment by jlippold** [comment]
Im getting this issue as well, whats the fix? 

`Caddy is having an issue setting up certificates, please investigate (docker logs caddy)`

**Comment by prom3theu5** [comment]
I had the same issue on a fresh install of Ubuntu 22.04
However I did come across a line regarding this issue: https://github.com/quic-go/quic-go/wiki/UDP-Receive-Buffer-Size

Following the instructions there and calling: `sysctl -w net.core.rmem_max=2500000` increased the buffer size and allowed the certificate request to go through fine

**Comment by ahteknik** [comment]
I am having this same issue, both with my own domain and the autocreated. Have verified domain names working separately.

Tried Frankfurt, Amsterdam (did not have image) and London. Same result in Frankfurt and London:

Testing Caddy setup (please be patient, this may take 1-2 minutes)
    Issue establishing connection...retrying in 15 seconds...
    Issue establishing connection...retrying in 20 seconds...
    Issue establishing connection...retrying in 25 seconds...
    Issue establishing connection...retrying in 30 seconds...
    Issue establishing connection...retrying in 35 seconds...
    Caddy is having an issue setting up certificates, please investigate (docker logs caddy)
    Exiting...

**Comment by ahteknik** [comment]
I also tried setting up a droplet on a Ubuntu 22.04 and running the script manually, exact same issue wether using the automated domain name or my own. 

Going to try the community version next.

Tried it - same problem.

**Comment by leftbrake** [comment]
Running as root, added `sysctl -w net.core.rmem_max=2500000`. Issue persists. 

Caddy log has a lot of entries like this: 
`order took too long (ca=https://acme.zerossl.com/v2/DV90)`

**Comment by Jachimo** [comment]
I'm running into this too, on an AWS Lightsail VPS and a custom domain with a wildcard entry pointing to the Lightsail VPS instance.  Installer v0.1.1, build/image v0.20.6.

I'm running (as root) `sudo wget -qO /root/nm-quick.sh https://raw.githubusercontent.com/gravitl/netmaker/master/scripts/nm-quick.sh && sudo chmod +x /root/nm-quick.sh && sudo /root/nm-quick.sh` and after entering my domain and email, hitting enter for the MQ and TURN username/pass (auto-generated passwords for both), it chugs for a while and then I get into a loop where Caddy is supposedly retrying, but it never works.  (Also, the intervals take MUCH longer than the stated number of seconds.)

I have no idea where to go from here. It's not even obvious where the Caddy logs are; I don't see any files in /var/log and there's no unit by that name that I can view with journalctl. So this is a show-stopper as far as I'm concerned.

**Comment by xtwo-0** [comment]
> I'm running into this too, on an AWS Lightsail VPS and a custom domain with a wildcard entry pointing to the Lightsail VPS instance. Installer v0.1.1, build/image v0.20.6.
> 
> I'm running (as root) `sudo wget -qO /root/nm-quick.sh https://raw.githubusercontent.com/gravitl/netmaker/master/scripts/nm-quick.sh && sudo chmod +x /root/nm-quick.sh && sudo /root/nm-quick.sh` and after entering my domain and email, hitting enter for the MQ and TURN username/pass (auto-generated passwords for both), it chugs for a while and then I get into a loop where Caddy is supposedly retrying, but it never works. (Also, the intervals take MUCH longer than the stated number of seconds.)
> 
> I have no idea where to go from here. It's not even obvious where the Caddy logs are; I don't see any files in /var/log and there's no unit by that name that I can view with journalctl. So this is a show-stopper as far as I'm concerned.

`docker logs caddy` is where the logs are at

**Comment by dlx-systems** [comment]
> Running as root, added `sysctl -w net.core.rmem_max=2500000`. Issue persists.
> 
> Caddy log has a lot of entries like this: `order took too long (ca=https://acme.zerossl.com/v2/DV90)`

Tried this, and ecverything else on this page, no go... Do accept that this is a reason for moving on please? I tried everything I could find on Google related to this issue, nothing 👎

**Comment by crawc** [comment]
Same issue here. @afeiszli can this be re-opened?

1. Fresh Ubuntu 22 Install, up-to-date.
2. Custom wildcard domain *.netmaker.mydomain.com
3. Ran installer as root.
4.  Changed the `net.core.rmem_max=2500000` option.

`Testing Caddy setup (please be patient, this may take 1-2 minutes)
    Issue establishing connection...retrying in 15 seconds...
    Issue establishing connection...retrying in 20 seconds...
    Issue establishing connection...retrying in 25 seconds...
    Issue establishing connection...retrying in 30 seconds...
    Issue establishing connection...retrying in 35 seconds...
    Issue establishing connection...retrying in 40 seconds...
    Issue establishing connection...retrying in 45 seconds...
    Caddy is having an issue setting up certificates, please investigate (docker logs caddy)
`

`docker logs caddy` doesn't show anything that sticks out.

**Comment by xman-76** [comment]
> Same issue here. @afeiszli can this be re-opened?
> 
>     1. Fresh Ubuntu 22 Install, up-to-date.
> 
>     2. Custom wildcard domain *.netmaker.mydomain.com
> 
>     3. Ran installer as root.
> 
>     4. Changed the `net.core.rmem_max=2500000` option.
> 
> 
> `Testing Caddy setup (please be patient, this may take 1-2 minutes) Issue establishing connection...retrying in 15 seconds... Issue establishing connection...retrying in 20 seconds... Issue establishing connection...retrying in 25 seconds... Issue establishing connection...retrying in 30 seconds... Issue establishing connection...retrying in 35 seconds... Issue establishing connection...retrying in 40 seconds... Issue establishing connection...retrying in 45 seconds... Caddy is having an issue setting up certificates, please investigate (docker logs caddy) `
> 
> `docker logs caddy` doesn't show anything that sticks out.

I got same issue... please help!

**Comment by kikipatton** [comment]
Same issue, stuck at retrying

**Comment by WoMec** [comment]
+1 ... same issue here. Fresh install of Debian 12.

**Comment by Aakif17** [comment]
Same issue, tried everything suggested in this thread.

**Comment by abhishek9686** [comment]
> Same issue, tried everything suggested in this thread.

are you using nip.io domain or custom domain?

**Comment by eyeball29** [comment]
I'm using a custom domain and also having the same issue. Should we be forwarding ports from our router if running a home server? Any other ports that need opening other than the ones listed on the main readme? In the logs for me it notes ```
""issuer":"acme-v02.api.letsencrypt.org-directory","error":"HTTP 400 urn:ietf:params:acme:error:connection - 24.107.226.23: Timeout during connect (likely firewall
problem)"}
```

**Comment by hatcreek68** [comment]
+1.  Custom domain ping OK; ports open; still I get:
Caddy is having an issue setting up certificates, please investigate (docker logs caddy)
