### ISSUE TITLE
Help: How can I add an SSL cert so I'm not using http?

### ISSUE THREAD

**Issue by bowen-song** [gravitl/netmaker#203]
Hi, apologies if this isn't the correct place to ask this question - I'm pretty new with this stuff. Second, really appreciate the work you're doing with this project; it's very cool!

Now, to the question: How can I use my own ssl cert with netmaker?

Here's my current setup of the server:
- hosted on google cloud platform
- using the base docker-compose file from the documentation
- http and https "allowed" in the google cloud platform firewall
- personal domain name from google
- cert ideally generated by letsencrypt/certbot

In times past, I've used certbot with nginx on docker successfully, but I'm not sure how to go about using https with netmaker in this instance (I took a brief peek through the ui and it seems like you are using nginx so I believe this should be possible?). Thanks!

**Comment by afeiszli** [comment]
Hi bowen, I have a whole guide on setting up netmaker behind nginx reverse proxy with letsencrypt. This guide is not 100% functional yet (is planned for next release) and for now you should use the older versions of the images. Other than that, in general this should work: https://netmaker.readthedocs.io/en/develop/quick-start.html#prepare-nginx

**Comment by bowen-song** [comment]
Thanks for the guide, I'll check it out and report back if there are any issues!
