### ISSUE TITLE
[Bug]: relay not working

### ISSUE THREAD

**Issue by eleaner** [gravitl/netmaker#2046]
### Contact Details

github@kisiel.net.pl

### What happened?

mesh of normal nodes (VPS) can ping each other easily,
relayed nodes can't ping anyone - neither relay nor nodes behind relay or each other nor 
the relayed nodes sit in my home network behind the broadband provider's private network, so I guess some double NAT
![image](https://user-images.githubusercontent.com/5169203/219506453-0a5a2709-5163-471d-96a2-6332d9260610.png)

if I remove the relay, the nodes in home network can ping each other
but not the VPSes

the weird thing is that if I do a simple wireguard mesh by hand
everybody can ping everybody
obviously, the VPSes cannot connect directly to my home network, but I guess the connection is initiated from the other side

### Version

v0.17.1

### What OS are you using?

Linux

### Relevant log output

```shell
I am happy to produce, but please guide how
```

### Contributing guidelines

- [X] Yes, I did.

**Comment by eleaner** [comment]
is there anything I could analyse?
please help

**Comment by mattkasun** [comment]
Can you provide the allowedips of each node

**Comment by eleaner** [comment]
thank you @mattkasun 
Happy to do that, but what exactly should I do?

**Comment by eleaner** [comment]
I hope that's it
internetpi: 10.102.21.9
allowed ips: 10.102.21.4/32, 10.102.21.254/32, 10.102.21.8/32, 10.102.21.5/32, 10.102.21.7/32, 10.102.21.6/32, 10.102.21.2/32, 10.102.21.3/32, 10.102.21.1/32

tungsten: 10.102.21.2
allowed ips: 10.102.21.4/32, 10.102.21.254/32, 10.102.21.8/32, 10.102.21.5/32, 10.102.21.7/32, 10.102.21.6/32, 10.102.21.3/32, 10.102.21.1/32, 10.102.21.9/32

bismuth: 10.102.21.3
 allowed ips: 10.102.21.4/32, 10.102.21.254/32, 10.102.21.8/32, 10.102.21.5/32, 10.102.21.7/32, 10.102.21.6/32, 10.102.21.2/32, 10.102.21.1/32, 10.102.21.9/32
 
oci11: 10.102.21.4 (relay)
 allowed ips: 10.102.21.3/32
 allowed ips: 10.102.21.9/32
 allowed ips: 10.102.21.2/32

**Comment by eleaner** [comment]
I recreated the network with ipv6, and it looks like the result is the same.

**Comment by eleaner** [comment]
OK, it looks like it was a very stupid mistake configuring port forwarding on my VPSes :(
