### ISSUE TITLE
Linux Install Without Docker - documentation may need to be changed from the mongodb creation command

### ISSUE THREAD

**Issue by bmullan** [gravitl/netmaker#206]
FYI as I was using your instructions
https://docs.netmaker.org/server-installation.html#linux-install-without-docker

When executing the following I kept getting an error executing:

> db.createUser({ user: “mongoadmin” , pwd: “mongopass”, roles: [“userAdminAnyDatabase”, “dbAdminAnyDatabase”, “readWriteAnyDatabase”]})
2021-08-09T14:45:32.154-0400 E QUERY    **[thread1] SyntaxError: illegal character @(shell):1:22**

I did some google searches and found that If you are using mongoshell or javascript then I had to use SINGLE Quotes not DOUBLE Quotes.    

**So the following works but not the above.**

> db.createUser({ user: 'mongoadmin' , pwd: 'mongopass', roles: ['userAdminAnyDatabase', 'dbAdminAnyDatabase, 'readWriteAnyDatabase']})

**Comment by afeiszli** [comment]
@bmullan we will need to update these docs. We are prepping for 0.7 release and are migrating from mongodb to rqlite (distributed sqlite), so this will not be relevant very soon.
