### ISSUE TITLE
[Bug]:  What is the API port ?

### ISSUE THREAD

**Issue by trump-7575** [gravitl/netmaker#2070]
### What happened?

I tried to access the netmaker API ( REST ) port to config the networks . Unfortunatly , the port ( 8081 ? ) is not open at all . Another words , I used netstat to check the ports and did not see a port named 8081 .  Is this interface not avail. at netmaker version 0.16.3 ?

Even though the log of netmaker seems O.K. and I did log into netmaker's ui (  https://dashboard.netmaker.mydomain.com /  )  .  What's wrong with it ?

### Version

v0.16.3

### What OS are you using?

Linux

### Relevant log output

```shell
~ # docker logs netmaker    -n   20
/\ "-.\ \   /\  ___\   /\__  _\ /\ "-./  \   /\  __ \   /\ \/ /    /\  ___\   /\  == \   
\ \ \-.  \  \ \  __\   \/_/\ \/ \ \ \-./\ \  \ \  __ \  \ \  _"-.  \ \  __\   \ \  __<   
 \ \_\\"\_\  \ \_____\    \ \_\  \ \_\ \ \_\  \ \_\ \_\  \ \_\ \_\  \ \_____\  \ \_\ \_\ 
  \/_/ \/_/   \/_____/     \/_/   \/_/  \/_/   \/_/\/_/   \/_/\/_/   \/_____/   \/_/ /_/ 
                                                                                         						        

[netmaker] 2023-02-24 20:05:20 connecting to sqlite 
[netmaker] 2023-02-24 20:05:21 database successfully connected 
[netmaker] 2023-02-24 20:05:21 no OAuth provider found or not configured, continuing without OAuth 
[netmaker] 2023-02-24 20:05:25 Configuring MQ... 
[netmaker] 2023-02-24 20:05:25 MQ config exists already, So Updating Existing Config... 
[netmaker] 2023-02-24 20:05:25 REST Server successfully started on port  8081  (REST) 
[netmaker] 2023-02-24 20:05:25 connecting to mq broker at mq:1883 with TLS? false 
[netmaker] 2023-02-24 20:06:30 checking for zombie nodes 
[netmaker] 2023-02-24 20:06:30 set new peers on network mynetwork 
[netmaker] 2023-02-24 20:07:30 checking for zombie nodes 
[netmaker] 2023-02-24 20:08:30 checking for zombie nodes 
[netmaker] 2023-02-24 20:09:30 checking for zombie nodes
```

### Contributing guidelines

- [X] Yes, I did.

**Comment by mattkasun** [comment]
The rest API is only available through the proxy at HTTPS://dashboard.your.domain

**Comment by trump-7575** [comment]
I tried to play with netmaker 0.17.1 and still have the problem. Any ideas ?

~ # curl  -v -H "Authorization: Bearer the_master_key"  -H  "Accept: application/json"  api.nm.111-222-6-111.nip.io:443/api/networks | jq
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0*   Trying 111-222-6-111:443...
* Connected to api.nm.111-222-6-111.nip.io (111-222-6-111) port 443 (#0)
> GET /api/networks HTTP/1.1
> Host: api.nm.111-222-6-111.nip.io:443
> User-Agent: curl/7.81.0
> Authorization: Bearer the_master_key
> Accept: application/json
> 
* Mark bundle as not supporting multiuse
* HTTP 1.0, assume close after body
< HTTP/1.0 400 Bad Request
< 
{ [48 bytes data]
100    48    0    48    0     0   3491      0 --:--:-- --:--:-- --:--:--  3692
* Closing connection 0
parse error: Invalid numeric literal at line 1, column 7

**Comment by mattkasun** [comment]
change your url to https://api.nm.111-222-6-111.nip.io/api/networks

**Comment by trump-7575** [comment]
Thankyou very much ~
