### ISSUE TITLE
Unsure which PORT to specify when setting the BACKEND_URL

### ISSUE THREAD

**Issue by bmullan** [gravitl/netmaker#208]
following the documentation:   https://docs.netmaker.org/server-installation.html#ui-setup

I see where I am to execute:

> sudo sh -c 'BACKEND_URL=http://127.0.0.1:PORT /usr/share/nginx/html/generate_config_js.sh > /usr/share/nginx/html/config.js'

But... (sorry for the dumb question) but from the above which **PORT** do I enter here... or is it up to me to pick something?
 
thanks

**Comment by afeiszli** [comment]
@bmullan this is the HTTP port for the netmaker API. By default this is 8081 (if you haven't set it any different. Also 127.0.0.1 should be set to whatever is the reachable (public) IP of the server.

You can set this port on the backend with the env var API_PORT.

You may want to wait until tomorrow, as we are prepping the 0.7 release and there will be a few changes/upgrades/depreciations.
