### ISSUE TITLE
[Bug]: adding node to second relay breaks connection

### ISSUE THREAD

**Issue by eleaner** [gravitl/netmaker#2081]
### What happened?

Adding the same node to the second relay seems to be breaking the connection

### Version

v0.17.1

### What OS are you using?

Linux

### Contributing guidelines

- [X] Yes, I did.

**Comment by mattkasun** [comment]
additional details required.

**Comment by eleaner** [comment]
oh I am sorry, it was reported so long ago I don't remember how I fixed it
