### ISSUE TITLE
[Bug]:  Failed to create a "is Point to Site" network

### ISSUE THREAD

**Issue by trump-7575** [gravitl/netmaker#2086]
### What happened?

I tried to create a network as described  at https://docs.netmaker.org/acls.html ( Scenario 1: Remote Access to/from Client devices )

When the network is created , I switched off the "Default Access Control" . In this case , the first node ( netmaker-1 )  has a "Allow"  Node Acl Rule which the rest nodes have a "Deny" acl rule.

But they DONOT connect to the first node at all.  What is wrong ?

### Version

v0.17.1

### What OS are you using?

Linux

### Contributing guidelines

- [X] Yes, I did.

**Comment by afeiszli** [comment]
"Point to Site" networks are deprecated in favor of using "default ACLs". The option will be removed from UI in next release.
Please see here for implementing via ACLs: https://docs.netmaker.org/acls.html#scenario-1-remote-access-to-from-client-devices
