### ISSUE TITLE
[Bug]: Version 18.5

### ISSUE THREAD

**Issue by virusczz** [gravitl/netmaker#2162]
### Contact Details

nebulacz@gmail.com

### What happened?

Engress: i add address: 0.0.0.0/0 => ip range can not be empty

### Version

v0.18.5

### What OS are you using?

Linux

### Contributing guidelines

- [X] Yes, I did.

**Comment by virusczz** [comment]
if i try a different ip all is ok, but with 0.0.0.0/0 no functioning :(

**Comment by virusczz** [comment]
in version 17.1 all was ok with 0.0.0.0/0

**Comment by afeiszli** [comment]
It is mentioned in the release notes now but 0.0.0.0/0 needs to be reimplemented, it will be in one of the next few releases. That is the correct workaround for now.

**Comment by mightywomble** [comment]
Completely broke my install.. Its kinda a fundamental thing.. :-( Appreciate the hard work, however this has now rendered netmaker useless to the usecase I have and I'll need to find an alternative product. So whomever made this decision, not a good one. (Above "fix" doesn't work)

**Comment by mattkasun** [comment]
internet gateways (0.0.0.0/0) restored in v0.18.7
