### ISSUE TITLE
[Bug]: Networks CIDR not applicated to nodes

### ISSUE THREAD

**Issue by rayfalling** [gravitl/netmaker#2169]
### Contact Details

me@rayfalling.com

### What happened?

I set the net work address raneg to CIDR 26
![image](https://user-images.githubusercontent.com/13343271/229331568-1b3d04d0-0377-4a75-95c8-193f0c1bba7e.png)
but node still have CIDR range 24
![image](https://user-images.githubusercontent.com/13343271/229331582-f9130e4b-2a60-4b03-bdeb-42552ed8b0c5.png)

This only happens after the network is created and modified. If network is create with CIDR 26 is correct

### Version

v0.18.5

### Contributing guidelines

- [X] Yes, I did.

**Comment by mattkasun** [comment]
networks are no longer editable
