### ISSUE TITLE
Netclient fails when interface does not exist.

### ISSUE THREAD

**Issue by hedgty** [gravitl/netmaker#221]
If the nm-\<network name\> interface does not exist, `netclient checkin -n <network name>` will fail and output `failed to parse interface`. This is a situation that occurs after reboots. The network will work again after running `netclient pull -n <network name>`.

I was able to temporarily fix this issue by making the changes in the diff file to the code and rebuilding netclient.
http://hastebin.com/xukovozego.diff

**Comment by afeiszli** [comment]
fixed in the latest hotfix. Thanks for the help @hedgty!
