### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by bose2273** [gravitl/netmaker#2219]
### Contact Details

surajit2273@gmail.com

### What happened?

Netmaker server version is 0.17.0 

I am trying to connect an ubuntu server to the netmaker server 

using the below command to join:

netclient join -t JhcGljb25uc3RyaW5nIjoiYXBpLm5ldG1ha2VyLnRlbGNhc3RhLmNvbTo0NDMiLCJuZXR3b3JrIjoidGVsY2FzdGEwMSIsImtleSI6ImIwYTg4NWNlNjMxMGRiNGYiLCJsb2NhbHJhbmdlIjoiIn0=

But getting the below error
2023-04-18 20:57:42 join failed Post "https:///api/v1/host/register/eyJhcGljb25uc3RyaW5nIjoiYXBpLm5ldG1ha2VyLnRlbGNhc3RhLmNvbTo0NDMiLCJuZXR3b3JrIjoidGVsY2FzdGEwMSIsImtleSI6ImIwYTg4NWNlNjMxMGRiNGYiLCJsb2NhbHJhbmdlIjoiIn0=": http: no Host in request URL 
root@netclient01:~# 

### Version

v0.17.0

### What OS are you using?

Linux

### Contributing guidelines

- [X] Yes, I did.

**Comment by mattkasun** [comment]
What version is the client?

**Comment by bose2273** [comment]
Client is 18.0

**Comment by bornav** [comment]
you need to install an older version of the client, the -t option has been deprecated

**Comment by bornav** [comment]
since you mentioned ubuntu, you can use the list "apt list -a netclient" to list all packages

and then when you decide what version works for you use "apt install netclient=0.17.1-0" the version is an example

**Comment by bose2273** [comment]
Thanks a lot @bornav  .. worked like a charm!!!!!!!
