### ISSUE TITLE
[Bug]: docker-compose.yml out of date

### ISSUE THREAD

**Issue by jalbstmeijer** [gravitl/netmaker#2225]
### Contact Details

--

### What happened?

I'm trying to use https://github.com/gravitl/netmaker/blob/master/compose/docker-compose.yml to setup NetMaker.
But it looks like this file is not working for the latest NetMaker release.

The best indication is the definition of MQ_USERNAME and  MQ_PASSWORD instead of MQ_ADMIN_PASSWORD.

Tried to fix it myself by getting info from https://netmaker.readthedocs.io/en/master/upgrades.html

But I end up with an error, I'm not sure how to fix. Cannot find this dynamic-security.json file anyware.

[netmaker] Fatal: failed to configure MQ:  open /etc/netmaker/dynamic-security.json: no such file or directory

Is there a better source for a working docker-compose.yml? or instructions?

### Version

v0.18.6

### What OS are you using?

Linux

### Relevant log output

```shell
netmaker  | 
netmaker  | [netmaker] 2023-04-20 13:42:17 connecting to sqlite 
netmaker  | [netmaker] 2023-04-20 13:42:17 database successfully connected 
netmaker  | [netmaker] 2023-04-20 13:42:17 no OAuth provider found or not configured, continuing without OAuth 
netmaker  | [netmaker] 2023-04-20 13:42:17 error setting iptables forward policy: exit status 3 
netmaker  | [netmaker] 2023-04-20 13:42:17 Configuring MQ... 
netmaker  | [netmaker] Fatal: failed to configure MQ:  open /etc/netmaker/dynamic-security.json: no such file or directory
```

### Contributing guidelines

- [X] Yes, I did.

**Comment by frayos** [comment]
You need to use this Conf : 
https://github.com/gravitl/netmaker/blob/master/docker/mosquitto.conf

You are using the previous version

**Comment by WebsliceNL** [comment]
I was and still use that version of mosquitto.conf

Not sure why you think a wrong mosquitto.conf config file for the "mq" container could result in the "netmaker" container not to find /etc/netmaker/dynamic-security.json

**Comment by WebsliceNL** [comment]
I see now I made a wrong assumption.
I was pulling gravitl/netmaker:latest , but it seems that is still v0.17.1 and not v0.18.6.
After pulling v0.18.6 the error went away.
