### ISSUE TITLE
Egress gateways appear function in UI but do not work.

### ISSUE THREAD

**Issue by hedgty** [gravitl/netmaker#223]
Egress gateways seem to work in the UI but they do not work. The PostUp and PostDown commands are modified properly, and the ui indicates that the gateway has been added. The netconfig file also indicated that the egress gateway has been added. However, the egress network range is never added to allowed-ips on other nodes.

**Comment by afeiszli** [comment]
fixed in latest hotfix. Thanks for the help @hedgty!
