### ISSUE TITLE
[Bug]: docker image server tag: v0.19.0 still shows "Server: v0.18.7" in UI

### ISSUE THREAD

**Issue by skygunner** [gravitl/netmaker#2265]
### What happened?

docker image server tag: v0.19.0 still shows "Server: v0.18.7" in UI

### Version

v0.19.0

### Contributing guidelines

- [X] Yes, I did.

**Comment by pernetz** [comment]
Same issue here. With `docker ps` command it seems the server is running with correct version.

![image](https://user-images.githubusercontent.com/130795064/236622400-35af5c39-bd4c-4254-8954-d053377b6555.png)

**Comment by mattkasun** [comment]
docker image updated:
to retrieve run
`docker-compose pull; docker-compose up -d`
