### ISSUE TITLE
[Bug]: External client config files with IPv6 endpoints lack `[]` separating the address and port.

### ISSUE THREAD

**Issue by Southpaw1496** [gravitl/netmaker#2273]
### Contact Details

paw@southpaw1496.me

### What happened?

When you create an External Client with an IPV6 endpoint and download the Wireguard configuration file, the `Endpoint` address doesn't separate the IP and port using square brackets, which Wireguard requires.

This is an example of what is generated:
```conf
[Peer]
PublicKey = G0OsUs6T1HOSmWZxWKMpiGcPEAGsgQOjcmlfgxxbs3I=
AllowedIPs = 10.1.1.0/24
Endpoint = 2001:db8::1:51821
PersistentKeepalive = 20
```

This is what should be generated:
```conf
[Peer]
PublicKey = G0OsUs6T1HOSmWZxWKMpiGcPEAGsgQOjcmlfgxxbs3I=
AllowedIPs = 10.1.1.0/24
Endpoint = [2001:db8::1]:51821
PersistentKeepalive = 20
```

### Version

v0.19.0

### What OS are you using?

Linux

### Contributing guidelines

- [X] Yes, I did.

**Comment by uGiFarukh** [comment]
@Southpaw1496, the fix will be available in v0.20.6
