### ISSUE TITLE
[Bug]: Installation Script: Permissions Denied

### ISSUE THREAD

**Issue by josifbg** [gravitl/netmaker#2310]
### Contact Details

josifbg@gmail.com

### What happened?

During the Installation of the new version 0.20 and following the installation script/guide when installing the certbot container the installation script stops with the error: Permission Denied.

### Version

v0.20.0

### What OS are you using?

Linux

### Relevant log output

```shell
Pulling config files...
Saving the config to /root/netmaker.env
Setting up SSL certificates...
chmod: cannot access 'certbot-entry.sh': No such file or directory
Unable to find image 'certbot/certbot:latest' locally
latest: Pulling from certbot/certbot
91d30c5bc195: Pull complete 
5d0bb5b9b8b7: Pull complete 
9369f9a4ffc3: Pull complete 
d7106b6bd561: Pull complete 
8c76a60d2b3a: Pull complete 
e08bf95bbd48: Pull complete 
26174528a65c: Pull complete 
41fea484b2e1: Pull complete 
5dd9ac53b45b: Pull complete 
899e8acb0a4c: Pull complete 
dad4a746029b: Pull complete 
b524cdf16a36: Pull complete 
Digest: sha256:92092d214a4eb75d049720d04f7acc50b40ea226d77736bce6a6bf43981b6e86
Status: Downloaded newer image for certbot/certbot:latest
docker: Error response from daemon: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "/opt/certbot/certbot-entry.sh": permission denied: unknown.
docker: Error response from daemon: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "/opt/certbot/certbot-entry.sh": stat /opt/certbot/certbot-entry.sh: no such file or directory: unknown.
Missing file: /root/letsencrypt/live/stun.net.daticum.bg/fullchain.pem
SSL certificates failed
root@netmaker:/home/daticum# cat /opt/certbot/certbot-entry.sh
cat: /opt/certbot/certbot-entry.sh: No such file or directory
```

### Contributing guidelines

- [X] Yes, I did.

**Comment by TobiaszCudnik** [comment]
`certbot-entry.sh` should be created in the same dir as `nm-quick.sh`. Seems like you dont have write permissions. Docker path `/opt/certbot/certbot-entry.sh` isnt relevant.

**Comment by josifbg** [comment]
Well, I am executing the installation script as a root... and I think I should have permission for any operations

**Comment by TobiaszCudnik** [comment]
Fixed in https://github.com/gravitl/netmaker/pull/2311.

You can test it with a local install, like so:
```
wget https://raw.githubusercontent.com/gravitl/netmaker/2310/nm-cert-path/scripts/nm-quick.sh
chmod +x nm-quick.sh
./nm-quick.sh -b local -t 2310/nm-cert-path
```

**Comment by josifbg** [comment]
Looks like the installation script is working now, but there is another issue when trying to create the admin user i have got "Could not reach server" and technically I am not able to use the Netmaker...

**Comment by TobiaszCudnik** [comment]
Theres a PR https://github.com/gravitl/netmaker/pull/2332 which should fix your problem, heres the installation steps if you'd like to test it before its merged:
```
wget https://raw.githubusercontent.com/gravitl/netmaker/NET-246/read-def-config/scripts/nm-quick.sh
chmod +x nm-quick.sh
./nm-quick.sh -b local -t NET-246/read-def-config
```
