### ISSUE TITLE
coredns fails to start - boot loop

### ISSUE THREAD

**Issue by TinyToadMilk** [gravitl/netmaker#232]
On Running:
"sed -i 's/REPLACE_MASTER_KEY/<your generated key>/g' docker-compose.quickstart.yml"
The containers all start running, except coredns, which enters a boot loop.
"93545dbbe145   coredns/coredns            "/coredns -conf /ubu…"   About a minute ago   Restarting (1) 12 seconds ago "
Running "docker logs --tail 50 --follow --timestamps coredns", results in:
"2021-08-16T06:40:10.810393260Z loading Caddyfile via flag: open `/ubuntwo/dnsconfig/Corefile:` no such file or directory"

**Comment by afeiszli** [comment]
CoreDNS will currently boot on repeat until a DNS entry is added, which should happen after the first network creation. Are you still getting this message after creating a network?

**Comment by afeiszli** [comment]
This has been fixed in a hotfix branch and will be in the next merge.

**Comment by afeiszli** [comment]
Fixed in latest release: Fixed in https://github.com/gravitl/netmaker/releases/tag/latest
