### ISSUE TITLE
[Bug]: v0.20.0 host still has associated nodes, when trying to delete a netclient host in unknown state

### ISSUE THREAD

**Issue by jalbstmeijer** [gravitl/netmaker#2322]
### What happened?

Upgraded from v0.19 docker images.
I found some duplicate netclient hosts from previous attempts.
They are in a "unknown" state. When I try to remove them I get the error:

```
Failed to delete host
host still has associated nodes
```
In the netmaker logs I see
```
netmaker  | [netmaker] 2023-05-20 09:34:36 admin failed to delete a host: host still has associated nodes 
netmaker  | [netmaker] 2023-05-20 09:34:36 processed request error: host still has associated nodes 
```
What does it mean? these hosts have no ingress or egress gw's assigned.

### Version

v0.20.0

### Relevant log output

```shell
netmaker  | [netmaker] 2023-05-20 09:34:36 admin failed to delete a host: host still has associated nodes 
netmaker  | [netmaker] 2023-05-20 09:34:36 processed request error: host still has associated nodes 
```
```


### Contributing guidelines

- [X] Yes, I did.

**Comment by afeiszli** [comment]
Netmaker prevents you from deleting a host if it is currently in networks. In the UI, remove the hosts from the network first, then delete the hosts.

**Comment by jalbstmeijer** [comment]
@afeiszli 

These hosts in unknown state are not mentioned in the network overviews.
I only see the healthy hosts in the  network overviews.

**Comment by hunterlijunchen** [comment]
@jalbstmeijer 健康的网络就可以先disconnect 然后再删除

**Comment by kaaass** [comment]
Suffering the same situation as @luzfcb. I got this message after disconnecting the host from every existing network.

**Comment by JPBeltman** [comment]
Experiencing the same issue. The node in question is not in my possession anymore but shows as healthy and is not removable.

**Comment by brapp0111** [comment]
Similar issue here.  I uninstalled netclient from a host without removing it from netmaker.  Re-installed netclient then rejoined the network.  Now there are two hosts with the same name, one listed as healthy and the other is listed as unknown.  I cannot delete the host listed as unknown.  I'm running version 0.20.1.

**Comment by abhishek9686** [comment]
Force delete is added in the upcoming release v0.20.5, which lets you delete the host and all of it's associated nodes at once

**Comment by Rudi9719** [comment]
Bringing this back up, I ended up in this situation however force delete does not solve the issue 
![The popup when force deleting an unknown host](https://github.com/gravitl/netmaker/assets/13631265/944063eb-6082-43b9-bdaa-b2664358c76d)
