### ISSUE TITLE
[Bug]: Adding a (additional) network fails

### ISSUE THREAD

**Issue by jalbstmeijer** [gravitl/netmaker#2324]
### What happened?

When I try to add a new network I get an error and no network is created.

### Version

v0.20.0

### Relevant log output

```shell
On the web gui:

Failed to create network
Key: 'Network.NetID' Error:Field validation for 'NetID' failed on the 'max' tag
```
```


### Contributing guidelines

- [X] Yes, I did.

**Comment by mattkasun** [comment]
based on error message you tried to create a network with a name longer than 12 chars.

**Comment by jalbstmeijer** [comment]
@mattkasun thank you. That was it.

Two suggestions:
- limit the input field too to 12 characters (maybe there are more limitations the input field could enforce?)
- make the error more obvious
