### ISSUE TITLE
[Bug]: 0.20  External Android Client can not scan the QR code

### ISSUE THREAD

**Issue by mithubindia** [gravitl/netmaker#2331]
### Contact Details

mayurithub1@gmail.com

### What happened?

Using Netmaker 0.20 - hosted on a public VPS

Not able to scan QR code for Android phone with Wireguard application. [ Tried to scan QR code several times, for several minutes - nothing happens ] 

Phone Model :  Samsung A03
Android Version - 13  - Kernel 4.14.199-25473037
Wireguard on Android Version - 1.0.20230512

### Version

v0.20.0

### Contributing guidelines

- [X] Yes, I did.

**Comment by FallingSnow** [comment]
I experienced the same issue. So I downloaded the config and was unable to import the config either. It turned out the issue was the filename containing dashes (`-`).

**Comment by markusglaetzner** [comment]
Same problem with iOS Device!

**Comment by Aceix** [comment]
Issue has been fixed in https://github.com/gravitl/netmaker-ui-2/pull/31. Thanks!
