### ISSUE TITLE
Website Down

### ISSUE THREAD

**Issue by fanuch** [gravitl/netmaker#234]
Tried to check out the documentation though it seems like the site is down.
Confirmed with:
![image](https://user-images.githubusercontent.com/4865267/129860379-f61e3862-d75b-4128-ad0c-c1e721310bf2.png)

Apologies if I missed a message or something and this is known

Edit: Noticed the [readthedocs.io](https://netmaker.readthedocs.io/en/v0.7.1/) link.
That is up

**Comment by afeiszli** [comment]
Yup, netmaker.org is down due to the tropical storm rolling through the southeast, but netmaker.readthedocs.io is the backup site and is identical. We should have netmaker.org back up today (though this is a wakeup call for implementing some disaster recovery).

**Comment by fanuch** [comment]
Hope all are well, and glad it's being dealt with!
I might leave this one open just in-case someone clicks on issues to report the same

**Comment by afeiszli** [comment]
Fixed, site is back up.
