### ISSUE TITLE
[Bug]: Unexpected Application Error!

### ISSUE THREAD

**Issue by christian-schlichtherle** [gravitl/netmaker#2355]
### What happened?

A bug happened!

When hosts are joining or leaving a network, the dashboard shows me a page starting with:

```
Unexpected Application Error!

undefined is not an object (evaluating 'D.name')

[rest not shown as it exposes hostnames etc]
```

Now I wanted to remove the network entirely but I can't because of that.

### Version

v0.20.0

### What OS are you using?

Linux

### Contributing guidelines

- [X] Yes, I did.

**Comment by Aceix** [comment]
similar to https://github.com/gravitl/netmaker/issues/2353. same underlying cause
