### ISSUE TITLE
[Bug]: installation script - invalid domain

### ISSUE THREAD

**Issue by eleaner** [gravitl/netmaker#2365]
### Contact Details

github@kisiel.net.pl

### What happened?

While running installation my domain is not accepted by the script
```
2) Custom Domain (e.x: netmaker.example.com)
#? nm.kisiel.net.pl
invalid option nm.kisiel.net.pl
```

### Version

v0.20.1

### What OS are you using?

Linux

### Contributing guidelines

- [X] Yes, I did.

**Comment by eleaner** [comment]
ok, I am officially stupid, delete it if you can

**Comment by sloped** [comment]
If you are like me and stumbled on this response and wished to know why OP felt stupid, you were probably like me and typing your domain at the first prompt instead of choosing and option (1 or 2). 

When prompted you need to choose option 2, then you can type in your domain name.
