### ISSUE TITLE
[Bug]: error installing daemon systemd not installed .. daemon not installed

### ISSUE THREAD

**Issue by eleaner** [gravitl/netmaker#2384]
### Contact Details

github@kisiel.net.pl

### What happened?

when upgrading from 0.20.0 to 0.20.1 it fails with
```
2023-06-08 19:32:48 (1.46 MB/s) - ‘netclient’ saved [16945152/16945152]

[netclient] 2023-06-08 19:32:50 error installing daemon systemd not installed .. daemon not installed
```

the same error when manually running 
`sudo netclient install`

although apparently the version has been upgraded
```
sudo netclient version
v0.20.1
```

### Version

v0.20.1

### What OS are you using?

Linux

### Contributing guidelines

- [X] Yes, I did.

**Comment by eleaner** [comment]
Ubuntu 20.04.6 LTS

installation and not upgrade does not seem to work at all

**Comment by mattkasun** [comment]
cannot duplicate.
fresh DO droplet
oot@issue-2384:~# cat /etc/os-release
NAME="Ubuntu"
VERSION="20.04.4 LTS (Focal Fossa)"
    1  wget fileserver.clustercat.com/releases/download/v0.20.1/netclient-linux-amd64 -O /tmp/netclient
    2  chmod +x /tmp/netclient
    3  /tmp/netclient install

no issues seen

**Comment by jrappeneker** [comment]
I get the same error

```
# cat /etc/os-release
NAME="Ubuntu"
VERSION="20.04.6 LTS (Focal Fossa)"
```

```
wget fileserver.clustercat.com/releases/download/v0.20.1/netclient-linux-amd64 -O /tmp/netclient
chmod +x /tmp/netclient
/tmp/netclient install

/tmp/netclient install
[netclient] 2023-06-09 04:39:37 error installing daemon systemd not installed .. daemon not installed
```

**Comment by eleaner** [comment]
I finally run it through docker

**Comment by mattkasun** [comment]
installing netclient on docker using netclient install or a package will not work as docker does not have systemd.   There is a netclient docker image you can use.
