### ISSUE TITLE
Netclient install script 404

### ISSUE THREAD

**Issue by agent-squirrel** [gravitl/netmaker#239]
The netclient install script: https://raw.githubusercontent.com/gravitl/netmaker/develop/scripts/netclient-install.sh references https://github.com/gravitl/netmaker/releases/download/v0.7.2/netclient which does not exist.

This line should be: https://github.com/gravitl/netmaker/releases/download/latest/netclient

**Comment by afeiszli** [comment]
hotfixed in 0.7.2

**Comment by anvial** [comment]
Hi,

for now https://github.com/gravitl/netmaker/releases/download/latest/netclient

does not exist.

What should be the proper link?

**Comment by afeiszli** [comment]
Hi @anvial , you need to point towards whatever version your server is running, e.g. https://github.com/gravitl/netmaker/releases/download/v0.9.3/netclient

**Comment by anvial** [comment]
Hi, thx. That's help. 

Also, there can be taken client-adding string from the 'access key' menu in GUI.
