### ISSUE TITLE
[Bug]: SERVER_BROKER_ENDPOINT env variable and  could not connect to broker, exiting

### ISSUE THREAD

**Issue by plejik** [gravitl/netmaker#2392]
### What happened?

So i try to install netmaker v0.20.1, configure it manually for not for test purpose and find out but ( for which i spend alsomt whole day to debug ) 
If i set `SERVER_BROKER_ENDPOINT="ws://mq:1883"` in netmaker.env i always get error 
```Fatal: could not connect to broker, exiting ... no servers defined to connect to```
But when i set it 
`SERVER_BROKER_ENDPOINT=ws://mq:1883` without quotes ( on .env or docker-compose ) it's connected with out any problem ( or via cli `export SERVER_BROKER_ENDPOINT="ws://mq:1883"` ) 

### Version

v0.20.1

### What OS are you using?

Linux

### Non worked example 

netmaker.env
```
...
# The address of the mq server. If running from docker compose it will be "mq". Otherwise, need to input address.
# If using "host networking", it will find and detect the IP of the mq container.
SERVER_BROKER_ENDPOINT="ws://mq:1883"
...
```
docker-compose.yml

```
volumes:
      - dnsconfig:/root/config/dnsconfig
      - sqldata:/root/data
    environment:
      # - SERVER_BROKER_ENDPOINT="ws://mq:1883"
 ```
 
### Working 
```
...
# The address of the mq server. If running from docker compose it will be "mq". Otherwise, need to input address.
# If using "host networking", it will find and detect the IP of the mq container.
SERVER_BROKER_ENDPOINT=ws://mq:1883
...
```
docker-compose.yml
```
volumes:
      - dnsconfig:/root/config/dnsconfig
      - sqldata:/root/data
    environment:
      # - SERVER_BROKER_ENDPOINT=ws://mq:1883
 ```

### Contributing guidelines

- [X] Yes, I did.

**Comment by abhishek9686** [comment]
I couldn't reproduce it, even with quotes the broker connection went through

**Comment by Nehereus** [comment]
Same issue here, solved by removing quotes. Docker version 20.10.5+dfsg1, build 55c4c88, System debian 11, I was using the netmaker.env file provided in the quick install guide

**Comment by YinScape** [comment]
I am reproducing on Ubuntu 18 with the following docker version

```
Client:
 Version:           20.10.21
 API version:       1.41
 Go version:        go1.18.1
 Git commit:        20.10.21-0ubuntu1~18.04.3
 Built:             Thu Apr 27 05:50:21 2023
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server:
 Engine:
  Version:          20.10.21
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.18.1
  Git commit:       20.10.21-0ubuntu1~18.04.3
  Built:            Thu Apr 27 05:36:22 2023
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.12-0ubuntu1~18.04.1
  GitCommit:
 runc:
  Version:          1.1.4-0ubuntu1~18.04.2
  GitCommit:
 docker-init:
  Version:          0.19.0
  GitCommit:


docker-compose version 1.17.1, build unknown
docker-py version: 2.5.1
CPython version: 2.7.17
OpenSSL version: OpenSSL 1.1.1  11 Sep 2018
```

**Comment by Brainpitcher** [comment]
The same stuff here, on ubuntu 20.04 with a quick start script and BTW the same with Digital Ocean Droplet
I removed the quotes but got no luck
