### ISSUE TITLE
Netclient glibc version

### ISSUE THREAD

**Issue by agent-squirrel** [gravitl/netmaker#240]
It appears the netclient as of version 0.7.2 wants Glibc 2.32 but as far as I'm aware the Ubuntu 20.04 system version is 2.31 and so it cannot be installed: 

```
./netclient.1: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by ./netclient.1)
```

**Comment by afeiszli** [comment]
hotfixed, updated release binaries should not have this issue (we accidentally built on a machine with different dependencies)
