### ISSUE TITLE
[Bug]: Cannot set custom static endpoint IP on a host.

### ISSUE THREAD

**Issue by Southpaw1496** [gravitl/netmaker#2439]
### Contact Details

paw@southpaw1496.me

### What happened?

The Host in question has an IPv6 address internally, but also has an IPv4 address assigned to it by the cloud provider (Hetzner). Its default endpoint is its IPv6 address, but I'm planning to use it as an ingress for External Clients, so I wanted to use IPv4 as it is more compatible.

I went to Hosts -> \<host\> -> Edit, enabled "Static Endpoint" and set the IP. I clicked "Update Host" and received the message "Host 7b8d84c8-57f7-49c9-81ee-9ba5b9b6e079 updated", however, the endpoint IP in Host Details is still shown as the IPv6 address, and if I refresh the page and go back to Host Settings, the Endpoint IP field is blank again.

### Version

v0.20.3

### What OS are you using?

Linux

### Relevant log output

```shell
No log output
```

### Contributing guidelines

- [X] Yes, I did.

**Comment by mattkasun** [comment]
fixed by https://github.com/gravitl/netmaker-ui-2

**Comment by mattkasun** [comment]
has not been released yet

**Comment by mattkasun** [comment]
Fixed in v0 20 4
