### ISSUE TITLE
"Error creating an enrollment key" during installation

### ISSUE THREAD

**Issue by servix** [gravitl/netmaker#2466]
Hi!
I'm trying to self host the solution to give it a try, never used before. 
I've just run the installation script https://raw.githubusercontent.com/gravitl/netmaker/master/scripts/nm-quick.sh following the instructions at https://github.com/gravitl/netmaker#get-started-in-5-minutes

I'm deploying in a public VM under Ubuntu 20.04.6 LTS
I've set to use EE edition and a custom domain

In the end of the installation, I'm getting the following error:

```
Testing Caddy setup (please be patient, this may take 1-2 minutes)
    Certificates ok
Downloading nmctl...
using server api.nm.<removed>.net
using master key VG94tVc<removed>QODm
2023/07/25 19:26:36 Error Status: 502 Response:
. . .
. . .
. . .
. . .
. . .
2023/07/25 19:26:41 Error Status: 502 Response:
./nm-quick.sh: line 817: [: : integer expression expected
Obtaining a netmaker enrollment key...
2023/07/25 19:26:42 Error Status: 502 Response:
Error creating an enrollment key

```

I've tried to run the script again, with the same results. Can't figure out why it's failing. I've run the bash script with -x option to debug, and I get the following:

```
+ setup_nmctl
+ local URL=https://github.com/gravitl/netmaker/releases/download/v0.20.4/nmctl-linux-amd64
+ echo 'Downloading nmctl...'
Downloading nmctl...
+ wget -qO /usr/bin/nmctl https://github.com/gravitl/netmaker/releases/download/v0.20.4/nmctl-linux-amd64
+ '[' '!' -f /usr/bin/nmctl ']'
+ chmod +x /usr/bin/nmctl
+ echo 'using server api.nm.<removed>.net'
using server api.nm.<removed>.net
+ echo 'using master key VG94t<removed>QODm'
using master key VG94t<removed>QODm
+ nmctl context set default --endpoint=https://api.nm.<removed>.net --master_key=VG94t<removed>8QODm
+ nmctl context use default
++ nmctl network list
2023/07/25 19:51:59 Error Status: 502 Response:
+ RESP=
+ [[ '' == *\u\n\a\u\t\h\o\r\i\z\e\d* ]]
+ setup_mesh
+ wait_seconds 5
+ (( a = 1 ))
+ (( a <= 5 ))
+ echo '. . .'
. . .
+ sleep 1
+ (( a++ ))
+ (( a <= 5 ))
+ echo '. . .'
. . .
+ sleep 1
+ (( a++ ))
+ (( a <= 5 ))
+ echo '. . .'
. . .
+ sleep 1
+ (( a++ ))
+ (( a <= 5 ))
+ echo '. . .'
. . .
+ sleep 1
+ (( a++ ))
+ (( a <= 5 ))
+ echo '. . .'
. . .
+ sleep 1
+ (( a++ ))
+ (( a <= 5 ))
++ nmctl network list -o json
++ jq '. | length'
2023/07/25 19:52:04 Error Status: 502 Response:
+ local networkCount=
+ '[' '' -lt 1 ']'
./nm-quick.sh: line 817: [: : integer expression expected
+ echo 'Obtaining a netmaker enrollment key...'
Obtaining a netmaker enrollment key...
++ nmctl enrollment_key create --unlimited --networks netmaker
2023/07/25 19:52:04 Error Status: 502 Response:
+ local tokenJson=
++ jq -r .token
+ TOKEN
=
+ test -z ''
+ echo 'Error creating an enrollment key'
Error creating an enrollment key
+ exit 1

```

![2023-07-25_16-56-48_putty_](https://github.com/gravitl/netmaker/assets/23242918/9985452d-db8b-481e-8966-dd72716697f1)

Looks like the API service is not responding....but don't know were to look for logs for each service neither.

Could you please help me diagnosing the issue, or what to check? 
Or maybe I miss something in the documentation regarding the logs and associated troubleshooting.

Thanks in advance
Best regards

**Comment by Aceix** [comment]
can you provide logs from your ubuntu server by running

`docker logs caddy`

`docker logs netmaker`

**Comment by servix** [comment]
Hi,

Thank you very much for your answer and the information. With the provided commands to review the logs, I was able to find out that there was an issue with the license.
It's solved now, you can close/delete the issue.

Thanks!
Best regards
