### ISSUE TITLE
[Bug]: Cannot connect to egress network.

### ISSUE THREAD

**Issue by N4v41** [gravitl/netmaker#2483]
### Contact Details

n4v41.naval@gmail.com

### What happened?

cannot connect to onprem network using egress gateway but can access netmaker network from onprem.
hi, this seetting worked fine in 17.04 but since latest upgrades i cannot connect to onprem services using the egress gateway. just updated to the 20.05 but still not working.
the egress range is not being added to the allowlist in the wireguard config.
![image](https://github.com/gravitl/netmaker/assets/45365461/865d2afd-2e12-427b-90c4-ec491de7ba93)

is there any workaround ?

### Version

v0.20.4

### What OS are you using?

Linux

### Relevant log output

```shell
ping 192.168.100.3
PING 192.168.100.3 (192.168.100.3) 56(84) bytes of data.
From 10.20.0.4 icmp_seq=1 Destination Host Unreachable
ping: sendmsg: Required key not available
From 10.20.0.4 icmp_seq=2 Destination Host Unreachable
ping: sendmsg: Required key not available
^C
--- 192.168.100.3 ping statistics ---
2 packets transmitted, 0 received, +2 errors, 100% packet loss, time 1008ms
```

### Contributing guidelines

- [X] Yes, I did.

**Comment by abhishek9686** [comment]
can you run pull on your peer and check if allowedIps gets updated?

**Comment by N4v41** [comment]
Hi @abhishek9686  neither pulling or rejoining a peer is updating allowedips using a network that was created before the upgrade, i tested creating a new network and in this case the allowed ips seems to be updated, i recreated the network and rejoined all hosts and the allowed ips were updated !
