### ISSUE TITLE
[Bug]:  Cannot install netclient on RHEL

### ISSUE THREAD

**Issue by cocoonkid** [gravitl/netmaker#2507]
### What happened?

A bug happened!

```
❯ dnf install netclient
Last metadata expiration check: 0:06:06 ago on Wed 09 Aug 2023 07:29:11 AM UTC.
Error:
 Problem: cannot install the best candidate for the job
  - nothing provides nftable needed by netclient-0.20.5-0.x86_64
(try to add '--skip-broken' to skip uninstallable packages or '--nobest' to use not only best candidate packages)
```

is there simply missing an s to make it nftables?

appending --no-best worked , but is this intended?

I just realized only v0.20.2 got installed.

### Version

v0.20.5

### What OS are you using?

Linux

### Contributing guidelines

- [X] Yes, I did.

**Comment by mattkasun** [comment]
netclient repo updated.

you may have to run dnf clean all prior.

**Comment by cocoonkid** [comment]
@mattkasun  thanks a big bunch!
