### ISSUE TITLE
[Bug]: How can I use different port, not 443, 80, 3479, 8089 and 51821-51830/udp ? And use my duckdns domain?

### ISSUE THREAD

**Issue by RobertusIT** [gravitl/netmaker#2531]
### What happened?

I, i tried to install netmaker, but my isp allow only a range of port that i can open.

So how with script installation, can i change these ports? Is possible? 

And I can use my duckdns domain?

### Version

v0.20.6

### What OS are you using?

Linux

### Contributing guidelines

- [X] Yes, I did.

**Comment by mattkasun** [comment]
Netmaker requires tcp ports 80 and 443 and udp port 51821

**Comment by FallingSnow** [comment]
@RobertusIT You can try changing the port netmaker uses. Here's my docker compose: https://gist.github.com/FallingSnow/d64b1bde75327ed13732af50dab89a95

Make sure to add `PUBLIC_PORT=65535` to your `netmaker.env` and replace `65535` with whatever port you want to use.
