### ISSUE TITLE
[Bug]:  loading Caddyfile via flag: open /root/dnsconfig/Corefile: permission denied

### ISSUE THREAD

**Issue by shyding** [gravitl/netmaker#2540]
### Contact Details

dshymail@gmail.com

### What happened?

A bug happened!
![image](https://github.com/gravitl/netmaker/assets/24986567/96279829-10e3-4c4d-9fed-75e827001d12)

i use wireguard go 

![image](https://github.com/gravitl/netmaker/assets/24986567/b9d3fd4c-efc0-49fb-bbb3-a3a1446cd47c)
![image](https://github.com/gravitl/netmaker/assets/24986567/1f5b8508-0116-4d67-ab9d-72ee8b82e2dd)

### Version

v0.20.6

### What OS are you using?

Unlisted

### Relevant log output

```shell
can't be visited
```

### Contributing guidelines

- [X] Yes, I did.

**Comment by marcbenedi** [comment]
I am facing the same issue.

**Comment by cocoonkid** [comment]
This is an upstream issue.
https://github.com/coredns/coredns/issues/6249
Just revert back to  [1.11.0]. Maybe [1.11.1] works?

And then update when it's fixed or the upgrade path is clear.

Good example to not always run everything on latest. ;-)

**Comment by tecnicompsi** [comment]
hi, i've deployed docker compose with coredns:1.11.0 and still with the same error.

**Comment by tecnicompsi** [comment]
yes, i'm sure. I deleted volume data and container from portainer and deployed docker compose with coredns:1.11.0.

![imagen](https://github.com/gravitl/netmaker/assets/121949384/e6f210f5-51e5-4cc3-b1c4-c45bd16d3521)

docker exec -it coredns -version say me thats the container is restarting, wait until the container is running.

**Comment by MaikelBr** [comment]
Got it working by using version 1.10.1 of coredns

**Comment by cocoonkid** [comment]
oh noes. I am so sorry 
![image](https://github.com/gravitl/netmaker/assets/43231640/90d3b71f-47d9-470c-8494-2b6dd4b1043c)

Should have simply checked my conf before telling everyone wrong version numbers
