### ISSUE TITLE
[Bug]: Finished Quick Install First time visiting dashboard requires a password

### ISSUE THREAD

**Issue by gummybuns** [gravitl/netmaker#2542]
### What happened?

I followed your documentation for the [Quick Install](https://docs.netmaker.org/quick-start.html) to use docker to set up a netmaker server. After finishing i didnt really know what to do (there is a single line that says to go to dashboard<your base domain>, it isnt in a `<pre>` tag or anything didnt really stand out. I would suggest adding it in the [Getting Started](https://docs.netmaker.org/getting-started.html) section as well).

Anyways, I eventually stumble into `dashboard.my_domain.com` and I am presented with a login screen, but I have not made an account yet. I dont see anything in the docs about a default account, and the [Setup Section](https://docs.netmaker.org/getting-started.html#setup) is pretty sparse. So maybe a possible bug in the initial onboarding process or maybe the docs can be improved to have a more defined getting started section.

### Version

v0.20.6

### What OS are you using?

Linux

### Relevant log output

```
[netmaker] 2023-08-27 18:45:02 connecting to "sqlite" 
[netmaker] 2023-08-27 18:45:02 database successfully connected 
[netmaker] 2023-08-27 18:45:02 no OAuth provider found or not configured, continuing without OAuth 
[netmaker] 2023-08-27 18:45:02 netmaker-stun listening on 0.0.0.0:3478 via udp 
[netmaker] 2023-08-27 18:45:02 REST Server successfully started on port  "8081"  (REST) 
[netmaker] 2023-08-27 18:45:02 listen tcp: address tcp/"8081": unknown port 
[netmaker] 2023-08-27 18:45:02 connecting to mq broker at "ws://mq:1883" # For EMQX websockets use `SERVER_BROKER_ENDPOINT=ws://mq:8083/mqtt` 
[netmaker] Fatal: could not connect to broker, exiting ... no servers defined to connect to 
```

interesting that im getting an error when trying to connect to broker, not sure if that is related

### Contributing guidelines

- [X] Yes, I did.

**Comment by gummybuns** [comment]
hmmm i instead ran your magic script https://github.com/gravitl/netmaker#get-started-in-5-minutes 
and this time i was able to get to a sign up page. it seemed to do a couple more steps that are not included in the getting started page? For example, you have these two method defined in your script:

- `setup_nmctl`
- `setup_mesh`

Im not entirely sure what these do but i didnt really see those steps in the quick install.

**Comment by cocoonkid** [comment]
The sign up page allows you to create the initial administrative user.

If that works and CORS is properly set (and you fixed the broker issue) it should work.

Gotta admit the docs are not up to date everywhere and it's a little bit of a puzzle but I can totally understand the devs are quite busy rolling out releases.

A real up to date doc or a person just taking care of these is surely a better addition when v1 gets released.

Until then so many things can change. I love this project. It' very well done AFAIK.

**Comment by DanielHons** [comment]
I was finding the same issues, but it worked out after i commented out the following config variables from the env file:
- API_PORT
- CORS_ALLOWED_ORIGIN

**Comment by mattkasun** [comment]
#2573 fixes
