### ISSUE TITLE
[Bug]: No source code available for nm-upgrade binaries, not possible to recompile them for older glibc

### ISSUE THREAD

**Issue by taladar** [gravitl/netmaker#2551]
### What happened?

As part of our upgrade process from 0.17.1 to 0.20.6 I just hit a major road-block. Apparently the nm-upgrade.sh script downloads a binary nm-upgrade-amd64 which is compiled to require glibc 2.34. Since our server is still on Debian bullseye (oldstable as of a month or two ago, bookworm is not yet supported by all the tools we need, most importantly puppet) I had to recompile netmaker itself for 0.20.6 (and 0.17.1 for that matter) which wasn't a big deal.

When I tried to do the same thing for the nm-upgrade tool I noticed that source code for it (and turnserver for that matter) does not seem to be available publicly anywhere.

Since calling this tool seems to be required to upgrade the existing installation it would be very useful if you could provide source code for nm-upgrade-amd64.

### Version

v0.20.6

### What OS are you using?

Linux

### Relevant log output

```shell
~ # ./nm-upgrade-amd64
./nm-upgrade-amd64: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by ./nm-upgrade-amd64)
./nm-upgrade-amd64: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by ./nm-upgrade-amd64)
./nm-upgrade-amd64: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by ./nm-upgrade-amd64)
```

### Contributing guidelines

- [X] Yes, I did.

**Comment by mattkasun** [comment]
source code for nm-upgrade 
https://github.com/gravitl/devops/tree/master/upgrade
