### ISSUE TITLE
[Bug]: Digital Ocean app setup fails after "Confirm Settings for Installation" step

### ISSUE THREAD

**Issue by BenJackGill** [gravitl/netmaker#2632]
### What happened?

Trying to setup on Digital Ocean using the Netmaker app: https://marketplace.digitalocean.com/apps/netmaker

After SSH into the droplet I am following the setup instructions. But it always exists after "Confirm Settings for Installation" step. The last line I see is "Pulling config files..." before it exits the setup.

### Version

v0.21.0

### Relevant log output

```shell
-----------------------------------------------------------------
                SETUP ARGUMENTS
-----------------------------------------------------------------
        domain: nm-plex.fakefake.com
         email: 3f1fe7ed54b11b05@email.com
     public ip: 111.222.333.444
-----------------------------------------------------------------
Confirm Settings for Installation
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Does everything look right? [y/n]: y
/root/nm-quick.sh: line 861: netclient: command not found
Stopping all containers...
-----------------------------------------------------------------
Beginning installation...
-----------------------------------------------------------------
. . .
. . .
. . .
Pulling config files...
```

### Contributing guidelines

- [X] Yes, I did.

**Comment by MisterTii** [comment]
#2636 

redownload nm-quick.sh from master would fix it, don't know anything about digitalocean specifics

**Comment by mattkasun** [comment]
marketplace one-click working with v0.21.1

**Comment by BenJackGill** [comment]
Then shouldn't the Marketplace app be updated so that it use the working v0.21.1 version?
