### ISSUE TITLE
 allowed IPs can not be empty again

### ISSUE THREAD

**Issue by pete1019** [gravitl/netmaker#267]
I just had this ISSUE:
Set allowed IPs in Node which was saved.
But then i tried to delete it again (empty) i was not able to save (error update...).
Node not set as egress gateway.

Deleted old ui container, pulled it again (v0.7.3) but same error.

Thanks

**Comment by 0xdcarns** [comment]
Just fixed, will need to repull v0.7.3 or v0.7 if using docker. Thanks!
