### ISSUE TITLE
Deprecating FreeBSD Client

### ISSUE THREAD

**Issue by abhishek9686** [gravitl/netmaker#2705]

**Comment by unquietwiki** [comment]
@abhishek9686 why would this client get deprecated, considering interest from the OPNsense users? I might have a use case for this myself in the near-future. Does it have to do with the various issues of how Wireguard has been implemented on BSD?

**Comment by kenjreno** [comment]
@abhishek9686 I to would like to see the BSD version continue as I am also running a OPNsense instance, and would like to see this implemented

**Comment by unquietwiki** [comment]
@gigadjo that reasoning makes a fair amount of sense.

**Comment by abhishek9686** [comment]
For FreeBSD, you can still integrate it into the network as external clients, check out this doc on how to integrate OPNsense, pfSense into the netmaker network. https://docs.netmaker.io/integrating-non-native-devices.html

**Comment by unquietwiki** [comment]
@abhishek9686 thank you for sharing that. That is an interesting capability...
