### ISSUE TITLE
Deprecating Netclient GUI

### ISSUE THREAD

**Issue by abhishek9686** [gravitl/netmaker#2709]

**Comment by unquietwiki** [comment]
@abhishek9686 Do existing users of the GUI version need to do anything post-deprecation? Is there a re-install procedure that needs to be done for end-users?

**Comment by abhishek9686** [comment]
> @abhishek9686 Do existing users of the GUI version need to do anything post-deprecation? Is there a re-install procedure that needs to be done for end-users?

the following versions after deprecation just won't involve the GUI build, on the UI you will be having instructions to install netclient as usual.
