### ISSUE TITLE
Correct way to update clients

### ISSUE THREAD

**Issue by MartinPaulEve** [gravitl/netmaker#271]
Hello,

Would it be possible either to tell me here, or to update the documentation, please, with the best way to update clients to the latest version of Netmaker/netclient, if one has followed the opinionated installation guide?

With many thanks,

Martin

**Comment by afeiszli** [comment]
Hi @MartinPaulEve, the correct way would be to download the latest netclient from the release pages, and place it under /etc/netclient on your systems.

**Comment by MartinPaulEve** [comment]
Ah OK. Thank you!
