### ISSUE TITLE
IPV6 Support

### ISSUE THREAD

**Issue by abhishek9686** [gravitl/netmaker#2713]

**Comment by unquietwiki** [comment]
Is this for making Netmaker clients peer over IPv6 networks and/or allowing IPv6-only netmaker networks?

**Comment by wingxia** [comment]
waitting for it

**Comment by abhishek9686** [comment]
After some internal testing communication over IPv6 networks should work, there are few exceptions like ipv6 egress ranges, need some enablement on kernel level for NAT to work https://docs.netmaker.io/egress-gateway.html#advanced-use-cases

**Comment by abhishek9686** [comment]
IPv6 is supported on netmaker from v0.24.0
