### ISSUE TITLE
[Bug]: Tenant creation is not working

### ISSUE THREAD

**Issue by martynovs** [gravitl/netmaker#2746]
### Contact Details

martynovs@gmail.com

### What happened?

I'm new user trying to create a tenant, but there is no tiers to select from.

In browser's console I see an error.
<img width="2560" alt="Screenshot 2023-12-20 at 17 06 14" src="https://github.com/gravitl/netmaker/assets/9567/66ab11a2-20ed-4853-8b8c-ab5f0653492d">

### Version

v0.21.2

### What OS are you using?

Mac

### Contributing guidelines

- [X] Yes, I did.

**Comment by abhishek9686** [comment]
@martynovs you should be able to create one right now

**Comment by martynovs** [comment]
It works now, thank you.
