### ISSUE TITLE
[Bug]: Failed to create client ingress cannot be created on nodes behind NAT

### ISSUE THREAD

**Issue by EricFROL** [gravitl/netmaker#2747]
### What happened?

Just decided to set up netmaker.
I have followed all previous steps fine, until I need to set up _Ingress + External Clients_. Adding any of my three connected hosts as a client returns me this alert as a popup (they all are on the same local network):

```
Failed to create client
ingress cannot be created on nodes behind NAT
```

Am I doing something wrong?

### Version

v0.20.2

### What OS are you using?

Linux, Windows

### Contributing guidelines

- [x] Yes, I did.

**Comment by unquietwiki** [comment]
@EricFROL I saw this come up on the Discord, and had a thought. If the ingress node is behind a firewall, are you able to forward TCP & UDP 51821-51831 to it? Or if it's something like a home connection, are you able to designate the ingress as a DMZ target?

**Comment by abhishek9686** [comment]
@EricFROL we don't block ingress creation even if host is behind NAT, on the UI we just show a warning, so I am not sure from where exactly are you getting this response
can you confirm your server version again?

**Comment by EricFROL** [comment]
@unquietwiki I currently have firewall disabled, so that can't be... how can I designate the ingress as a dmz target??

@abhishek9686 yes, v0.20.2

**Comment by abhishek9686** [comment]
> @unquietwiki I currently have firewall disabled, so that can't be... how can I designate the ingress as a dmz target??
> 
> @abhishek9686 yes, v0.20.2

okay that's an old version, this check has been removed in newer versions

**Comment by EricFROL** [comment]
Well that's the version that's the version stated in https://docs.netmaker.io/quick-start.html. Should I put latest?

**Comment by abhishek9686** [comment]
> Well that's the version that is stated in https://docs.netmaker.io/quick-start.html. Should I put latest?

we are updating the docs, use v0.21.2

**Comment by EricFROL** [comment]
Closing as working on v0.21.2.
Thank you.
