### ISSUE TITLE
[Bug]: error creating default EMQX authenticator on EMQX 5.4.0

### ISSUE THREAD

**Issue by Effect-Wei** [gravitl/netmaker#2752]
### Contact Details

effect-w@outlook.com

### What happened?

When I run Netmaker with EMQX 5.4.0(Latest) I always get "error creating default EMQX authenticator".

_I guess the reason is as follows:_

In EMQX 5.4.0, `password_hash_algorithm` no longer provides a default value. [See EMQX v5.4 API Docs](https://github.com/gravitl/netmaker/blob/54a3afc19ac610714d5d4454cd18a06219127b2f/mq/emqx.go#L139)
But [emqx.go](https://github.com/gravitl/netmaker/blob/54a3afc19ac610714d5d4454cd18a06219127b2f/mq/emqx.go#L139) did not follow up on this change.

### Version

v0.21.2

### What OS are you using?

Linux

### Relevant log output

```shell
[netmaker] 2023-12-27 12:43:47 error creating default EMQX authenticator {"code":"BAD_REQUEST","message":"{\"reason\":\"required_field\",\"path\":\"root.password_hash_algorithm.name\",\"matched_type\":\"authn:builtin_db_api/authn_hash:bcrypt_rw_api\",\"kind\":\"validation_error\"}"


Formatted JSON:
{
    "code": "BAD_REQUEST",
    "message": {
        "reason": "required_field",
        "path": "root.password_hash_algorithm.name",
        "matched_type": "authn:builtin_db_api/authn_hash:bcrypt_rw_api",
        "kind": "validation_error"
    }
}
```

### Contributing guidelines

- [X] Yes, I did.

**Comment by abhishek9686** [comment]
@Effect-Wei Currently netmaker only supports v5.0.9, emqx has incompatbile changes over different versions wrt their Apis.
Unless there is an absolute requirement that we need to upgrade to a higher version of emqx, otherwise we won't be updating it soon.
