### ISSUE TITLE
[Bug]: error creating default EMQX ACL authorization mechanism on EMQX 5.4.0

### ISSUE THREAD

**Issue by Effect-Wei** [gravitl/netmaker#2753]
### What happened?

When I run Netmaker with EMQX 5.4.0(Latest) I always get "error creating default EMQX ACL authorization mechanism".

This bug may be related to here: [emqx.go](https://github.com/gravitl/netmaker/blob/54a3afc19ac610714d5d4454cd18a06219127b2f/mq/emqx.go#L249)

### Version

v0.21.2

### What OS are you using?

Linux

### Relevant log output

```shell
[netmaker] 2023-12-27 13:16:27 error creating default EMQX ACL authorization mechanism {"code":"BAD_REQUEST","message":"{duplicated_authz_source_type,built_in_database}"} 
{"time":"2023-12-27T13:16:27.457196393Z","level":"INFO","source":"&{  0}","msg":"error creating default ACL rules <html><head><title>404 - NOT FOUND</title></head><body><h1>404 - NOT FOUND</h1></body></html>"}
```

### Contributing guidelines

- [X] Yes, I did.

**Comment by abhishek9686** [comment]
we are using emqx version `emqx/emqx:5.0.9` currently
