### ISSUE TITLE
Adding and modifying coredns configuration

### ISSUE THREAD

**Issue by sinaowolabi** [gravitl/netmaker#276]
It would be great to able to modify coredns configuration for arbitrary requirements.
For instance if a node is an egress gateway, coredns could be used to forward specific dns zones that the node belongs to.
Cool things like that.

**Comment by afeiszli** [comment]
Fixed in 0.8.1. Server now generates a static Corefile on startup, which does not get modified in the future. This Corefile can be modified however you want. Or, you can take the configuration and use it with your own CoreDNS server.
