### ISSUE TITLE
Database connection issue on the netmaker docker

### ISSUE THREAD

**Issue by pcfriek1987** [gravitl/netmaker#278]
When deploying the netmaker containers and looking in the netmaker docker log it will give you an error:

2021/09/15 19:26:56 error occurred initializing DNS: tried all peers unsuccessfully. here are the results:
   peer #0: http://:/db/query?timings&level=strong&transaction failed due to Post "http:///db/query?timings&level=strong&transaction": http: no Host in request URL

Even putting SQL_CONN in the dockers compose file makes no difference.

It's not on every installation though.

**Comment by afeiszli** [comment]
This should be solved in the latest releases. Issue appears to be tied to systemd-resolved being turned off on the server, as per the old install documentation. In the new deployment, we recommend keeping on systemd-resolved. If you continue to run into this issue, feel free to re-open the ticket, but it should be solved now.
