### ISSUE TITLE
[Bug]: CoreDNS - cannot assing requested address

### ISSUE THREAD

**Issue by WoMec** [gravitl/netmaker#2782]
### Contact Details

vomacka.j@gmail.com

### What happened?

Install on fresh Ubuntu 22.04, server is running behind reverse proxy. 
Installation script hangs on Caddy testing. Logs shows correct certificate assignment, but coreDNS container keeps restarting. Probably because it wants to listen on public IP, on on private IP of server. 

### Version

v0.22.0

### What OS are you using?

Linux

### Relevant log output

```shell
root@netmaker:~# docker logs coredns
Listen: listen tcp *my_public_IP*:53: bind: cannot assign requested address
Listen: listen tcp *my_public_IP*:53: bind: cannot assign requested address
Listen: listen tcp *my_public_IP*:53: bind: cannot assign requested address
Listen: listen tcp *my_public_IP*:53: bind: cannot assign requested address
```

### Contributing guidelines

- [X] Yes, I did.

**Comment by klucsik** [comment]
Have same issue.
My install running behind an HAProxy as I want to save up on nodes. Moved http/s port to differnet port in the compose.yaml, and used HAproxy to forward traffic to these ports (to Caddy basically) based on hostname

**Comment by klucsik** [comment]
If you use similar setup as me, dont forget that the mqtt broker in netclient needs websocket conection, and you probably need to update your reverse proxy to accomodate that

**Comment by abhishek9686** [comment]
@WoMec @klucsik  coredns issue has been fixed, the v0.22.0 image has been patched with this fix, please pull newer version of netmaker image and try it

**Comment by abhishek9686** [comment]
follow this doc for successful coredns setup  https://docs.netmaker.io/architecture.html#coredns

**Comment by klucsik** [comment]
@abhishek9686  new image is working well
