### ISSUE TITLE
[Bug]: https://raw.githubusercontent.com/gravitl/netmaker/master/scripts/nm-certs.sh is missing

### ISSUE THREAD

**Issue by PavelNiedoba** [gravitl/netmaker#2790]
### What happened?

Official documentation  `https://netmaker.readthedocs.io/en/master/quick-start.html`  mention `https://raw.githubusercontent.com/gravitl/netmaker/master/scripts/nm-certs.sh` file, but it's missing. Therefore netmaker cannot be installed.

Also the installation expect to be in /root folder, which is discouraged.  

Certificates should be generated inside container automatically. 

### Version

v0.22.0

### What OS are you using?

Linux

### Relevant log output

```shell
root@vm-vpn:~# wget https://raw.githubusercontent.com/gravitl/netmaker/master/scripts/nm-certs.sh
--2024-01-23 19:12:15--  https://raw.githubusercontent.com/gravitl/netmaker/master/scripts/nm-certs.sh
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.111.133, 185.199.108.133, 185.199.109.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.111.133|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2024-01-23 19:12:15 ERROR 404: Not Found.
```

### Contributing guidelines

- [X] Yes, I did.

**Comment by abhishek9686** [comment]
nm-certs has been deprecated using  this cmd to install netmaker `sudo wget -qO /root/nm-quick.sh https://raw.githubusercontent.com/gravitl/netmaker/master/scripts/nm-quick.sh && sudo chmod +x /root/nm-quick.sh && sudo /root/nm-quick.sh`

**Comment by PavelNiedoba** [comment]
I believe it's still bug, because https://netmaker.readthedocs.io/en/master/quick-start.html is obsolete and should be updated

**Comment by pquan** [comment]
This issue also affects the nm-upgrade.sh script. 
The script will wget https://raw.githubusercontent.com/gravitl/netmaker/v0.22.0/scripts/nm-certs.sh and fail. 
Bash will exit due to error and the whole  upgrade process stops in an inconsistent state (no env created etc).

**Comment by abhishek9686** [comment]
> This issue also affects the nm-upgrade.sh script. The script will wget https://raw.githubusercontent.com/gravitl/netmaker/v0.22.0/scripts/nm-certs.sh and fail. Bash will exit due to error and the whole upgrade process stops in an inconsistent state (no env created etc).

from which version are you trying to upgrade from?

**Comment by pquan** [comment]
Upgrading from 0.17.1 as per instructions.
