### ISSUE TITLE
How to install netclient on Wireguard-go

### ISSUE THREAD

**Issue by sunny61** [gravitl/netmaker#2802]
### What happened?

How to install netclient on Wireguard-go?
I ran Wireguard go and wanted to install netclient on top of it, but the installation always did not detect Wireguard

### Version

v0.22.0

### Relevant log output

```shell
I ran Wireguard go and wanted to install netclient on top of it, but the installation always did not detect Wireguard
```

### Contributing guidelines

- [X] Yes, I did.

**Comment by Aceix** [comment]
tracked in [netclient repo](https://github.com/gravitl/netclient/issues/684)
