### ISSUE TITLE
[Bug]: Cannot generate certificate via Caddy when ISP blocks port 80

### ISSUE THREAD

**Issue by alternativesurfer** [gravitl/netmaker#2817]
### What happened?

A bug happened!

We need the ability to change challenge types in Caddy when ISPs block certain ports.
https://caddyserver.com/docs/automatic-https#dns-challenge

### Version

v0.22.0

### What OS are you using?

Linux

### Relevant log output
![image](https://github.com/gravitl/netmaker/assets/10135929/3ddcc029-1728-47ce-bfe8-5395adda898d)

_No response_

### Contributing guidelines

- [X] Yes, I did.

**Comment by abhishek9686** [comment]
Those ports are needed for the ACME HTTP and TLS-ALPN challenges (80 and 443 respectively).
I think this isn't an issue relevant to netmaker, but you should probably use Caddy forums to get more answers.
