### ISSUE TITLE
Deleting egress on dual gateway node

### ISSUE THREAD

**Issue by mattkasun** [gravitl/netmaker#285]
If you create both an ingress and egress gateway on the same node and then delete the egress gateway the post up/post down for the node is cleared.  The node still indicates that it is an ingress gateway, but with no iptables rules, it will not function properly.

**Comment by 0xdcarns** [comment]
This was fixed in 0.8.1, leaves the postup/down for ingress gateway if it is still an ingress gateway after removing the egress. Good find
