### ISSUE TITLE
Why can't my nodes reach each other directly?

### ISSUE THREAD

**Issue by OnieMa** [gravitl/netmaker#2873]
### Contact Details

maaoyuya@qq.com

### What happened?

 After I installed the official NetMaker tutorial to create a network and added several clients, my client can only access one node (my server) and the other nodes cannot be accessed.     
 
![image](https://github.com/gravitl/netmaker/assets/84728457/4a8bf389-37f1-4a50-a219-2427be47b8fd)

### Version

v0.23.0

### What OS are you using?

Linux

### Contributing guidelines

- [X] Yes, I did.

**Comment by yabinma** [comment]
Failover node enabled in the network?
It can be checked in the host list page.
Disable the failover node and check again please.

**Comment by OnieMa** [comment]
My host now has these ：
 
<img width="1199" alt="image" src="https://github.com/gravitl/netmaker/assets/84728457/42ce7f69-babe-42ee-b2ad-f63ff5e258cc">

<img width="499" alt="image" src="https://github.com/gravitl/netmaker/assets/84728457/e8ec9d0e-50e7-4e4b-a48d-6d4c199c290e">


Among them, ucloud is a vps pvs with a public network, pvs3541011713 is in a company's intranet environment, pi and maclan are under the same local area network (they can ping each other), and all devices cannot ping, including ucloud.

**Comment by yabinma** [comment]
Have you checked the network firewall configuration? For making the host communicating directly each other,  ICMP protocol and UDP port 51821-51830 should be enabled.

**Comment by abhishek9686** [comment]
@OnieMa were you able to resolve the issues see on your side?

**Comment by abhishek9686** [comment]
@OnieMa why have you closed the issue as `not planned`?
