### ISSUE TITLE
[Bug]: IPv6 not assigned with netclient on MacOS

### ISSUE THREAD

**Issue by RomLecat** [gravitl/netmaker#2879]
### What happened?

The Wireguard interface does not get IPv6 configured on MacOS 14.4.1 (Apple Silicon) with NetClient 0.23.0.
IPv6 is enabled on the net, and the host has an IP assigned on Netmaker, but the IP is not configured on the interface.

IPv6 works fine in other Linux nodes.

### Version

v0.23.0

### What OS are you using?

Mac

### Relevant log output

```shell
sudo netclient list
[
 {
  "network": "vnet",
  "node_id": "12c71ec4-e8b2-4ed1-a301-53d64b8cc6b0",
  "connected": true,
  "ipv4_addr": "192.168.255.2/24",
  "ipv6_addr": "fd00:261c:d742:d778::2/64"
 }
]

ifconfig utun69
utun69: flags=8051<UP,POINTOPOINT,RUNNING,MULTICAST> mtu 1420
        inet 192.168.255.2 --> 192.168.255.2 netmask 0xffffff00
        inet6 fe80::bed0:74ff:fe25:fe4d%utun69 prefixlen 64 scopeid 0x1d
        nd6 options=201<PERFORMNUD,DAD>
```

### Contributing guidelines

- [X] Yes, I did.

**Comment by abhishek9686** [comment]
@RomLecat Issues with IPV6 Routing have been addressed in v0.24.0
