### ISSUE TITLE
[Bug]: Cannot Access The Api Server - Netmaker

### ISSUE THREAD

**Issue by SMUEric1127** [gravitl/netmaker#2892]
### What happened?

Hi! I have just installed netmaker, the ui is showed up but keep saying 
<img width="758" alt="image" src="https://github.com/gravitl/netmaker/assets/85500156/f5f4ca91-055f-4c49-b684-f2c846508e04">

I have checked the backend and saw this error
```

root@localhost:~# docker logs netmaker
              
 __   __     ______     ______   __    __     ______     __  __     ______     ______    
/\ "-.\ \   /\  ___\   /\__  _\ /\ "-./  \   /\  __ \   /\ \/ /    /\  ___\   /\  == \   
\ \ \-.  \  \ \  __\   \/_/\ \/ \ \ \-./\ \  \ \  __ \  \ \  _"-.  \ \  __\   \ \  __<   
 \ \_\\"\_\  \ \_____\    \ \_\  \ \_\ \ \_\  \ \_\ \_\  \ \_\ \_\  \ \_____\  \ \_\ \_\ 
  \/_/ \/_/   \/_____/     \/_/   \/_/  \/_/   \/_/\/_/   \/_/\/_/   \/_____/   \/_/ /_/ 
                                                                                         													 

[netmaker] 2024-04-11 01:09:10 connecting to sqlite 
[netmaker] 2024-04-11 01:09:10 database successfully connected 
[netmaker] 2024-04-11 01:09:10 failed to fetch database records for hosts 
[netmaker] 2024-04-11 01:09:10 no OAuth provider found or not configured, continuing without OAuth 
2024/04/11 01:09:10 ERROR acls migration failed. error getting networks error="could not find any records"
[netmaker] 2024-04-11 01:09:10 REST Server successfully started on port  8081  (REST) 
[netmaker] 2024-04-11 01:09:10 connecting to mq broker at ws://mq:1883 
[netmaker] 2024-04-11 01:09:13 connected to MQ Broker 
[netmaker] 2024-04-11 01:09:13 node update subscription failed 
[netmaker] 2024-04-11 01:09:13 host update subscription failed 
[netmaker] 2024-04-11 01:09:13 node client subscription failed 
[netmaker] 2024-04-11 01:09:14 node metrics subscription failed 
root@localhost:~# docker exec -it netmaker sh
~ # wget localhost:8081
Connecting to localhost:8081 (127.0.0.1:8081)
wget: server returned error: HTTP/1.1 404 Not Found
~ # 

```

Do you all have any idea ? Thank you

### Version

v0.23.0

### What OS are you using?

Linux

### Contributing guidelines

- [X] Yes, I did.

**Comment by abhishek9686** [comment]
@SMUEric1127 seems like a certs problem, can you check the logs of the caddy container, to check certs are generated correctly for your domains

**Comment by SMUEric1127** [comment]
@abhishek9686 Hi, thank you a lot for your fast response! Unfortunately, I only have 1 VPS and it's already running nginx proxy manager. I have managed to have letsencrypt running. Here is the log from the browser

login:1 Access to XMLHttpRequest at 'https://api.NM_DOMAIN' from origin 'http://dashboard.NM_DOMAIN' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

Do you think I should add the CORS to the api or the dashboard ? Thank you a lot!

**Comment by SMUEric1127** [comment]
Hello @abhishek9686, after all, I think it's really the reverse proxy issue - nginx proxy manager. I have managed to fix it by setup the proxy again. Thank you for your help!
