### ISSUE TITLE
[Bug]: Netclient on k8s does not communicate with server except for joining

### ISSUE THREAD

**Issue by Davam1r** [gravitl/netmaker#2953]
### What happened?

Hello!

I am trying to setup netmaker server on kubernetes cluster (v1.27) which is running in AWS EKS. It will be used for remote access to services of the k8s server. I successfully deployed the server on my cluster using provided helm-chart. 

What I need is to deploy netclient into the same k8s cluster so it can act as an egress gateway to the cluster services. However, after  creating a deployment with netclient based on the k8s guides, it will only check-in with the server during netclient join but after that it does not seem to communicate at all. That means after a while the netclient host will show health status "error".
There are no error logs on the netclient pod and neither on the server.  I will be glad if anyone can help me.

This issue was not happening with netmaker v0.17.1 as that version still has built-in netclient which can be the easily used to create the egress gateway without problems.

This is my deployment of the netclient:
```
resource "kubernetes_deployment" "netclient-gateway" {
  depends_on = [ helm_release.netmaker ]
  metadata {
    name = local.gateway_name
    namespace = var.kubernetes_namespace

    labels = merge(
      local.shared_labels,
      {
        app = local.gateway_name
      },
      var.labels)
  }

  spec {
    selector {
      match_labels = {
        app = local.gateway_name
      }
    }

    replicas = 1

    template {
      metadata {
        labels = {
          app = local.gateway_name
        }
      }

      spec {
        host_network = true

        affinity {
          pod_affinity {
            required_during_scheduling_ignored_during_execution {
              label_selector {
                match_labels = {
                  app = local.name
                }
              }
              topology_key = "kubernetes.io/hostname"
            }
          }
        }

        init_container {
          name  = "init-log-file"
          image = "busybox"
          command = [
            "sh",
            "-c",
            "mkdir -p /var/log && touch /var/log/netclient.log"
          ]
          volume_mount {
            mount_path = "/var/log"
            name       = "log-volume"
          }
        }

        container {
          name = local.gateway_name
          image = "gravitl/netclient:${local.netmaker_version}"

          security_context {
            privileged = true
          }
          
          env {
            name  = "PORT"
            value = "51822"
          }
          
          env {
            name  = "IS_STATIC"
            value = "yes"
          }
          
          env {
            name  = "HOST_NAME"
            value = "k8s-gw"
          }
          
          env {
            name  = "ENDPOINT"
            value_from {
              field_ref {
                field_path = "status.hostIP"
              }
            }
          }
          
          env {
            name  = "TOKEN"
            value = local.gateway_token
          }
          
          volume_mount {
            mount_path = "/etc/netclient"
            name       = "etc-netclient"
          }

          volume_mount {
            mount_path = "/var/log"
            name       = "log-volume"
          }
        }
        
        volume {
          persistent_volume_claim {
            claim_name = kubernetes_persistent_volume_claim.netclient-storage.metadata[0].name
          }
          name = "etc-netclient"
        }

        volume {
          name = "log-volume"
          empty_dir {}
        }
      }
    }
  }
}

resource "kubernetes_persistent_volume_claim" "netclient-storage" {
  metadata {
    name      = "netclient-storage-claim"
    namespace = var.kubernetes_namespace
  }
  
  spec {
    storage_class_name = data.kubernetes_storage_class.efs.metadata[0].name
    access_modes = ["ReadWriteMany"]
    resources {
      requests = {
        storage = "128Mi"
      }
    }
  }
}
```

### Version

v0.24.1

### What OS are you using?

Linux

### Contributing guidelines

- [X] Yes, I did.

**Comment by Davam1r** [comment]
> @wuwo1952368901 we have updated the image with a fix, also made changes to manifest, please re-try https://github.com/gravitl/netmaker/blob/master/k8s/client/netclient-daemonset.yaml

Thank you for the reply. 
I suppose you mean the `gravitl/netclient:develop` image so I am going to try it out right now.

**Comment by abhishek9686** [comment]
> > @wuwo1952368901 we have updated the image with a fix, also made changes to manifest, please re-try https://github.com/gravitl/netmaker/blob/master/k8s/client/netclient-daemonset.yaml
> 
> 
> 
> Thank you for the reply. 
> 
> I suppose you mean the `gravitl/netclient:develop` image so I am going to try it out right now. 

No the release image v0.24.1

**Comment by Davam1r** [comment]
> > > @wuwo1952368901 we have updated the image with a fix, also made changes to manifest, please re-try https://github.com/gravitl/netmaker/blob/master/k8s/client/netclient-daemonset.yaml
> > 
> > 
> > Thank you for the reply.
> > I suppose you mean the `gravitl/netclient:develop` image so I am going to try it out right now.
> 
> No the release image v0.24.1

Dockerhub tells me that the v0.24.1 image was pushed 18 days ago.. I dont think I will find any new fixes in there.

**Comment by Davam1r** [comment]
So i tried it anyway and as expected.. nothing changed.

**Comment by abhishek9686** [comment]
> So i tried it anyway and as expected.. nothing changed.

try the gravitl/netclient:v0.24.1, it has been updated now

**Comment by Davam1r** [comment]
> > So i tried it anyway and as expected.. nothing changed.
> 
> try the gravitl/netclient:v0.24.1, it has been updated now

Alright, I tried again and it is working well now. Thank you. 

Was the issue that the daemon was not starting up correctly after `netmaker install` is called ?

**Comment by yabinma** [comment]
> > > So i tried it anyway and as expected.. nothing changed.
> > 
> > 
> > try the gravitl/netclient:v0.24.1, it has been updated now
> 
> Alright, I tried again and it is working well now. Thank you.
> 
> Was the issue that the daemon was not starting up correctly after `netmaker install` is called ?

Eventually correct.  After joining the network, netclient will update the configuration and run in progress. But an volume mount issue interrupted the progress, the daemon could not run properly.
