### ISSUE TITLE
Unable to login due to SSO being Premium Only

### ISSUE THREAD

**Issue by Wombosvideo** [gravitl/netmaker#2991]
### Contact Details

luca.bosin@wilkebosin.ventures

### What happened?

Due to the unannounced licensing change where SSO is now suddenly a paid feature when self-hosting netmaker I am no longer able to log into any of my accounts (superadmin is also SSO)

### Version

v0.24.2

### What OS are you using?

Linux

### Contributing guidelines

- [X] Yes, I did.

**Comment by abhishek9686** [comment]
you can rollback the server version to v0.24.0, and transfer the super-admin role to a user with basic auth, and then upgrade to the latest version

**Comment by Wombosvideo** [comment]
This is not a fix

**Comment by abhishek9686** [comment]
> This is not a fix but a poor workaround

fix is that you need to upgrade to the pro version.
oAuth has always been a pro feature, just that it was not gated previously and we have moved it to pro pkg.

**Comment by Wombosvideo** [comment]
Then try to update the documentation so it includes this fact. [This page](https://docs.netmaker.io/user-management.html#integrating-oauth) has a separate section "Users in Netmaker Professional" but the "Auth0" section is not there but in the section before that. Even on the [Netmaker Professional](https://docs.netmaker.io/pro/index.html) page, nothing is mentioned about SSO. So saying it has always been a Pro feature sounds like a big lie to me.

**Comment by abhishek9686** [comment]
We will update the docs.
you can visit our website to see the difference between each plan - https://www.netmaker.io/pricing
