### ISSUE TITLE
Netclient on Macos not working correctly

### ISSUE THREAD

**Issue by pcfriek1987** [gravitl/netmaker#300]
I've added the netclient on MacOS and at first sight it seems to work as it shows up under Netmaker. 

Although after some time it goes from Healthy to Warning to Error. 

After a reboot it's not loaded either and the logs are empty.

**Comment by 0xdcarns** [comment]
If using 0.8, just make sure to rename binary to netclient and copy to /etc/netclient/ directory. Waiting for the v0.8.1 binary to be built, but the code is updated to handle this automatically in that release.

**Comment by pcfriek1987** [comment]
Works by building the latest 0.8.1 client on MacOS. :)
