### ISSUE TITLE
Installation script is broken on Debian Systems

### ISSUE THREAD

**Issue by gaby** [gravitl/netmaker#319]
The installation script is trying to install the `docker` package, which on debian is a Window Manager. The correct package for Ubuntu is `docker.io` or `docker-ce` which requires extra configuration.

In my opinion all these scripts trying to install tools and stuff on the host system should be avoided, it makes using `netmaker` really difficult. 

When the script installed `docker` window manager on our Ubuntu Server, it corrupted and bunch of stuff and we had to PXE boot the server.

**Comment by afeiszli** [comment]
@gaby apologies, we will update the packages in the readme script to use docker.io or docker-ce. To reiterate from #320, the README script should not be used as an "official" way to install for production reasons, and instead should just be used as a way to try out Netmaker quickly before moving on to a more customized install using one of the other guides: [quick start](https://docs.netmaker.org/quick-start.html), [advanced installation](https://docs.netmaker.org/server-installation.html) docs instead.

**Comment by gaby** [comment]
@afeiszli Thanks! Looking forward to trying netmarker again today.
