### ISSUE TITLE
[Bug]: upgrading from v0.24.2 to v0.26.0: UI still reports v0.24.2 after upgrading

### ISSUE THREAD

**Issue by mfide** [gravitl/netmaker#3253]
### What happened?

Hello,

I was using the community version of the netmaker v0.24.2 in a docker container on my Ubuntu 22.04 server which was working fine for me.

I decided to upgrade the server by changing the following lines in `netmaker.env` file to:

```
SERVER_IMAGE_TAG=v0.26.0
UI_IMAGE_TAG=v0.26.0
```

And then simply, `docker compose down && docker compose pull && docker compose up -d`

They started running without any problems and containers have the latest images:
![image](https://github.com/user-attachments/assets/b583cc02-0b11-4b4b-a222-864cac2b1f6d)

But when I login to my dashboard, it says that UI is still v0.24.2 while all my clients and server upgraded automatically to v.26.0:
![image](https://github.com/user-attachments/assets/e4906186-ddb6-4c48-ad4f-26426831819f)

What could be the problem for me?

Thanks.

### Version

v0.26.0

### What OS are you using?

Linux

### Contributing guidelines

- [X] Yes, I did.

**Comment by abhishek9686** [comment]
@mfide this could be a browser cache issue, open the tab in incognito to confirm the behaviour

**Comment by mfide** [comment]
You are right, incognito shows correct version:
![image](https://github.com/user-attachments/assets/fbee2a43-1fef-4205-a43f-9dc3c53e9852)

I did also CTRL+F5 but it still shows old version in normal mode.

**Comment by Aceix** [comment]
@mfide is this still happening in normal mode? or the cache has updated now?

**Comment by mfide** [comment]
> @mfide is this still happening in normal mode? or the cache has updated now?

It still has the problem in the normal mode. I don't know how to fix it. I have tried all F5, CTRL+F5 or Shift+F5 combinations.

**Comment by mfide** [comment]
I have just seen you have a new version v0.30.0. And that one seems working fine :)
![image](https://github.com/user-attachments/assets/21458784-9222-4ac4-aeef-e7131e38595b)
