### ISSUE TITLE
[Bug]: Can`t create The Remote Access Gateway-v0.30.0

### ISSUE THREAD

**Issue by izztt** [gravitl/netmaker#3264]
### Contact Details

izztto@gmail.com

### What happened?

When I want to create The Remote Access Gateway...
When I click on the button it is gray and says "only admins can create gateways"
But the account I use is a "Super-admin"
![netmaker-bug-crag](https://github.com/user-attachments/assets/a47e8847-83e0-4edc-98bf-8e087539451a)
![netmaker-bug-user](https://github.com/user-attachments/assets/9efdd2ff-fbc1-465d-b2f1-355f15c8257a)

### Version

v0.30.0

### What OS are you using?

Linux

### Contributing guidelines

- [X] Yes, I did.

**Comment by Aceix** [comment]
@izztt loking in to this asap

**Comment by izztt** [comment]
@Aceix 
 I pull the latest ui image. It works fine now. thanks👍👍👍

**Comment by izztt** [comment]
👍👍👍
