### ISSUE TITLE
[Bug]: ARM64 image for Netmaker UI 0.30.0 is missing in Docker registry

### ISSUE THREAD

**Issue by christian-schlichtherle** [gravitl/netmaker#3268]
### What happened?

[See here](https://hub.docker.com/r/gravitl/netmaker-ui/tags)

### Version

v0.30.0

### What OS are you using?

Linux, Windows, Mac

### Contributing guidelines

- [X] Yes, I did.

**Comment by Aceix** [comment]
there were some incompatible changes in our dependencies causing this.
we are trying to reolve and will release for arm64

**Comment by christian-schlichtherle** [comment]
... and for whatever reason, just now Docker Hub tells me the ARM64 image is gone again.
