### ISSUE TITLE
netclient-install

### ISSUE THREAD

**Issue by m1ckyb** [gravitl/netmaker#342]
Hi,

Only small issue i am having is with the install script @ https://raw.githubusercontent.com/gravitl/netmaker/master/scripts/netclient-install.sh

As i have installed this on some ARM64 devices i have had to modify the script to download the ARM64 client, can you make it so the script detects the system architecture and downloads the correct client?

Otherwise i am loving this..

**Comment by afeiszli** [comment]
added in v0.8.4
