### ISSUE TITLE
Netclient on kubernetes 

### ISSUE THREAD

**Issue by theonlydoo** [gravitl/netmaker#379]
# Intro
first of all: thanks :) netmaker is a nice tool

# What seems to be the issue

Actually, there is two.

## First issue, documentation

The first one is related to [the documentation](https://docs.netmaker.org/server-installation.html?highlight=netclient%20template%20yaml#netclient-daemonset) which states that [this file](https://github.com/gravitl/netmaker/blob/6227f0040ce4de0ca31280a4cfb90183089190f6/kube/components/netclient-template.yaml.backup) should be used to pop up a new netclient. Container image is [rather old](https://github.com/gravitl/netmaker/blob/6227f0040ce4de0ca31280a4cfb90183089190f6/kube/components/netclient-template.yaml.backup#L19) and doesnt fit [latest version's](https://hub.docker.com/layers/gravitl/netclient/v0.8.3/images/sha256-31e14e22ff301582316f725bdb8c6ff93aa35294a7a1d5c8726267fb7a5d1288?context=explore) files.

## Second issue, kubernetes

The second one is more technical, is it possible to provide with more examples on netclient's setup? For instance, my hosting provider's managed k8s is relying on Arch nodes. Since wg is trying to call iptables, shoudn't iptables be mounted as well? I tried to do so, but iptables was missing some so files. After mounting `/usr/lib/x86_64-linux-gnu` it resulted in a working iptables setup, but everything else went to hell inside the container. 

# Last part: kubernetes considerations

In a kubernetes cluster that forbids 
```yaml
        securityContext:
          privileged: true
```
Has gravitl or netmaker contributors designed a workaround ?  Is it possible to use a userspace wg in such a case? It seems that it'd result in a feature loss (e.g. gateway nodes route publishing).

**Comment by theonlydoo** [comment]
Thank's for your thorough reply, I think the "privileged" container issue is kind of a catch 22. The only potential workaround would be to run a sidecar container inside each pod, therefore avoiding host interraction.

Can you provide a netclient kubernetes manifest which would use an initContainer?

**Comment by afeiszli** [comment]
@theonlydoo we now have updated documentation at https://k8s.netmaker.org which should link to the latest manifests. The new manifests provide both kernel and userspace versions, so for managed k8s, you can simply use userspace. We also have a manifest for DigitalOcean which will install WireGuard on top of the hosts, and that may be converted pretty easily to match other systems as well.

Lastly, we are still using privileged=true, and at this point I don't think there is a workaround, besides being more specific with the permissions. For now, I will close with the assumption that running these containers will require advanced permissions, but feel free to re-open if you have another suggestion for how to go about it.

**Comment by theonlydoo** [comment]
Thanks so much for the documentation :) 

Picking between `privileged` and specific `CAPS` is a matter of design choice imho, NET_ADMIN should be sufficient for most of netmaker's features. I was trying to run netmaker on OVH's manged kubernetes on a testing cluster. I think that each hosting has its own kubernetes flavour and it'll be rather complicated to run an unprivileged container on each and every one of them. Kudos for doing so on DO though!
