### ISSUE TITLE
solution for ERRORs on netclient install 

### ISSUE THREAD

**Issue by pete1019** [gravitl/netmaker#405]
if ERRORs occur on netclient install: give more hints to a solution.

For example:
```
2021/10/29 20:19:02 [netclient] joining Test1 at .......eu:443
2021/10/29 20:19:02 [netclient] error installing: rpc error: code = Unknown desc = Key: 'Node.Name' Error:Field validation for 'Name' failed on the 'in_charset' tag
2021/10/29 20:19:02 Failed to authenticate: rpc error: code = Unauthenticated desc = Something went wrong with Auto Login: rpc error: code = Unknown desc = crypto/bcrypt: hashedPassword is not the hash of the given password
```

Problem was the hostname which had dots in it:
my.svr.local

So give a hint about the hostname or even BETTER: just get rid of the "."

THANKS!

**Comment by tetov** [comment]
```
2021/10/31 14:34:35 [netclient] error installing: rpc error: code = Unknown desc = Key: 'Node.Name' Error:Field validation for 'Name' failed on the 'max' tag
```

I second this. I had to find this issue before I realized my hostname was too long. (fixed using `--name short-name`).

**Comment by afeiszli** [comment]
We currently have no solution to this, but will add to triage and see what we come up with.

**Comment by afeiszli** [comment]
Error messages are a lot better now, and gRPC has been removed entirely.

Worth noting, we have verbosity now for logs on the client. When running a command, set the log level using:

-v (log level 1)
-vv (log level 2)
-vvv (log level 3)

ex: netclient join -t nsari3ar3fakr -vvv
