### ISSUE TITLE
netclient on mipsle, build failed.

### ISSUE THREAD

**Issue by oycol** [gravitl/netmaker#416]
there  does not have a MIPS architecture NetClient, but i only use wireguard  in openwrt. when i build with **GOARCH=mipsle go build -ldflags "-s -w"** , There's an error /tmp/go-build2451609279/b001/_pkg_.a(netclient.syso): unsupported arch 5

**Comment by pete1019** [comment]
How would Netclient work if there is no MIPS Version for it?

But the topic OPENWRT and Netclient is very interessting. You do much with OPENWRT?

Which openwrt router are you using with how much ROM/Flash and Ram?

Thanks

**Comment by oycol** [comment]
My openwrt device does not have enough environment to build it。

i built it on x86 linux , build failed , I just need the netclient binaries。

**Comment by pete1019** [comment]
Okay, i still would like to know which openwrt router you are using. ROM/Falsh and RAM size? Thx
You do a lot with openwrt?

Would be nice if we could use Netclient for almost every OpenWRT router.
Can you help with that?

**Comment by oycol** [comment]
ok，this is the information ，https://openwrt.org/toh/lenovo/newifi_d2

**Comment by oycol** [comment]
i'm a novice to openwrt,  just a user.

**Comment by pete1019** [comment]
okay, the router has 32MB of flash and 512MB of RAM. It could work.
But somebody else might need to help here on compiling @afeiszli

**Comment by oycol** [comment]
thank you!!

**Comment by afeiszli** [comment]
@oycol move syso to a different directory and re-run the build. Syso is only a dependency for building on Windows.

**Comment by oycol** [comment]
its running, thanks,  it not fully support by systemd.
Although there will be some new problems， thank you。

![image](https://user-images.githubusercontent.com/23732968/139591453-874cade7-df23-4ea8-b2c9-0ff7c75bffa8.png)

**Comment by pete1019** [comment]
> its running, thanks, it not fully support by systemd. Although there will be some new problems， thank you。
> 
> ![image](https://user-images.githubusercontent.com/23732968/139591453-874cade7-df23-4ea8-b2c9-0ff7c75bffa8.png)

@afeiszli is there any alternative to systemd (systemctl)?
https://openwrt.org/docs/techref/initscripts

**Comment by afeiszli** [comment]
@pete1019 , two things are necessary here:
1. When running the join command, add --daemon=off. If you do this, it will not attempt to set up systemd
2. You will need to configure your own way of "daemonizing" checkins. It can be a cron job, a script, or anything, but you just need to run the following command on loop, ideally about once every 10 seconds: "/etc/netclient/netclient checkin -n all
"

That's all the systemd daemon is doing anyway. You can even run it manually for testing purposes.

**Comment by pete1019** [comment]
> @pete1019 @oycol, two things are necessary here:
> 
> 1. When running the join command, add --daemon=off. If you do this, it will not attempt to set up systemd
> 2. You will need to configure your own way of "daemonizing" checkins. It can be a cron job, a script, or anything, but you just need to run the following command on loop, ideally about once every 10 seconds: "/etc/netclient/netclient checkin -n all
>    "
> 
> That's all the systemd daemon is doing anyway. You can even run it manually for testing purposes.

@afeiszli thank you for the input!

@oycol how does that sound to you? Will you be able to make it work with this?

**Comment by oycol** [comment]
Yes，I found the service  desc  in the code. It works very well，i  still  need time to learn about it。

10M in size， it so big in openwrt. but my device still  has  space，maybe  it can be smaller with the upx (maybe ,  I search in google), but it isn't the first thing to me .  (I don't have the ability to change the code :sob: ）

**Comment by pete1019** [comment]
> Yes，I found the service desc in the code. It works very well，i still need time to learn about it。
> 
> 10M in size， it so big in openwrt. but my device still has space，maybe it can be smaller with the upx (maybe , I search in google), but it isn't the first thing to me . (I don't have the ability to change the code 😭 ）

Please explain exactly how you solved the cronjob now on your OpenWRT:
/etc/netclient/netclient checkin -n all

**Comment by oycol** [comment]
simple,run a bg shell, every 10s run checkin.  it still need to be optimized,but now it's useful.

**Comment by pete1019** [comment]
> simple,run a bg shell, every 10s run checkin. it still need to be optimized,but now it's useful.

What needs to be optimized?
Thanks

**Comment by oycol** [comment]
as you say,the init script.  and i found  some bug with  openwrt client,maybe .Maybe I am not familiar with wg or netclient.I will  experiment again.
