### ISSUE TITLE
Creating Invalid Group returns http.StatusOK

### ISSUE THREAD

**Issue by mattkasun** [gravitl/netmaker#42]
creating a group with a duplicate name to existing group or creating a group with a name that is too long does not provide any error indication.  The group is not created in the database (console error) but the api returns a http.StatusOK with no body the same as successful group creation.

**Comment by mattkasun** [comment]
also applies to creating a group with a bad address range.

**Comment by afeiszli** [comment]
definitely still an existing problem...I can even create a duplicate in the UI which causes all sorts of problems.

**Comment by afeiszli** [comment]
ok with validation on we're good to go. I'll close once I merge into develop.

**Comment by afeiszli** [comment]
closed  with #95
