### ISSUE TITLE
Wrong mask in network interface on Linux

### ISSUE THREAD

**Issue by restanrm** [gravitl/netmaker#423]
If the mask of the network in Netmaker isn't `/24`, the mask is wrongly defined. The value is currently hardcoded in  https://github.com/gravitl/netmaker/blob/34915cb50bde91968b740fb4d1a463993da24c1a/netclient/wireguard/kernel.go#L18

**Comment by afeiszli** [comment]
I believe we'll be working on fixing this in the next 1-2 releases.

**Comment by mattkasun** [comment]
PR #723
