### ISSUE TITLE
Bug:  edit the net ip will cause grpc down.

### ISSUE THREAD

**Issue by oycol** [gravitl/netmaker#424]
when I want to exchange the  main virtual ip with two client on whe web  ( in the relay mode)，the  api  server  down and can't start again, maybe the sql data failed . 

![image](https://user-images.githubusercontent.com/23732968/139856839-b1cbce9e-edd3-4796-bd24-06a9f5f36eea.png)

**Comment by afeiszli** [comment]
@oycol what version are you running?

**Comment by oycol** [comment]
maybe the latest.  0.8.5, gravitl/netmaker       latest    9b784a32d35a    6 days ago

**Comment by afeiszli** [comment]
You can see in the UI by hovering over the info icon ( i ).

**Comment by oycol** [comment]
oh, 0.8.4.., maybe that  is  the latest  version on dockerhub

**Comment by afeiszli** [comment]
There appears to be an issue with Docker Hub we are working to resolve on this image tag. Sometimes the SHA is pointing to the older version. We hope to have a fix for this later today, but in the meantime, please pull v0.8.5 and confirm in the UI that you are running v0.8.5 for server and gui. This should resolve the issue.
