### ISSUE TITLE
Leftover wireguard interface when container is stopped in network_mode: host

### ISSUE THREAD

**Issue by Belphemur** [gravitl/netmaker#440]
Hello,

When the container is stopped in `network_mode: host`, the interface created by the container stays on the host.

When starting the container again, it crash, complaining it can't bind the port 518XX since the wireguard interface is already bound to the port.

**Comment by afeiszli** [comment]
This should no longer be an issue as of 0.9.4. We also now recomment _not_ running with host networking on the server. Please let us know if this issue is still encountered.
