### ISSUE TITLE
Not able to ping between nodes

### ISSUE THREAD

**Issue by MANKUD** [gravitl/netmaker#443]
Hello,

I have just set up netmaker on my digital ocean VPN with UFW disabled. I am able to ping the nodes from the server and also ping the server from the nodes. But the nodes are not able to ping each other. is there something that I am doing wrong?

![image](https://user-images.githubusercontent.com/83474708/140561546-669f147c-3952-466f-91e0-948ab99640ee.png)

**Comment by oycol** [comment]
setup your netmaker in relay mode  with your home and desktop node，then try again ，telnet 3306 port if in windows，ping sometimes in windows with firewalld，if you can't reach other node in relay mode, check your node setting,if you can reach ,check your nat mode.

**Comment by afeiszli** [comment]
Solved offline. @MANKUD can you please summarize your issue / solution and mark as closed? In general, set MTU to 1450 for windows (network default) and reboot machine if connection is not working.

**Comment by MANKUD** [comment]
@oycol Issue was with the routing table should be fixed in the next release.

Thank you for helping me fix the issue @afeiszli

**Comment by afeiszli** [comment]
FYI, fix is a simple command that needs to be run post-interface creation:

`route add <network range> mask <network mask> <node ip>`

**Comment by afeiszli** [comment]
added automatically in 0.9.0
