### ISSUE TITLE
docker-compose up failed on armv8 

### ISSUE THREAD

**Issue by tomjamescn** [gravitl/netmaker#447]
I think the image does NOT support arm64 arch now.
`docker-compose up` failed on my oracle VM.Standard.A1.Flex (arm64)

Error msg:

> Attaching to netmaker, netmaker-ui
netmaker       | standard_init_linux.go:228: exec user process caused: exec format error
netmaker-ui    | standard_init_linux.go:228: exec user process caused: exec format error
netmaker exited with code 1
netmaker       | standard_init_linux.go:228: exec user process caused: exec format error
netmaker       | standard_init_linux.go:228: exec user process caused: exec format error
netmaker       | standard_init_linux.go:228: exec user process caused: exec format error

**Comment by afeiszli** [comment]
Armv8 is supported on the client, not the server. However, we do have an arm64 version you can try. Change the tags in the docker-compose for the netmaker-ui and netmaker images to "test-workflow" (gravitl/netmaker:test-workflow).

**Comment by tomjamescn** [comment]
@afeiszli thanks, i made a mistake, it is arm64 not armv8. I'll try your solution.
