### ISSUE TITLE
connection lost after restart os

### ISSUE THREAD

**Issue by tomjamescn** [gravitl/netmaker#450]
after restart os, my connection lost, how to find it back?

`wg show` show nothing after restart os on node.

**Comment by afeiszli** [comment]
Was the server restarted or the client? What is the OS of the machine?

**Comment by tomjamescn** [comment]
@afeiszli client restart. 

`Linux arm-instance 5.11.0-1020-oracle #21~20.04.1-Ubuntu SMP Wed Sep 29 15:41:45 UTC 2021 aarch64 aarch64 aarch64 GNU/Linux`

**Comment by afeiszli** [comment]
@tomjamescn are you still encountering this? I see you're running on Oracle. We typically do not recommend Oracle because they set a lot of their own custom networking rules which tends to cause issues.
