### ISSUE TITLE
Quick install doesn't work

### ISSUE THREAD

**Issue by ethanfowler** [gravitl/netmaker#451]
Hi, I'm trying to do a quick trial and cannot get the quick install instructions to work for me. Installation script finishes but I am unable to connect to the dashboard. I'm on an EC2 Ubuntu 20.04 instance, with what I think are the correct firewall holes:
Inbound:
![image](https://user-images.githubusercontent.com/23166946/140918389-25efc102-f712-4b87-a9b6-a8f5642306af.png)
Outbound:
![image](https://user-images.githubusercontent.com/23166946/140918475-050cc7f2-58df-40c7-8747-39cc6e8d300a.png)
I can SSH into the server, which I think demonstrates that the rules are working correctly.

I am trying to access the dashboard at the script-output-specified url, `dashboard.nm.xx-xx-xx-xx.nip.io` (I have obfuscated the IP here for obvious reasons), but get a "refused to connect".

One thing of concern to me is that there is nothing listening on port 443 on the EC2 instance:

```$ sudo lsof -i -P -n | grep LISTEN
systemd-r   387 systemd-resolve   13u  IPv4  19637      0t0  TCP 127.0.0.53:53 (LISTEN)
sshd        659            root    3u  IPv4  23619      0t0  TCP *:22 (LISTEN)
sshd        659            root    4u  IPv6  23630      0t0  TCP *:22 (LISTEN)
container  1824            root   12u  IPv4  30045      0t0  TCP 127.0.0.1:40809 (LISTEN)
docker-pr 10978            root    4u  IPv4 146977      0t0  TCP xx.xx.xx.xx:53 (LISTEN)
docker-pr 12845            root    4u  IPv4 159408      0t0  TCP *:50051 (LISTEN)
docker-pr 12850            root    4u  IPv6 159414      0t0  TCP *:50051 (LISTEN)
docker-pr 12862            root    4u  IPv4 159464      0t0  TCP *:8081 (LISTEN)
docker-pr 12867            root    4u  IPv6 159470      0t0  TCP *:8081 (LISTEN)
docker-pr 13064            root    4u  IPv4 160704      0t0  TCP *:8082 (LISTEN)
docker-pr 13069            root    4u  IPv6 160713      0t0  TCP *:8082 (LISTEN)
```

And, looking at the `docker-compose.yml` generated by the script, there is no docker container using port 443. I am confused as to how this is supposed to work.

**Comment by ethanfowler** [comment]
Hm, the main `docker-compose.yml`, used in the quick install, does not set up the Caddy web server, as far as I can tell. Have you moved away from it, or incorporated it into one of the Netmaker images?

**Comment by ethanfowler** [comment]
Ok, doing the non-quick setup (manually editing https://raw.githubusercontent.com/gravitl/netmaker/develop/compose/docker-compose.caddy.yml) works. I think the quick install is borked.

**Comment by afeiszli** [comment]
@ethanfowler which quick install, the script, or the docs instructions?

**Comment by afeiszli** [comment]
I believe Caddy also needs port 80 to help setting up certificates.

**Comment by afeiszli** [comment]
NVM I just found the issue. Thanks for opening this. We changed the script yesterday and the compose file it pointed to was out of date. Just tested it and it should be working now.

**Comment by ethanfowler** [comment]
Thanks!
