### ISSUE TITLE
Expiring peer or timer/expiring functions for Peer

### ISSUE THREAD

**Issue by rhenigma** [gravitl/netmaker#47]
Expiring peer. Add timer/expiring functions to peer (somewhat like OpenVPN expiring clients maybe?)

    Use cases for expiring peer functions would be in a situation 
    where i'd like to add peer for my office mate and let just say that he/she is a temporary staff 
    working on a project for about 3 months. I would really like some automated script/panel to automatically 
    remove the config lines without having manually logged in and delete the peer.

**Comment by afeiszli** [comment]
Adding to v0.2 features list.
1. Add ExpirationDateTime to Node (default to max datetime)
2. Make field visible/editable in GUI + DateTime Selector
3. Server runs check on interval to see if there are any expired nodes
4. If ExpirationDateTime has passed, delete node.

**Comment by afeiszli** [comment]
In development branch, will be in v0.2 release.
