### ISSUE TITLE
Bandwidth consumption for each peer

### ISSUE THREAD

**Issue by rhenigma** [gravitl/netmaker#48]
Request for bandwidth consumption for each peer and total consumption hour/day/week/months

For bandwidth consumption use cases where some of the providers didn't provide basic vnstat or equivalent to that to monitor bandwidth usage. That would be a nice addition to the project too.

**Comment by afeiszli** [comment]
Roadmapping this for v0.5, scheduled for end of May. This is a great production feature to have but we need to prioritize a couple other features ahead of this. Schedule allowing, we may be able to fit it in sooner.

**Comment by Belphemur** [comment]
Any plan for this ?
Should it be re-planned for a following release ?

It would be a great addition, especially with external clients.

**Comment by subzero355** [comment]
Excited for this to happen.. I have web traffic flowing between the peers and wanted to see how much each peer is consuming.

**Comment by afeiszli** [comment]
metrics are added in Netmaker EE under v0.16.0
