### ISSUE TITLE
IPv6 config not removed when disable dualstack

### ISSUE THREAD

**Issue by chefkoch-de42** [gravitl/netmaker#492]
When disabling dualstack mode in vpn the allowed ips are not being updated on the clients.
When removing the ipv6 net definition in network after disabling dualstack, ipv6 ips still exist in allowed ips

Regards

**Comment by afeiszli** [comment]
adding to triage

**Comment by afeiszli** [comment]
No longer applicable. "Dual Stack" is no longer a feature.
