### ISSUE TITLE
Missing show-all option in nodes panel dropdown

### ISSUE THREAD

**Issue by stianlaa** [gravitl/netmaker#496]
Greetings!
I couldn't find a github issue template you're using, so I just found one laying about. Thanks for a great piece of software thus far, I'm looking forward to see where you're going with this. 

## Context

This is a minor UI issue found when playing around with nodes and networks.

## Process to find/recreate issue
1. Go to netmaker dashboard v0.9
2. Go to the nodes page
3. All nodes are displayed, select an element in the `Select Network` dropdown
Now we can't choose any option to show all network nodes

## Expected result

An option *All networks* or similar to show all network nodes.  

## Possible Fix

Add dropdown option displaying all networks

**Comment by 0xdcarns** [comment]
Added for nodes in v0.9.1 image of UI if you want to pull it.

**Comment by stianlaa** [comment]
Excellent, that was quick. I'll check it out next time I'm bumping our version.
