### ISSUE TITLE
expire date and last checkin date not rendered correct in edit mode

### ISSUE THREAD

**Issue by chefkoch-de42** [gravitl/netmaker#497]
expire date and last checkin date not rendered correct in edit mode.
If you exit the edit mode, the date is shown in correct human readable format.

![grafik](https://user-images.githubusercontent.com/91177996/142868494-329b2d6b-46ab-4be8-b077-71681254c759.png)

**Comment by 0xdcarns** [comment]
if you use UI version v0.9.1 this has been updated

**Comment by chefkoch-de42** [comment]
Thx for pointing to the new update
