### ISSUE TITLE
In section labeled Pre-Reqs it talks about viewing the Advanced Usage docs to install w/out Docker?

### ISSUE THREAD

**Issue by bmullan** [gravitl/netmaker#50]
In the section labeled Pre-Reqs it says...
**  
> Install Docker (can run without Docker as well, but is not preferred. If this is a requirement, view the Advanced Usage docs).  
**  
i intend to try Netmaker with LXD containers (re system not application containers) so although I can run Docker I try not to when possible.

So when it mentions _**Advanced Usage docs**_  where do I find those?

Under Roadmaps it lists "Advanced Usage docs" ... but those sound like a "future' effort?

thanks
Brian

**Comment by afeiszli** [comment]
Hi @bmullan, that sounds like an interesting use case. Apologies, those docs are not written up yet. However, if you are familiar with mongodb, golang, and apache or nginx, that would be sufficient to run without docker. The general steps are:

1. install and start mongodb
2. clone the netmaker repo and build the golang binary
3. change and source the "defaultvalues.sh"
4. run the golang binary
5. clone the netmaker-ui repo and build the static files
6. host those files from the webserver of your choice

I will try to have those docs written up by the end of the week.

**Comment by afeiszli** [comment]
adding to enhancements list for v0.2.

**Comment by afeiszli** [comment]
@bmullan sorry for the delay. The docs have been added to docs/USAGE.md if you want to check it out and see if it works for you.

**Comment by afeiszli** [comment]
Direct link: https://github.com/gravitl/netmaker/blob/master/docs/USAGE.md#non-docker-installation
