### ISSUE TITLE
web session timeout not properly handled 

### ISSUE THREAD

**Issue by a1ad** [gravitl/netmaker#511]
After the session timeout it's still possible to can navigate all the different menus (even the keys) except the nodes, the nodes list is empty.
You need to manually reload the webpage to be redirected to the login page. 

The redirect needs to happen automatically after the session timeout or when clicking on one of the UI buttons.

**Comment by afeiszli** [comment]
@a1ad please open this issue in the netmaker-ui repo, and we can solve this in the next release.

**Comment by afeiszli** [comment]
Actually, this should be already solved in the latest 0.9.1 UI image
