### ISSUE TITLE
Timestamps are incorrectly displayed in the web UI

### ISSUE THREAD

**Issue by frprm** [gravitl/netmaker#512]
Some timestamps are displayed wrongfully. 

For example:
In the **Networks** list:
![image](https://user-images.githubusercontent.com/31648426/143134484-7dfa3c8d-2909-4f1f-af66-5d2ed3759fa2.png)

In the **Node** screen:
![image](https://user-images.githubusercontent.com/31648426/143134686-63ba124b-8386-4b41-8be0-769525fd29e8.png)

It looks like the month is actually the year on 2 digits...

**Comment by afeiszli** [comment]
@frprm please open this issue in the netmaker-ui repo, and we can solve this in the next release.
