### ISSUE TITLE
UDP hole punching not working

### ISSUE THREAD

**Issue by a1ad** [gravitl/netmaker#515]
My (net)clients on the LAN with an opensense as firewall cannot punch holes through the firewall. I have a tailscale client on the same LAN that is punching holes like a champ.

Screenshot of the opnsense status page, here you only see the tailscale client:
![image](https://user-images.githubusercontent.com/29516835/143204640-23350990-4e23-4e25-9099-29d724df6b8a.png)

I v got 2 netclients on the same LAN. The config setting on the client is correct: udpholepunch: "yes"

**Comment by afeiszli** [comment]
Hi, I believe you are the user with Netmaker server on the local network, correct?

**Comment by a1ad** [comment]
Yes indeed, we found a workaround on Discord.

**Comment by afeiszli** [comment]
Okay, I'm trying to find the thread on discord to post it here. IIRC:

1. server is on the local network
2. when nodes connect to the server, they have the same public ip and are disregarded
3. because of this, server does not get a udp hole punch address, and it is not sent to the other clients

Does that sound right?

**Comment by afeiszli** [comment]
@a1ad looking for more details on this. May close as out of scope otherwise (since server was run on local network).

**Comment by a1ad** [comment]
> Okay, I'm trying to find the thread on discord to post it here. IIRC:
> 
>     1. server is on the local network
> 
>     2. when nodes connect to the server, they have the same public ip and are disregarded
> 
>     3. because of this, server does not get a udp hole punch address, and it is not sent to the other clients
> 
> 
> Does that sound right?

Yes indeed!

**Comment by afeiszli** [comment]
Okay, we're going to close this as out of scope for now. UDP Hole Punching needs the server to be in a public location. We should add some docs specifying this but for others who come across it, if you're running your server locally, UDP Hole Punching needs to be turned off.
