### ISSUE TITLE
OpenWRT netmaker package

### ISSUE THREAD

**Issue by sbilly** [gravitl/netmaker#516]
Hi

I've made a github action to build `ipk` files for multi version OpenWRT. Is it possible to add it to official release?

- RELEASE: https://github.com/sbilly/netmaker-openwrt/releases
- Code: https://github.com/sbilly/netmaker-openwrt

**Comment by afeiszli** [comment]
Hi, we will consider this in a future release as an enhancement. For now the script works fine. If we add a package for OpenWRT we will need to start hosting packages for all other linux distros too, so need a generic solution to this.

**Comment by afeiszli** [comment]
Closing as out of scope for now. Will re-consider once we have a generic approach to package management for different linux distros.
