### ISSUE TITLE
Missing gcompat in netclient docker image

### ISSUE THREAD

**Issue by HagaiBarel** [gravitl/netmaker#522]
Hello,

While running `netclient` as containerized daemonset on kubernetes, and mounting the host's `wg` to the container, I'm getting a `file not found` error although the mount is successful and I can see the `wg` binary in the container's file system (at `/usr/bin/wg`). It seems the `gcompat` isn't installed in the image, which makes the `glibc/musl` issue surface.

For reference, here's my environment spec:
Kubernetes version: v1.21.5-gke.1802
Base OS: Ubuntu 20.04.3
Cloud Provider: GCE
wireguard and wireguard-tools installed on the host

To fix it, I've used the following `Dockerfile`:

```docker
FROM gravitl/netclient:v0.9.0

RUN apk add --no-cache gcompat
```

That fixed the issue and netclient is able to work with the host's `wg` binary and modify it's configuration. I'm not sure which `Dockerfile` is exactly used for building this image, I'm referring to the `gravitl/netclient:v0.9.0` currently available in [DockerHub](https://hub.docker.com/layers/gravitl/netclient/v0.9.0/images/sha256-b145dbc54931586c752e297b117cca5b8ccf7705d2690cdaeee7b49305e98421?context=explore). 

Would be happy to submit a fix if you can point me to the right place

**Comment by afeiszli** [comment]
Added gcompat in 0.9.1 image version
