### ISSUE TITLE
Missing `gravitl/netmaker:v0.9.1` Docker image

### ISSUE THREAD

**Issue by Madh93** [gravitl/netmaker#523]
Hi,

It seems the [v0.9.1](https://github.com/gravitl/netmaker/releases/tag/v0.9.1) release has not upload the new Docker Image:

    $ docker pull gravitl/netmaker:v0.9.1
    Error response from daemon: manifest for gravitl/netmaker:v0.9.1 not found: manifest unknown: manifest unknown
    
In [Docker Hub](https://hub.docker.com/r/gravitl/netmaker/tags) the latest tag was [v0.9.1-doks](https://hub.docker.com/layers/gravitl/netmaker/v0.9.1-doks/images/sha256-a219cd6cd6a866d9851f41a705e57cac50c572bf716913b7cfa8139155e5a2d2?context=explore) :confused:

**Comment by afeiszli** [comment]
Pushed 0.9.1
