### ISSUE TITLE
external clients not listed in netmaker.hosts

### ISSUE THREAD

**Issue by chefkoch-de42** [gravitl/netmaker#529]
external clients are not listed in netmaker.hosts file for CoreDNS

**Comment by afeiszli** [comment]
Hi @chefkoch-de42, I'm going to mark this as out-of-scope for now. External clients are meant only for **inbound** traffic, so having private DNS added to these machines does not make much sense.

**Comment by chefkoch-de42** [comment]
Well I understand your concern, but for me it is interesting to get a reverse lookup for all vpn nodes. As I do not masquerade on egress gw to my local lan, I see the vpn ips in my logs. My local dns server is asking coredns for reverse ip ranges.
Or is the coredns netmaker api plugin matching to all nodes in the vpn config?

Maybe this can be reopened
