### ISSUE TITLE
SystemD Service Hangs

### ISSUE THREAD

**Issue by afeiszli** [gravitl/netmaker#53]
Running "systemctl status netclient" usually hangs. Appears to be due to service file.

https://askubuntu.com/questions/1004853/systemd-is-hanging-when-i-start-or-restart-a-service
https://fabianlee.org/2017/05/21/golang-running-a-go-binary-as-a-systemd-service-on-ubuntu-16-04/

We should change Type to simple and see if this fixes.

Adding to v0.2 Fixlist

**Comment by afeiszli** [comment]
punting to v0.3

**Comment by 0xdcarns** [comment]
Netclient will be refactored in 0.8.1

**Comment by afeiszli** [comment]
Fixed as of 0.8.3. Netclient on Linux now uses a single timer, which decreases hang substantially.
