### ISSUE TITLE
Feature Request: make egres gw with configurable (on/off) masquerading in webgui

### ISSUE THREAD

**Issue by chefkoch-de42** [gravitl/netmaker#530]

**Comment by afeiszli** [comment]
@chefkoch-de42 are you able to just edit the postup/postdown to remove the masquerade?

**Comment by chefkoch-de42** [comment]
yes, but a switch button is nice ;-)
feel free to close this if you do not agree

**Comment by afeiszli** [comment]
I think the logic would end up getting overly complicated by this. If editing the postup/postdown works, it would be better to avoid that logic since I think it will end up getting messy.

**Comment by afeiszli** [comment]
I think we will close this for now. We are trying to simplify the UI and this would complicate it. Since this can be achieved by modifying postup/postdown, that should be sufficient.
