### ISSUE TITLE
0.9.1 Windows 10 - script not recognizing wireguard as being installed

### ISSUE THREAD

**Issue by RzNmKX** [gravitl/netmaker#536]
❯ . { iwr -useb  https://raw.githubusercontent.com/gravitl/netmaker/master/scripts/netclient-install.ps1 } | iex; Netclient-Install -version "v0.9.1" -token "tokenhere"

ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Script     0.0        netclient-install                   {Netclient-Install, Quit}
'WireGuard' is installed.
re-running setup to confirm all components are installed.
'netclient' is installed.

❯ netclient
2021/12/07 10:53:02 Gravitl Netclient on Windows started
2021/12/07 10:53:02 error running command: wg help
2021/12/07 10:53:02
2021/12/07 10:53:02 Please install WireGuard before using Gravitl Netclient. https://download.wireguard.com

**Comment by RzNmKX** [comment]
Navigating to c:\program files\wireguard and running the script from there does work

**Comment by afeiszli** [comment]
I believe that the script and netclient both need to be run from particular locations in powershell. I'm going to label this as a docs enhancement

**Comment by afeiszli** [comment]
Added in docs enhancement, and also now no longer applicable as of 0.14, as we have an MSI installer instead of powershell script.
