### ISSUE TITLE
Netclient can't set dns, missing resolvectl

### ISSUE THREAD

**Issue by HagaiBarel** [gravitl/netmaker#540]
Hello,

Running `gravitl/netclient:v0.9.1` image as kubernetes daemonset and getting this error while trying to set `dnson`:

```
2021/12/08 14:14:51 exec: "resolvectl": executable file not found in $PATH
2021/12/08 14:14:51 WARNING: resolvectl not present. Unable to set dns. Install resolvectl or run manually.
```

Since the image is based on `alpine` and `resolvectl` is part of `sysetmd` this will likely never work.

One possible solution might be to use `resolvconf` instead but `resolvectl` seems hardcoded in the source code so I'm not sure how this will work

**Comment by afeiszli** [comment]
I believe resolvconf and resolvectl are not 1:1. We'd like to use resolvconf where possible but would need to figure out the appropriate commands to switch between the two. One option for the daemonset would be to simply modify dns settings in the yaml to include the additional nameserver.

**Comment by afeiszli** [comment]
I would put this as an enhancement rather than an issue, as we have stated that systems without resolvectl will not support auto-dns.

**Comment by RzNmKX** [comment]
> I would put this as an enhancement rather than an issue, as we have stated that systems without resolvectl will not support auto-dns.

The quick install guide doesn't say anything about resolvectl, nor is it present in troubleshooting guide, and the nm-quick.sh script doesn't have it either. As far as I can tell the only place that mentions it is https://netmaker.readthedocs.io/en/master/server-installation.html#system-compatibility. I've never done a pull request so maybe I'll start with helping you guys update the docs.

**Comment by afeiszli** [comment]
It is mentioned in the docs, but we definitely need to be better about it, since this is not obvious: https://docs.netmaker.org/client-installation.html?highlight=resolvectl#private-dns-management.

**Comment by afeiszli** [comment]
closing this for now, but we may be changing the resolvectl dependency in a future release
