### ISSUE TITLE
Wireguard tunnel via TCP

### ISSUE THREAD

**Issue by yangchuansheng** [gravitl/netmaker#555]
Due to ISP restriction I am looking to see if we can use the TCP wrapper. UDP is blocked.

but wireguard doesn't support TCP natively and it needs to be integrated with other tools such as udptunnel or udp2raw to enable that feature.

Could we use netmaker over TCP?

**Comment by afeiszli** [comment]
Hi, this could potentially be roadmapped at some point in the future, but not likely within the next 6 months at least. I'm going to close this as out of scope for now, but can revisit later next year.
