### ISSUE TITLE
Ingress Gateway does not work in a Docker container

### ISSUE THREAD

**Issue by Zottelchen** [gravitl/netmaker#556]
**Summary**
It appears as if an external device can connect to the ingress gateway, however it can't reach another node. The ingress gateway can however reach the other nodes.

**Sample Setup**
Nodes:
```
10.154.241.1 - netmaker instance
10.154.241.2 - the ingress gateway
10.154.241.3 - other node
...
```
External devices:
```
10.154.241.10 - Windows 10 device
10.154.241.11 - Android device
```

`.10` (and `.11`) can connect to the ingress gateway `.2`. This can be confirmed via a simple ping. `.10` can not reach `.1`, `.3` or any other node. `.2` can make a connection to any other node.

**Tried, not working solutions**

* making sure `sysctl net.ipv4.ip_forward` is set to 1

**Current workaround**
Running the netclient on the host instead of in a docker container.

**Comment by afeiszli** [comment]
@Zottelchen we have not experienced this issue in any testing. Can you confirm this is still an issue in 0.9.4?

**Comment by afeiszli** [comment]
closing, as we have not heard an update. If you are still experiencing this issue, please re-open
