### ISSUE TITLE
admin can not delete other account

### ISSUE THREAD

**Issue by KadeDivent** [gravitl/netmaker#560]
UI: 0.9.2
Server: 0.9.2

I created an admin account, and then I created a regular account (account name: test1)

I can't delete the  regular  account  (test1) with the admin account

But when I gave the regular account  (test1) administrator privileges and logged in with this account

I can delete this account  myself (use test1 delete test 1)

and when I deleted myself ,I also remained logged in,

**Comment by 0xdcarns** [comment]
We have found the issue for this and it will be fixed in the next minor release, thank you!

**Comment by 0xdcarns** [comment]
should be fixed in 0.9.3
