### ISSUE TITLE
failed to create admin

### ISSUE THREAD

**Issue by lihaiz** [gravitl/netmaker#565]
sudo wget -qO - https://raw.githubusercontent.com/gravitl/netmaker/master/scripts/nm-quick.sh | bash -s -- -d xx.ddns.net -e example@email.com
Installation succeeded, use http://xx.ddns.net:8082 open the web, create admin failed, 
tips:Could not reach server

**Comment by hehh2001** [comment]
同样的问题出现，我是采用docker安装，容器正常运行，之后打开网页，无法创建管理员

**Comment by afeiszli** [comment]
I'm going to pair this with an existing bug, which is that when the server connection is failing, it just says "failed to create admin"

**Comment by shizunge** [comment]
> > 一定是您使用访问仪表板的问题本地计算机无法清除连接您访问的服务器。如果确保您可以将其或至少可以ping通。它可能，请服务器计算机上的端口和防火墙。
> > 我使用谷歌翻译，如果阅读困难，请见谅。
> 
> 可以访问的，已经关闭了所有防火墙了

Check whether you can access:

> https://api.NETMAKER_BASE_DOMAIN/api/networks

Where `https://api.NETMAKER_BASE_DOMAIN` is the `BACKEND_URL` environment variable you set.

If you go directly to that URL from you browser, you should get a JSON file saying "error verifying user token" (expected, because header is not correct).  Or you can access the API via `curl` with a correct header, see https://netmaker.org/api.html.

**Comment by lijc016** [comment]
> 同样的问题出现，我是采用docker安装，容器正常运行，之后打开网页，无法创建管理员

经过排查，有可能是因为GFW的拦截导致的；我在海外服务器配置出现了这个问题，在本地配置成功。
详细可以看一下TLS报错。

**Comment by afeiszli** [comment]
@lijc016 @lihaiz @hehh2001 is this issue still relevant?

**Comment by Nexxus-LMT** [comment]
having the same issue. and i can reach the url specified. using ngnix as a reverse proxy

**Comment by srezone** [comment]
version 0.14.3 have same issue.

**Comment by afeiszli** [comment]
@srezone @Nexxus-LMT try tunning the following: curl -H 'Content-Type: application/json' https://api.nm.67-207-85-236.nip.io/api/users/adm/hasadmin

If it returns "false" then the API is healthy. However, my guess is there is some certificate error in the middle which is preventing a good connection to your API.

**Comment by afeiszli** [comment]
Closing, since there has been no update here.
