### ISSUE TITLE
netclient still change endpoint when isstatic set.

### ISSUE THREAD

**Issue by WooDragon** [gravitl/netmaker#571]
My network is pertty simple

client behind firewall(openwrt) <-> server with public IP

I have multiple openwrt device without public IP and connect them to server with public IP.

there is global proxy configured on gateway, which means the server never get the right client endpoint, I'm expect server act as passive service, just not change client side endpoint.

so I've set client "isstatic", but server netclient still change client endpoint every 15s...

for now, I'm set keepalive value to 1, so client wireguard will send heartbeat packet every second.

It's work for me that netclient block tunnel every 15s, but I still hope maybe there is some better solution or fix it if that is an issue.

Thanks.

**Comment by mattkasun** [comment]
@WooDragon are you still experiencing this problem?

**Comment by mattkasun** [comment]
The only time netclient updates its endpoint is if isstatic is false or roaming is true.

**Comment by afeiszli** [comment]
This should be functional as of 0.12.0. Closing, please re-open if you still experience the issue.

**Comment by WooDragon** [comment]
Hi
I've finally upgrade netmaker from 0.9.x to 0.14.1, then I found that I set persistent keepalive to 0 on UI, then the value at server is 15s, not 0s.

I'm not sure if it's expected behavior, maybe 0 is allowed in UI, but when netclient try set it to 0 is not allowed on wireguard.

If we need passive node,maybe remove whole persistent keepalive line from config is better than set it.
