### ISSUE TITLE
Access Key API 

### ISSUE THREAD

**Issue by mattkasun** [gravitl/netmaker#58]
- Duplicate access keys with same name can be created.  Deleting key deletes all keys with same name
- Deleting access key does not return mongo.DeleteResullt
- Deleting non-existent access key returns http.StatusOK

**Comment by afeiszli** [comment]
I think this was solved in some of the commits but did not keep track. Will test today.

**Comment by mattkasun** [comment]
Just tested this on v0.2 

 

- Still problem

   -   Duplicate access keys with same name can be created. Deleting key deletes all keys with same name
  
- fixed in v0.2
   -   Deleting non-existent access key returns http.StatusOK

-  OBE by changes to response messages
   -   Deleting access key does not return mongo.DeleteResullt
