### ISSUE TITLE
arm64 container images are only published on the test-workflow tag

### ISSUE THREAD

**Issue by lnhrdt** [gravitl/netmaker#592]
Based on comments in #480 I thought that arm64 images were being published but I ran into the same issues described in #457 when trying to run v0.9.3, v0.9.2, and v0.9.1. Then I looked at the [actual images on docker hub](https://hub.docker.com/r/gravitl/netmaker/tags) and noticed that only the `test-workflow` tag has an arm64 version published. However that tag was published 2 months ago. I'd like to use the current version and upgrade when new versions are released.

Can you start publishing arm64 container images for new versions?

**Comment by lnhrdt** [comment]
Making things a little more complicated, I'm now also noticing that rqlite does not publish arm64 images (rqlite/rqlite-docker#12). Is that why you didn't start publishing arm64 images based on the work done in #480?

**Comment by mattkasun** [comment]
![image](https://user-images.githubusercontent.com/32648129/148562489-e81eb1af-dfa5-428e-885d-df3efd3f2c12.png)

arm64 image is now on dockerhub

suggest you use sqlite rather than rqlite

**Comment by lnhrdt** [comment]
Amazing @mattkasun! Can you do the same for the [netmaker-ui image](https://hub.docker.com/r/gravitl/netmaker-ui) as well?

**Comment by mattkasun** [comment]
docker hub now has arm64 image for netmaker-ui as well

**Comment by lnhrdt** [comment]
@mattkasun thank you I've got everything working now on arm64!

**Comment by lnhrdt** [comment]
Hey @mattkasun I wish I had seen this coming earlier, but could you also help get arm64 images published for the [netclient image](https://hub.docker.com/r/gravitl/netclient)?

**Comment by lnhrdt** [comment]
Hey @mattkasun I wish I had seen this coming earlier, but could you also help get arm64 images published for the [netclient image](https://hub.docker.com/r/gravitl/netclient)?

**Comment by mattkasun** [comment]
@lnhrdt  I will put it in the backlog but it will be a low priority task as I (personal opinion) see no advantages to running netclient in a container.  Just download the netclient binary for your architecture and join a network.  Everything will be setup by joining a network.  I am open to changing the priority if you have a compelling use case for running netclient in container.
![image](https://user-images.githubusercontent.com/32648129/148622732-a8fe8c54-534b-4ae0-b0d2-a5e8a1a7b77a.png)

**Comment by lnhrdt** [comment]
Thanks @mattkasun! Your perspective is helpful – I'm still learning netmaker and understanding its architecture.

I'm interested in running a containerized version of the client because I'm managing the rest of my infrastructure on kubernetes. I find that it helps me automate patching and upgrades, as well as version control all of my configuration. And at this point it's just the most familiar/comfortable approach to me. I was trying to follow your kubernetes documentation here to setup my client nodes:
https://docs.netmaker.org/server-installation.html#netclient-daemonset

Do you still think I should consider a native install? Is there something about the way netmaker works that I might be missing?

**Comment by mattkasun** [comment]
@lnhrdt my knowledge of kubernetes is limited. You may very well have a valid usecase.

**Comment by lnhrdt** [comment]
@afeiszli I see that you're the primary contributor on the [netmaker k8s templates](https://github.com/gravitl/netmaker/tree/master/kube). Any thoughts here on if it's worthwhile to get the netclient container running on arm64 like the rest of netmaker's containers? Or am I barking up the wrong tree?

**Comment by 0xdcarns** [comment]
We will/should add it to the workflow. That image was sort of an after thought that happened to be necessary/helpful for some k8s setups and we just never added it the workflow officially.

**Comment by mattkasun** [comment]
arm64 container available -- has been tested on an oracle arm vps

![image](https://user-images.githubusercontent.com/32648129/148702783-b3a8bb77-30dc-4652-a7b0-4ca83eca6d0e.png)

**Comment by afeiszli** [comment]
@mattkasun  @lnhrdt are we good to close this?

**Comment by lnhrdt** [comment]
@afeiszli I haven't had a chance to test the netclient container yet but if you're eager to close the issue, no problem. If I run into any issues after digging in, I'll just reopen or open a new issue.

Thank you so much for your help @mattkasun and & @afeiszli!
