### ISSUE TITLE
Request: To change the license to AGPL

### ISSUE THREAD

**Issue by harishpillay** [gravitl/netmaker#597]
I understand the motivation of the current license of SSPL. I feel it would be better expressed in the AGPL and that would mean that the code is is truly FOSS compliant which, as it stands, SSPL is not.

**Comment by afeiszli** [comment]
We periodically review our decision on the licensing to see if another license makes more sense. I'll leave this open to allow others to comment with their thoughts.

**Comment by turicas** [comment]
It would be awesome to have a FLOSS-compliant license! The product is great but I have some contracts where only FLOSS can be deployed (I think any OSI-approved copylefted license will do the job).

**Comment by timwhite** [comment]
I was looking at netmaker vs a few other mesh wireguard services and won't be considering netmaker due to its SSPL licence. AGPL would be a fine licensee that's recognised as open source. Netmaker has more features than the other options I'm looking at, but a licence that prevents us from using it as it's not truely open.

**Comment by blitzcaster** [comment]
Your website mentioned open source, yet you're using a licensed that are not considered open source by both OSI and FSF. Would you mind changing your wording to "source-available" to avoid misleading people?

![screenshot](https://user-images.githubusercontent.com/29270388/198842751-2574ec21-e6d6-4e1d-9d2c-3d6efef15eb0.png)

**Comment by bartmathijssen** [comment]
I have to agree with the previous points made. I am really excited for Netmaker's future, but as long as Netmaker doesn't have a FOSS license, I am not willing to pull the trigger to use it to manage my whole network.

**Comment by DolevBaron** [comment]
I'll have to agree with the general consensus here - In my opinion, the current license restricts NetMaker's use cases and potential.
Shouldn't requiring the publication of any modified version of the original source code be enough? (without the same restriction for 3rd-party programs)

**Comment by ptman** [comment]
source available / fair code https://faircode.io/

**Comment by afeiszli** [comment]
Netmaker is now on the Apache-2.0 license :) closing.

https://github.com/gravitl/netmaker/blob/master/LICENSE.md
