### ISSUE TITLE
netmaker windows client default to panic

### ISSUE THREAD

**Issue by jonaspetersorensen** [gravitl/netmaker#599]
Client: [netclient.exe, v0.9.3](https://github.com/gravitl/netmaker/releases/tag/v0.9.3)
OS: Win10, Win11

## Bug

When attempting to run `netclient.exe` without any commands then the client will panic,

```
panic: runtime error: index out of range [0] with length 0

goroutine 1 [running]:
github.com/gravitl/netmaker/netclient/command.getWindowsInterval()
        C:/Windows/Temp/netmaker/netclient/command/commands.go:75 +0x8f
github.com/gravitl/netmaker/netclient/command.RunUserspaceDaemon()
        C:/Windows/Temp/netmaker/netclient/command/commands.go:91 +0x67
main.main()
        C:/Windows/Temp/netmaker/netclient/main.go:35 +0x10f
```

This was quite confusing and made us believe for a long time that the client was broken.

Running the client with any command works just fine.
Example: `netclient.exe help` will return the proper help message.

## Suggested fix

When a user run `netclient.exe` without any commands then make it default to `netclient.exe help`

**Comment by afeiszli** [comment]
This sounds like a reasonable fix, adding to triage.

**Comment by afeiszli** [comment]
running without a command now pops up with the GUI (as of 0.14.0), closing.
