### ISSUE TITLE
When the netmaker's CLIENT_MODE turned off，the "UDP Hole Punching" can not work well, because of the node's Listen Port can not be updated.

### ISSUE THREAD

**Issue by MitchellJo** [gravitl/netmaker#606]
My Netmaker Server used Docker Compose Install.
And I turned off the netmaker's ```CLIENT_MODE```, because I don't want the Server run its own client.

Everything work well but the "UDP Hole Punching".

Then, I check the client's wg setting, and it seems the ```Listen Port``` can not updated to netmaker, but the ```Endpoint``` can.

And then, I check the installation, the difference of my ```compose.yml``` and the [official's](https://github.com/gravitl/netmaker/blob/master/compose/docker-compose.yml) is ```CLIENT_MODE```.

So, I turn on the netmaker's ```CLIENT_MODE```, restart the docker, and, it work!

It seems if the netmaker server do not run its own client, the CoreDNS or the "UDP Hole Punching" can not work well.

- version
  - netmaker : v0.9.3
  - netclient : v0.9.3

**Comment by cx9208** [comment]
yes i found it in https://docs.netmaker.org/getting-started.html#create-a-network

**Comment by MitchellJo** [comment]
> yes i found it in https://docs.netmaker.org/getting-started.html#create-a-network

😂 Well, it's my fault that I didn't read the document carefully.
