### ISSUE TITLE
Hub/Concentrator (Wireguard support)

### ISSUE THREAD

**Issue by dragon2611** [gravitl/netmaker#62]
Might be worth looking into provisioning a Hub/Concentrator, whilst full mesh is nice there are instances where it might not work (Esp with NAT/Firewalls in the way)

If the allow list on the peers is setup correctly and forwarding is enabled on the "Hub/concentrator" then it should be possible to generate a hybrid setup where you could for instance have servers in a mesh but a client gateway, It should then be possible to generate a static config for the standard wireguard client for things like windows/mobile clients.

**Comment by afeiszli** [comment]
We're roadmapping a "relay server" mode which will do what you are envisioning. I haven't set it in a version yet but it should be in by v0.3 or  v0.4 (either 3 or 5 weeks from now).

In the next iteration, v0.2, we are adding a "gateway mode" for accessing private networks. Depending on the way  we set it up you may  be able  to use it for that as well.

**Comment by afeiszli** [comment]
@dragon2611 please check out the tutorial video we have released for setting up gateways. Does this accomplish what you need?
https://youtu.be/krCKBJhwwDk

**Comment by afeiszli** [comment]
Closing, as in v0.5 we introduce "ingress gateways" which accomplishes this functionality.
