### ISSUE TITLE
Unable to join networks on Windows

### ISSUE THREAD

**Issue by ethanfowler** [gravitl/netmaker#623]
Was able to join a network on Windows, but other nodes were unable to ping the Windows node, despite all firewalls being off. Removed the Windows node from the network in an attempt to re-add it as a fix, and now the Windows machine cannot join any networks. The output is as follows:
```
netclient.exe join -t <key>
2022/01/18 10:26:43 Gravitl Netclient on Windows started
2022/01/18 10:26:43 [netclient] joining haptx1 at grpc.nm.<domain>.com:443
2022/01/18 10:26:43 [netclient] error installing: rpc error: code = Unavailable desc = connection error: desc = "transport: authentication handshake failed: EOF"
2022/01/18 10:26:43 Failed to authenticate: rpc error: code = Unauthenticated desc = Something went wrong with Auto Login: rpc error: code = Unavailable desc = connection error: desc = "transport: authentication handshake failed: read tcp 192.168.1.56:49606-><netmaker-public-ip>:443: wsarecv: An existing connection was forcibly closed by the remote host."
2022/01/18 10:26:43 [netclient] invalid CIDR address:
2022/01/18 10:26:43 [netclient] removed <network-name> network locally
```

We have tried:

- completely removing netclient, wireguard and retrying
- the powershell script
- restarting the netmaker server
- generating and using new keys
- a different network adapter (in case it was a duplicate MAC issue)

**Comment by afeiszli** [comment]
Which version are you running?

**Comment by ethanfowler** [comment]
Netmaker 0.9.1. We did try netclient 0.9.4 (latest), with the same result.

I've been hesitant to upgrade Netmaker and potentially lose established networks.

**Comment by ethanfowler** [comment]
Upgrading to 0.9.4 seemed to fix the issue.
