### ISSUE TITLE
Is it possible to add an Android device to the mesh?

### ISSUE THREAD

**Issue by danielkrajnik** [gravitl/netmaker#628]
Or does it need to go through a separate ingress gateway? Has it been considered or is it perhaps already on the roadmap?

**Comment by afeiszli** [comment]
At some point we will have an Android app, but it is much further down the roadmap. That is a high level of effort, and there is not a strong reason to need direct p2p from Android/iOS.

**Comment by danielkrajnik** [comment]
thank you for confirming that. Do you know by any chance any way Android devices can be configured behind NAT using wireguard or in any other way? If you happened to stumbled upon any such solution that would be really helpful.

**Comment by afeiszli** [comment]
Do you need to reach the Android directly behind the NAT, or is the Android reaching out from behind the NAT? If your Android is behind NAT but the Ingress is public (which it should be) then you will have no problem.

**Comment by danielkrajnik** [comment]
I was wondering if it's possible to have two Android devices behind two diffrent NATs that could communicate via a direct tunnel with a help of a STUN-like server helping them find their IP addresses and punch UDP holes in their NATs.

**Comment by afeiszli** [comment]
Ahhh I see, no that is not something we enable at this point. At some point in the future we will build Android/iOS apps and then it will work, but until then, direct p2p is not enabled for phones.

**Comment by danielkrajnik** [comment]
thanks again for confirming. In my case I'm trying to put Matrix server for a p2p instant messagner and just found out that they have rolled out [their onw p2p version](https://matrix.org/blog/2020/06/02/introducing-p-2-p-matrix). Not sure yet if it does NAT traversal, but can there be p2p without one?

**Comment by afeiszli** [comment]
You can have p2p without NAT traversal, it is just a very bad working p2p :) Sorry we are unable to support your use case at this time. I will update this issue whenever we get an Android client built.
