### ISSUE TITLE
Does Ingress gateway relay all packets like TURN or only points other node to like STUN?

### ISSUE THREAD

**Issue by danielkrajnik** [gravitl/netmaker#629]
Sorry if this is a wrong place for general questions, but does ingress gatway relay all the packets of external clients to nodes on the mesh or does it help establish direct connection between that external client and that ndoe on the mesh? 

I really hope not. It would turn it a hub-and-spoke model again. The reason why it would be useful, is because Android doesn't have any netclient available as far as I know. I think Tailscale has one though? Is there any reason not to support Android?

**Comment by afeiszli** [comment]
The Ingress gateway routes traffic directly, acting as a relay for "external clients." This is mainly to support devices that do not support the netclient. Netclient is p2p, but ext clients are hub-and-spoke via gateway.
