### ISSUE TITLE
Add the possibility for any oauth provider to be supported ( e.g.: authentik )

### ISSUE THREAD

**Issue by ranomier** [gravitl/netmaker#636]
I have my own single sign on with https://goauthentik.io/
I would like to be independent from other provider, so it would be awesome to just configure all the oauth variables.

Is this a thing that is possible?

Nice work, so far :) :D

**Comment by afeiszli** [comment]
Hi @ranomier, we would like to support something like authentik, but there are a few options which makes it a bit more difficult to decide:
- keycloak
- authelia
- auth0
- supertokens

Would like to hear some more community input. We're also very open to PR's if this is something anyone is open to tackling.

**Comment by ranomier** [comment]
Why not add a general option where you can add any oauth provider, many other projects do it like that. For example gitea.

**Comment by afeiszli** [comment]
That sounds pretty reasonable. We're not working on OAuth right now but we'll discuss it in our next roadmapping session.

**Comment by afeiszli** [comment]
Generic OIDC has been added in 0.14.5, closing.

**Comment by ranomier** [comment]
Noice!
