### ISSUE TITLE
Is MondoDB required?

### ISSUE THREAD

**Issue by patstrom** [gravitl/netmaker#638]
The [no-docker documentation](https://netmaker.org/server-installation.html#nodocker) mentions MongoDB in the "intro" but then it proceeds to install rqlite. MongoDB isn't really mentioned in the architecture documentation either.

Is MongoDB an old dependency? Should it be removed from the documentation altogether?

**Comment by afeiszli** [comment]
MongoDB is not required. Netmaker used MongoDB early on but that has been removed. We'll update the docs.

**Comment by patstrom** [comment]
Nice! Cheers
