### ISSUE TITLE
mipsle softfloat build?

### ISSUE THREAD

**Issue by deluxghost** [gravitl/netmaker#641]
use `GOMIPS=softfloat` when `go build` to support FPU emulator, this might fix issues for some device

https://stackoverflow.com/questions/55154143/golang-binary-not-running-on-mips

Edit: upx packaging does not work on my device either, I must enable softfloat and remove upx to get it works. I don't know what causes this, but I can help with testing.

**Comment by afeiszli** [comment]
@mattkasun thoughts on this?

**Comment by mattkasun** [comment]
netclient-linux-mips-hardfloat
netclient-linux-mips-softfloat
netclient-linux-mipsle-hardfloat
netclient-linux-mipsle-softfloat

are build for each release
