### ISSUE TITLE
allow changes to server listening addr

### ISSUE THREAD

**Issue by deluxghost** [gravitl/netmaker#643]
reason: I am trying to only serve http/grpc through a reverse proxy

**Comment by shizunge** [comment]
You can do it with traefik (and other reverse proxy I believe)
You do not need to use Caddy.
Here is an example https://github.com/bsherman/netmaker-traefik

**Comment by deluxghost** [comment]
> You can do it with traefik (and other reverse proxy I believe)
> You do not need to use Caddy.
> Here is an example https://github.com/bsherman/netmaker-traefik

isn't that still expose 8081 and 50051 on the host server?

**Comment by shizunge** [comment]
Ah, the example is still use `network_mode: host`. 

In my setup, I use docker network, and I set `CLIENT_MODE=off`. `network_mode: host` is only required if you are using  `CLIENT_MODE=on`.

I started my client manually on the host after netmaker server starts up, then connect it to the  netmaker server .

**Comment by shizunge** [comment]
Actually, you can already use env variable  `API_PORT: "8081"` and `GRPC_PORT: "50051"` to change the port.

**Comment by alcroito** [comment]
Hi.

It's not about changing port numbers, but rather not exposing the services to be accessible via the public host ip.

The linked https://github.com/bsherman/netmaker-traefik indeed does not expose the ports.

But when not using traefik (e.g. nginx or caddy) that doesn't seem currently possible.

It would be nice to allow specifying the listener address to 127.0.0.1, to avoid exposing the ports on the public network.

**Comment by afeiszli** [comment]
@alcroito @deluxghost  sIn the new docker compose, with Caddy, docker ports for api are no longer exposed publicly: https://github.com/gravitl/netmaker/blob/master/compose/docker-compose.contained.yml

thanks to @fersingb for this!

**Comment by alcroito** [comment]
> @alcroito @deluxghost In the new docker compose, with Caddy, docker ports for api are no longer exposed publicly: https://github.com/gravitl/netmaker/blob/master/compose/docker-compose.contained.yml
> 
> thanks to @fersingb for this!

Please re-read my last comment. It was already possible to limit the port when using non-host network mode. With host network mode, support would have to be added to the netmaker api service. docker-compose would not help.

**Comment by mattkasun** [comment]
netmaker no longer uses host mode
