### ISSUE TITLE
After creating a network, execute WG show. There is no network interface. 

### ISSUE THREAD

**Issue by Pinkpiglet** [gravitl/netmaker#650]
version: "3.4"

services:
  netmaker:
    container_name: netmaker
    image: gravitl/netmaker:v0.9.4
    volumes:
      - /etc/netclient/config:/etc/netclient/config
      - dnsconfig:/root/config/dnsconfig
      - /usr/bin/wg:/usr/bin/wg
      - /data/sqldata/:/root/data
    cap_add: 
      - NET_ADMIN
    restart: always
    privileged: true
    environment:
      SERVER_HOST: "xx.xx.xx.xx"
      SERVER_API_CONN_STRING: "xx.xx.xx.xx:8081"
      SERVER_GRPC_CONN_STRING: "xx.xx.xx.xx:50051"
      COREDNS_ADDR: "xx.xx.xx.xx"
      GRPC_SSL: "off"
      DNS_MODE: "on"
      SERVER_HTTP_HOST: "xx.xx.xx.xx:8081"
      SERVER_GRPC_HOST: "xx.xx.xx.xx:50051"
      API_PORT: "8081"
      GRPC_PORT: "50051"
      CLIENT_MODE: "on"
      MASTER_KEY: "FpWAuPFyxNRzdqsVUW02qydWx2vjmy"
      SERVER_GRPC_WIREGUARD: "off"
      CORS_ALLOWED_ORIGIN: "*"
      DISPLAY_KEYS: "on"
      DATABASE: "sqlite"
      NODE_ID: "netmaker-server-1"
    ports:
      - "51821-51830:51821-51830/udp"
      - "8081:8081"
      - "50051:50051"
  netmaker-ui:
    container_name: netmaker-ui
    depends_on:
      - netmaker
    image: gravitl/netmaker-ui:v0.9.3
    links:
      - "netmaker:api"
    ports:
      - "8082:80"
    environment:
      BACKEND_URL: "http://xx.xx.xx.xx:8081"
    restart: always
  coredns:
    depends_on:
      - netmaker 
    image: coredns/coredns
    command: -conf /root/dnsconfig/Corefile
    container_name: coredns
    restart: always
    ports:
      - "127.0.0.1:53:53/udp"
      - "127.0.0.1:53:53/tcp"
    volumes:
      - dnsconfig:/root/dnsconfig
volumes:
  sqldata: {}
  dnsconfig: {}
![20220128032446](https://user-images.githubusercontent.com/38532706/151429850-a98238f2-c49f-41f0-bd73-f43fd6a30f5c.png)
![20220128032459](https://user-images.githubusercontent.com/38532706/151429859-4d5d5a3d-9da3-472d-af72-39519e709713.png)

**Comment by Pinkpiglet** [comment]
![Uploading 20220128032906.png…]()

**Comment by afeiszli** [comment]
Hi, this is because by deafult, we do not use host networking on the server. That means the interface is inside of the netmaker server container, not on the host machine.

If you run "docker exec -it netmaker /bin/sh" and then run "wg show" you will see the interface.

**Comment by Pinkpiglet** [comment]
okay, thank you.
