### ISSUE TITLE
Routes not working, pings dropping, mac client issues after reboot.

### ISSUE THREAD

**Issue by kennyparsons** [gravitl/netmaker#661]
I successfully implemented the vanilla server from the quickstart using docker compose, just behind nginx. I can create networks, keys, and add nodes (but mac has issues on reboot - more on that later). 

However, the nodes cannot ping each other. I have 2 nodes added (10.100.1.2 and .3). The netclients are updated, even manually pulling configs down. The linux client shows the mac client in its routing table, using the netmaker interface. But pings to the other client on the network timing out. Even pings to itself are timing out. 

Not sure what to do here. For sake of testing, these two clients are even on the same physical network.

**Comment by afeiszli** [comment]
Hi @kennyparsons, please share your client version and Operating System.

There is a known bug for nodes on the same network if UDP Hole Punching is turned on, so I am guessing this is the issue. It uses the public IP and port rather than local, which can cause issues if they're on the same LAN.

**Comment by kennyparsons** [comment]
```
❯ sudo ./netclient -v
Netclient CLI version v0.9.4
```

OS: MacOS 12.1
Server: 0.9.4 (I think)

I say "I Think" because the UI is not working any more. It keeps asking me to create an admin, like this is the first time it's run. Logs don't show anything odd, but I cannot proceed. Even if trying to give in and create an admin user. Just says "cannot create user XYZ"

**Comment by kennyparsons** [comment]
Hi @afeiszli I'm still having issues with this, even with a client not on the same lan.

**Comment by kennyparsons** [comment]
I created a new network, added a client on the same LAN as the server (is this the problem?), made it an ingress gateway, added an external client to that gateway, and the device cannot ping either itself, the network gateway, or the external client.
