### ISSUE TITLE
docs: missing sentence?

### ISSUE THREAD

**Issue by jimt** [gravitl/netmaker#685]
Sentence contains `%` rather than first of two benefits of enabling **UDP Hole Punching**.

> This has two benefits. For one, it%. It also means, you dont usually have to worry about opening up the local firewall for ports (for instance, 51821).

https://github.com/gravitl/netmaker/blob/master/docs/_build/html/_sources/getting-started.rst.txt?plain=1#L38

**Comment by afeiszli** [comment]
please add docs issues to the docs repo here: https://github.com/gravitl/netmaker-docs/issues
