### ISSUE TITLE
Android: external client QR code fails

### ISSUE THREAD

**Issue by jimt** [gravitl/netmaker#686]
Attempting to use the QR code to add an Android WireGuard client (v1.0.20211029) fails with:
 **Unable to import tunnel: Unknown section in config**

Downloading the `.conf` file, transferring it to the phone, and adding the tunnel with **Import from file or archive** works as expected.

Using Docker images pulled 2022-02-06:
* UI: 0.9.3
* Server: 0.9.4

**Comment by afeiszli** [comment]
@jimt can you post the conf that gets created (without the identifying info). Would also be good to see the conf from a QR code vs the downloaded config.

**Comment by jimt** [comment]
Sorry for the noise.  Apparently, it is a function of my monitor and/or Pixel 6.  I've tried several more times this morning and about 50% of the time I can successfully scan the QR code and 50% of the time I get the **Unable to import tunnel** message.  I guess yesterday I was just unlucky and got 3 failures in a row before giving up and downloading the config manually.

**Comment by afeiszli** [comment]
huh we have had issues with the config files in the past, so feel free to re-open this if you see an issue!
