### ISSUE TITLE
Get error when using netclient

### ISSUE THREAD

**Issue by sihuan** [gravitl/netmaker#687]
I am using archlinux and I have netclient installed at `/usr/bin/netclient`.
When I run `netclient join -t <my token>` in my home directory (/home/sihuan) I get the following error
```text
2022/02/06 20:43:57 [netclient] joining SiHuanNet at grpc.xxx:443
2022/02/06 20:43:58 [netclient] node created on remote server...updating configs
2022/02/06 20:43:59 [netclient] retrieving peers
2022/02/06 20:43:59 [netclient] starting wireguard
2022/02/06 20:43:59 [netclient] writing wg conf file to: /etc/netclient/config/nm-SiHuanNet.conf
2022/02/06 20:43:59 stat /home/sihuan/netclient: no such file or directory
2022/02/06 20:43:59 [netclient] error installing: stat /home/sihuan/netclient: no such file or directory
2022/02/06 20:44:00 [netclient] removed machine from SiHuanNet network on remote server
2022/02/06 20:44:00 [netclient] removed WireGuard interface: nm-SiHuanNet
2022/02/06 20:44:00 [netclient] removed SiHuanNet network locally
2022/02/06 20:44:00 [netclient] removed systemd remnants if any existed
2022/02/06 20:44:01 [netclient] removed systemd remnants if any existed
```
I think this error is encountered when `netclient` is in the `PATH` and you don't run it with an absolute path.
To fix this I will submit a pull request.

**Comment by mattkasun** [comment]
@sihuan I am not sure if you were aware but running netclient join will install netclient (in /etc/netclient/ V0.9X or /sbin/ V.0.10) so there is no need to install it into /usr/bin. Just run netclient join with an absoute path ie. ./netclient join -t <token>

**Comment by sihuan** [comment]
> @sihuan I am not sure if you were aware but running netclient join will install netclient (in /etc/netclient/ V0.9X or /sbin/ V.0.10) so there is no need to install it into /usr/bin. Just run netclient join with an absoute path ie. ./netclient join -t

Yes, I know that running `netclient join` will install itself.
In fact this error occurs when copying from the current location of netclient to /etc/netclient/, which does not always get the current location correctly.
I prefer to have it as a software package managed by the package manager(for archlinux, `pacman`) rather than download&run, so I wrote a [PKGBUILD](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=netclient) for archlinux and it is installed in /usr/bin

**Comment by mattkasun** [comment]
Nice work on the pkgbuild. Did you consider including the systemd service and timer?

**Comment by sihuan** [comment]
I'm actually quite happy to include the service and timer in the package and not copy the extra binaries to /etc/netclient. But this would require changes to the program that might affect how it runs on other distributions. So write a patch just for archlinux ?  or change its default behavior that manual installation will require installing netclient and service &timer files to the specified location

**Comment by mattkasun** [comment]
suggest you wait for release of v0.10.0.  if your package installs the binary and service files in the correct locations, a subsequent join will skip the install step but still work on other distros.

**Comment by afeiszli** [comment]
@mattkasun can we close this?
