### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by thebaltee** [gravitl/netmaker#69]
When attempting to follow the instructions for install, "Pull this repo: git clone https://github.com/falconcat-inc/WireCat.git". the repo comes up as invalid..  Suggestions?

**Comment by afeiszli** [comment]
Pushed a  hotfix to the getting started docs. It says the right repo now (this one). https://github.com/gravitl/netmaker/blob/v0.1/docs/GETTING_STARTED.md

That said, I recommend using the Quick Start docs from the README in the  root of the repo (docker-compose up)
