### ISSUE TITLE
Missing gravitl/netclient:v0.9.4 Docker image

### ISSUE THREAD

**Issue by Jasz** [gravitl/netmaker#694]
The newest versions I see are [latest](https://hub.docker.com/layers/gravitl/netclient/latest/images/sha256-766eb2c90d3cf893177e66d0b9b092ec7d662d4ea374ac3a4dc4eafa9a7d701e?context=explore) and [v0.9.3](https://hub.docker.com/layers/gravitl/netclient/v0.9.3/images/sha256-de96657f207679f2c4cec311963b6ad8c1f11e70f8a623ac68c2ee0e805b8332?context=explore).

When trying to pull v0.9.4 I'm getting

```
Pulling netclient (gravitl/netclient:v0.9.4)...
ERROR: manifest for gravitl/netclient:v0.9.4 not found: manifest unknown: manifest unknown
```

**Comment by cardinalfan1** [comment]
In addition to this, the command provided for docker netclient is not working:

`docker run -d --network host  --privileged -e TOKEN=<token>`

**Comment by cardinalfan1** [comment]
I take that back, the 0.9.3 image is working fine for me currently, just the 0,9.4 image not available

**Comment by mattkasun** [comment]
images are on docker hub now
