### ISSUE TITLE
gravitl/netmaker:v0.9.4-kube /root/netclient: not found

### ISSUE THREAD

**Issue by nrukavkov** [gravitl/netmaker#695]
Hello, the last version for k8s `v0.9.4-kube` doesn't work fine. I suppose something wrong with Dockerfile. I looked at version 0.8.4-kube and there was nothing about entrypoint netclient. But in 0.9.4-kube there is `netclient` set as entrypoint.

```
netmaker-0                                       0/1     CrashLoopBackOff    1          18s
netmaker-1                                       0/1     CrashLoopBackOff    1          11s
```

```
bash-3.2$ kubectl logs netmaker-0 --namespace=charts
./entrypoint.sh: line 14: /root/netclient: not found
[netclient] joining network
Failed to join, quitting.
```

**Comment by afeiszli** [comment]
Please upgrade to v0.14.5 or later, which has resolved issues with k8s netclient and netmaker images (use the regular gravitl/netclient:v0.14.5 image rather than with the -kube tag)
