### ISSUE TITLE
Cannot docker into lxc instance

### ISSUE THREAD

**Issue by CICCIOSGAMINO** [gravitl/netmaker#73]
I cannot install netmaker through the docker-composer into lxc instance, every time i get these errors:

Starting mongodb ... error

ERROR: for mongodb  Cannot start service mongodb: OCI runtime create failed: container_linux.go:349: starting container process caused "process_linux.go:449: container init caused \"rootfs_linux.go:58: mounting \\\"proc\\\" to rootfs \\\"/var/snap/docker/common/var-lib-docker/overlay2/2c57334a4eefe5643b04ad0c34a349b75f3651f4a0a5c8bc10661e01f06bb072/merged\\\" at \\\"/proc\\\" caused \\\"permission denied\\\"\"": unknown

ERROR: for mongodb  Cannot start service mongodb: OCI runtime create failed: container_linux.go:349: starting container process caused "process_linux.go:449: container init caused \"rootfs_linux.go:58: mounting \\\"proc\\\" to rootfs \\\"/var/snap/docker/common/var-lib-docker/overlay2/2c57334a4eefe5643b04ad0c34a349b75f3651f4a0a5c8bc10661e01f06bb072/merged\\\" at \\\"/proc\\\" caused \\\"permission denied\\\"\"": unknown
ERROR: Encountered errors while bringing up the project.

**Comment by afeiszli** [comment]
Hi @CICCIOSGAMINO, LXC  is not currently a supported platform for  the project. If you would like to install on LXC, I recommend  running the  mongodb, server binary, and static frontend  files directly inside of LXC as opposed to using docker. We will have docs for doing this in our next release. See #50

**Comment by CICCIOSGAMINO** [comment]
> Hi @CICCIOSGAMINO, LXC is not currently a supported platform for the project. If you would like to install on LXC, I recommend running the mongodb, server binary, and static frontend files directly inside of LXC as opposed to using docker. We will have docs for doing this in our next release. See #50

Thanks !!

**Comment by afeiszli** [comment]
@CICCIOSGAMINO We now have instructions for running a non-docker installation, which can be found here: https://github.com/gravitl/netmaker/blob/master/docs/USAGE.md#non-docker-installation. This is also referenced in issue #50. I'm going to close this issue for now but if you continue running into LXC issues, feel free to re-open or submit a new ticket if you run into different issues.
