### ISSUE TITLE
network does not initialize after reboot

### ISSUE THREAD

**Issue by majoragee** [gravitl/netmaker#744]
Version: 0.10.0

I have three Ubuntu 20.04-based hosts that are not re-establishing a connection after a reboot.

```
journalctl -u netclient

-- Reboot --
Feb 11 21:10:39 host systemd[1]: Started Netclient Daemon.
Feb 11 21:10:39 host netclient[1464]: 2022/02/11 21:10:39 [netclient] netclient go routine started for xnet
Feb 11 21:10:39 host netclient[1464]: 2022/02/11 21:10:39 [netclient] daemon started for network: xnet
```

Immediately after reboot, `netclient list` returns the correct config, but `wget show` returns nothing.  Everything starts working after a manual checkin. 

```
sudo netclient checkin
2022/02/11 21:11:10 [netclient] running checkin for all networks
2022/02/11 21:11:10 [netclient] failed to parse interface
2022/02/11 21:11:10 [netclient] waiting for interface...
2022/02/11 21:11:10 [netclient] interface ready - netclient.. ENGAGE
2022/02/11 21:11:11 [netclient] checked in successfully for xnet
```

**Comment by majoragee** [comment]
0.10.0 using the script to install netclient and join the network

**Comment by afeiszli** [comment]
This should no longer be a problem as of 0.14.0. We run a pull on daemon startup so WireGuard will always get started. Feel free to reopen if you are still experiencing this issue.
