### ISSUE TITLE
Suddenly can not join a network. 

### ISSUE THREAD

**Issue by thelittlerocket** [gravitl/netmaker#745]
network 0.10.0
Netclient CLI version dev

I just start from scratch yesterday with 0.10.0 and everything seems to work fine, add a couple of servers to a network without issues, but now when I try to add a new server to the same or another network, it won't let me, I got error messages as follow, it happens on the same server which was joined the same network yesterday with success, if I leave a network and try to re-join to the same network, it will also fail.

Both Debian and Ubuntu with the same result
```
Distributor ID:	Debian
Description:	Debian GNU/Linux 9.13 (stretch)
Release:	9.13
Codename:	stretch
```
```
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.6 LTS
Release:	18.04
Codename:	bionic
```

Error Message
```
2022/02/12 14:46:07 [netclient] joining default at grpc.mydomain.com:443
2022/02/12 14:46:07 [netclient] error installing: rpc error: code = Unknown desc = error: node traffic key is nil
2022/02/12 14:46:08 Failed to authenticate: rpc error: code = Unauthenticated desc = Something went wrong with Auto Login: rpc error: code = Unknown desc = no result found
2022/02/12 14:46:08 [netclient] removed default network locally
2022/02/12 14:46:08 [netclient] removed systemd remnants if any existed
2022/02/12 14:46:09 [netclient] removed systemd remnants if any existed
```

**Comment by majoragee** [comment]
I encountered this last night as well, also on a network where the same command worked fine just hours earlier.  I'm not sure what the issue is, but I was able to download netclient manually and use  `netclient join`  to successfully join the network.

**Comment by afeiszli** [comment]
@thelittlerocket how did you run your client install, did you use the install script? We have a bug right now where the script will point to the wrong release version, which would cause this issue. That's why @majoragee was able to successfully join by downloading the correct netclient directly. We are working to patch this right now.

If you installed using some method other than the "curl ... netclient-install.sh" script, then we may have to further investigate.

**Comment by afeiszli** [comment]
The server image should currently be working, so if you re-pull the image it should work fine. However we are testing out the automation workflow today so be forewarned that it could revert.

**Comment by thelittlerocket** [comment]
Hi @afeiszli 
I manually pull down the netclient 0.10.0 binary and it works now.
I saw that the pre-defined script when access keys have been generated, the VERSION is vdev, if using 0.10.0 then it will work without error.

Thanks,
