### ISSUE TITLE
docker netclient option not working

### ISSUE THREAD

**Issue by cardinalfan1** [gravitl/netmaker#747]
One of the options presented for access keys thru the netmaker ui is thru docker:

`docker run -d --network host  --privileged -e TOKEN=<token> -v /etc/netclient:/etc/netclient --name netclient gravitl/netclient:vv0.10.0`

First, I think there is a typo in the tag, should be v0.10.0

Second, when this is run, it seems to run an instance of netmaker? When I run 

`docker logs netclient`

The following output is given

```
[netmaker] 2022-02-12 16:35:53 connecting to sqlite 
[netmaker] 2022-02-12 16:35:54 database successfully connected 
[netmaker] 2022-02-12 16:35:54 no OAuth provider found or not configured, continuing without OAuth 
[netmaker] 2022-02-12 16:35:54 Agent Server successfully started on port  50051 (gRPC) 
[netmaker] 2022-02-12 16:35:54 REST Server successfully started on port  8081  (REST) 
[netmaker] 2022-02-12 16:35:54 connecting to mq broker at <ip>:1883
```

Thanks for the help!

**Comment by afeiszli** [comment]
There's an error in the workflow that cause the server image to be pushed to the client tag in the latest release, I've just pushed a client image so if you re-pull it should work. 

That said, we're testing out the workflow as we speak so if it fails, it may push the old tag again; should be stable by the end of the day.

**Comment by cardinalfan1** [comment]
Thanks!
