### ISSUE TITLE
error in 'VERSION=vv0.10.0' client install string 

### ISSUE THREAD

**Issue by carebare47** [gravitl/netmaker#756]
Hi, 

I ran the following on an aws ubuntu20.04 VM: `wget -qO - https://raw.githubusercontent.com/gravitl/netmaker/master/scripts/nm-quick.sh | sudo bash`

When this finished, I accessed the dashboard at `https://dashboard.nm.<my-public-ip>.nip.io/`, went to 'Access Keys' and then 'defaultkey'

The client install command from the dashboard looks like this:
`curl -sfL https://raw.githubusercontent.com/gravitl/netmaker/master/scripts/netclient-install.sh | VERSION=vv0.10.0 KEY=.....`

This client install line doesn't work for me, unless I change `VERSION=vv0.10.0` to `VERSION=v0.10.0`

This issue isn't blocking me (easy local fix), just wanted to make sure you were aware of it

Thanks,
Tom

**Comment by afeiszli** [comment]
Apologies, we're working on some conflicts between the automation workflow and versioning. I just pushed up a new server image that will work while we're sorting it out. Here are the steps to fix your system:

    1.  docker kill netmaker
    2.  docker rm netmaker
    3.  docker pull gravitl/netmaker:v0.10.0
    3.  docker-compose up -d

**Comment by 0xdcarns** [comment]
It's possible the non hotfixed version of UI is still on docker hub, so I've just re run the workflow to correct it, it should be available to re-pull in about 40 min.

**Comment by carebare47** [comment]
Great, problem solved, thanks all
