### ISSUE TITLE
Issue in reaching web endpoints when in network

### ISSUE THREAD

**Issue by cardinalfan1** [gravitl/netmaker#757]
When inside a network and trying to reach the web endpoint, e.g. `dashboard.netmaker.example.com`... this is unreachable if the netmaker node is also an egress gateway for the internet, i.e. `0.0.0.0/0`. May be a hairpinning issue?

**Comment by afeiszli** [comment]
0.0.0.0/0 will not work currently with Netmaker, please check out this documentation: https://docs.netmaker.org/egress-gateway.html#vpn-nat-gateway
