### ISSUE TITLE
resolvectl in gravitl/netclient:v0.9.3

### ISSUE THREAD

**Issue by codot-fr** [gravitl/netmaker#759]
Hello,

I'm using gravitl/netclient:v0.9.3 as a sidecar on a kubernetes pod to join the pod to a netmaker network. I tried to activate DNS on the node config from the Netmaker UI but it fails has resolvectl is not built in the image. Is this intentional?

Thanks

2022/02/14 14:22:51 exec: "resolvectl": executable file not found in $PATH
2022/02/14 14:22:51 WARNING: resolvectl not present. Unable to set dns. Install resolvectl or run manually.
2022/02/14 14:22:52 [netclient] checked in successfully for SPINE

**Comment by afeiszli** [comment]
resolvectl dependency has been removed as of 0.12.0
