### ISSUE TITLE
[BUG] Changing the range of a network make the server reset its ip to the wrong one

### ISSUE THREAD

**Issue by Belphemur** [gravitl/netmaker#782]
When doing a range update on a network, all the node get a new IP.
The server is expected to always get the last IP of the range. It doesn't.

This cause reachability issue where the clients can't connect to the server.

# Step
* Create a network: 10.42.0.0/24
	*  Server has the IP 10.42.0.254/24
* Change the range of the network: 10.0.42.0/24
	* Server has the IP 10.0.42.1

**Comment by afeiszli** [comment]
The code has been refactored and this should no longer be an issue as of 0.13.0. Tested on 0.14.0.
