### ISSUE TITLE
Feature: Optionally email users updated WireGuard configuration

### ISSUE THREAD

**Issue by schmorrison** [gravitl/netmaker#787]
Proposal: Admin can define parameters for an outbound SMTP Email/Password configuration, and an email address for each device that is configured on the network. When device credentials are changed an email can be sent to each relevant email address with the appropriate configuration file as attachment or QR Code and possibly instructions.

--------------------

I would like to try providing this PR, but was hoping to get some insight into an appropriate entry point for such a feature.

Thanks and best regards,

Schmorrison

**Comment by afeiszli** [comment]
We'd welcome a community feature for this, but this is out of scope for us to build into the community version ourselves.
