### ISSUE TITLE
Rebranding Incomplete

### ISSUE THREAD

**Issue by mattkasun** [gravitl/netmaker#8]
Repo still contains references to meshclient and wirecat

[grep_output.txt](https://github.com/gravitl/netmaker/files/6211018/grep_output.txt)

**Comment by afeiszli** [comment]
Though it will break existing implementations when we do change it...

**Comment by afeiszli** [comment]
I guess better to do earlier before more people run real workloads on it

**Comment by afeiszli** [comment]
Fixed in PR #57
