### ISSUE TITLE
`netclient daemon` does not respond to a request to change a client's listening port 

### ISSUE THREAD

**Issue by vitex** [gravitl/netmaker#805]
I created a v0.10.0 network `test24` with `Address Range (IPv4)` set to `10.24.0.0/24`, `Default Listen Port` set to `51821`, and `UDP Hole Punching` set to `off`. I performed a manual `netclient join` to add a client node, started `netclient daemon` in a terminal window, and then used the dashboard to change that client node's `Listen Port` to `50024`.

A log message from `netclient daemon` reported that it had received a message to update the client node, but the node's `Listen Port` as reported by `wg show` did not change to `50024` until I executed 'netclient checkin` several minutes later. Thus `netclient daemon` is not a complete replacement for calling `netclient checkin` periodically.

**Comment by afeiszli** [comment]
fixed in v0.11.0
