### ISSUE TITLE
Unable to login after docker server reboots/crashes

### ISSUE THREAD

**Issue by zholbrook** [gravitl/netmaker#82]
After my docker server reboot due to a network driver failure I was unable to login to the UI once services were restored.

**Comment by afeiszli** [comment]
Can you please provide any logs?

**Comment by afeiszli** [comment]
And did the UI / developer console display any error?

**Comment by afeiszli** [comment]
@zholbrook any updates here? If not we will need to close this.

**Comment by zholbrook** [comment]
I was unable to find any logs, but my host became unable to contact its default route and I ended up having to reboot to fix the issue.
