### ISSUE TITLE
Error installing client on OPNSense

### ISSUE THREAD

**Issue by Ixian** [gravitl/netmaker#836]
After reading Netmaker now supports FreeBSD & OPNSense I installed Netmaker on a Digital Ocean droplet per instructions. When it successfully completed it output client strings for me to use however I cannot get it to work on OPNSense.

When I run the command:

`curl -sfL https://raw.githubusercontent.com/gravitl/netmaker/master/scripts/netclient-install.sh | sudo KEY=myuniqueprivatekeystring sh -`

It runs through the checks, tells me it is connecting to the default service (which appears correct) then the following error is output:

`[netclient] error installing: rpc error: code = Unknown desc = error: node traffic key is nil
2022/02/23 13:29:39 Failed to authenticate: rpc error: code = Unauthenticated desc = Something went wrong with Auto Login: rpc error: code = Unknown desc = no result found
`

Am I missing steps? What I'd like to do is have a site-to-site tunnel between my OPNSense Firewall and my Netmaker droplet and have clients connect to the droplet and in turn access my internal network behind OPNSense. Any pointers?

**Comment by Ixian** [comment]
Update - I just generated a new token and was able to connect with that. 

I am getting errors now when I try to create egress or ingress gateways with my Opnsense instance - it says "FreeBSD is not supported for <>". Is it not possible to create a tunnel to a BSD/OPNSense install for external clients?

**Comment by 0xdcarns** [comment]
Right now we only do egress on linux machines. In the future we may support other unix OS types. To get around it in the meantime, you could manually add rules to route traffic to a CIDR and then update the allowed IPs section of the node with those CIDRs potentially. (Not tested, just a suggestion)
