### ISSUE TITLE
Failed to create access key

### ISSUE THREAD

**Issue by gkl1368** [gravitl/netmaker#837]
On version 0.11.0, when I want to create access key, it always show
<img width="393" alt="image" src="https://user-images.githubusercontent.com/12904884/155492232-dd370dcf-21a4-4e3b-b41b-b7f3e22f0d26.png">

**Comment by afeiszli** [comment]
Was this an upgrade or a fresh install? And do you have a comms network in your dashboard? Please provide as much information as possible.

**Comment by gkl1368** [comment]
> Was this an upgrade or a fresh install? And do you have a comms network in your dashboard? Please provide as much information as possible.

It's a fresh install, and this occurs after I create a network and then to get access key to allow client join the network.

**Comment by 0xdcarns** [comment]
Did you install via the `nm-quick.sh` script? If not, please make sure your env variables/config matches the required ones in the latest docker-compose.contained.yml and restart your netmaker server after doing so. It should auto generate a comms network, but it seems your instance did not.

**Comment by gkl1368** [comment]
> Did you install via the `nm-quick.sh` script? If not, please make sure your env variables/config matches the required ones in the latest docker-compose.contained.yml and restart your netmaker server after doing so. It should auto generate a comms network, but it seems your instance did not.

I install with docker and config all env variables. You mean I need restart netmaker after create a network?

**Comment by 0xdcarns** [comment]
No, it should have created it. But I may try a `docker restart netmaker` and you should see in the logs in the beginning if it created the comms network or not. If not I would attempt the `nm-quick.sh` on another machine (if possible) and compare the differences in the environments.

**Comment by gkl1368** [comment]
> No, it should have created it. But I may try a `docker restart netmaker` and you should see in the logs in the beginning if it created the comms network or not (`docker logs netmaker`). If not I would attempt the `nm-quick.sh` on another machine (if possible) and compare the differences in the environments.

<img width="1298" alt="image" src="https://user-images.githubusercontent.com/12904884/155688369-c1be60cd-6a44-4faa-b989-833fe6c5265b.png">
this is a log of netmaker

**Comment by gkl1368** [comment]
I found the problem, the auto generate comm network is miss netid, this is I use api to get information of nodes.
<img width="797" alt="image" src="https://user-images.githubusercontent.com/12904884/155702745-7646b82f-b082-431b-addc-bf0f4a46ff07.png">

**Comment by 0xdcarns** [comment]
Would you mind sharing your compose file (with any sensitive data removed) or more setup information?

**Comment by 0xdcarns** [comment]
Nevermind, I was just shown your configuration. You need to run with CLIENT_MODE=on and PORT_FORWARD_SERVICES should be `"mq,ssh"`, not `"mq.ssh"`

**Comment by gkl1368** [comment]
after turn on client_mode, it worked. Thakns.
