### ISSUE TITLE
Docker image gravitl/netclient:v0.11.0 not working on arm64

### ISSUE THREAD

**Issue by daveterra** [gravitl/netmaker#838]
Following error is produced: 

> netclient   | [netclient] joining network
> netclient   | /root/netclient: line 1: ELF: not found
> netclient   | /root/netclient: line 1: syntax error: unexpected end of file (expecting ")")
> netclient   | Failed to join, quitting.

**Comment by TheNexter** [comment]
I confirm same with Pi4 with pi os lite complet clean install + docker
