### ISSUE TITLE
Netmaker server can't pull update to node but...

### ISSUE THREAD

**Issue by Neptunespace** [gravitl/netmaker#841]
**Netmaker version for this problem :**

- Netmaker 0.10.0
- Netmaker 0.11.0

I add my node, every node working perfectly but after ~ 5 minutes every node exept the main node running by default go in warning

<img width="1166" alt="image" src="https://user-images.githubusercontent.com/93327314/155985747-3fa4d85a-c00c-4e11-b7ae-ec480d54a775.png">

**My main server test :**

- I have try on aws > full port open no firewall > same problem
- Dedicated server > full port open no firewall > same problem

**My client :**
Always same problem with every client

- raspberry pi 4 (no docker client)
- dedicated x86 server full port open in ubuntu 20.04 LTS (docker version of client and not docker version)
- AWS server full port open in ubuntu 20.04 LTS (docker version of client and not docker version)

**Log for netmaker server :**

```
[netmaker] 2022-02-28 12:37:44 error decrypting when updating node  dbe53f5d-6ea2-45a0-97c5-fabc2131c198 recieved invalid message from broker [] 
[netmaker] 2022-02-28 12:37:44 error decrypting when updating node  07c30d8a-7678-4ffa-aa25-eb849a922bcb recieved invalid message from broker [] 
[netmaker] 2022-02-28 12:38:26 error decrypting when updating node  692bd74e-4358-44b9-9294-d1b2819867cb recieved invalid message from broker [] 
[netmaker] 2022-02-28 12:38:27 error decrypting when updating node  bd458269-c8df-4a89-b72a-1d45da1274d0 recieved invalid message from broker []
```

I can push update manual in the node with the command > netclient pull
After i push my node back to blue but 5 minutes after back to warning because server can't pull update to node it self 🙁

**Comment by schemen** [comment]
I seem to run into the same issue. Simple mostly default "Quick-Install" installation

**Comment by TheNexter** [comment]
Same here to
I have try with the "manual" version installation with the documentation and the "automatic" script with my domain settings no more

**Comment by 0xdcarns** [comment]
The docker netclient is not currently stable and will be fixed (likely) later this week

**Comment by TheNexter** [comment]
> That is your "comms" network which all the message queue updates go over with the server. This way your networks can achieve consensus uninterrupted, whereas in 0.10.0 if you made a network wide change or tried to update your public key, your network connections would break. This is sort of a stepping stone for us, where in the future all connections will go over your WG port and then you only have to expose a single udp port to connect to your server.

Ohhh ok, nice feature :)

Your project is super nice men, thx 🙏

**Comment by cpdeethree** [comment]
I'm still getting this issue in v0.12.1 of the netclient.

**Comment by afeiszli** [comment]
> I'm still getting this issue in v0.12.1 of the netclient.

What OS?

**Comment by cpdeethree** [comment]
two netclient nodes running on DOKS - so Ubuntu. Here are some logs from Netmaker server

```bash
netmaker       | [netmaker] 2022-03-26 13:39:28 error decrypting when updating node  d814e2cc-cfee-4c30-a3a4-a3cc3bc31073 recieved invalid message from broker [] 
mq             | 1648301968: Client CnIrivYVARDbHTwkzbjBOhx disconnected.
mq             | 1648301996: New connection from *snip*:51692 on port 1883.
mq             | 1648301996: New client connected from *snip*:51692 as fniNKQwJnZekcGjPNvpPNAz (p2, c1, k30).
netmaker       | [netmaker] 2022-03-26 13:39:56 error decrypting when updating node  04624e2c-57e1-4a48-9829-1cab6a375f92 recieved invalid message from broker [] 
mq             | 1648301996: Client fniNKQwJnZekcGjPNvpPNAz disconnected.
mq             | 1648301996: New connection from *snip*:51694 on port 1883.
mq             | 1648301996: New client connected from *snip*:51694 as ySSaosCxQxUkoqVAArZqpdJ (p2, c1, k30).
netmaker       | [netmaker] 2022-03-26 13:39:56 error decrypting when updating node  d814e2cc-cfee-4c30-a3a4-a3cc3bc31073 recieved invalid message from broker [] 
mq             | 1648301996: Client ySSaosCxQxUkoqVAArZqpdJ disconnected.
```

It's the same problem as OP/others have been having. On initial bootstrap the clients join fine, no errors, then about 5 minutes later or sometimes a bit longer they shift to error state and start throwing this.

**Comment by cpdeethree** [comment]
After upgrating to netmaker v0.12.1 this issue is no longer occurring on my nodes.

**Comment by afeiszli** [comment]
Since the comms network is no longer a feature in 0.14.0 and this issue is linked to the comms network setup, I'm going to close this for now. If users are still experiencing this in 0.14.0, e will track this via #999
