### ISSUE TITLE
Stopping the docker netclient does not stop wg

### ISSUE THREAD

**Issue by schemen** [gravitl/netmaker#843]
## Issue
I want to stop the netclient container to stop the wg tunnels for now. 

`docker stop netclient`

Doing so leaves the wireguard tunnels open and running.

## Quick fix
I can run  `wg-quick down /etc/netclient/config/nm-<ID>.conf` to shut it down. It would be nice if a stop procedure of the docker client does this as well.

**Comment by afeiszli** [comment]
fixed with #1139
