### ISSUE TITLE
windows leave node after the configuration is not deleted, can not rejoin the node

### ISSUE THREAD

**Issue by QZAiXH** [gravitl/netmaker#846]
netclient、netmaker：0.11.0
. \netclient.exe leave -n com is successful, but the configuration is still there when wg show
![image](https://user-images.githubusercontent.com/23068780/156091970-902f81a0-343c-4f88-9001-4b3eb5e6c1af.png)

When I rejoin node it will not do
![image](https://user-images.githubusercontent.com/23068780/156092178-88a0452c-60d3-46d6-9e7e-6e27a1936859.png)

**Comment by afeiszli** [comment]
This should be fixed as of 0.14.0
