### ISSUE TITLE
Ext Client to CIDR not routing on Ingress/Egress node behind NAT.

### ISSUE THREAD

**Issue by schmorrison** [gravitl/netmaker#847]
I have the network below, version 0.10.0. The drawn blue line shows a set of external clients that can access CIDR from main netmaker server node (GCP). The drawn red line shows a set of external clients that cannot access the same CIDR from Ingress/Egress node which is the owner of the CIDR records.

The Ingress/Egress node is behind CG-NAT, I believe the router is allocated an ipv4 by the ISP (I don't believe the endpoint IP has ever changed, maybe this is logged somewhere). NAT-holepunching is enabled network wide. I'm nervous to tamper with the default settings (ie MTU) because the tunnel from the main netmaker server is functional, seeming to indicate that the IP/port is accessible from WAN.

![image](https://user-images.githubusercontent.com/17385251/156231388-59cf6461-53cc-406a-84bf-51af75244f08.png)

**Comment by afeiszli** [comment]
Hi @schmorrison, trying to understand your diagram more fully, is the extent of the issue just the 1 ext client (with red line) unable to access 1 egress gateway (other red line)?

**Comment by schmorrison** [comment]
Hi @afeiszli unfortunately the entire set of ext clients associated with that node seem to have the same problem, similarly the entire set of ext clients of the main netmaker-1 node function properly.

**Comment by schmorrison** [comment]
@afeiszli V0.12.2 fixes this?

**Comment by afeiszli** [comment]
Hi @schmorrison are you still experiencing this issue? Ext clients should get all egress gateways in their AllowedIPs

**Comment by mattkasun** [comment]
@schmorrison have you had a chance to try with a newer version?

**Comment by mattkasun** [comment]
Closing as no response received.
