### ISSUE TITLE
I con't join the network on OpenWRT because of an error

### ISSUE THREAD

**Issue by 18984002666** [gravitl/netmaker#851]
2022/03/03 04:44:22 [netclient] joining home at <PublicIP>:50051
2022/03/03 04:44:22 [netclient] error installing: rpc error: code = Unknown desc = Key: 'Node.MacAddress' Error:Field validation for 'MacAddress' failed on the 'macaddress_unique' tag
2022/03/03 04:44:22 Failed to authenticate: rpc error: code = Unauthenticated desc = Something went wrong with Auto Login: rpc error: code = Unknown desc = missing mac address
2022/03/03 04:44:22 [netclient] could not flush peer routes when leaving network, home
2022/03/03 04:44:22 [netclient] removed home network locally
2022/03/03 04:44:23 [netclient] removed systemd remnants if any existed
2022/03/03 04:44:23 [netclient] removed systemd remnants if any existed

**Comment by xcf13363175** [comment]
same error

**Comment by 18984002666** [comment]
Now，the error is:

2022/03/03 23:57:46 [netclient] joining work <PublicIP>:50051
2022/03/03 23:57:46 [netclient] node created on remote server...updating configs
2022/03/03 23:57:46 [netclient] retrieving peers
2022/03/03 23:57:46 Error retrieving peers
2022/03/03 23:57:46 rpc error: code = Unknown desc = unexpected end of JSON input
2022/03/03 23:57:46 [netclient] failed to retrieve peers
2022/03/03 23:57:46 [netclient] error installing: rpc error: code = Unknown desc = unexpected end of JSON input
2022/03/03 23:57:46 [netclient] removed machine from work network on remote server
2022/03/03 23:57:46 [netclient] could not flush peer routes when leaving network, work
2022/03/03 23:57:46 [netclient] error running command: wg-quick down /etc/netclient/config/nm-work.conf
2022/03/03 23:57:46 [netclient] wg-quick: `/etc/netclient/config/wg0.conf' does not exist
2022/03/03 23:57:46 [netclient] removed work network locally
2022/03/03 23:57:47 [netclient] removed systemd remnants if any existed
2022/03/03 23:57:47 [netclient] removed systemd remnants if any existed

**Comment by xcf13363175** [comment]
Same error as above.

**Comment by mattkasun** [comment]
macaddress validation was removed #927
