### ISSUE TITLE
MTU mismatch between ingress/egress gateway and external clients

### ISSUE THREAD

**Issue by patstrom** [gravitl/netmaker#857]
The default MTU when setting up an ingress + external clients is 1280 for the ingress and nothing for the generated external client configurations, which means they use the WireGuard default which is 1420.

This has mostly worked fine but it has caused intermittent issues. What is the idea behind the 1280 default? And why are the external clients not made to match it? Is it a mistake or is there a reasoning behind it?

**Comment by afeiszli** [comment]
This is just an oversight and should be added. Would you be open to working on this / submitting a PR? It should be a pretty simple fix. You can see how we set DNS based on the DefaultExtClientDNS field.

**Comment by patstrom** [comment]
I don't necessarily have a good way to test the changes but from what I can tell this should be the necessary patch, is that correct?

```
diff --git a/controllers/ext_client.go b/controllers/ext_client.go
index 345e9e6..6044b68 100644
--- a/controllers/ext_client.go
+++ b/controllers/ext_client.go
@@ -154,6 +154,7 @@ func getExtClientConf(w http.ResponseWriter, r *http.Request) {
        config := fmt.Sprintf(`[Interface]
 Address = %s
 PrivateKey = %s
+MTU = %d
 %s

 [Peer]
@@ -164,6 +165,7 @@ Endpoint = %s

 `, client.Address+"/32",
                client.PrivateKey,
+               gwnode.MTU,
                defaultDNS,
                gwnode.PublicKey,
                newAllowedIPs,
```

**Comment by 0xdcarns** [comment]
Added in v0.12.1. Please re open if still an issue from that version on.
