### ISSUE TITLE
connectivity ping 

### ISSUE THREAD

**Issue by mgabet** [gravitl/netmaker#884]
Hello,

Can you explain me why the netmaker server linux can't ping / access to the netclients? but netclients can ping the netmaker (*255 ip) and ping each others clients.

Basically I want all my netclients from AWS to be accessible from GCP netmaker server.

**Comment by mgabet** [comment]
imagine that all my 4 server are on 4 differents internet network and I want 1 netmaker server on another network to access them all, what configuration should I set?

**Comment by afeiszli** [comment]
the default netmaker deployment does not put the wireguard interface on the host. You can use the "host network" version of the docker compose to deploy onto the host, and then you'll be able to ping, but by default, we keep the interfaces contained in docker to make it easier to manage.
