### ISSUE TITLE
Got confused by Ingress and Realy.

### ISSUE THREAD

**Issue by Marerc** [gravitl/netmaker#885]
I am trying to understand the arch of netmaker and got this problem:  
Ingress is the node that can let the devices without original netmaker client join the network, should the ingress gw relay all the traffic from external client to the meshed network? And, the Relay node let the devices under double NATed network connect to a node with public ip so that it can access the mesh network. So what is the differences between them?

**Comment by mattkasun** [comment]
external clients do not have netclient running.  Any change to their configuration require you to download (or manually update) the wireguard configuration. 

relayed cients do have netclient and therefore will receive automatic updates.
