### ISSUE TITLE
a

### ISSUE THREAD

**Issue by mgabet** [gravitl/netmaker#886]
a

**Comment by mgabet** [comment]
@afeiszli any idea my friend? how can I open new ports?

**Comment by afeiszli** [comment]
I'm not sure if I understand what you are looking for. This is on the client-side right? The netclient only requires the port used by wireguard (you can see which port it is using in "wg show"). I do not know where those other ports would be coming from.

**Comment by mgabet** [comment]
> I'm not sure if I understand what you are looking for. This is on the client-side right? The netclient only requires the port used by wireguard (you can see which port it is using in "wg show"). I do not know where those other ports would be coming from.

i've opened others ports on my client, why can't I access them on my other servers inside my netclient network?
something specific to do in wg conf? or else? thanks
