### ISSUE TITLE
No communication between nodes

### ISSUE THREAD

**Issue by Zed08w** [gravitl/netmaker#914]
Hello all,

Trying to test out Netmaker, I have installed and set up on Linode, Racknerd and my own hardware. On all three installations I tried my own website or the standard one.

I did the following;

1. Updated Ubuntu 20.04 
2. installed dependencies 
3. opened ports:   sudo ufw allow proto tcp from any to any port 443 && sudo ufw allow 53/udp && sudo ufw allow 53/tcp && sudo ufw allow 51821:51830/udp
4. Installation command:  wget -qO - https://raw.githubusercontent.com/gravitl/netmaker/master/scripts/nm-quick.sh | sudo bash -s -- -d mynetmaker.domain.com(used my domian)
5. access webui and got commands for new machines. 
6. installed onto several machines. none would communicate on the 10.x.x.x networks.
7. tried to ping the other nodes and it does not communicate.

I followed this video from Netmaker devs to install https://www.youtube.com/watch?v=NWMYPU2FCjI

I also tried to enable the ingress status on my clients. did not change anything

i assume I am just doing something wrong. I tried several networks. I deleted the default one and tried others, no luck. 

There is also a default 172.x.x.x network that is unabled to be deleted

Can someone point me in the right direction? I am very excited to use this product

**Comment by afeiszli** [comment]
Hi, how have you configured firewall on these machines? We have a guess that there is an issue with port forwarding. The server attempts to set port forwarding to MQ on startup. If that is not functioning, node updates will not work.

**Comment by afeiszli** [comment]
We discovered this issue in v0.12.0. It should be fixed in v0.12.1. Please upgrade and feel free to re-open if you still experience the issue.
