### ISSUE TITLE
Netmaker community/ forums

### ISSUE THREAD

**Issue by JPBeltman** [gravitl/netmaker#923]
Hi everyone,

First off, since this is my first post/issue in this community; I've been following development roughly since v0.5.11, around the time I started my homelab & realized I didn't know that much about networking.
I think you've made an incredible piece of software/service, accessible for motivated beginners but still in depth enough for more experienced users. The amount of documentation and the guides from @afeiszli are a blessing. Finally managed to setup a DO server node without too many issues thanks to your long in depth video about netmaker from last month. 

So on to my question;
Are there any official forums for netmaker (or planned)? I still have unanswered questions after scouring through the docs, the issues pages, reddit and other random forums and I don't feel like they're worthy to issue an issue since they aren't really. 
I'm also asking it because there are so many possibilities,use-cases and combinations of setups for netmaker so it would nice to see what others do with it, I already saw some layouts in the issues of which I hadn't even thought about

Also, if a node has an error/warning status under nodes/graphs; where would I be able to see that error? It's solved by pulling the latest netclient configuration on the troubled node but I couldn't find any reference to it in the UI itself nor in the docs. 

Anyhow, excellent work! Can't wait till I'm able to contribute too.

edit: typo's and added question about node status

**Comment by mattkasun** [comment]
Join the netmaker discord https://discord.gg/4h5nvB3S

The node warning/error status indicated that the node has not checked in with the netmaker server in either the last 5 minutes(warning) or 30 minutes (error).

**Comment by JPBeltman** [comment]
Thanks for your reply, I dislike the chaotic nature of Discord so I'll be waiting for something a bit more structured and based on posts instead of chats. 

How did you find out about the meaning of the status?

**Comment by afeiszli** [comment]
Closing this for now, as the official forum is Discord, and there are not currently any plans to change this
