### ISSUE TITLE
[Feature Request]: netclient list nodeid

### ISSUE THREAD

**Issue by TheNexter** [gravitl/netmaker#926]
### What happened?

To automate deploy egress it could be good to have :
netclient list nodeid

Now the api needs the nodeid to add gateway and we can't have it without this feature :(

We can find in interface but when i type netclient list i don't have the nodeid
<img width="395" alt="Capture d’écran 2022-03-21 à 02 18 51" src="https://user-images.githubusercontent.com/17613028/159194804-7238bead-f204-4ecc-9b25-0b3fe606903e.png">

### Version

v0.12.0

### What OS are you using?

Linux

### Contributing guidelines

- [X] Yes, I did.

**Comment by mattkasun** [comment]
fixed in v0.12.2
