### ISSUE TITLE
[Bug]: API, impossible to add gateway to a node

### ISSUE THREAD

**Issue by TheNexter** [gravitl/netmaker#928]
### What happened?

curl  -d  '{ "rangestring": "145.0.0.1/24", "interface": "netmakerdocker"}' -H 'Content-Type: application/json' -H "authorization: Bearer **_myprivatekey_**" localhost:8081/api/nodes/netmaker/**_mynodeid_**/creategateway

### Version

v0.12.0

### What OS are you using?

Linux

### Relevant log output

```shell
{"Code":500,"Message":"IP Ranges Cannot Be Empty"}
```

### Contributing guidelines

- [X] Yes, I did.

**Comment by afeiszli** [comment]
appropriate format for the API call is **curl -d '{ "ranges": ["145.0.0.1/24"],**

Tested and works. Please consider opening an issue or PR on the netmaker-docs repo to have the reference updated: https://github.com/gravitl/netmaker-docs
