### ISSUE TITLE
[Bug]:no bugs.I just can't find a 32-bit netclient for windows

### ISSUE THREAD

**Issue by perfectstorm01** [gravitl/netmaker#930]
### What happened?

I can't find a 32-bit netclient for windows, would you consider making one, I found that it can't be used for 32-bit windows during deployment, thank you very much for considering my problem, this work is really amazing, thank you again for being able to use it.

### Version

v0.12.0

### What OS are you using?

Windows

### Contributing guidelines

- [ ] Yes, I did.

**Comment by perfectstorm01** [comment]
In addition, I would like to know whether to consider the automatic routing function of windows, that egress function always prompts that it cannot be configured on windows

**Comment by ok-john** [comment]
Hey @perfectstorm01, this will build a 32-bit netclinet.
```bash
$ GOARCH=386 GOOS=windows GOHOSTARCH=amd64 CGO_ENABLED=0 go build -o bin/windows/netclient-386
```
I'll add these to our artifacts in the coming releases.

**Comment by perfectstorm01** [comment]
I appreciate your reply and thoughtfulness，but I'm not very good at programming, could you help me compile a 32-bit netclient, and then hang it in the attachment, or send it to my email：perfectstrom01@163.com. Grateful!

> Hey @perfectstorm01, this will build a 32-bit netclinet.
> 
> ```shell
> $ GOARCH=386 GOOS=windows GOHOSTARCH=amd64 CGO_ENABLED=0 go build -o bin/windows/netclient-386
> ```
> 
> I'll add these to our artifacts in the coming releases.

I appreciate your reply and thoughtfulness，but I'm not very good at programming, could you help me compile a 32-bit netclient, and then hang it in the attachment, or send it to my email：perfectstrom01@163.com. Grateful!

**Comment by si458** [comment]
the latest 0.12.2 doesnt work on 32bit Windows 10 either

**Comment by afeiszli** [comment]
32bit windows is not supported. If users need 32-bit support, they will need to compile themselves as listed above.

**Comment by PizzaProgram** [comment]
Can somebody please tell me:
- where can I get the latest version of netclient_x86.msi or exe for **Win7 32bit** ?

It is not fair that it's:
- nowhere written, that `netclient.exe` is only for 64 bit.
_(Not at readme.md, nor at docs)_

Also `netclient_x86.msi` is suggesting it can run on both OSes !
The setup process does not show any error message, it is finishing as if everything would be alright... 👎 
 (Only the `winsw.wrapper.log` log file reveals there is a problem, hidden at `C:\Program Files\Netclient\` folder. )

This ticket should not be closed.

**Comment by PizzaProgram** [comment]
I have no idea, what that one line means:

`$ GOARCH=386 GOOS=windows GOHOSTARCH=amd64 CGO_ENABLED=0 go build -o bin/windows/netclient-386`

But if it's so easy to compile with this "one line", that everybody should know how, why isn't it automated to generate a release?
I know about 100+ restaurants, where still using 200+ `Win7 32bit` PCs as their POS systems daily without any problems. _(And some with XPs, also working perfectly fine every each day!)_
 
I'd like to help them to switch from OpenVPN to netmaker for their remote access.

I would like to donate to this project, if this could be solved ?

**Comment by ok-john** [comment]
@afeiszli @0xdcarns to fix this issue you could just remove the hard coding to `Program Files (x86)` and have it be architecture dependent to the aforementioned or `Program Files` for 32 bit windows systems.

Hope you folks are doing well, cheers.
