### ISSUE TITLE
[Bug]: UI Errors Showing In v0.12.0

### ISSUE THREAD

**Issue by SiM22** [gravitl/netmaker#942]
### Contact Details

sim22eg@protonmail.com

### What happened?

I am not sure if this is a server or UI issue. As far as I can tell i am not able to see any issue with the backend, all nodes can contact each other and the core seems to work fine. 

The issue is in the UI. 2 Issues here.
<img width="1477" alt="Screen Shot 2022-03-21 at 23 15 20" src="https://user-images.githubusercontent.com/5759618/159378663-a2c7fdf9-917d-4a21-822d-1ca2268d8443.png">

As you can see in the image the first issue is the difference in version between what is shown on the side bar and what is shown in the node list for the server.

Second issue is that the OS X client is connected and working fine, but it shows Error in the node list. If i go to the node and do a leave and then join again, it will show as healthy but after 15 mins it will show Error again. But the client/node can ping other nodes fine.

### Version

v0.12.0

### What OS are you using?

Linux, Mac

### Contributing guidelines

- [X] Yes, I did.

**Comment by afeiszli** [comment]
@SiM22 if you update the network (any of the peers) or update the mac node itself, does it receive and process the update properly?

**Comment by SiM22** [comment]
Yes it does recieve updates. I changed the IP in the UI of the jumpbox

Before

```
Simons-Work-MBP:~ root# netclient list | jq
{
  "networks": [
    {
      "name": "IxCJRpcb",
      "current_node": {
        "name": "old-zamboni",
        "interface": "nm-IxCJRpcb",
        "private_ipv4": "172.25.0.1",
        "public_endpoint": "x.x.x.x"
      },
      "peers": [
        {
          "name": "netmaker-1.IxCJRpcb",
          "private_ipv4": "172.25.255.254"
        }
      ]
    },
    {
      "name": "homelab",
      "current_node": {
        "name": "Simons-Work-MBPlocaldomain",
        "interface": "nm-homelab",
        "private_ipv4": "10.20.30.1",
        "public_endpoint": "x.x.x.x"
      },
      "peers": [
        {
          "name": ""---..homelab",
          "private_ipv4": "10.20.30.4"
        },
        {
          "name": ""---..homelab",
          "private_ipv4": "10.20.30.5"
        },
        {
          "name": ""---..homelab",
          "private_ipv4": "10.20.30.8"
        },
        {
          "name": ""---..homelab",
          "private_ipv4": "10.20.30.2"
        },
        {
          "name": "jumpbox.homelab",
          "private_ipv4": "10.20.30.3"
        },
        {
          "name": ""---..homelab",
          "private_ipv4": "10.20.30.254"
        }
      ]
    }
  ]
}
```

After (notice jumpbox IP)

```
Simons-Work-MBP:~ root# netclient list | jq
{
  "networks": [
    {
      "name": "IxCJRpcb",
      "current_node": {
        "name": "old-zamboni",
        "interface": "nm-IxCJRpcb",
        "private_ipv4": "172.25.0.1",
        "public_endpoint": "x.x.x.x"
      },
      "peers": [
        {
          "name": "netmaker-1.IxCJRpcb",
          "private_ipv4": "172.25.255.254"
        }
      ]
    },
    {
      "name": "homelab",
      "current_node": {
        "name": "Simons-Work-MBPlocaldomain",
        "interface": "nm-homelab",
        "private_ipv4": "10.20.30.1",
        "public_endpoint": "x.x.x.x"
      },
      "peers": [
        {
          "name": ""---..homelab",
          "private_ipv4": "10.20.30.254"
        },
        {
          "name": ""---..homelab",
          "private_ipv4": "10.20.30.2"
        },
        {
          "name": ""---.",
          "private_ipv4": "10.20.30.8"
        },
        {
          "name": ""---..homelab",
          "private_ipv4": "10.20.30.5"
        },
        {
          "name": "jumpbox.homelab",
          "private_ipv4": "10.20.30.11"
        },
        {
          "name": "---.homelab",
          "private_ipv4": "10.20.30.4"
        }
      ]
    }
  ]
}
```

**Comment by si458** [comment]
i have a similar issue with the version, server was running 0.12.0 with 2 nodes connected, 
i upgraded the server to 0.12.1 which worked correctly, 
then i stopped the netclient service on the 2 nodes, replaced the binarys with 0.12.1, then restarted the netclient services,
web UI still shows the nodes as 0.12.0 ?

**Comment by mattkasun** [comment]
PR #980 fixes

**Comment by si458** [comment]
@mattkasun yes indeed 0.12.2 fixes the issue! thanks!
