### ISSUE TITLE
[FEATURE REQUEST] OpenID connect as an oauth provider

### ISSUE THREAD

**Issue by Banh-Canh** [gravitl/netmaker#972]
Hello,

Would it be possible to add OpenID connect as an oauth provider ? So we can use our own selfhosted identity provider such as Keycloak or Authentik.

Thanks.

**Comment by dschaper** [comment]
Looks like a duplicate of #636

**Comment by Banh-Canh** [comment]
Indeed, sorry for that. The other issue should be enough
